### ISSUE TITLE
[質問]重複録画スキップについて

### ISSUE THREAD

**Issue by unicode45** [l3tnun/EPGStation#102]
EPGStationに重複録画をスキップする機能はありませんでしょうか？
TvheadendのようなPVRソフトでは録画した番組情報を一定期間保存し、
ルールで録画予約する場合に同じ番組名は重複録画を行わずにスキップする機能があって重宝しています。特にBS・CS系は再放送が多くて、このような重複防止機能があると助かります。

**Comment by l3tnun** [comment]
そのような機能はないです。
とても良い機能だと思いますが、実装するには結構大きな修正が必要になりそうですね。

**Comment by unicode45** [comment]
ご対応ありがとうございます。
早速feature-102ブランチをPullしましたが、
簡単な使い方や検証方法を教えて頂けますでしょうか？

**Comment by l3tnun** [comment]
まだ作業は完了してないですよ。
DBの不可逆な変更があるので完了するまでは使用しないほうが良いです

**Comment by l3tnun** [comment]
feature-102 ブランチにて実装が一応完了しました。
データベースの仕様が完全に固まったわけではないので本番環境での仕様は非推奨です。

使い方
検索ページにて
1. 通常通り検索オプションを設定
2. 録画済み番組を排除 を有効化
3. 日数を指定
4. ルール追加 or 更新

最初の時点では同じ番組名の番組が予約されていますが、そのうちの 1 つでも録画が終わるとその番組名が記録されて、予約情報更新時に同じ番組名の予約は削除されます。

記録された番組名は一定期間経過すると削除されます。
config.json の recordedHistoryRetentionPeriodDays で設定できます。デフォルトは 30 日となっています。

軽い動作説明
1. ルールで予約された番組の録画が終了した時、番組名が記録される。[再] などの [] で囲まれた部分は削除される
2. 検索やルール追加、更新時に録画済み番組を排除が有効な場合、1. で追加した番組名と同じ番組があれば検索結果から排除する

本当は検索時に同名番組を排除するのではなく、除外状態にしてスキップされていることが明示的にわかる形がいいのですが、プログラムの構造的に厳しかったのでこのような形になりました。

かなり分かりづらい説明になりましたが試してもらえれば分かると思いますので、時間が空いている時に試してみてください。

**Comment by unicode45** [comment]
早速試させていただきました。
既存のsqlite3では上手く動かなかったため、新しく用意したmysqlのdbで無事動きました。
一度録画されると、同じタイトル名の番組は予約およびルールの検索結果からも消えることも確認しました。
ただ、スキップされた番組がリストから急に消えてしまい、少し逆にわかりづらいと思います。
あくまでも参考例としてtvheadendのスキップ処理の表示方法を挙げますが、スキップされる番組はhtml書式の取り消し線でスキップされたことを表したりしますので、ご検討のほどお願いいたします。

**Comment by l3tnun** [comment]
> 既存のsqlite3では上手く動かなかったため

データベースのアップグレード処理が入っているのですがエラーがでましたか？

取り除かれたことが明示できればそれに越したことは無いのですが、SQL で重複したものか区別したものか判別するのが難しいですね。

**Comment by unicode45** [comment]
buildや起動、動作自体に特に異常は見られませんでしたが、録画されても同じタイトル名の番組は予約リストに残ったままで上手くスキップされなかったため、dbをmysqlに変更して新規作成しました。
何か問題を調べる方法があればご指導のほどお願いします。

>  SQL で重複したものか区別するのが難しいですね。

なるほど。納得しました。ご検討ありがとうございます。

**Comment by unicode45** [comment]
1. recordedHistoryRetentionPeriodDaysの設定反映について
config.jsonでrecordedHistoryRetentionPeriodDaysを追記し、365日に設定しましたが、
検索では常に初期値が6日になります。
上記の説明文ではデフォルトが30日とのことでしたので、こちらとも一致しないと思います。
なお、日数設定で0などで無期限などの設定があればいいと思いました。

2. sqlite3について
既存のDBおよび新規作成のDBともに以下のテーブルが
Encoded          Recorded         Rules
Programs         RecordedHistory  Services
になっており、新規DBでも添付ファイルのようにスキップはうまく行われませんでした。
（録画が完了し、サムネイルも作成されていますが、予約から消えません）
![recskip](https://user-images.githubusercontent.com/13643547/41809476-25d7bda6-7729-11e8-9cae-ed8f44424be7.jpg)

**Comment by unicode45** [comment]
訂正します。バグレポ後に気づきましたが、
sqlite3の新規DBでは録画終了後５分ほどで予約から重複番組が消えたことが確認できました。
（PCの仕様と更新周期の問題？）
同様の問題だったかもしれませんので、マイグレーションされた既存のDBでも検証を続けたいと思います。

**Comment by l3tnun** [comment]
config.json の recordedHistoryRetentionPeriodDays は RecodedHistory にデータを保存する期間で、検索時に指定する日数とは違います。
ややこしくて申し訳ない。

> なお、日数設定で0などで無期限などの設定があればいいと思いました。

なるほど、0 日で無期限設定できるようにしたいと思います。

----

sqlite の検証ありがとうございます。
こちらの環境での結果と合わないので OS, node のバージョンを教えてもらってもいいでしょうか？

----

先程

> SQL で重複したものか区別するのが難しいですね。

と書きましたが、判別することができました。（恥ずかしい）
ルール検索時の除外と同じように検索結果と番組表で重複していることが分かるようになる予定です。

**Comment by l3tnun** [comment]
リロードしていませんでした。

> sqlite3の新規DBでは録画終了後５分ほどで予約から重複番組が消えたことが確認できました。
>（PCの仕様と更新周期の問題？）

デフォルトでは 10分毎に予約情報を更新しているので、録画完了後次の予約更新時に反映されます。

**Comment by unicode45** [comment]
> RecodedHistory にデータを保存する期間で、検索時に指定する日数とは違います。
ご説明ありがとうございます。勘違いしました。

> なるほど、0 日で無期限設定できるようにしたいと思います。
> ルール検索時の除外と同じように検索結果と番組表で重複していることが分かるようになる予定です。

ありがとうございます。これでスキップ状況がわかりやすくなると思いますので楽しみです。

> こちらの環境での結果と合わないので OS, node のバージョンを教えてもらってもいいでしょうか？

はい。nodeはv8.11.2
OSはCentOS、3.10.0-693.el7.x86_64になります。

**Comment by unicode45** [comment]
既存のSqlte3はやはり録画が終わっても重複番組が予約リストから消えませんでした。
録画完了から15分以上経過しても、予約タブの「予約情報更新」を試しても結果は同じでした。

**Comment by l3tnun** [comment]
こちらの環境では起きないので os を揃えて検証してみます。

今更新に区切りがついたので最新版に更新してもらえますか？
重複予約が打ち消し線で表示されるようになりました。

**Comment by l3tnun** [comment]
あ、RecordedHistory に登録されるのはルール予約だけです。
手動予約ではだめです。

**Comment by unicode45** [comment]
mysqlで確認しました。ルール予約の編集画面上で録画済みの番組はグレーの背景で取り消し線がかかっていました。
なお、sqlite3の既存のdbにおける検証はよろしくお願いいたします。

**Comment by l3tnun** [comment]
sqlite3 の方は明日検証してみます。
機能的にはほぼ実装完了なので他になにかあれば言ってください。

**Comment by unicode45** [comment]
欲を言えば
ルールの編集画面でルールごとにスキップされた状況を追うのが大変でしたので、ルールの編集画面同様、予約リストにおけるスキップ表示（取り消し線）があればと思いました。

これと同時にルール編集画面や予約リストでスキップされた番組の詳細情報に「スキップしない（録画する）」があれば、何らかの理由（前回ドロップなどで上手く録画できなかった。字幕版だけでなく吹替版も録画したいなど）で再録画したい場合に役に立つと思います。

ご検討のほどお願いいたします。

**Comment by l3tnun** [comment]
以下の変更を加えました

* 従来の重複ページ (予約の競合) を競合に名前を変更し、重複で番組の重複状態の一覧を見れるように変更
* 重複の解除を追加
* 重複の設定を検索プションではなくルール追加オプションに移動
* 録画終了後に重複情報を更新するように

sqlite3 の動作ですが、Centos 7.5 をインストールし試してみましたが新規、アップグレード共に問題は確認できませんでした。

実装はほぼ終わりましたのでなにかあれば言ってください。

**Comment by unicode45** [comment]
sqlite3のアップグレードの件は再現できなかったとのことで申し訳ありませんでした。

> 従来の重複ページ (予約の競合) を競合に名前を変更し、重複で番組の重複状態の一覧を見れるように変更
> 重複の解除を追加

ありがとうございます。非常に見やすく、重複の解除も行えて嬉しい限りです。

> 重複の設定を検索プションではなくルール追加オプションに移動

挙動について1点気になる点があります。もし認識が間違っていたら教えていただきたいですが、
ルールで重複排除期間を後から短くした場合、該当する時間以降は重複スキップされず、録画予約の対象になるべきかと思いますが、添付ファイルのように日数を減らして適用を変更し、再度ルールを開いても排除する期間が正しく設定されていない気がします。
sqlite3のDBの件もあって環境に依存する問題かもしれませんが、
ご確認のほどお願いいたします。
![duplitated1day](https://user-images.githubusercontent.com/13643547/41819416-410b80b2-77fb-11e8-985e-9b1dc2c65e08.jpg)

**Comment by l3tnun** [comment]
その日数は RecodedHistory を検索する日数です。
```現在時刻 - 日数``` の期間に録画された番組名に該当する予約を重複するとみなします。

**Comment by unicode45** [comment]
> 現在時刻 - 日数 の期間に録画された番組名に該当する予約を重複するとみなします。

ご説明ありがとうございます。遡って検索する日数とのこと、承知しました。
それ以外は動作に特におかしな点はないと思います。
本当にお疲れ様でした。ありがとうございます。

**Comment by l3tnun** [comment]
ダメダメだったので revert して戻しました。

**Comment by l3tnun** [comment]
今度こそうまく変更できたので日数の挙動を変更しました。

**Comment by l3tnun** [comment]
master にマージしましたので閉じます。
