### ISSUE TITLE
新規録画予約追加時のコマンド実行

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#110]
いつもお世話になっております。
ここ最近のアップデートで録画準備失敗時や録画失敗時のコマンド実行なども追加されて外部連携機能に力を入れているなと感じています。

さて、表題の件ですが現時点で実装予定があったりするでしょうか。
というのも、私は自宅と実家に設置した録画機それぞれのログを[Discord](https://discordapp.com)上に集約して通知するようにしています。
![snapcrab_2018-6-21_0-49-17_no-00](https://user-images.githubusercontent.com/9246266/41669761-864060e6-74ed-11e8-90fe-22fafec00996.png)

他アプリでは録画予約時にもコマンドが打てる事が多く、録画予約追加時に通知が飛ぶようにしていました。（画像で言う一番上のNEWアイコンのあるもの）
録画ルールなどで自動予約にしているものがキチンと予約されているかの確認も兼ねているためです。
新規追加の際だけの通知で構わないので、実装していただけると大変助かるので、ご検討いただければと思います。

----
別件ですが、`encode`や`recordedPreStartCommand`には _**CHANNELID**_ が渡されるのに、`recordedStartCommand`と`recordedEndCommand`にはないのはどのような理由によるものでしょうか。
上記のスクリーンショットのように、ログにチャンネル名も含めようと思った際に
1. _**RECORDEDID**_ を用いてEPGStationのAPIから番組情報を取得
1. 取得した番組情報から _**CHANNELID**_ を入手
1. その _**CHANNELID**_ を用いてMirakurunのAPIからチャンネル名を取得する

という大変アレな作業をしてるのですがどうにかならないでしょうか。
（じゃあ`encode`コマンドでやれよって感じでもありますが・・・）

**Comment by l3tnun** [comment]
新規録画予約追加時についてですが良い機能だと思いますので実装しようと思います。
ただ、#102 の実装がまだ終わっていませんのでその後になります。

> recordedStartCommandとrecordedEndCommandにはないのはどのような理由によるものでしょうか。

特に理由はないです。ただの入れ忘れですね。
実装しておいて自分で使用していないので、この情報が欲しいとか書いていただけると助かります。

**Comment by advancedbear** [comment]
実装予定ありがとうございます！
喫緊の課題ではないので、後回しでも全然構いません。

コマンドの環境変数については、ぶっちゃけ私自身はnodeでスクリプトを書いてることもあって「最低限の情報は与えるのでAPIを叩いてください」という方針でも十分だったりします。
ただ、[tvrockのコマンド](http://d.hatena.ne.jp/Fushihara/20101123/1290501075)や、[EDCBのコマンド](https://github.com/epgdatacapbon/EDCB/blob/master/Document/Readme_EpgTimer.txt#L934)辺りにある変数がサッと手に入ると、他のソフトとログ形式を揃えることも出来そうだなとは感じます。
あとはHTTPリクエストを投げられない素のバッチファイルとかが助かるくらいでしょうか……？

ちなみに、録画結果のdrop数とかを取得するのは難しいんでしょうか。
tvrock時代は「ログ内のdrop数の値が0以上ならばtscheck.exeにtsファイルを投げて該当秒数を探り出して、ffmpegで該当秒数前後1秒を一覧にしてドロップシーンを把握」みたいなことをやっていましたが、必要だったかと言われるとそうでもないんですよね・・・。
![snapcrab_2018-6-21_22-36-48_no-00](https://user-images.githubusercontent.com/9246266/41722505-bc54cdc8-75a3-11e8-8561-11cabf5b9726.png)

**Comment by l3tnun** [comment]
なるほど、とりあえず今回は channelId, channel名, ファイルフルパスあたりを追加しておこうと思います。

> ちなみに、録画結果のdrop数とかを取得するのは難しいんでしょうか。

[aribts](https://github.com/rndomhack/node-aribts) を使えば可能ですが、必須でもないしとりあえずいいかなといった感じで機能的には用意していません。
ぼちぼち需要はあると思いますので drop カウントの負荷が大きくなければ実装してもいいかなとは思っています。

**Comment by advancedbear** [comment]
更新ありがとうございました。
Linux環境では録画予約時のコマンドの実行と、追加された各環境変数の確認ができました。

---
一点、ご質問なのですがWindows環境におけるコマンド実行は、パス区切りをバックスラッシュ2つ（≒エスケープ済みバックスラッシュ）にする以外に注意点は無かったでしょうか。
というのも、ReservationAdded、RecordedStart、RecordedEndいずれの場合にも、コマンド欄に
```
"reservationAddedCommand": "C:\\PROGRA~1\\nodejs\\node.exe E:\\Users\\advanced_bear\\Documents\\EPGS-to-Discord\\index.js reserve"
```
などと入力した場合にコマンドが実行されないです。
`EPGStation/logs/Operator/system.log`上では、LogのConfigをDebugに指定していても
```
[2018-07-02T00:07:25.860] [INFO] system - reservation add start process run: C:\PROGRA~1\nodejs\node.exe E:\Users\advanced_bear\Documents\EPGS-to-Discord\index.js reserve
[2018-07-02T00:07:27.107] [INFO] system - reservation add start process is fin
```
といった形で特にエラーなども出力されずにプロセスが終了したとみなされてしまいます。
全く同じコマンド（バックスラッシュは1個ですが）を単体でCMD上で動作させれば正常に動きますし、Linux環境で
```
"reservationAddedCommand": "/usr/bin/node /home/epgstation/EPGS-to-Discord/index.js reserve"
```
として動作しているので、外部プログラム側が環境変数が取れていないとかそういうわけでも無いと思うのですが・・・。
（Windows環境だとダメということはあるかもしれないですが・・・）

該当コードは [advancedbear/EPGS-to-Discord](https://github.com/advancedbear/EPGS-to-Discord) にあります。（汚いコードで恐縮ですが）

**Comment by advancedbear** [comment]
すみません、上記ですが改めて確認したところLinux環境でも動作していませんでした。
ちょっと自分でも改めて再確認してみたいと思います。（コード含め）

**Comment by advancedbear** [comment]
大変申し訳ないです、自分のミスでした。
（cwdがEPGStationフォルダになることをすっかり失念していました。__dirnameをpath.joinするだけで正常動作しましたので問題ありませんでした。

![snapcrab_2018-7-2_2-4-37_no-00](https://user-images.githubusercontent.com/9246266/42136766-6f84f24c-7d9c-11e8-8817-7016ffa2b924.png)

期待していたどおりの動作が行えたので満足しています。
ありがとうございました。

**Comment by advancedbear** [comment]
![snapcrab_2018-7-12_19-47-47_no-00](https://user-images.githubusercontent.com/9246266/42628915-8cb95fc4-860c-11e8-8e02-c63d766b8f35.png)
本来は新規録画予約の際だけ実行されるものだと思うのですが、重複して実行されることがありますね。
30分毎に実行されているのでEPGの更新タイミングだとは思うのですが、ProgramIDが変わっているわけでもないので何なんでしょう。

![snapcrab_2018-7-12_19-49-58_no-00](https://user-images.githubusercontent.com/9246266/42629002-d3b5e67c-860c-11e8-8740-4f48401a68e5.png)
今の所テレビ愛知の番組でしか発生してないのでテレビ局依存の問題なのかもしれません。

**Comment by l3tnun** [comment]
予約の定期更新はデフォルト値では 10 分毎に更新されるようになっています。
そのため考えられそうな事はこんな感じですかね。

1. 新しく program A が新規追加
↓ 10 分後
2. program A が何らかの理由で番組情報から消滅。そのため予約情報から program A が消える
↓ 10 分後
3. program A が番組情報から復活し、予約情報に program A が新規追加される

Mirakurun の EPG 採取間隔がデフォルトの場合 15 分間隔なので、Mirakurun 側で番組情報の消滅、復活が起こるとその様になるかもしれません。

**Comment by l3tnun** [comment]
こちらの環境でも発生するか確認してみますのでしばらくお待ち下さい。

ちなみに重複実行の頻度はどれくらいですか？

**Comment by advancedbear** [comment]
時間帯はまちまちですが、頻度的には毎日起きていますね
とは言え、地上波の番組でしか起こっていない上に地上波番組をそこまで自動予約していないので…。

ただ、発生する番組は深夜アニメが多いですね。
朝アニメ（ゲゲゲの鬼太郎）やゴールデンタイムバラエティ（鉄腕ダッシュ、ブラタモリ）、深夜バラエティ（タモリ倶楽部）ではこのような現象は起きていませんので……。

ただ、京都寺町三条のホームズ（テレビ愛知）などはなかなか凄く、火曜日04:27に最初の1回が実行された後、6:27、7:37、10:57、13:37、17:07、20:07、23:07と8回も実行されました。
ただ、日付が変わった途端ピタリと止まったので、その日のうちしか起きない現象のようですね。

**Comment by advancedbear** [comment]
![snapcrab_2018-7-12_21-49-25_no-00](https://user-images.githubusercontent.com/9246266/42634173-7a029b32-861d-11e8-8c90-93672fde6af9.png)

https://gist.github.com/advancedbear/13981ff42158f1b06f54d6ebc425fe9c
この部分が実行された時間帯（7月11日15時00分～18時15分）のMirakurunのログ（stdout）ですが、別段異常は無いように思えますね……。
TunerProcessが起動している様子もないので新たなEPG情報を取得しているわけでもなさそうです。

ちなみに、（コードを読めば済む話でもありますが）新規と更新の判別は何を基準にされてるんでしょう。
Mirakurun側のProgramIDだけでしょうか、それともその他の値も見ていますか？
一応、予約時の実行コードでMirakurunのAPI叩いてprograms/{id}をまるごと取得してログに出してみますね。

**Comment by l3tnun** [comment]
> 一応、予約時の実行コードでMirakurunのAPI叩いてprograms/{id}をまるごと取得してログに出してみますね。

```reservationAddedCommand``` 実行時のことでしょうか？
```reservationAddedCommand``` 実行時点ではおそらく mirakurun 上にデータがあるので意味がないですね。

やるとしたら、
1. program.json を適当な間隔で保存
2. 新規予約から重複実行が起きた時刻間の programs.json から該当する programId の番組情報が消えていないか確認する

といったところでしょうか。
正直手順が複雑で面倒ですね。

**Comment by l3tnun** [comment]
> reservationAddedCommand 実行時点ではおそらく mirakurun 上にデータがあるので意味がないですね。

意味はあるかもしれないです。すいません。
epgstation が mirakurun から番組情報を取得し DB へ保存する際に何らかの理由で DB 上へ保存されず番組情報が欠落する可能性があるかもしれないです。

EPGStation の ```logs/Operator/system.log``` の7月11日17時57分ごろにエラーとか記録されていたりしますか？

**Comment by advancedbear** [comment]
>`reservationAddedCommand` 実行時点ではおそらく mirakurun 上にデータがあるので意味がないですね。

確かに、比較すべき更新前の予約情報が保持されていないことになりますからコマンド実行時の番組情報だけあってもという感じはしますね。
programs.jsonの定期バックアップ、Linux環境ならlogrotateのhourlyでなんとかなりそうですがWindows環境なのでちょっと厳しいですね。

>EPGStation の `logs/Operator/system.log` の7月11日17時57分ごろにエラーとか記録されていたりしますか？

自分もそれ取得しようと思っていたのですが、ログ設定をDEBUGにしたままなことを忘れていてログが流れてしまっていました。
ログ設定をinfoに戻したので、とりあえず次回発生時のログは取得できると思いますので……。

**Comment by l3tnun** [comment]
こちらの環境でも発生しました。 (Linux, MySQL 8.0)
確認したところ epgstation が mirakurun から番組情報を取得し DB へ保存する際に、特定の局の最後の方の番組情報が欠けることがあるようです。
ちょうど深夜アニメの時間帯にかぶります。

とりあえずの対処として config.json へ以下のように設定を追加してみてください。

```
"programInsertMax": 10,
```

番組情報を DB へ落とし込む時にバルクインサートとマルチプルインサートを使用しているのですが、マルチプルインサートの件数をデフォルトの 100 から 10 に変更すると発生しなくなることを確認しました。

なぜこの対処方法で問題が起きないのかは不明なのでこれから検証したいと思います。

お聞きしたいのですが、使用している DB は何でしょうか？

**Comment by l3tnun** [comment]
最新の master にて ```programInsertMax``` の上限値、デフォルト値を 10 に修正しました。
試してみてください。

**Comment by advancedbear** [comment]
京都寺町三条のホームズ（テレビ愛知）とゆらぎ荘の幽奈さん（三重テレビ）の2件、先週までは連続実行起きてましたが今週は起きなかったようです。
programInsertMaxのデフォルト値10が効いているようです。
対応いただきありがとうございました。
