### ISSUE TITLE
Android、ios端末からのTSライブ視聴が出来なくなりました

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#111]
Windows10 home x64
node.js v8.10.0
Mirakurun 2.7.0
EPGStation 0.9.7

いつもお世話になります。
いつからかはわかりませんが、Androidおよびios端末からのTS無変換ライブ視聴ができなくなりました。
Windows端末からは正常に再生されますが、Android端末で再生しようとすると”その場所
 http://192.168.12.60:8887./api/streams/live/3185657344/mpegts%3Fmode=0 は再生できません”と表示されて失敗します。
HLSライブ視聴は問題なく行えます。

config.jsonの関連部分は以下の通りです。

        "maxStreaming": 1,
        "mpegTsStreaming": [
            {
                "name": "無変換"
            },
            {
                "name": "QSVenc(vfr)",
                "cmd": "C:\\PROGRA~4\\QSVEnc_3.06\\QSVEncC\\x64\\QSVEncC64.exe -c h264 --la-icq 30 --la-depth 10 --tff --vpp-deinterlace none --vpp-denoise 20 --audio-codec aac --audio-stream :stereo --avsync vfr --format mpegts --log C:\\TV\\EPGStation\\recorded\\QSVencC_error.txt -i - -o -"
            },
            {
                "name": "QSVenc(forcecfr)",
                "cmd": "C:\\PROGRA~4\\QSVEnc_3.06\\QSVEncC\\x64\\QSVEncC64.exe -c h264 --la-icq 30 --la-depth 10 --tff --vpp-deinterlace none --vpp-denoise 20 --audio-codec aac --audio-stream :stereo --avsync forcecfr --format mpegts --log C:\\TV\\EPGStation\\recorded\\QSVencC_error.txt -i - -o -"
            },
            {
                "name": "QSVenc(dual_mono)",
                "cmd": "C:\\PROGRA~4\\QSVEnc_3.06\\QSVEncC\\x64\\QSVEncC64.exe -c h264 --la-icq 30 --la-depth 10 --tff --vpp-deinterlace none --vpp-denoise 20 --audio-codec aac --avsync vfr --audio-ignore-decode-error 30 --audio-stream 1?FL,FR --format mpegts --log C:\\TV\\EPGStation\\recorded\\QSVencC_error.txt -i - -o -"
            }
        ],
        "mpegTsViewer": {
            "ios": "vlc-x-callback://x-callback-url/stream?url=http://ADDRESS",
            "android": "intent://ADDRESS#Intent;package=org.videolan.vlc;type=video;scheme=http;end"
        },

よろしくお願いします。

**Comment by l3tnun** [comment]
バグであったので修正しました

**Comment by l3tnun** [comment]
ちなみに Android の VLC アプリが 3.x.x の場合、何度か視聴を繰り返していると同じようなエラーがでて vlc で再生できていない現象を確認しています。

MX Player、 BS Player 等代替アプリはあるのですが TS 無変換再生の場合再生開始までのラグが一番少ないのでが VLC なので、私の環境では vlc を 2.0.6 へダウングレードして使っています。

**Comment by cuckoozero** [comment]
お世話になりました。
version 0.9.8で正常に再生されることを確認しました。
またVLCアプリの情報もありがとうございました。
現時点では同様の症状は見られませんが、今後発生した場合は同様に対応したいと思います。
