### ISSUE TITLE
MySQL 8.0でwait DBになる。

### ISSUE THREAD

**Issue by arkmarou** [l3tnun/EPGStation#114]
はじめまして。
Windows環境で使わせていただいております。

MySQL 8.0をインストールしたマシンにEPGStationをインストールした場合、system.logにwait DBと出てウェブページが表示されない状態になります。
これはMySQL 8.0ですとEPGStationが対応していないのでしょうか。

素人な質問で大変恐縮ですが、教えていただけましたら幸いです。

**Comment by l3tnun** [comment]
データベースとの接続が確認できない場合そのように表示されます。
接続設定が正しく出来ているか確認してください。

もし他のMySQLでの確認が取れている場合は何らかの不具合かもしれません。

**Comment by l3tnun** [comment]
その後なに変化はありましたか？

Windows 10 RS4 + MySQL 8.0 環境を用意して試してみましたが、私の手元の環境では正常に動くことを確認しました。
どうしても動かないようであれば MariaDB, SQLite3 等代替手段はありますのでそちらに変更することをおすすめします。

**Comment by arkmarou** [comment]
お返事が遅くなり申し訳ありません。

当方ほかにMySQLを使用するものを入れておらず、確認することができません。

仮想PCにてもう1度作り直してみましたが、やはりwait DBで止まってしまいます。
実機は5.7で正常に動作していますので無理にアップデートしなくても良いのですが、新しいバージョンのほうが良いかと思いテストしてみた次第でした。

l3tnunさんの用意していただいた環境は、README.mdの通りの手順でコマンドを打ったときにデータベースの権限付与のところでエラーなど出ませんでしたでしょうか？

よろしくお願いいたします。

**Comment by l3tnun** [comment]
ああ、それは MySQL 5.7 での手順となりますので 8.0 ではこんな感じかと思います。

```
create database database_name;
grant all on database_name.* to username@localhost;
alter user username@localhost identified with mysql_native_password BY 'password';
```

**Comment by l3tnun** [comment]
開発当初は MySQL しか対応データベースがなかったので doc では MySQL での手順を書いていますが、
Windowsではデータベースサーバを別途立てるのは結構面倒なので、SQLite3 で構築するのが個人的にはおすすめです。

**Comment by l3tnun** [comment]
> EPGStationで利用する場合はどのように配置し設定すれば良いのでしょうか？

Readme に書いてある通りですが ```dbType``` を ```mysql``` から ```sqlite3``` と書き換えれば利用可能です。
初期状態では正規表現での検索ができませんが  [doc/sqlite3-regexp.md](https://github.com/l3tnun/EPGStation/blob/master/doc/sqlite3-regexp.md) の手順で有効化できます。

**Comment by l3tnun** [comment]
MySQL での問題は解決したようなので閉じます
