### ISSUE TITLE
drop 数カウント

### ISSUE THREAD

**Issue by l3tnun** [l3tnun/EPGStation#116]
#110 より
録画時に drop 数をカウントする

**Comment by advancedbear** [comment]
度重なるアップデートお疲れ様です。

こちらの機能、無事実装完了してMasterにマージされたようなので利用させていただいています。
`isEnabledDropCheck` を `true` にすることで、ドロップ数を始めとする各カウントが行われていることは確認しました。

1つ質問なのですが、この `isEnabledDropCheck` を有効にした時点でログ出力も有効になっているようですが、ログファイルの出力先を変更する設定項目は追加されていますか？
現時点だと、録画データと同階層内にPlainTextなログファイルが出力されているかと思いますが、これを別フォルダへ保存するような設定には出来ないでしょうか。

理想を言えばログ出力は無しでDB上への記録だけというのが1番なのですが、WebUIへの表示にログファイルを使っているようなので、こちらはしょうが無いと思います。
ただ、録画データ用に使用しているHDDは動画以外のファイルが格納されるように構成していなかったので、ログの出力先に関しては変更可能にしていただきたいです。

**Comment by l3tnun** [comment]
config.json に ```dropCheckLogDir``` を追加し .log ファイルの保存先を指定できるようにしました

これまでに生成された ```.log``` ファイルは ```dropCheckLogDir``` で指定されたディレクトリに移動されていない場合、EPGStation 側で参照できないので注意してください
```npm run move-log``` を実行することで ```recorded``` に保存されている ```.log``` ファイルを ```dropCheckLogDir``` で指定したディレクトリに移動できるので使ってみてください。

**Comment by advancedbear** [comment]
ご対応頂きありがとうございます。

質問なのですが、 `dropCheckLogDir` を `/hoge/log` から `/fuga/log` に変更した際に、手動でログファイルを移動させれば正常に動作するという認識で良いでしょうか？
`npm run move-log` は `recorded` フォルダからの移動にしか対応しないようですので、ディレクトリを移動させる場合などは手動での移動で対処可能なのでしょうか。

**Comment by l3tnun** [comment]
> 質問なのですが、 `dropCheckLogDir` を `/hoge/log` から `/fuga/log` に変更した際に、手動でログファイルを移動させれば正常に動作するという認識で良いでしょうか？

そうです。```dropCheckLogDir``` 配下の構成が同じであれば問題ありません。
