### ISSUE TITLE
自動予約ルールのマッチ数（自動予約数）の確認

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#117]
いつも素早い更新作業お疲れ様です。
そして、次から次へと要望を出すばかりで申し訳ありません。

検索からルール追加をした場合に、「ルール」タブで追加済みのルール一覧が表示されるかと思いますが、このルール一覧に自動予約数を表示する機能をつけることは出来ますでしょうか。

「予約」タブでは予約の一覧を見ることが出来ますが、どのルールによって予約された物かは分かりません。
「ルール」タブでは録画済みの一覧を見るボタンはありますが、ルールによって予約された予約の一覧を見ることが出来ません。
そのため、ルールを作成した後、実際に録画予約が行われているかチェックしようと思うと、ルールタブと予約タブを何度も行き来しないといけない状況かなと思います。

今回追加していただいた #110 があれば自前で管理することも出来なくはないのですが、せっかくPC/スマホ両対応なEPGStationがあるのでWebUI上で確認できると便利かなと思いました。
理想としては、ルール画面のカラムの最右列（曜日の隣）に予約数を数字で表記し、数字をクリックすることで吹き出し（ポップアップ）で予約の一覧を見ることが出来る感じではあるのですが・・・。

ただ、ルールと予約の間を紐づけるような情報がDB上に無いようでしたら上記実装はかなり変更が必要なのではないかなという予想も付くので、出来る範囲で改善していただければと思います。

よろしくお願いします。

**Comment by l3tnun** [comment]
予約件数の表示は可能ですね。
予約のポップアップ表示はすぐには出来ないですね。

お察しの通り予約情報が DB 上に無いため予約情報の取得は、Web サーバを担当する Service プロセスが予約情報を持つ Operator から予約情報を取得するようになっています。
このときのプロセス間通信に Node で用意されている IPC 通信を使用していますが、データを大量にやり取りすると恐ろしく遅くなるため、予約情報を全部取得するなどの操作が難しいのが現状です。
(そのため通信量を減らすために、全予約情報の programId と ruleId だけを取得する /api/reserves/all が用意されていたりします。)

ただ、ルール編集ページと同様にルールの検索結果を取得する事は簡単なので、ポップアップに予約情報一覧ではなくそのルールでの検索結果を表示させて予約状況を把握することは可能です。

**Comment by l3tnun** [comment]
feature-117 ブランチにてルールのテーブル表示にて予約数を表示するようにしました。

予約のポップアップ表示についてはポップアップ表示部分 (BalloonComponent) の構造上表示が難しいので実装を見送ります。
予約確認には編集ボタン -> ルール編集ページへ移動で代用できるかなあと思います。

**Comment by advancedbear** [comment]
feature-117ブランチ確認しました。
予約数の表示だけでもだいぶ利便性が良くなりますね。
同一番組が複数チャンネルで放送することを知らずに予約していた場合などに「あれ？なんで予約2なんだ？」と気づけるだけで十二分の意味がありますので・・・。

>予約確認には編集ボタン -> ルール編集ページへ移動で代用できるかなあと思います。

予約数が異なっていることに気付いた場合は同時に予約ルールの編集もしたいと思うことがほとんどだと思うので、その方針で特に問題ないと思います。

**Comment by l3tnun** [comment]
master にマージしたので閉じます。
