### ISSUE TITLE
ローカルファイルの有無を確認して録画済みのリストをクリーンアップする

### ISSUE THREAD

**Issue by arkmarou** [l3tnun/EPGStation#119]
要望なのですが、当方が視聴する際、EPGStationをインストールしたマシンで直接再生視聴をしています。
視聴後に削除する場合ファイラーから削除するのですが、そうするとEPGStationの録画済みに残ってしまいます。
これらを［録画済みを整理する］ボタン的なものでファイルの有無を確認してクリーンアップすることは可能でしょうか？

**Comment by l3tnun** [comment]
現在そのような機能はありませんが、あれば便利なので実装しようと思います。

**Comment by l3tnun** [comment]
実装が完了しました。
録画済みページの右上のメニューに クリーンアップ が追加されました。
クリックすると以下のものが削除されます。

* データベース上に登録があるが実際にはファイルがないデータ
* データベース上に登録されていないファイル
* 空のディレクトリ

ご確認ください。

**Comment by arkmarou** [comment]
無事クリーンアップが動作し、録画済みが整理されました。
ありがとうございました。
引き続き使わせていただきます。
