### ISSUE TITLE
WindowsでSQLite3を用いたセットアップ

### ISSUE THREAD

**Issue by arkmarou** [l3tnun/EPGStation#126]
Windows 10 Professional x64
node.js v8.11.3 LTS
Mirakurun 2.7.0
EPGStation 1.0.4

便利に使わせていただいております。

Windows環境ではSQLite3がおすすめと教えていただきまして、仮想環境にて新たに環境を組み始めたのですが、config.jsonの"dbType"を"sqlite3"に書き換え、"mysql"項目を削除した状態でnpm startをしたところ、

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Windows\System32\EPGStation\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Windows\System32\EPGStation\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EPGStation@1.0.4 start: `node dist/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EPGStation@1.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-07-18T07_54_23_353Z-debug.log
```

と表示されEPGStationが立ち上がりません。
エラー文のパスを辿ると、
EPGStation\node_modules\sqlite3\lib
より以下が存在しないことがわかりました。

こちらご教授お願いできますでしょうか？

また上記とは関係ないのですが、enc.sh (enc.js)のdocumentなどはありますでしょうか？
現状H264 mainを使用して720p30にエンコードしていますが、H264 subの設定をいじって720p60のエンコードをしたいと思っています。

以上2点、よろしくお願いいたします。

**Comment by l3tnun** [comment]
module が正しくインストール出来ていないのでは無いのでしょうか?
node_modules を削除して readme のインストール手順をもう一度やってみてください。
あと、C:\Windows\System32 に EPGStation がインストールされいる様に見えるのですが、それはよろしくないので別の場所にインストールしてください。

enc.js に特にドキュメント等はありません。ffmpeg に引数をセットし起動しているだけです。
60fps化は EPGStation に限る話ではなく ffmpeg 等のエンコードソフトの話になりますのでここでは扱いません。

**Comment by arkmarou** [comment]
管理者権限で起動したコマンドプロンプトで、ディレクトリを移動せずそのまま

**Comment by arkmarou** [comment]
そうしましたら`"sub"`やオリジナルのエンコード設定を追加する場合、`config.json`に追記したのち、`enc.js`には`let mode = 'sub'`とそれ以下のコードを追記すれば動作するのでしょうか？

**Comment by l3tnun** [comment]
やりたい事がよくわかりませんが、```ffmpeg``` 実行時の引数を適切にセットしてあげれば動きますよ。

**Comment by ohmsa** [comment]
横から失礼します。

私は

config.json
` "encode": [
        {
            "name": "H264",
            "cmd": "/bin/bash %ROOT%/config/enc.sh qsv",
            "suffix": ".mp4",
            "default": true
        },
        {
            "name": "H264-sub",
            "cmd": "/bin/bash %ROOT%/config/enc.sh sub",
            "suffix": "-sub.mp4"
        },
        {
            "name": "CINEMA",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe C:\\EPGStation\\config\\enc.js cinema",
            "suffix": "-c.mp4"
        },
        {
            "name": "DRAMA",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe C:\\EPGStation\\config\\enc.js drama",
            "suffix": "-d.mp4"
        }
    ],
`


enc.js
``if(mode == 'qsv'){
    if(videoHeight > 720) {
        args = ['-i', input, '-global_quality', '16', '-c:v', 'h264_qsv', '-s', '1280x720', '-vf', 'pullup', '-r', '24', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
        args = ['-i', input, '-global_quality', '16', '-c:v', 'h264_qsv', '-vf', 'pullup', '-r', '24', '-c:a', 'copy', output];
    }
}else if(mode == 'cinema'){
    if(videoHeight > 720) {
    args = ['-i', input, '-global_quality', '14', '-c:v', 'h264_qsv', '-s', '1920x1080', '-vf', 'pullup', '-r', '24000/1001', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
    args = ['-i', input, '-global_quality', '14', '-c:v', 'h264_qsv', '-vf', 'pullup', '-r', '24000/1001', '-c:a', 'copy', output];
    }
}else if(mode == 'drama'){
    if(videoHeight > 720) {
    args = ['-i', input, '-global_quality', '23', '-c:v', 'h264_qsv', '-s', '1920x1080', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
    args = ['-i', input, '-global_quality', '23', '-c:v', 'h264_qsv', '-c:a', 'copy', output];
    }
}else if(videoHeight > 720) {
    //    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif=0:-1:1', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];    
} else {
//    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif=0:-1:1', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
}

といった感じでオリジナルエンコード設定を追加しています。このように設定するとWindows環境ならばQSVで高速エンコード可能です。
多分if文まわりやエンコードの調整周りはもう少し何とかなる気はしますが、エンコード設定の追加方法はこのような感じで行えばOKです。

**Comment by ohmsa** [comment]
文字化けしてしまいました。
他の設定を参考にしてもらえれば。

**Comment by arkmarou** [comment]
ohmsa様

エンコードの追加設定、ありがとうございます。
当方そのやり方を調べているところでした。

元から記載がある、

https://github.com/l3tnun/EPGStation/blob/035725c9665b84801c8d83f47dcec7c41efff322/config/enc.js#L1-L2

などは消去して、そのまま`if(mode == 'qsv'){`からスタートしているのでしょうか？

**Comment by ohmsa** [comment]
いいえ。enc.jsの

`let args;

if(videoHeight > 720) {

    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];

} else {

    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];

}



let child = spawn(ffmpeg, args);`

のif文を書き換えたり追加したりしています。
まずはconfig.jsonの名前や引数だけ変えてみてどう動くか弄ってみては。

**Comment by ohmsa** [comment]
`    "encode": [
        {
            "name": "H264",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe C:\\EPGStation\\config\\enc.js qsv",
            "suffix": ".mp4",
            "default": true
        },
        {
            "name": "H264-sub",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe  C:\\EPGStation\\config\\enc.js sub",
            "suffix": "-sub.mp4"
        },
        {
            "name": "CINEMA",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe  C:\\EPGStation\\config\\enc.js cinema",
            "suffix": "-c.mp4"
        },
        {
            "name": "DRAMA",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe C:\\EPGStation\\config\\enc.js drama",
            "suffix": "-d.mp4"
        }
    ],`

`if(mode == 'qsv'){
    if(videoHeight > 720) {
        args = ['-i', input, '-global_quality', '16', '-c:v', 'h264_qsv', '-s', '1280x720', '-vf', 'pullup', '-r', '24', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
        args = ['-i', input, '-global_quality', '16', '-c:v', 'h264_qsv', '-vf', 'pullup', '-r', '24', '-c:a', 'copy', output];
    }
}else if(mode == 'cinema'){
    if(videoHeight > 720) {
    args = ['-i', input, '-global_quality', '14', '-c:v', 'h264_qsv', '-s', '1920x1080', '-vf', 'pullup', '-r', '24000/1001', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
    args = ['-i', input, '-global_quality', '14', '-c:v', 'h264_qsv', '-vf', 'pullup', '-r', '24000/1001', '-c:a', 'copy', output];
    }
}else if(mode == 'drama'){
    if(videoHeight > 720) {
    args = ['-i', input, '-global_quality', '23', '-c:v', 'h264_qsv', '-s', '1920x1080', '-c:a', 'copy', output]; 
    //ffmpeg -i in.ts -global_quality 23 -c:v h264_qsv -s 1280x720 -vf pullup -r 24 -c:a copy optout720p.mp4
    } else {
    args = ['-i', input, '-global_quality', '23', '-c:v', 'h264_qsv', '-c:a', 'copy', output];
    }
}else if(videoHeight > 720) {
    //    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif=0:-1:1', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-s', '1280x720', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];    
} else {
//    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif=0:-1:1', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
    args = ['-dual_mono_mode', mode, '-i', input, '-vf', 'yadif', '-preset', 'veryfast', '-aspect', '16:9', '-c:v', 'libx264', '-crf', '23', '-f', 'mp4', '-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2', output];
}`

一部ミスしていたので書き直し。これで今エンコードできています。

**Comment by arkmarou** [comment]
他の方の設定を見ることができたため、自分でちょっといじってみました。

`config.json`

https://github.com/l3tnun/EPGStation/blob/035725c9665b84801c8d83f47dcec7c41efff322/config/config.sample.json#L17-L29

この部分は

```
    "encode": [
        {
            "name": "H264 (60p)",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe %ROOT%\\config\\enc.js 60p",
            "suffix": ".mp4",
            "default": true
        },
        {
            "name": "H264 (30p)",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe %ROOT%\\config\\enc.js 30p",
            "suffix": ".mp4"
        },
        {
            "name": "H264 (24p)",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe %ROOT%\\config\\enc.js 24p",
            "suffix": ".mp4"
        }
    ],
```

このように変更。

`enc.js`

https://github.com/l3tnun/EPGStation/blob/035725c9665b84801c8d83f47dcec7c41efff322/config/enc.js#L4-L7

この部分は

```
let mode = 'main';
if(process.argv.length >= 3 && (process.argv[2] === '60p' || process.argv[2] === '30p' || process.argv[2] === '24p')) {
    mode = process.argv[2];
}
```

このように変更。

https://github.com/l3tnun/EPGStation/blob/035725c9665b84801c8d83f47dcec7c41efff322/config/enc.js#L13-L20

この部分は

```
let args;
if(mode == '60p'){
    if(videoHeight > 720) {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    } else {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    }
}else if(mode == '30p'){
    if(videoHeight > 720) {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    } else {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    }
}else if(mode == '24p'){
    if(videoHeight > 720) {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    } else {
        args = ['-dual_mono_mode', mode, '-i', input, (省略), output];
    }
}

let child = spawn(ffmpeg, args);
```

このように記載することで、条件分けしたエンコードをすることができました。

ありがとうございました。

**Comment by l3tnun** [comment]
解決したようなので閉じます

**Comment by ohmsa** [comment]
すごく今更ですが、これ本来は「音声を主音声副音声どちらを残してエンコードするかの場合分け」だったんですね。
