### ISSUE TITLE
サムネイルの再生成について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#127]
先ほどはお騒がせいたしました。

今回いろいろ触っているうちに「config//config.sample.jsonが存在するのでgit pull出来ません」というエラーが出て0.8.4からアップデートできていなかったことがわかりました。該当ファイルをリネームしたところ1.0.4にアップデートでき、いろいろ機能が増えていることに気づきました。

早速調べてクリーンアップを試したところ、これまでのサムネイルファイルまできれいに消えてしまいました。

後でドロップした録画データを消したりするのにサムネを使っていたので、サムネイルが消えたのは困りました。

もう一度サムネイルを再生成する機能をつけることは可能でしょうか。

**Comment by ohmsa** [comment]
クリーンアップで消していない番組のサムネイルまで消してしまうのは仕様、ということでしょうか・・・・・・

**Comment by l3tnun** [comment]
> クリーンアップで消していない番組のサムネイルまで消してしまうのは仕様、ということでしょうか・・・・・・

そのような仕様ではありません。
データベース上に ts ファイルもしくはエンコード済み (encoded) ファイルが登録されていて、実際にはファイルが存在しない場合にサムネイルが削除されるようになっています。

```git clean -f``` のような操作をしないと消える事はありません。

**Comment by l3tnun** [comment]
サムネイル再生成機能を追加しました。
ご確認ください。

**Comment by l3tnun** [comment]
肝心な使用法を書いていませんでした。
```http://<ip address>:<port>/api/debug``` にアクセスし swagger ui 上の ```/recorded/thumbnail``` のプルダウンをクリックして ```Try it out``` をクリックすれば動きます。

**Comment by ohmsa** [comment]
ご対応ありがとうございます。

早速アップデートし、試してみようと思います。

サムネが消えた理由が謎ですが、これで対処できます。

**Comment by l3tnun** [comment]
手順が一部抜けていました。
Try it out をクリック後 ```Execute``` をクリックですね。

**Comment by ohmsa** [comment]
お世話になっております。

recorded IDが必要のようですが、これはどのような値が必要なのでしょうか。

**Comment by l3tnun** [comment]
それは ```/recorded/thumbnail``` ではなく ```/recorded/{id}/thumbnail``` を見ているように思えるのですが、どうでしょうか？

**Comment by ohmsa** [comment]
Ver１．０．４のままだったので、あげてからやり直しました。

今のところ消えてしまった過去録画のサムネ再生成はできていないようです。

**Comment by l3tnun** [comment]
> 消えてしまった過去録画

これって epgstation 上で ts or エンコード済みファイルが見えているんですよね？

そうであれば ```/recorded/thumbnail``` を叩けば再生成されるはずです

**Comment by l3tnun** [comment]
再生成ではなく新しい録画ではサムネイルは作成 & 表示されていますか？

あと ```/recorded/thumbnail``` 実行時の Operator のログを貼っていただきたいです

> h264は24pでエンコードしているためハイビジョン放送は新ウェブプレイヤーでは再生できないようですが

それは正しい mp4 フォーマットでエンコード出来ていないだけです。

**Comment by l3tnun** [comment]
> operatorログですが、一旦ログ消してからサムネイル再生成してログを貼れば良いでしょうか。

それでもいいですし、```/recorded/thumbnail``` を叩いた際 ```logs/Operator/system.log``` に

```
[2018-07-22T11:31:02.493] [INFO] system - start regenerate thumbnail request
[2018-07-22T11:31:02.496] [INFO] system - regenerate thumbnail request completed
```

といったログは必ず出力されるので ```start regenerate thumbnail request``` 以降のログで ok です。

**Comment by ohmsa** [comment]
確認したところ、1706番から降順で
[2018-07-22T11:05:26.170] [INFO] system - regenerate thumbnail: 2
[2018-07-22T11:05:26.170] [INFO] system - push thumbnail: 2
[2018-07-22T11:05:26.170] [INFO] system - regenerate thumbnail request completed

というログは出ています。一方でサムネイルフォルダには新しいものしか入っていないようです。
サムネイルフォルダをconfig.jsonで変えているのですが、再生成時のサムネイルフォルダはconfig.json記述の場所で会っておりますでしょうか。

もう一度一旦ログ消しからサムネイル再生成してみます。

**Comment by l3tnun** [comment]
```
[2018-07-22T11:54:27.776] [INFO] system - start regenerate thumbnail request
[2018-07-22T11:54:27.779] [INFO] system - regenerate thumbnail: 617
[2018-07-22T11:54:27.779] [INFO] system - push thumbnail: 617
[2018-07-22T11:54:27.787] [INFO] system - regenerate thumbnail request completed
[2018-07-22T11:54:28.276] [INFO] system - create thumbnail: 617
[2018-07-22T11:54:28.276] [INFO] system - add thumbnail: 617
```

これは recordedId のサムネイルが再生成されたときのログですが、通常であれば ```regenerate thumbnail request completed``` の前後に

```
create thumbnail:  xxx
add thumbnail: xxx
```

と表示されるはずです。

> サムネイルフォルダをconfig.jsonで変えているのですが、再生成時のサムネイルフォルダはconfig.json記述の場所で会っておりますでしょうか。

config.json の ```thumbnail``` オプションのことでしょうか？
```thumbnail``` オプションでサムネイルの保存場所を変更しても問題なく再生成されますよ。(上記のログがその状態です)

**Comment by ohmsa** [comment]
SwaggerUI上でExecuteを押すとExecute/Clearの表示になり、ここでExecuteを押すと過去に向かって2番組分再生成され適用されることを確認しました。Swagger側ではLoadingがくるくる回り、すぐに終了します。

ログファイルを添付します。
[system.log](https://github.com/l3tnun/EPGStation/files/2216691/system.log)

**Comment by l3tnun** [comment]
２つしか再生成されていないようですね。
コードの方を少し見てみますのでお待ち下さい。

**Comment by ohmsa** [comment]
サムネイルフォルダを見るに、新しいものから古い方へ2つ、ランダムに1-2つで一度実行するたびに3-4サムネが作られるようです。

**Comment by l3tnun** [comment]
master 最新にて修正を加えました。
これで大丈夫なはずです。
ご迷惑おかけしました。

**Comment by ohmsa** [comment]
早速の対応ありがとうございます。

PS C:\EPGStation> git pull
error: Your local changes to the following files would be overwritten by merge:
        package.json
Please commit your changes or stash them before you merge.
Aborting
Updating a1951ce..dd7687a

と出ますが、package,jsonは全部で1000超あります。当方の環境の不具合でしょうか。

**Comment by l3tnun** [comment]
package.json が 1000 個とは一体どのような状況なのでしょうか？

```
git checkout package.json
```

とでも実行すれば package.json のコンフリクトは解消されると思います。

git の問題なのでこちらではわかりませんね。

**Comment by ohmsa** [comment]
ありがとうございます。
git checkout package.json
で解消しました。

**Comment by ohmsa** [comment]
ver

**Comment by ohmsa** [comment]
ver1.0.6にしたところサムネイルがモリモリ再生成されていることを確認しました。
対応ありがとうございました。

**Comment by ohmsa** [comment]
１つ原因に思い当たる節が出てきました。

録画フォルダをD:\DTVとして、サムネフォルダをD:\DTV\Thumbフォルダにしていました。
この状態でクリーンアップかければD:\DTV\Thumbが消されるのも当然です。

サムネフォルダを映してクリーンアップかけてみようと思います。

**Comment by l3tnun** [comment]
そのようなディレクトリ構成では消えますね

**Comment by ohmsa** [comment]
重ね重ね対応ありがとうございました。
