### ISSUE TITLE
アップロード機能について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#132]
#83 
1．エンコード済みmp4であってもTSとしてアップロードされるためWebプレイヤー再生ができません
　 mp4として扱われるオプションが欲しいです。

2．アップロード時に日付や時刻、チャンネル等指定するので、それらから番組名を生成
　（config.json準拠で）してそれを基に名前を付けてアップロードできるとありがたいです。

お手数おかけしてばかりですみませんが、1番だけでもお時間のある時にでも検討していただければ幸いです。

**Comment by l3tnun** [comment]
> 1．エンコード済みmp4であってもTSとしてアップロードされるためWebプレイヤー再生ができません
　 mp4として扱われるオプションが欲しいです。

画面右下に表示されている + ボタンを押してエンコードファイルとしてアップロードしてください。

![2018-07-22 19 42 52](https://user-images.githubusercontent.com/16516088/43044753-7b7cf9a4-8de7-11e8-8724-a3dcec3a23d8.png)

> 2．アップロード時に日付や時刻、チャンネル等指定するので、それらから番組名を生成
> 　（config.json準拠で）してそれを基に名前を付けてアップロードできるとありがたいです。

アップデートされるファイルが TS だけなら番組情報を取り出しそのようなことも可能ですが、そうではありませんので無理です。

**Comment by ohmsa** [comment]
１．
すみません、右下の＋に気づきませんでした。

2.　TSファイルからではなく、入力中の番組情報からconfig.jsonにのっとった番組名生成は不可能でしょうか。例えば、
201807220900-ゲゲゲの鬼太郎【蟹坊主と古の謎】 #17[字][多][デ]_フジテレビ
の場合、この内
【yyyymmddhhmm】-【ルール名】_【放送局】
の部分を作れればと思いまして。

**Comment by ohmsa** [comment]
すみません【ルール名】はすなわち番組名ではありませんでした。
config.json上で
%YEAR%%MONTH%%DAY%%HOUR%%MIN%-%TITLE%_%CHNAME%
の場合、入力中の番組情報から
201807220900-%TITLE%_フジテレビ
までを名前として生成しておき、%TITLE%だけ編集すれば良い状態にしておければ手間が省けるのではと思いました。

**Comment by l3tnun** [comment]
recordedFormat で必要なプロパティが入力情報だけではいくつか足りないため難しいです。

**Comment by ohmsa** [comment]
すみません説明不足でした。
手入力でフォーマットまで合わせて入力する波照間なので、いくつか足りない情報だけ手入力したい、という意味でした。

**Comment by l3tnun** [comment]
んん？？やりたいことがよくわかりません。

現状はアップロード時にファイルを選択し、そのままの名前で recorded へ保存します。
重複時は (1) 等をつけてリネームしますが。

**Comment by advancedbear** [comment]
>入力中の番組情報からconfig.jsonにのっとった番組名生成は不可能でしょうか。

横槍になりますが、ohmsaさんの仰っている`番組名`の概念そのものがEPGStationで定義される`番組名`の定義と異なっているように感じます。

EPGStationにおいて通常、`番組名`という単語は`api/schedule/detail/{id}`や`api/recorded/{id}`で取得できる番組情報の`name`項目を指します。  
ですので、`番組名生成`という概念はアップロード画面における`タイトル`がこれに該当します。  

ですが、ohmsaさんの書き込みを見る限り、
>config.json上で
%YEAR%%MONTH%%DAY%%HOUR%%MIN%-%TITLE%_%CHNAME%
の場合、入力中の番組情報から
201807220900-%TITLE%_フジテレビ
までを名前として生成しておき

というように、保存されるファイル名のことを`番組名`と仰っているように感じられます。  
ですので、要望として正しく記述するのであれば
#### ファイルアップロード時にrecordedFormatに合わせたファイル名に投稿して欲しい
ということかと思われます。  

実フォルダを参照してソートする場合などでは、確かにファイル名のフォーマットが揃っている方が好都合だなとは感じますが、もともとこの機能が想定されていたユースケースが「EPGStation上やKODI上で編集済み動画を見たい」というものだったと思うので、実ファイルを触るケース自体が考慮外な気がします。
実フォルダを参照してファイル名を扱う用途ならば、EPGStationを介さずに一般のリネームソフトを使ったほうが遥かに速い上に便利なのではないかなと思いますが……。

**Comment by advancedbear** [comment]
と、上記のコメントを書き込んでからふと気付いた解釈ですが、もしかして
「アップロードするファイル名を`recordedFormat`を基準にパースすれば、`recordedFormat`に含まれている情報は自動入力できるのでは？」という発想でしょうか

斬新な発想とは思いますが事故率が高そうですね……。  
`recordedFormat`と異なるフォーマットのファイル名を渡されたことをどう判別するのかとかいろいろ課題は多そうですがどうなんでしょう。

**Comment by ohmsa** [comment]
度々説明が足りずすみません。大体advancedbear氏の仰る感じで、
地デジ及びBSはニコニコ実況つきで視聴したいので、m2tsファイルをTVTest+TVTPlay+NicoJKで再生しております（いずれwebプレイヤーにニコニコ実況ログ取得＆再生機能をつけられればと勉強中です）。この関係で直接ファイルを触るので、ファイル名（私の言う番組名）をきちんとしておきたいというのと、いずれHDDがいっぱいになったらBDなりHDDなりに退避させる可能性があるのでその際にもファイル名を揃えたいと思いました。

今回は偶々別PCで録画されていたのですが、ファイル名が
--1-20180722-0900-8.mp4
であったためこれを
201807220900-XXXXXX（今更伏せ字）_フジテレビ.mp4
としてアップロードすることとしました。名前を変えてから項目を入れていたのですがこの時に
・どのみち日にち時刻を入れるのであればそこから他のきちんと録画されたファイル名と整合性のあるファイル名でアップロードしたい（できる限りきちんと録画された体でアップロードしたい）
というのと
・それが無理（必要性を感じられない）でもせめてconfig.jsonで記述したフォーマットをあげればそこから分かる範囲で必要項目が入力出来れば
と思いました。

説明が足りなすぎたのと、そもそも作者が想定していなかった（生ファイルを弄る）ケースということ理解致しました。重ね重ねお詫び申し上げます。
