### ISSUE TITLE
Basic認証のユーザー数を追加する

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#133]
Nodeは触りますがJavaScriptばかりでTypeScriptに触れていないのでInterface廻りがサッパリ分からないのですが、下記のような感じに変えて複数ユーザーでBasic認証行っています。
（fork先のコードをインラインで貼り付けられないのでこのような形ですみません）

##### https://github.com/advancedbear/EPGStation/blob/multiuser-auth/src/server/Service/Server.ts#L42
```diff
  // basic auth
  const basicAuthConfig = config.basicAuth;
  if (typeof basicAuthConfig !== 'undefined') {
-      this.app.use(BasicAuth(basicAuthConfig.user, basicAuthConfig.password));
+      this.app.use(BasicAuth(basicAuthConfig));
  }
```

##### https://github.com/advancedbear/EPGStation/blob/multiuser-auth/src/server/Service/BasicAuth.ts#L9-L12
```diff
- export default (user: string, pass: string) => {
+ export default (users: {}) => {
      return (request: express.Request, response: express.Response, next: express.NextFunction): 
      express.Response | void => {
          const result = auth(request);
-         if (typeof result === 'undefined' || result.name !== user || result.pass !== pass) {
+         if (typeof result === 'undefined' || !users[result.name] || result.pass !== users[result.name]) {
```

##### config.json
```json
"basicAuth": {
    "user1": "password1",
    "user2": "password2",
    "user3": "password3"
}
```

ユーザー名とパスワードをkey:valueの関係にするのがマトモかどうかはともかく、複数ユーザーの認証に対応していただけると助かります。  
家族間であってもユーザー名とパスワードをシェアするのはなんとなく気持ち悪いので……。

**Comment by l3tnun** [comment]
一度決めた仕様を変更する事は利用者に混乱を招くのでなるべくやりたくないです。
現状の ```basucAuth``` の仕様と両立可能な方法があれば修正します。

**Comment by advancedbear** [comment]
確かに、既存の`basicAuth`コンフィグパラメータのままでは確実にエラーを吐く変更ですので、知らずにアップデートしたユーザーに混乱を与えそうですね。  
私自身は、npmのbasic-authを使った複数ユーザーの認証方法はこの手の方法しか知らないです。
既存のコンフィグに変更を加えずにとなると、別パラメータを作ったりということになりそうですが、同一目的のオプションが別パラメータに存在するのはこれまた混乱の種ですね。

そういった制約を含めて考えると意外と難しい内容だと分かったので、必要に応じて自分の環境のみで行うようにします。

### P.S.
他に同様のことをしたい人が居るかはわかりませんが、最初の投稿のコードは動作はしますがビルド時にInterface廻りで怒られるので、コピペして使うのはやめましょう。
