### ISSUE TITLE
ファイルをアップロードするときに必要な項目を赤字で表示

### ISSUE THREAD

**Issue by arkmarou** [l3tnun/EPGStation#136]
いつも便利に使わせていただいております。

データベースに登録されていないファイル・フォルダーはクリーンアップで削除されてしまうため、手動でファイルを追加しようと思っています。
この際、`必要な項目が入力されていません。`と表示され、どの項目が必要なのかがわからずアップロードができません。

こちらについて、必要な項目にアスタリスクを表示させたり、未入力の項目を赤字で指摘したりできますでしょうか？

よろしくお願いいたします。

**Comment by l3tnun** [comment]
入力必須項目に※追加し、赤色で強調するように修正しました。

> 未入力の項目を赤字で指摘

こちらは実装が複雑になるので行いません。
