### ISSUE TITLE
番組表の改善について

### ISSUE THREAD

**Issue by unicode45** [l3tnun/EPGStation#138]
### 環境
* Version of EPGStation: `1.0.8`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.11.3
* Version of NPM: `5.6.0`
* **OS: Debian Stretch
* Architecture: x64

### Issue
いつも愛用させていただいています。本日は主にユーザビリティの面でお聞きしたいです。

①ライブ視聴について
「番組表」で気になる番組が放送中の場合、
リアルタイム視聴のために
1. メニュー＞「ライブ」選択
2. 番組の種類（GR/BS/CS）を選択
3. 該当番組へ移動・クリック
4. ポップアップで配信方法を選択し、「視聴」をクリック
を繰り返していますが、直接番組表のポップアップに視聴を追加し、直接配信させることはいかがでしょうか？

②番組表の曜日変更
最大24時間表示になっているため、表示する曜日を変更するには
1. 右上の🕓アイコンをクリック
2. 放送種類・曜日・時間などを選択
3. 「表示」ボタンをクリック
の3つのDepthになっています。種類や時間などはそのままに曜日だけを素早く移動できるようにメニュー上にワンクリックで移動可能な曜日切り替えのドロップダウンや◀▶ボタンを設けてはいかがでしょうか？

ご検討のほどお願いいたします。

**Comment by l3tnun** [comment]
ライブ視聴について

番組表からは局名をクリックすればポップアップが表示されますが、それではだめでしょうか？

![2018-08-02 18 22 57](https://user-images.githubusercontent.com/16516088/43575237-4d9c1946-9681-11e8-9458-0cc6ced1b743.png)

----

> 種類や時間などはそのままに曜日だけを素早く移動できるようにメニュー上にワンクリックで移動可能な曜日切り替えのドロップダウンや◀▶ボタンを設けてはいかがでしょうか？

便利そうですがメニュー部分にこれ以上アイコンは増やせないですし、EMWUI のように局名の上の部分にヘッダーのを追加して時刻を移動できるようにするのはいいのですが、モバイル端末で見た際に番組表の表示エリアが狭くなるのでやりたくないです。

**Comment by l3tnun** [comment]
まああと、番組表って見た目より複雑極まりないのであんまり弄りたくないってところですかね。

**Comment by unicode45** [comment]
早速ご返答ありがとうございます。

> ライブ視聴について
> 番組表からは局名をクリックすればポップアップが表示されますが、それではだめでしょうか？
勉強不足で失礼しました。こちらを使わせていただきます。

>まああと、番組表って見た目より複雑極まりないのであんまり弄りたくないってところですかね。
ドロップダウンは幅も必要ですが、現在Staticテキストの「番組表BS 08/02(木)」自体をドロップダウンにするか、せめて◀▶ボタンで前日・翌日へ移動できればと思います。
ご検討のほど、お願いいたします。

**Comment by l3tnun** [comment]
> 現在Staticテキストの「番組表BS 08/02(木)」自体をドロップダウンにするか、せめて◀▶ボタンで前日・翌日へ移動できればと思います。

ああ、header のタイトル部分のところですか
この部分はプルダウンを配置することを念頭に置いて作られていないのでできるかわからないですね。
多分ポップアップを追加して対応することになると思います。

**Comment by l3tnun** [comment]
feature-138 ブランチにてこのようになりました

![2018-08-02 21 07 11](https://user-images.githubusercontent.com/16516088/43582686-284c4e56-9698-11e8-9224-8c3360f5c063.png)

クリックすると該当の日付に移動します。
問題なければマージします

**Comment by unicode45** [comment]
> feature-138 ブランチにてこのようになりました

素早いご対応ありがとうございます。使いやすく、嬉しい限りです。
引き続きよろしくお願いいたします。

**Comment by l3tnun** [comment]
master へマージしたので閉じます。
