### ISSUE TITLE
【報告】Webプレイヤー上で再生できないmp4が存在する

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#142]
### 環境
* Version of EPGStation: `不明（drop数表示等あり/どうやって調べればよいのでしょう）`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.11.3`
* Version of NPM: `6.2.0`
* OS:Windows 10 pro
* Architecture: x64

### Issue
　・エンコード負荷低減のため、エンコード設定でQSVを使用するようにしてみたところ、出来上がった一部mp4がWebプレイヤー上で再生できない
　・ローカルではすべて再生可能

◆症状（mp4ファイルについて）
　・Webプレイヤー上では読み込みの円が回るが、送信元のタスクマネージャを見ても送信が増えない
　・Webプレイヤー上で再生できない番組でもmpc-hcやスマホのMXプレイヤーでは再生可能
　・AT-Xやテレ朝チャンネル等CSの番組はWebプレイヤー上で再生可能
　・地デジ ：Eテレ、総合の番組を除きWebプレイヤー上で再生不可
　・BS　　：BS1、BSプレミアムの番組を除きWebプレイヤー上で再生不可

◆再生不可の例
[201807221000-キラッとプリ☆チャン「心の迷いを抜けてみた!」[字][デ]_テレビ東京１.mp4]
1280x720 8Bit AVC/H.264 High@3.1 1:1 Progressive 24.00fps 29598f 4462.41kb/s
MPEG4-AAC 48.00kHz 16Bit 2ch 255.66kb/s
[Extra][2]
ISO Base Media v1
MetaData
[MPEG4] 00:20:33.250 (1233.250sec) / 728,060,414Bytes

[201807212330-ゆらぎ荘の幽奈さん 第2話「温泉卓球の幽奈さん」_ＢＳ１１イレブン.mp4]
1280x720 8Bit AVC/H.264 High@3.1 1:1 Progressive 24.00fps 43285f 3205.15kb/s
MPEG4-AAC 48.00kHz 16Bit 2ch 255.70kb/s
[Extra][2]
ISO Base Media v1
MetaData
[MPEG4] 00:30:03.541 (1803.541sec) / 781,305,351Bytes

◆再生可の例
[201807212150-[生]2018 F1グランプリ 第11戦 ドイツGP 公式予選_フジテレビＮＥＸＴ.mp4]
1280x720 8Bit AVC/H.264 High@3.1 1:1 Progressive 24.00fps 144093f 7971.40kb/s
AAC 48.00kHz 2.0ch(2/0 L+R) LC 252.37kb/s
[Extra][2]
ISO Base Media v1
MetaData
[MPEG4] 01:40:03.875 (6003.875sec) / 6,176,551,350Bytes

[201806051729-キラッとプリ☆チャン「ワタクシ、チャレンジしてみましたわ!」_ＢＳジャパン.mp4]
1280x720 8Bit AVC/H.264 High@3.1 1:1 Progressive 29.97fps 52217f 1560.29kb/s
AAC 48.00kHz 2.0ch(2/0 L+R) HE(LC) 191.51kb/s
[Extra][2]
ISO Base Media v1
MetaData
[MPEG4] 00:29:02.307 (1742.307sec) / 383,411,761Bytes
※エンコード設定変更前

真空波動研Lite 180519 / DLL 180519 Unicode

◆エンコードパラメータ
QSVのLA-ICQでエンコード。24pにテレシネ変換
args = ['-i', input, '-global_quality', '26', '-c:v', 'h264_qsv', '-s', '1280x720', '-vf', 'pullup', '-r', '24', '-c:a', 'copy', output]; 

※201806051729-キラッとプリ☆チャン「ワタクシ、チャレンジしてみましたわ!」_ＢＳジャパン.mp4のみEPGStationデフォルトのh264設定を使用

ローカルやＭＸプレイヤーでは再生できることから、Webプレイヤー側に何かあるのかと思い報告させていただきます。

※追伸
再生できるｍｐ4も、Ｗｅｂプレイヤー上でボタンやシークバーでスキップすると「動画がスキップされて再生されているのに読み込みマークがぐるぐる回り続ける」状態になります。24ｐ/60i問わずのようです。

**Comment by ohmsa** [comment]
失礼いたしました。上記の事例、Microsoft Edgeで確認していたのですが、Vivaldiでは再生もスキップも問題なくできました。Microsoft Edgeだけの問題のようです。

お騒がせいたしました。

**Comment by ohmsa** [comment]
Internet Explorerでも民放チャンネル番組の24p変換mp4再生不可・再生できる動画でもスキップ時のグルグル問題を確認しました。

IE系と相性が悪いようです。

**Comment by l3tnun** [comment]
EPGStation の version は package.json  の version を確認するか、```/api/debug``` にアクセスすればわかります。

動画の再生能力は各 Web ブラウザに依存しますので、EPGStation の問題では無いです。

**Comment by ohmsa** [comment]
1.1.0でした。ありがとうございます。
結局のところ、「enc.jsにて音声をcopyにしている」と、
・民放（地デジ、BS）はＷｅｂプレイヤーで音が出ない（Ｃｈｒｏｍｅ系）
・民放（地デジ、BS）は再生できない（ＩＥ系）
ということが判りました。

これまで、少しでも早くエンコードができるように
'-c:a', 'copy'
としていましたが、元の
'-c:a', 'aac', '-ar', '48000', '-ab', '192k', '-ac', '2'
に戻したところこれまで再生できなかったチャンネルの動画が再生できることを確認しました。

一つ気になるのは、IE系で再生中、（音声付きで再生できるmp4であっても）スキップするとグルグルマークが再生終了まで消えないことです。クライアント側は複数のPCで確認しましたが、鯖側は1台だけなのでおま環かもしれませんが……
