### ISSUE TITLE
【提案】タスク確認・管理UIの導入について

### ISSUE THREAD

**Issue by unicode45** [l3tnun/EPGStation#143]
### 環境
*Version of EPGStation: 1.0.8
*Version of Mirakurun: 2.7.1
*Version of Node: `v8.11.3
*Version of NPM: 5.6.0
*OS: Debian Stretch
*Architecture: x64

### Issue
現在「競合」でチューナー数の上限越えは確認できますが、その他の
・録画中
・（ライブ）配信中
・エンコード中
・使用中のチューナー数
等の状況やタスクが見られ、進捗確認やタスクのON/OFF（一時中止、中断、再開）が出来るUIの導入予定はありませんでしょうか？
ライブ配信はメニューに配信停止が設けられていますが、エンコード等は進捗確認のためにプロセスを見る必要があるため、これらのタスクをWeb上で確認、制御できるUIがあればと思いました。

ご検討のほど、お願いいたします。

**Comment by l3tnun** [comment]
録画中に関してはトップ or 録画済みページにてサムネイルが生成されていないもの ≒ 録画中となるので必要性があまり感じられないです。

---

エンコードに関してですが現状は、トップ or 録画済みページの各録画番組のメニューにてエンコード中 or エンコード待ちのものは停止できるようになっています。
確認に関しては各録画の詳細にてビデオリンクが灰色になっている項目がそれに当たります。

エンコード中、エンコード予定のリストが確認できることは便利だと思いますのでそれらが確認できるようなページを追加したいと思います。

---

使用中のチューナは Mirakurun によって抽象化されて EPGStation 側ではどのチューナを使用しているかは全く意識していません。
そのため、EPGStation 側で使用中のチューナ数や使用中のチューナを確認するような機能を追加する予定はありません。

**Comment by unicode45** [comment]
新設なご説明ありがとうございます。

> エンコード中 or エンコード待ちのリストの確認や、それらのまとめてキャンセル等できることは便利だと思いますので、エンコード状況を管理するページを追加したいと思います。

その際にはよろしくお願いいたします。

**Comment by l3tnun** [comment]
最新の master にてエンコード待ち状態、キャンセルするページを追加しましたので close します
