### ISSUE TITLE
【報告】Windows版でアップデート時にPowerShelの表示が停止する？

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#146]
### 環境
* Version of EPGStation: `1.1.1`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.11.3`
* Version of NPM: `6.2.0`
* OS:Windows 10 pro
* Architecture: x64

### Issue
手順にあるように以下の流れでアップデートを行いました。
 $ git pull
 $ npm update
 $ npm update -D
 $ npm run build
最後のrun buildのところで、
[01:33:35] Finished 'build-server' after 58 s
のあたりでPowerShellの表示が止まりました。終わるのを待っていましたが、なかなか動かないためフリーズしていないかEnterを押してみたところ

[01:34:19] Version: webpack 4.8.3
Built at: 2018-08-25 01:34:18
 Asset      Size  Chunks                    Chunk Names
app.js  1.19 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = app.js
[01:44:36] Finished 'build-client' after 12 min
[01:44:36] Starting 'build'...
[01:44:36] Finished 'build' after 17 μs

と続きが表示され、サービスからEPGStationを再起動したところ無事アップデートされているようです（Enterを押したのは1：４４頃）。

今回だけではなく、以前にも同じようなことがあったように記憶しております。インストール作業中に何らかの入力待ち状態が発生しているのでしょうか。

**Comment by l3tnun** [comment]
> インストール作業中に何らかの入力待ち状態が発生しているのでしょうか。

```npm run build``` はソースからビルドする部分ですが、特に入力待ち状態が発生するようには作られていません
gulp or webpack 周りのバグかも知れませんが EPGStation 側では特にできることはないのでこの issue は閉じます

**Comment by ohmsa** [comment]
確かにビルド部分は手を出しようがないですね。
