### ISSUE TITLE
【要望】局・時間指定録画予約機能

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#147]
お世話になります。

現在EPGStationの録画予約は番組単位であり、局・時間指定での録画ができないと思います。
例えば本日の24時間テレビのような非常に長大な番組をすべて録画する必要はない場合、局・時間を指定して必要な箇所だけを録画できると助かります。

ご検討よろしくお願いします。

**Comment by l3tnun** [comment]
最新の master にて追加しました。

番組表 -> 適当な番組をクリック -> 詳細 -> 時刻指定予約トグル on

以上の手順で時刻を指定しての予約ができるようになります。

注意点は以下となります
・EPG情報を使用した予約ではないため、番組表に表示されない
・EPG情報を使用して自動的に番組タイトル等は更新されない
・番組が延長しても追従しない

録画マージンは config.json で以下の設定をしてください。

- timeSpecifiedStartMargin
手動予約時の開始マージン(秒)

- timeSpecifiedEndMargin
手動予約時の終了マージン(秒)

何か問題があれば再度オープンしてください。

**Comment by Ahilu** [comment]
すみません関連しそうな項目でしたので、ここにコメントさせてもらいます。
平日だけ局・時間指定で録画をしたいのですがそういうことはできますでしょうか？
具体的には、平日に放送があります紙うさぎロペのあたりの時間だけＣＸのめざましテレビを録画したいというものなのですが。。。

**Comment by l3tnun** [comment]
見落としていました。すいません。
現状その様なの機能ありません。

機能追加を検討します。

**Comment by l3tnun** [comment]
v2.0で時間指定のルールが作成できるようになり、対応できるようになりました。
ですので、閉じます。
