### ISSUE TITLE
除外キーワードの正規表現が効かない

### ISSUE THREAD

**Issue by takuo** [l3tnun/EPGStation#150]
### 環境
* Version of EPGStation: `1.0.4`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.11.4`
* Version of NPM: `5.6.0`
* OS: ubuntu `18.04`
* Architecture: `x64`
* MariDB: `10.3`

### Issue

自分が仕様を誤解しているのかもしれませんが、除外キーワードの正規表現が効かないようです。

画像を添付します。

![epgstation-ignore-keyword](https://user-images.githubusercontent.com/109764/44940249-e7ddc200-adc6-11e8-8a7f-61eb82266d73.png)

**Comment by takuo** [comment]
補足となりますが、検索対象に「概要」が含まれてるかどうかで結果が変わってきました。
おそらくですが、「キーワード」、「除外キーワード」それぞれで検索対象を選択できるようになると期待する結果を得られそうす。

**Comment by l3tnun** [comment]
除外キーワードでは正規表現が使用できないようになっています
キーワード部分で not を使えば十分かなあと作成当初はぼんやり思っていましたが、対応したほうが良さそうなので対応します

あとコードを見て気がついたのですが、概要、タイトル、詳細を複数選択時に除外キーワードが正しく機能していないようなので修正します

今こちらの制作に割く時間があまりないので遅くなります

**Comment by takuo** [comment]
正規表現つかえるだけでも助かりました。
ありがとうございます。

**Comment by l3tnun** [comment]
最新の master にてキーワードと除外キーワードのそれぞれでオプションの指定ができるようになったので閉じます

**Comment by subarashi896** [comment]
除外キーワードを複数追加することは可能ですか？
