### ISSUE TITLE
【要望】バッチ機能の追加

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#152]
### 環境
* Version of EPGStation: `1.1.1`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.11.3`
* Version of NPM: `6.2.0`
* OS:Windows 10 pro
* Architecture: x64

### Issue
現在バッチ的に処理できるのは「録画済み番組」の「編集」からの複数番組削除だけですが、
・複数録画番組をまとめてエンコード
・AT-X等で同じ番組（同じ話）が録画された場合、一つに絞る
といった「現在手動で行えるが手間がかかる」作業を自動化出来ると便利そうだと感じました。

・複数録画番組をまとめてエンコード
　-録画時はTSのみに設定したが後になってエンコードしたくなった
　-エンコードする設定だったが何故かエンコードがつまって特定の時間からエンコードされていない
　-番組の特性に合わせエンコード設定を変えた
等、後からエンコードしたくなることがあります。現在は一つ一つ手動でencodeを押していますが、「編集」機能の様に複数録画番組をクリックして一括してエンコードキューに入れることは可能でしょうか。（ついでですが、後からｅｎｃｏｄｅを選択するとTS削除が選べないので追加していただけますと幸いです）
また、気づかずエンコードされていない番組（TSしか存在しない番組）を見つけ出してエンコードする事が出来ればありがたいのですが、可能でしょうか。

・AT-X等で同じ番組（同じ話）が録画された場合、一つに絞る
番組名でルールを組むと同じアニメの同じ話が地デジ、BS、AT-X等で複数録画されることがあります。録れなかったときのバックアップとしては良いのですが、後になって消すのが煩雑です。例えばBS>地デジ>AT-X（容量大）>AT-X（容量小）の順番に優先順位をつけ、「BSでDropなしで録画できたら以降録画しない」「BSでドロップがあり地デジになかったらBSを削除」「BSも地デジもDropがあるが少ない方を残す」といった厳選が自動で出来たらありがたいです。
また、既に録画済み番組もDrop情報や容量、録画時間等で自動的に一つに絞れればHDDが空いて助かります。
現在「録画済み番組を排除」はありますが、おそらくDropしていたかどうか等は考慮されないと思いますので「録画後にDropを見て」判断ができれば。

以上、ご一考頂けますと幸いです。

**Comment by l3tnun** [comment]
> ・複数録画番組をまとめてエンコード
複数録画番組をまとめてエンコードですが、ソースファイルの状態が１つに定まらないため (TS ファイルが削除されていたり各録画番組ごとに状況が異なる場合が考えられるため) 無理です

> TS削除が選べないので追加していただけますと幸いです
これは追加できそうなので検討します

> また、気づかずエンコードされていない番組（TSしか存在しない番組）を見つけ出してエンコードする事が出来ればありがたいのですが、可能でしょうか。
録画検索時の条件を少し修正すればできるはずなので検討します

> ・AT-X等で同じ番組（同じ話）が録画された場合、一つに絞る
これはできなくはないですが、人によって条件が異なる (テロップが入っていたら消す等)のと、処理の内容が複雑なので (実装したとしておそらく誤爆する可能性がある) 実装する予定はないです

> 現在「録画済み番組を排除」はありますが、おそらくDropしていたかどうか等は考慮されないと思いますので「録画後にDropを見て」判断ができれば。
これは可能ですが、どのパケットがドロップしたか (EIT なのか ビデオ、音声等なのか)判断できないので判定が非常にシビアになりますね
drop, error, scrambling がある一定個数以上なら ok といった閾値の設定が必要になりそうですが、それで大丈夫なのかは人の目で見ないと何とも言えなさそうです

いくつかの機能は追加できそうですが、issue が溜まっているのでいつ実装できるか未定です

**Comment by ohmsa** [comment]
検討ありがとうございます。

>>これはできなくはないですが、人によって条件が異なる (テロップが入っていたら消す等)のと、処理の内容が複雑なので
例えばルール予約の画面に自動で残した番組を表示し、残りをゴミ箱フォルダに移動しておく、見たいなことを考えましたがゴミ箱と言う機能を実装するのも煩雑そうですね。

>>これは可能ですが、どのパケットがドロップしたか (EIT なのか ビデオ、音声等なのか)判断できないので
以前どなたかが「ドロップした前後のキャプチャを取る」ということをされておりましたが、あの方法は目から鱗でした。INFOの下部にドロップがあればその付近のキャプチャを表示する、といった機能があれば便利そうですが、ドロップだらけだった場合どこで切るか等問題はありそうです。

ドロップが扱えるとなると「ドロップが閾値を越える→自動的に録画打ち切り」等も出来そうですね。

要望ばかりで申し訳ないです。自分でも改善出きるようプログラム勉強しております。

**Comment by ohmsa** [comment]
すみません､タグの使い方を間違えたようです。

**Comment by advancedbear** [comment]
そもそも、バッチ処理的な事はすべてAPIを利用してローカルマシン上で実行すべきあって、ウェブGUIから実行するべきではないと思います。
そのためのAPIであるとも言えますし、既存APIで実現可能な機能を新規機能としてソフトウェアに追加するのは如何なものかと思います。

---

>エンコードされていない番組（TSしか存在しない番組）を見つけ出してエンコードする

これは、 `/api/recorded/{id}` で取得可能な `original` 辺りを参照することで、「TSしか存在しない番組」を抽出する事ができますから、それらを `/api/recorded/{id}/encode` に投げていくことで実現すべきと思います。
簡単なスクリプトとしては以下のような感じになるかと。

```javascript
const request   = require('request')
const epgstation = "http://localhost:8888/api" //EPGStationのAPIアドレス
var encodeQueue = [] //エンコードする番組のIDを格納する配列変数
var recordedList //録画一覧を格納する変数

request.get(`${epgstation}/recorded`, (err, res, body)=>{
    // 直近24番組の一覧を取得する
    if(!err) {
        // 録画一覧をJSONオブジェクトとして格納する
        recordedList = JSON.parse(body).recorded
        // 各録画ごとに処理を実行
        for(recorded of recordedList) {
            // 「録画中ではない」かつ「未エンコード」な番組を判定
            if(!recorded.recording && recorded.original) {
                // エンコードする番組として配列に録画IDを格納
                encodeQueue.push(recorded.id)
                console.log(`${recorded.name}をエンコードキューに追加`)
            }
        }
        console.log(encodeQueue)
        // エンコードする番組ごとに処理を実行
        for(id of encodeQueue) {
            // encodeを実行するAPIに対して録画IDを渡す
            request.post({
                uri: `${epgstation}/recorded/${id}/encode`,
                headers: {
                    "Content-type": "application/json"
                },
                // modeを切り替えることでエンコード設定を変更可能
                body: "{'mode': 0}"
            }, (e, r, b) => {
                if(e) console.error(e)
                else console.log(b)
            })
        }
    }
})
```

---

>同じ番組（同じ話）が録画された場合、一つに絞る

これも `/api/recorded/{id}` で取得可能な `name` 辺りを使えば判定できそうですし、BS・地デジの判定は `channelType` に含まれていますし、ファイルサイズも `filesize` として定義されていますから上記スクリプトと同じような感じで対処できそうな気はしますよね。
これらの情報が存在していれば同一番組同士で比較を実施して、消去して良いと思うものに対して `DELETE /api/recorded/{id}` を叩く感じで。

---

>以前どなたかが「ドロップした前後のキャプチャを取る」ということをされておりましたが、あの方法は目から鱗でした。

こちら、おそらく私のことかなと思いますが、これは全てローカルのnodeスクリプトで実行していました。
```bash
ffmpeg.exe -ss $TIME -i $MPEG2FILE -y -t 1 -r 1 -vf scale=640:360,tile=5x6 -loglevel fatal -f image2 $OUTPUT
```
といった感じにffmpegを叩くことで
![image](https://user-images.githubusercontent.com/9246266/45223282-cf533780-b2f1-11e8-8b56-e5aab47fa7d5.png)
こんな感じの画像が出力可能ですが、見て分かる通り肉眼でドロップが確認可能なサイズにするにはそれなりの大きさで表示せざるを得ず、WebGUI上で表示をすれば明らかにスペースを専有するためデメリットの方が大きいかと思います。
特にスマートフォンでの閲覧をメインに考えているEPGStationでは、大きな画像を表示するのは避けたいところでしょう。

**Comment by advancedbear** [comment]
ちなみにですが、今現在私は「ドロップした前後のキャプチャを切り出して画像にする」ということは行っていません。
以前はTSselectと連携することによってドロップ時刻を **動画再生時間ベース** で取得していたので上記のような画像が出力できましたが、EPGStationで提供されるドロップ情報は **放映時刻ベース** でのドロップ時刻がログ出力されているため、これをffmpegで解釈可能な **動画再生時間ベースでのドロップ時刻** に変換する作業が非常に煩雑であると感じたためです。

もし現在のEPGStationの現在のドロップログの仕様でこの機能を実現するのであれば、 `time: 2018/09/07 20:09:33` といった形で出力されるログデータと、 `STARTAT` から変換した時刻とを差し引きしたりする作業が必要です。
もちろん、以前と同じように録画ファイルをTSselectに渡してしまえば同様のデータが取得できますから実現可能ですが、EPGStation内でドロップカウントされているのに、再度TSselectでドロップカウントをするのはリソースの無駄だなと感じました。

なので、現在は `dropCnt` だけを参照して、ドロップ発生時には通知を出す、程度に留めています。

**Comment by l3tnun** [comment]
> そもそも、バッチ処理的な事はすべてAPIを利用してローカルマシン上で実行すべきあって、ウェブGUIから実行するべきではないと思います。
> そのためのAPIであるとも言えますし、既存APIで実現可能な機能を新規機能としてソフトウェアに追加するのは如何なものかと思います。

ごもっともな指摘だと思います。
そのため、最新の master にて手動エンコード追加時の TS 削除オプションの追加だけを行いました。

あとは特に追加できそうな機能がありませんので閉じます。
