### ISSUE TITLE
【要望】無変換配信によるデュアルモノ番組について

### ISSUE THREAD

**Issue by Rihy** [l3tnun/EPGStation#156]
### 環境
* Version of EPGStation: `1.1.1`
* Version of Mirakurun: `2.5.7`
* Version of Node: `v7.10.1`
* Version of NPM: `6.2.0`
* OS:Win10 Pro
* Architecture: x64

### Issue
KodiとIPTV Simple Clientでライブ視聴していますが、デュアルモノ番組だとステレオとして扱われ二重に聴こえてしまいます。

Config.jsonの無変換部分にデュアルモノ番組のみ片側音声だけ配信というコマンドを実装して頂きたいです。

ご検討宜しくお願い致します。

**Comment by l3tnun** [comment]
それは EPGStation の問題ではなく ffmpeg の設定の問題です

```JSON
"mpegTsStreaming": [
    {
        "name": "dual mono main",
        "cmd": "%FFMPEG% -re -dual_mono_mode main -i pipe:0 -c:a aac -ar 48000 -ab 192k -ac 2 -c:v copy -tune fastdecode,zerolatency -f mpegts pipe:1"
    }
]
````

このように設定しましょう

もしくは [dual mono 対応 Kodi](https://github.com/0p1pp1/xbmc) を自前でビルドして使用してください
