### ISSUE TITLE
番組表のチャンネルの並び替えが正常に行われない

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#157]
### 環境
* Version of EPGStation: `1.1.3`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.12.1`
* Version of NPM: `6.4.1`
* OS: Debian Stretch
* Architecture: x64
* Tuner: PT2 (recdvb)

### Issue
素晴らしいソフトをご提供くださり、ありがとうございます。
チャンネルの並び替えに不具合があるようなので報告いたします。

config.jsonにて
"serviceOrder": [1024, 1032, 1040, 1064, 1048, 1072, 1056, 23608, 23610, 24632, 27704],
のように設定しましたが、本来
NHK総合、NHKEテレ、日テレ、テレ朝、TBS、テレ東、フジ、MX1、MX2、tvk、チバテレ
となるべきところ、実際には
NHK総合、NHKEテレ、チバテレ、tvk、日テレ、テレ朝、TBS、テレ東、フジ、MX1、MX2
となってしまいます。

なお、Mirakurunのchannels.ymlにおいても上記のSIDの順番でチャンネルを記載しています。

**Comment by epgdatacapbon** [comment]
ご回答ありがとうございます。動作の確認ができました。
https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#serviceorder
の記載がわかりにくいため、変更したほうが良いように思います。
PR出しますので、よかったらご検討ください。

**Comment by l3tnun** [comment]
ああ、確かにこれは誤解しますね。すいません。
excludeServices も同様に修正が必要ですね

**Comment by l3tnun** [comment]
devel へマージしました
feature-143 ブランチと一緒に master へ反映させるので少々お待ち下さい

> ただ、技術的な困難があるのかもしれませんが、個人的にはSID指定の方が便利だと思います。

たしかに sid 指定のほうが便利ですね。
chinachu と同じ仕様で今の形になりましたが、技術的に難しいというわけではないので、要検討というところですかね
現状の serviceOrder との仕様の兼ね合いもあるので sid 対応するかは未定です

**Comment by epgdatacapbon** [comment]
了解です。
よろしくおねがいします。
