### ISSUE TITLE
ルール画面が動作しない

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#158]
### 環境
* Version of EPGStation: `1.1.3`
* Version of Mirakurun: `2.7.1`
* Version of Node: `v8.12.1`
* Version of NPM: `6.4.1`
* OS: Debian Stretch
* Architecture: x64
* DB: SQLite3

### Issue
環境依存かもしれませんが、ルール画面に移行しても画面が真っ白で操作できない（ルールを作成できない）ようです。Windows 10 Chrome 69.0.3497.100 と Android 8.1で確認しました。

![1](https://user-images.githubusercontent.com/3530452/45936436-61955400-bff1-11e8-8ae7-29d69e1813d4.png)

それと些細なことですが、検索画面等のチェックボックスが、完全な青のボックス（中に✓）にならず、白い隙間が表示されます。

![2](https://user-images.githubusercontent.com/3530452/45936437-635f1780-bff1-11e8-90d4-45a6faa3c87b.png)

**Comment by l3tnun** [comment]
こちらの環境で検証してみましたが、問題は確認できませんでした。

サーバ
* 環境は同じ

クライアント
* macOS + Chrome(69.0.3497.100)
* android 6.0.1 + Chrome(69.0.3497.100)

Windows環境は今手元にないので、Windows 10 + Chrome での検証はもう少しお待ち下さい

もしかしたら ```node_modules``` が正しくインストールできなかったのかもしれませんね。
```node_modules``` ディレクトリを削除して EPGStation のインストール作業もう一度行うとうまくいくかもしれません

> それと些細なことですが、検索画面等のチェックボックスが、完全な青のボックス（中に✓）にならず、白い隙間が表示されます。

確かにその通りですね。css 周りが原因だと思いますが、そのうち修正したいと思います

**Comment by epgdatacapbon** [comment]
検証ありがとうございます。検索、録画、ストリーミング、EPG予約等、他の部分はすべて正常に動くのでこれだけが動かないのが不思議です。ご助言の通りnode_modulesも再インストールしましたが、ダメでした。

考えられる理由としては、rootでのインストールをさけるため、epgstationのユーザーを作成して、ユーザー権限でインストールし、pm2での自動起動だけrootで行ったことに起因しているのかもしれません。

まず最初の検証として、SwaggerのAPIで直接rulesを書き込んでみて、EPGStationのルールページに表示されるか見てみようと思います。

**Comment by epgdatacapbon** [comment]
ユーザー（epgstation）でもう一度git cloneからやり直しましたが、ダメでした。
/api/docs#/rules/post_rulesから、
{
  "search": {
    "keyword": "string",
    "ignoreKeyword": "string",
    "keyCS": true,
    "keyRegExp": true,
    "title": true,
    "description": true,
    "extended": true,
    "GR": true,
    "BS": true,
    "CS": true,
    "SKY": true,
    "station": 0,
    "genrelv1": 0,
    "genrelv2": 0,
    "startTime": 0,
    "timeRange": 1,
    "week": 0,
    "isFree": true,
    "durationMin": 0,
    "durationMax": 0,
    "avoidDuplicate": true,
    "periodToAvoidDuplicate": 0
  },
  "option": {
    "enable": true,
    "directory": "string",
    "recordedFormat": "string"
  },
  "encode": {
    "mode1": 0,
    "directory1": "string",
    "mode2": 0,
    "directory2": "string",
    "mode3": 0,
    "directory3": "string",
    "delTs": true
  }
}
をExecuteしたところ
{
  "code": 500,
  "message": "Internal Server Error",
  "errors": "AddRuleError"
}
でした。
データベースへの書き込み権限かとも思ったのですが、/api/reservesは動くのでdatabase.dbへの書き込みは問題ないということですよね。

**Comment by l3tnun** [comment]
```JSON
{
  "search": {
    "keyword": "hogehoge",
    "title": true,
    "GR": true,
    "week": 127
  },
  "option": {
    "enable": true
  }
}
```
こちらではどうでしょう？

予約周りは DB を使用していなくて (```./data/reserves.json``` に予約データが記録されています)
DB の書き込み確認であれば、起動時に番組情報や録画時に録画番組を DB へ記録しているので、手動で録画ができていれば大丈夫なはずです

**Comment by epgdatacapbon** [comment]
できました。。。
すみません、使い方がわかってないだけでした。。。
ルールは「ルール」の画面から追加ができると思っていたのですが、
追加は「検索」画面から行い、「ルール」の画面では削除と変更しかできない
ということだったんですね。

理解不足でお騒がせしました。

**Comment by l3tnun** [comment]
いえいえ、解決して何よりです

検索ページは検索とルールの作成を兼任している形になります。

**Comment by epgdatacapbon** [comment]
あとは、別の方が書かれていた「時間指定録画」さえできれば完全にchinachuから乗り換えられますね。

個人的なことですが、手をつけようと思いながら途中になっていた、recdvbのチャンネル定義を外出しにするモチベーションが湧いてきました (^_^)
