### ISSUE TITLE
スマートフォン用のクライアントアプリ

### ISSUE THREAD

**Issue by kakushino** [l3tnun/EPGStation#163]
スマートフォン用のクライアントアプリの再公開をお願いします。
ストアで公開すると削除されるのであれば、インストールファイルの公開をお願いします。

**Comment by l3tnun** [comment]
EPGStation 向けにスマートフォン用のアプリを開発していたことはありません

Readme の↓について言っているのであれば、これはアプリではありません
Web をアプリっぽく見せているだけです

![](https://raw.githubusercontent.com/wiki/l3tnun/EPGStation/images/demo/demo.gif)

Android だけの話になりますが chrome で EPGStation へアクセスし、 chrome のメニューからホーム画面へ追加をすればこのようになります
