### ISSUE TITLE
【要望】録画のクリンナップ機能について

### ISSUE THREAD

**Issue by Takunsyo** [l3tnun/EPGStation#164]
クリンナップを押したら、説明も警告もなくそのままハードドライブに存在するすべてのファイルを削除した。今ファイルの回復に頭を痛めています。

要望としてはクリンナップを押してから、何をするかの詳しい説明が表示するようにして、このまま進むか、辞めるかを選択できるようにして頂きたい。

お願いします。

**Comment by l3tnun** [comment]
録画のメインメニューのクリーンアップのことですね？
確かにダイアログ等で実行前にワンクッション置いたほうが丁寧ですね。

ちなみに動作内容としては、recorded (もしくは config.json で設定したディレクトリ) 下にある EPGStation の管理外ファイル、ディレクトリを削除するようになっています。
そのため、recorded 下に不要なものを置くことは推奨しません。
あと、recorded 下に thumbnail ディレクトリを設置することは想定されていないので注意してください。

**Comment by l3tnun** [comment]
最新の master にてクリーンアップ実行前にダイアログを挟みましたので閉じます

**Comment by Takunsyo** [comment]
> 録画のメインメニューのクリーンアップのことですね？
> 確かにダイアログ等で実行前にワンクッション置いたほうが丁寧ですね。
> 
> ちなみに動作内容としては、recorded (もしくは config.json で設定したディレクトリ) 下にある EPGStation の管理外ファイル、ディレクトリを削除するようになっています。
> そのため、recorded 下に不要なものを置くことは推奨しません。
> あと、recorded 下に thumbnail ディレクトリを設置することは想定されていないので注意してください。

私はHDDごと録画用にしていたのでルートフォルダがrecordedディレクトリです、動画管理用の自分が作ったアプリ等を置いています。最近EPGStationへ録画環境を移行しましたので、以前録画したものもそのままありましたので、クリンナップを押したら一発でパーでした。正直痛かったｗ。
