### ISSUE TITLE
npm installに失敗する

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#169]
### 環境
* Version of EPGStation: `1.x.x`
* Version of Mirakurun: `2.7.0`
* Version of Node: `v8.11.3`
* Version of NPM: `6.4.1`
* OS:Windows 10
* Architecture: x64

### Issue
何度もお世話になっております。
サブPCでも使ってみようとインストールしておりますがgit clone後「npm install」で失敗します。
mirakurun最新版を使った弊害かと敢えて古めのものをインストールしてみたのですが、それでもエラーが
[2018-10-24T11_50_51_777Z-debug.log](https://github.com/l3tnun/EPGStation/files/2510457/2018-10-24T11_50_51_777Z-debug.log)
発生してしまいます。

おま環の可能性も高いですが、念のためエラーログを添付いたします。

**Comment by advancedbear** [comment]
`npm cache clean` からの `npm install` でどうでしょうか。

ログ最後らへんで
>warn pacote cached data for material-design-lite@https://registry.npmjs.org/material-design-lite/-/material-design-lite-1.3.0.tgz (sha1-0ATOP+6Zoe63Sni4oyUTSl8RcdM=) seems to be corrupted. Refreshing cache.

が出てますので……

**Comment by ohmsa** [comment]
advancedbearさん

毎々ありがとうございます。
npm cache clean
は非推奨と怒られましたが、
npm cache verify
でいけました。

おま環でした。本当にありがとうございます。
