### ISSUE TITLE
npm run buildでエラー

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#170]
### 環境
* Version of EPGStation: 1.x.x
* Version of Mirakurun: 2.7.3
* Version of Node: v10.13.0
* Version of NPM: 6.4.1
* OS:Windows 10
* Architecture: x64

### Issue
すみません、お尋ねします。
mirakurunをアップデートしてからか、windowsをアップデートしてからか、リアルタイム視聴などでmirakurunを呼び出すとCPU使用率が100%に張り付いてうまくデータが流れてこない状態になりました。
Nodeをアップデートしてみようと思いLTS最新版をインストール後、改めてEPGStationをインストールしようとしたところ、npm run buildでエラーが出てしまうようになってしまいました。
[2018-11-01T10_43_40_608Z-debug.log](https://github.com/l3tnun/EPGStation/files/2538185/2018-11-01T10_43_40_608Z-debug.log)
再起動したり、npm cache clean, npm cache verifyをしてみたりしたのですが変化がないようです。
他の方法や改善点などご指摘いただければありがたいです。

**Comment by l3tnun** [comment]
今出先で詳細な確認が取れませんが、node_modulesを削除し、npm installからやり直してみて下さい

それでも駄目な場合nodeのバージョンを8.x.xへ落としてみてくだい
（node 10で動くか私が確認していないためです）

明日時間が取れるのでその時見てみます

**Comment by cuckoozero** [comment]
`node_modulesを削除し、npm installからやり直し`
でうまくいきました!
早速のご対応ありがとうございました！
