### ISSUE TITLE
【要望】「録画済み」一覧にファイルサイズを表示する機能

### ISSUE THREAD

**Issue by LaFr4nc3** [l3tnun/EPGStation#173]
現在, ファイルサイズの確認は録画済みファイルのDOWNLOADタブから確認できるようになっていて, 一覧画面からは見ることができないと思います.

私は, 録画したファイルを整理するときにサイズを参考にするのですが, 
各ファイルを開き, DOWNLOADタブでサイズを確認することを繰り返し行うのは, 
とても手間がかかり, また比較もしづらいです.

なので, 録画済みの一覧画面にファイルサイズの表示を追加してもらえると助かります.
もしくは, 編集画面時のみ表示するでもいいかもしれません.

ご検討よろしくおねがいします.

**Comment by l3tnun** [comment]
編集中に表示させるのいいアイデアですね。
番組概要を表示させるよりいいと思いますので、編集時にファイル容量を表示するように変更したいと思います。
通常時は行数を増やさないと表示場所が確保できないので未定です。

**Comment by l3tnun** [comment]
最新の master にて、編集時にファイル容量を表示するように変更しましたので閉じます。
