### ISSUE TITLE
【質問】config.jsonに使用可能なパラメータについて

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#174]
### 環境
* Version of EPGStation: `1.1.9`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS: Windows 10 pro
* Architecture: x64

### Issue
現在、EPGStationにて録画した番組について、
・画質を求めない番組及びアニメ：720/24p　AAC192kHz
・映画など5.1chの可能性がある番組：1080/24p オーディオは再エンコなし
・上記の設定でなぜかカクカクになる番組：1080i　AAC192kHz
のようにエンコードオプションをかえております。

番組表の段階で「ジャンル名」や「チャンネル名」といった情報は既知だと思うのですが、
例えばジャンルが「アニメ・特撮-国内アニメ」なら「（あらかじめ準備している）アニメ用エンコードプロファイルで予約」であったり、「そのch、時間帯の平均ビットレートに対し0.1倍のビットレートでエンコード」であったり、「録画中ドロップが発生している」なら「エンコードが止まる可能性があるためエンコードしない」といった条件付けが出きると便利そうです。

現在はあらかじめエンコードオプションを指定して録画予約をしていますが、「ジャンルによるエンコプロファイル変更」であれば
"cmd": "C:\\PROGRA~1\\nodejs\\node.exe C:\\EPGStation\\config\\enc.js AAA"
のAAA部分にジャンルを与え、enc.jsのprocess.argv[2]でエンコードオプションを切り替えれば良さそうです。
一方でドロップ情報やビットレート等は簡単に送れそうにありません。

ビットレートは新たに監視する機能が必要そうですが、エンコード終了時にドロップ情報等を取得する方法ありますでしょうか。

**Comment by l3tnun** [comment]
ジャンル情報はエンコードコマンド実行時の環境変数として渡されていますので、それを参照しましょう。

どの番号がどのジャンルにあたるかは以下を参照してください。(16進数表記なので注意してください)
https://github.com/l3tnun/EPGStation/blob/master/src/client/lib/event.ts

ビットレート情報については ffprobe 等を使用し自前で取得してください。

ドロップ情報については必要な情報を環境変数で渡すように変更したいと思います。

**Comment by l3tnun** [comment]
最新の master にて、エンコード時の環境変数でドロップ情報を渡すように変更しましたので閉じます。

**Comment by ohmsa** [comment]
早速の対応ありがとうございます。

**Comment by ohmsa** [comment]
初歩的な質問でお恥ずかしいのですが、環境変数で渡された情報の扱い方について伺いたく存じます。
encode.jsにて「input」「output」が扱えているということは、encode.jsにて

let drop = dropCntt;
if(drop == 0){
    //エンコード設定
}

みたいに書けば「無ドロップ時にはエンコードを行ってドロップ時にはエンコードしない」となるのでは……と試してみましたが、そもそもエンコードキューに乗りません。

errorCntにはdropの数値が入っている（0で初期化してresult[pid].dropを+=しているので）と思うのですが、errorCntの扱い方を間違えているのでしょうか。

未熟故頓珍漢なことを聞いているかもしれませんが、お力をお借りしたく存じます。

**Comment by l3tnun** [comment]
よく分かりませんがドロップ情報は環境変数で渡されますので、

```
const drop = parseInt(process.env.dropCnt, 10);
```

このようにすれば見れるはずです。

**Comment by ohmsa** [comment]
ありがとうございます。

const drop = parseInt(process.env.dropCnt, 10);
const error = parseInt(process.env.errorCnt, 10);
const scramble = parseInt(process.env.scramblingCnt, 10);
errorCount = drop + error + scramble ;

とし、このerrorCountを使って
if(errorCount == 0){
    //エンコード設定
}
とすることで
・ドロップ／エラー／スクランブルが一つでもあるファイルはエンコードされない
・D/E/Sが一つもないファイルはエンコードされる
という設定になりました。
