### ISSUE TITLE
【質問】別PCでのレストアについて

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#176]
### 環境
* Version of EPGStation: `1.2.0`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows10
* Architecture: x64

### Issue
EPGStationそのものの不具合ではなさそうなので恐縮なのですが……

PC:AからPC:Bにお引越しをしようとしています。
PC:B側はEPGStationが動くまでセットアップしています。
PC:Aでデータベースをバックアップし、
録画フォルダをPC:BにコピーしてPC:BでDBをレストアしようとすると
"Check DB revision"
"Revision information is wrong"
と出てレストアに失敗します。

DBレビジョンと聞きPC:AとPC:BのmySQLやEPGStation、node.jsのバージョンを確認しましたが、
すべて揃っているようです。

検索しても解答らしきものが得られず困っております。どなたかお知恵を拝借したく……

**Comment by ohmsa** [comment]
[2018-11-13T01_25_26_507Z-debug.log](https://github.com/l3tnun/EPGStation/files/2574291/2018-11-13T01_25_26_507Z-debug.log)
エラーログはこのようになっております。

**Comment by l3tnun** [comment]
手元の環境では再現しませんので閉じます

**Comment by ohmsa** [comment]
すみません。元のEPGstationが古かったようでした。
お互いを1.2.0にすることでレストアできました。
新環境ではエンコードもできることを確認しましたが、なぜかサムネイルが生成されないので主導生成試してみます。

**Comment by ohmsa** [comment]
上記のサムネイルが生成されない件、/api/debugで手動生成を試みてもダメでした。

Code:200　予期しないエラー
 cache-control: private, no-cache, no-store, must-revalidate 
 connection: keep-alive 
 content-length: 12 
 content-type: application/json; charset=utf-8 
 date: Tue, 11 Dec 2018 00:14:16 GMT 
 etag: W/"c-QETVAhUYmmve97quvZif9EL6tqM" 
 expires: -1 
 pragma: no-cache 
 x-powered-by: Express 

主にサーバ用途としてコーデック等は追加していないのですが、ffmpegだけでサムネイル生成は出来るのでしょうか。若しくは、何らかのコーデック（CCCPなど）を入れる必要がありますでしょうか。

**Comment by l3tnun** [comment]
サムネイルの作成を指示するだけなのでエラー結果はその api からは見えません。
operatorLogConfig.json の system のレベルを debug に変更後、再起動すればサムネイル生成時の ffmpeg のエラー出力がログに残ります。

ffmpeg については分かりませんが、下記のDockerfile のような手順でビルドすれば動作することは確認しています。

https://github.com/l3tnun/docker-mirakurun-epgstation/blob/master/epgstation/Dockerfile

**Comment by ohmsa** [comment]
ありがとうございます。ログを確認したところ
[2018-12-12T12:17:59.309] [ERROR] system - ffmpeg is not found: C:\EPGStation\bin\ffmpeg
[2018-12-12T12:17:59.309] [INFO] system - regenerate thumbnail: 5448
となっており、ffmpegの指定がおかしかったようです。
確かにconfig.jsonにはC:\\EPGStation\\bin\\ffmpegと記述していました。

実際にはC:\\EPGStation\\binフォルダ内のffmpeg.exeを使っていたのですが、C:\\EPGStation\\bin\\ffmpeg
とbinフォルダの一段下にffmpegフォルダを作り、そこにffmpeg.exeをコピーするとサムネイルが生成されるようになりました。

一方で
C:\\EPGStation\\bin\\
内のffmpeg.exeをリネームした所
・サムネイルは生成される（bin/ffmpegフォルダのffmpeg.exeを使用している様子）
・エンコードされない（binフォルダ内のffmpeg.exeを使用している？）
ような挙動となりました。

少々バグのにおいがします。

C:\\EPGStation\\bin\\ffmpeg
これはWindows的にはffmpegフォルダを指定していますが、Linuxだとffmpegファイルを指定しているようにも見えます。

**Comment by l3tnun** [comment]
```
C:\\EPGStation\\bin\\ffmpeg.exe
```

と書きましょう

**Comment by ohmsa** [comment]
承知しました。勉強になりました。
