### ISSUE TITLE
"recordedEndCommand"で呼び出したtsselectが途中で停止する

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#180]
### 環境
* Version of EPGStation: `1.2.3`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.14.0`
* Version of NPM: `6.4.1'`
* OS: Ubuntu18.04.1
* Architecture: x64

### Issue
お世話になっております。
"recordedEndCommand"で録画後に追加で欲しい処理をいくつかシェルスクリプトに
まとめて実行させているのですが、tsselectが途中で停止してしまうケースがあります。
tsselect "recorded_file.ts" >> "tsselect_log.txt"

単独で実行させる分には問題は無いのですが、複数番組が重なると発生するようです。
tsselectが停止している状態でpsコマンドを実行すると、以下のように
tsselectがスリープ状態になっていることが確認できます。

$ ps ax | grep tsselect
  PID TTY      STAT   TIME COMMAND
15300 ?        S      0:00 tsselect recorded_file.ts

実行中のシェルスクリプトをkillすると後続のシェルスクリプト
("recordedEndCommand"で実行されているので環境変数が違うだけの同じもの)
が動き出しますが、またtsselect部分の処理で止まってしまいます。

下記のように標準エラー出力(tsselectでは進捗の%表示)を捨てると、
複数番組の録画が重なっても止まらなくなったようです。
tsselect "recorded_file.ts" 2> /dev/null >> "tsselect_log.txt"

状況からcronでスクリプトを実行した際などに発生するバッファ不足の
症状に似ていますが、ここから先確認する方法がわかりませんでした。

tsselectはこちらで公開されているものを使わせていただいてます。
https://github.com/shesee/tsselect-linux

以上、よろしくお願いします。

**Comment by advancedbear** [comment]
同じ症状ですかね？
https://github.com/l3tnun/EPGStation/issues/140#issuecomment-410145917

私はNodeスクリプトのspawnで呼び出していたことが起因でしたが、bashでも同じようなアレがあるんでしょうか。

**Comment by l3tnun** [comment]
お二人の言うとおり、stderr 出力が溢れているのかもしれないですね。
EPGStation 側でスクリプトを呼び出す際に何らかの設定が必要かもしれないので、土日にでも見てみます。

**Comment by tokohito** [comment]
＞ advancedbearさん
過去スレッドの検索を怠っていました。ありがとうございます。

＞ l3tnunさん
よろしくお願いします。

**Comment by l3tnun** [comment]
修正完了しましたので閉じました

**Comment by l3tnun** [comment]
ちなみに現象の原因としてはこれみたいですね

https://github.com/nodejs/node/issues/4236

**Comment by tokohito** [comment]
修正ありがとうございます。私の方でも問題が解消されたことが確認できました。
