### ISSUE TITLE
"recordedEndCommand"でsedを使った文字列置換に失敗する

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#181]
### 環境
* Version of EPGStation: `1.2.3`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.14.0`
* Version of NPM: `6.4.1'`
* OS: Ubuntu18.04.1
* Architecture: x64

### Issue
お世話になっております。
"recordedEndCommand"で録画後に実行しているシェルスクリプトにsedを使った
文字列置換を使用しているのですが、yオプションが意図した通りに機能しません。

───
#!/usr/bin/env bash
export LANG=en_US.UTF-8
echo "ターミナル文字コード" | nkf -g>> "debug.txt"
filename="${RECPATH##*/}"
filename="${filename%.*}"
filename=`echo "${filename}" | sed 's/　/\ /g'`
echo filename: "${filename}">> "debug.txt"

filename=`echo "${filename}" | sed 'y/ＡＢＣ/ABC/'`
echo filename: "${filename}">> "debug.txt"
───

全角<->半角置換しようとした際に、上記の例ですとsオプションで
1文字ずつ置換する分には問題ないのですが、yオプションで
置換しようとすると変数がnullになってしまいます。
(指定文字数の大小、置換元か置換先かは関係なし)
全角を含まない指定であれば、yオプションでも問題ありません。
nkf -gの出力結果はUTF-8になっています。

おま環のような気もしますし、sオプションを使えば
回避も可能ではありますが、確認いただけますでしょうか。

以上、よろしくお願いします。

**Comment by l3tnun** [comment]
時間があるときに確認してみます。
sedのバージョンを書いていただけると助かります。

**Comment by tokohito** [comment]
$ sed --version
sed (GNU sed) 4.4

です。よろしくお願いします。

**Comment by l3tnun** [comment]
確認してみましたが、こちらの環境では再現しないですね。

**Comment by tokohito** [comment]
確認ありがとうございます。
申し訳ありませんが、私の方でも問題が再現できませんでした。
1.2.4アップデート後に再現テストを行ったのでその影響かとも
考えましたが、流石にそう都合よくいくわけないと思いますし
以前のテスト時点のスクリプトがそのまま残っているわけではないので
何か他のスクリプト変更に伴って修正されてしまったのかもしれません。

お騒がせして申し訳ありませんが、クローズとさせてください。
