### ISSUE TITLE
録画失敗判定について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#183]
### 環境
* Version of EPGStation: `1.2.0`
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows 10 pro
* Architecture: x64

### Issue
便利に使っております。v1.2.0から編集画面で容量が出るようになり、録画失敗ファイルを探すのに重宝しております。

この編集画面で、
・ドロップ・エラー・スクランブル
・動画時間
も表示されると失敗ファイルを探すのに便利だと思いました。動画時間は難しいにしても、D/E/Sはご一考いただけると幸いです。如何でしょうか。

**Comment by l3tnun** [comment]
D/E/S については可能ですね。
動画の時間情報はDB上で持っていないので無理です。

**Comment by l3tnun** [comment]
最新の master にて対応したので閉じます。

**Comment by ohmsa** [comment]
対応ありがとうございます。編集時にかなり便利になりました。

・D/E/Sが0でない時は文字を赤い太字で表示（もしくは背景を薄いピンク色に）
・D/E/Sが0の時は表示しない
様な強調があると更に便利そうです。

要望だらけで申し訳ないのですが、お手隙の際一考いただけますと幸いです

**Comment by l3tnun** [comment]
master にて表示の強調を行いましたので閉じます。

**Comment by ohmsa** [comment]
実装ありがとうございます。

ものすごく管理しやすくなりました。
