### ISSUE TITLE
【要望】ルール画面のUI操作等について

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#185]
お世話になっております。
お忙しいところ申し訳ありませんが、3点ほど要望を提出させてください。

1. ルールの複数件数選択について
シリーズものを中心にルール録画を活用しています。
シーズンが終わると使用したルールは不要になるので削除することにしているのですが、
如何せん件数が多いと削除するのも一苦労です。(今数えてみたらルールで115件ありました)
ルールの一覧画面で個々のルールの左端にチェックボックスを配置していただき
複数選択による一括削除などができると便利かと思いました。
また24ルール/1ページ構成になっていますが、件数が多いと目的の物を探したりページ移動
するのも時間がかかるため、検索窓、総件数表示や任意ページへのジャンプリンクなどもあると
便利かと思います。(いづれもGmailのUIイメージが近いかと思います)

2. ルール設定時の画面遷移について
ルールを設定するのにもっぱら番組表ページから検索する形で設定するのですが、
次ページの検索画面で「追加」ボタンをクリックした後に直前に開いていた
番組表ページに遷移する設定が欲しいです。
(番組表から番組の単独予約指定をした場合と同じようなイメージ)
とりわけ翌日以降の番組を選択していた場合などGR/BS→日付選択と2段階
操作が必要になるため、番組表からルール設定するスタイルが冗長な
操作サイクルになりがちだと感じました。

3. 録画済みファイルの登録情報変更について
"recordedEndCommand"に登録したシェルスクリプトで、録画ファイルは
最終的にLAN内にある別のファイルサーバへ移動するという運用をしています。
このままですと録画済みリストに登録されたファイルのパス情報と
一致しなくなるためクリーンアップでリスト抹消する他ないのですが、
可能であればファイルパスを変更して移動先のファイルサーバ上のファイルを
EPGStationのWebUI上から参照できるようにしたいと考えています。
"/recorded/{id}/upload" APIを使って録画済み番組のファイル情報だけ
書き換えできるかもと思い試してみましたが、"errors": "TsFileAlreadyExists"
というレスポンスで上書きできませんでした。
他に方法があればお教えください。

以上、ご検討くださいますようよろしくお願いします。

**Comment by l3tnun** [comment]
いい機能ですね。検討します。

3. についてですが、EPGStationではそのような事は想定して作られていないです。

#71 のに近い要望だと思いますが、当時と比べて構造が随分変わり実現できるかもしれないので
再度検討してみます。

**Comment by tokohito** [comment]
回答いただきありがとうございます。
3.については仰る通り#71の方の要望と本質的には同一です。

どうぞよろしくお願いします。

**Comment by l3tnun** [comment]
version 1.3.8 にて以下に対応しました

- ルールの検索
- ルールの複数削除
- ルール追加 or 更新後に前のページに戻る設定を追加

総件数表示や任意ページへのジャンプリンクはページネーションの拡充で対応したいと思います。
(総件数表示はいいUIが思いつかないので実装しないかもしれません)

**Comment by tokohito** [comment]
対応ありがとうございます、後ほどアップデートさせていただきます。

一点訂正がございます。
https://github.com/l3tnun/EPGStation/issues/71 について先に対応いただいていますが、私は転送先ファイルサーバ上に
録画キーワードと放送局に対応したサブディレクトリを作成してから
その配下にファイルを移動させていますので、上記の修正ですと
やはりEPGStationのパスと乖離してしまうという事に今更ながら気が付きました。

上書き更新用APIなどが無いと実現できないと思われますが、もし気が向いたらで
かまいませんのでご検討ください。

**Comment by l3tnun** [comment]
うーん、難しいですね。
recorded 下の任意のディレクトリへ移動するapiは追加できそうですが、
recorded外に移動の場合は無理ですね。

**Comment by l3tnun** [comment]
最新の master にて pagenation を刷新したので閉じます
