### ISSUE TITLE
録画時、H264-subを選択したのに1280x720で録画される

### ISSUE THREAD

**Issue by shirow-github** [l3tnun/EPGStation#186]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.11.4`
* Version of NPM: `6.4.1`
* OS:Vine Linux Seed
* Architecture: x86

### Issue
現在、Chinachuの録画環境からの移行テストをしております。
「番組表」→ポップアップ右下の「H264-sub」を選択、録画完了後にしばらくしてmp4ファイルが出来上がります。
suffixも「ファイル名-sub.mp4」になっているのですが、1280x720になっております。
enc.shを見ると、720x480になるはずなのですが...。

**Comment by advancedbear** [comment]
`sub` の意味は、副音声を意味しているのであって解像度の指定ではありません。

https://github.com/l3tnun/EPGStation/blob/master/config/enc.sh
```
function getHeight() {
    echo $VIDEORESOLUTION | sed -e "s/[^0-9]//g"
}

if [ `getHeight` -gt 720 ]; then
    $FFMPEG -dual_mono_mode $mode -i "$INPUT" -vf yadif -preset veryfast -c:v libx264 -crf 23 -f mp4 -s 1280x720 -c:a aac -ar 48000 -ab 192k -ac 2 "$OUTPUT"
else
    $FFMPEG -dual_mono_mode $mode -i "$INPUT" -vf yadif -preset veryfast -c:v libx264 -crf 23 -f mp4 -s 720x480 -c:a aac -ar 48000 -ab 128k -ac 2 "$OUTPUT"
fi
```
から分かるように、解像度の指定はあくまで元動画の `VIDEORESOLUTION` (=動画解像度)に準じており、元動画が縦720px以上であれば1280x720で、720px未満であれば720x480でエンコードされるようになっています。

`H264-sub` を指定した際に引数として渡される `sub` は
```
 $FFMPEG -dual_mono_mode $mode -i "$INPUT" -vf yadif -preset veryfast -c:v libx264 -crf 23 -f mp4 -s 1280x720 -c:a aac -ar 48000 -ab 192k -ac 2 "$OUTPUT"
```
から分かるように、 `-dual_mono_mode` の値として利用されます。  
すなわち、多重音声の抜き出し対象の指定でしかありません。

**Comment by l3tnun** [comment]
advancedbearさんのおっしゃる通りの仕様となっています。

自由に書換えできますのでお好みに調整してあげてください。

**Comment by shirow-github** [comment]
自分の勘違いだったようで、お手数おかけしました。
ご指摘ありがとうございました。
本件クローズ致します。
