### ISSUE TITLE
新番組検索機能

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#188]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows10
* Architecture: x64

### Issue
再検討ありがとうございます。

画面遷移について横から要望（検索について）なのですが、現在
・［新］、＃１でルール化し、"編集"を押して新番組をリスト表示
・(例)"[字]ジョジョの奇妙な冒険 第4部 #1,2"　をクリックし、検索をクリック
・検索画面に遷移
・"放送局"を"すべて"
・"＃１"や"１話"を削除（不要なことが多い）
でシリーズ予約化しています。

ここの
「放送局を"すべて"に変更」
だけでも自動化できれば、「新番組検索」としてかなり使えると思います。
そのルール録画で[終]を検知したら1か月後にルールを自動削除……までは行かないにせよ、
「新番組検索機能」
（ルールの時限化）
というのはニッチすぎますでしょうか。

要望だらけで申し訳ないのですが、ご一考いただけますと幸いです。

**Comment by l3tnun** [comment]
技術的には可能ですが、UI が難しいですね。

検討してみます。

**Comment by l3tnun** [comment]
v2.0で番組表からの検索時に下記項目を有効にするか設定で変更できるようになりました、

* 検索時に放送局情報を含むか
* 検索時にジャンル情報を含むか

専用のUIは追加できませんでしたが、これで対応できるかと思います。
