### ISSUE TITLE
録画済み一覧のリスト表示

### ISSUE THREAD

**Issue by tosono** [l3tnun/EPGStation#189]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.11.3`
* Version of NPM: `6.4.1`
* OS:Ubuntu 18.04.1 LTS
* Architecture: x64

### Issue
録画一覧はサムネイル付きで表示されてますが、
本数が多くなってくると逆に見づらいので、リスト表示って出来ないでしょうか。

シリーズ物で録画済みが3桁とかになってくると、サムネイルはいらないから、
タイトル一覧で見れる方が色々と捗るので。

**Comment by l3tnun** [comment]
検討してみます。

**Comment by l3tnun** [comment]
version 1.2.9 にて実装されました。
録画済みページのメニュー -> 設定 -> list 表示を有効化する
で切り替えができます。

なお、ある程度幅が必要なため、表示幅が十分ないと今までと同じ表示になります。
