### ISSUE TITLE
【提案】録画番組検索について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#192]
### 環境
Version of EPGStation: 1.2.5
Version of Mirakurun: 2.7.2
Version of Node: v8.11.3
Version of NPM: 5.6.0
OS:Windows10
Architecture: x64

### Issue
何度もすみません。表題の件、録画済画面での検索についてです。

現在キーワード・ルール・放送局・ジャンルが選べますが、
ここに”ファイル形式”があると先述の「何らかの理由でエンコードできなかった番組」のピックアップが容易になりそうです。
・”TSのみ”で検索
エンコードされなかった番組を探すのに使用
・”TS・mp4”で検索
TS（またはmp4）を削除するのに使用（"編集"メニューで削除したいTS/ｍｐ４選択できると尚便利）

「要望ばかり出していないで自分で開発したら」かもしれませんが、すこしずつ勉強中ですので申し訳ありませんがご一考いただけますと幸いです。

**Comment by l3tnun** [comment]
最新の master にて対応しました。

”TSのみ”で検索 に関しては DB の都合上難しかったため、
TSを必ず含む番組を検索できるオプションの追加になりました。

複数削除については TS or エンコード済みファイルのどちらかを選択して削除できるようになりました。

これ以上の対応は難しいので閉じます。

**Comment by ohmsa** [comment]
ご対応ありがとうございます。
