### ISSUE TITLE
【要望】EPG番組情報のテキストファイル出力

### ISSUE THREAD

**Issue by ai02** [l3tnun/EPGStation#194]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v10.14.2`
* Version of NPM: `6.5.0`
* OS:Ubuntu 18.04LTS,Raspbian
* Architecture: x64,ARM

EPGStation をUbuntu18.04LTS(AMD64)とRaspbian(ARM)にて稼働させております。
これは最近の流行なのでしょうけど、スマートフォンを意識したUIになっており
タッチ操作する人には使いやすいと思います。

さて、以前より当方ではWindows環境でEPGDataCap(EDCB)を使っており、
極力EDCBに合わせる運用をしています。
TSファイルの記録と同時に、EPG番組情報のテキストも別ファイルで保存しており、
この場合のファイル拡張子は「.ts.program.txt」となっています。

EPGStation側で、DBから取得したEPG番組情報を、番組録画と同時に
別途テキストファイルに出力できるでしょうか?
そうなれば、「EpgDataCap互換」の動作が実現します。
録画ファイルのサムネイルにはEPG情報が表示されているので、
実現も不可能ではないのでは?と思うのですが…。

他のソフトに動作を合わせて欲しい、というのは
ソフト制作側にとっては失礼なお願いかも知れませんが、
ご検討のほどよろしくお願いします。

...

**Comment by l3tnun** [comment]
可能ですが、必要性が分かりません。
録画された番組情報が必要であればapi経由で取得しましょう。

**Comment by ai02** [comment]
必要性が感じられない、ですか。
録画ファイルそのものに対する要望ではないので、
優先度は低いかも知れませんね。

お忙しい中わざわざご回答いただき、ありがとうございました。

**Comment by l3tnun** [comment]
.ts.program.txt を使って何をするのか分からないので、
何をするために必要なのか分からないと言うところですね。
明確な理由があれば実装の検討はします。
