### ISSUE TITLE
[要望]excludeServicesのSIDによる指定

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#197]
[#161](https://github.com/l3tnun/EPGStation/issues/161)と同様、
excludeServicesもSIDで設定できるようにして頂けましたら幸いです。

**Comment by l3tnun** [comment]
手が周り次第実装しますね

**Comment by epgdatacapbon** [comment]
お礼が遅れましたが、チャンネルの並び順のSID実装ありがとうございました。
この度もご考慮頂きありがとうございます。

**Comment by l3tnun** [comment]
excludeSid オプションを追加し対応しましたので閉じます。
