### ISSUE TITLE
【提案】番組表のUI改善について

### ISSUE THREAD

**Issue by gifuhabu** [l3tnun/EPGStation#203]
### 環境
* Version of EPGStation: `1.2.7`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS: Linux
* Architecture: x64

### Issue
いつもお世話になっております。大変有用なアプリケーションを作っていただきありがとうございます。
少し気になるところがあったので書かせていただきます。

現時点の番組表の仕様だと、左上の文字を押して出てきたポップアップから日付を指定して飛ぶと今の時間を基準に番組表が始まってしまいます。
例えば今が23時でポップアップで土曜日を指定すると、土曜日の23時から次の日曜日にかけての番組表が表示されてしまい、左上の日付だと土曜日となっているのに実際は日曜日の番組が大半となってしまい不自然に感じます。
本日を選択した場合は自然な挙動だと思いますが、本日以外を選択した場合はその日の0時から始まるように番組表を表示する方がより自然でわかりやすいと思います。
大変申し訳ございませんが、ご検討よろしくお願いいたします。

**Comment by l3tnun** [comment]
なるほど、おっしゃるとおりですね。
修正します。

**Comment by l3tnun** [comment]
最新の master にて修正完了したので閉じます。

**Comment by gifuhabu** [comment]
ありがとうございます！
動作確認しました。
迅速に実装していただき本当にありがとうございました。
