### ISSUE TITLE
予約画面に移行しない

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#205]
### 環境
* Version of EPGStation: `1.3.1`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v10.15.x`
* Version of NPM: `6.4.1`
* OS: Debian Stretch
* Architecture: x64

### Issue
...
予約1件、競合なしの状況で、一旦「競合」をクリックして画面を表示（空白）させたあとに「予約」をクリックしようとしても競合の画面のままになってしまう。それ以降予約画面に移動することができない。

いったんURL直打ちでルートページを表示させた後（/#!/）であれば予約画面に移行できる。

なお、config.jsonで"subDirectory"を指定した環境でテストしています。

**Comment by l3tnun** [comment]
こちらの環境でも再現できました。
バグですね、修正します。

**Comment by l3tnun** [comment]
最新の master にて修正完了したので閉じます。
