### ISSUE TITLE
【要望】ライブ視聴画面での、チャンネル一覧表示について

### ISSUE THREAD

**Issue by shirow-github** [l3tnun/EPGStation#215]
### 環境
* Version of EPGStation: `1.3.7`
* Version of Mirakurun: `2.8.3`
* Version of Node: `v8.15.0`
* Version of NPM: `6.5.0`
* OS:Vine Linux Seed
* Architecture: x86

### Issue
現在、ライブ視聴画面ではGR・BS・CSと切り替えてチャンネル情報を表示していますが、
GR・BS・CS全てのチャンネルを一覧表示出来るように出来ないでしょうか？

表示画面のイメージとしては、Chinachuのダッシュボード画面の様なのをイメージしてます。

そして表示の切り替えは、録画済み画面の「設定」→「list表示を有効化する」の様に
トグルスイッチで切り替えられたらと思います。

理由としては、空いた時間にザッピングして何か面白い番組がしていないか探しやすいからです。

ご検討頂けたら幸いです。
よろしくお願い致します。

**Comment by l3tnun** [comment]
apiの構造的に特に問題はないので可能ですが、
(issueが溜まっているので)いつ実装できるかは分からないです。
気長にお待ちください。

**Comment by shirow-github** [comment]
ご検討ありがとうございます。
実装されるのを、楽しみに待っております。

**Comment by l3tnun** [comment]
最新の master にて対応しました
