### ISSUE TITLE
【要望】チャンネル名も半角に変換するオプションの追加

### ISSUE THREAD

**Issue by gifuhabu** [l3tnun/EPGStation#217]
### 環境
* Version of EPGStation: `1.3.8`
* Version of Mirakurun: `2.8.0`

### Issue
お世話になっております。
#210 のプルリクエストで半角全角変換の設定が追加されましたが、個人的にチャンネル名も一緒に半角に設定するオプションがほしいです。
自分はrecordedFormatで録画ファイル名にチャンネル名を入れるように設定していますが、全角だと検索に引っかからなく不便に感じるからです。
チャンネル名を全角のままにしたい人もいると思うのでconvertDBStrに更にオプションを追加するのはどうでしょうか。
またこのオプションに設定した場合はWEB上のチャンネル名が表示される部分の全てを半角に変換するようにしてほしいです。
お手数ですが、よろしければご検討いただけたら幸いです。

**Comment by l3tnun** [comment]
なるほど、検討しますね（いつ実装できるかは分かりませんが）

> 自分はrecordedFormatで録画ファイル名にチャンネル名を入れるように設定していますが、全角だと検索に引っかからなく不便に感じるからです。

EPGStationでファイル名での検索は出来ないですよ？

**Comment by gifuhabu** [comment]
ご検討ありがとうございます。
ファイラーから直接アクセスするときに検索したいんです。
