### ISSUE TITLE
データベースのバックアップエラー

### ISSUE THREAD

**Issue by scandium-j** [l3tnun/EPGStation#220]
### 環境
* Version of EPGStation: `1.3.8`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v8.9.4`
* Version of NPM: `5.6.0`
* OS:Windows 10
* Architecture: x64

### Issue
データベースのバックアップをしようとしたところ以下のエラーが出てバックアップができない状況です。こちら側のデータベースがおかしくなっているのかよくわからないのですが、何かわかりますでしょうか？

--- read datas ---
DB Revision Info
Rules
(node:10408) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'query' of undefined
(node:10408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

データベースはMySQL 5.7.23です。
ちなみにEPGStationのバージョン 1.3.3ではバックアップできました。

**Comment by l3tnun** [comment]
version 1.3.8 で DB の構造に変更があったのでそのせいかもしれません、確認します。

**Comment by l3tnun** [comment]
最新の master にて修正しました。
問題があれば再度オープンしてください。
