### ISSUE TITLE
【質問】一部チャンネルが番組表に現れない

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#224]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows10
* Architecture: x64
### Issue
番組表にナショナルジオグラフィックやカートゥーンネットワーク等出てこないチャンネルがあります。

放送局自体は契約済みで、BonDriver_Mirakurun→TVTestのチャンネルスキャンでは認識され、視聴も可能です。

mirakurunのchannels.ymlの記述が悪いのかもしれませんが、TVTestからは見えるので不思議です。

どなたか、
・Windows環境
・ナショジオが選局可能（番組表にある）
という方いらっしゃいますでしょうか。

**Comment by l3tnun** [comment]
Mirakurun 上ではチャンネルとして認識されていますか？
↓で確認できます。

```http://Mirakurun-Host:port/api/channels```

**Comment by ohmsa** [comment]
されてないので、Mirakurun側の問題ですかね。

BonDriver_Mirakurun→TVTestのチャンネルスキャンだと見つかるので勘違いしてしまいました。

**Comment by l3tnun** [comment]
ならばMirakurunの設定が問題ですね

**Comment by gifuhabu** [comment]
Mirakurunのchannels.ymlのチャンネル設定に問題があると思います。
MirakurunにはBSCSのチャンネルスキャンの機能はないので、EDCBあたりをビルドしてチャンネルスキャンを行うとチャンネル情報のファイルができるのでそれを参照しながら設定を見直してみると直るともいます。
