### ISSUE TITLE
npm run buildで137エラー

### ISSUE THREAD

**Issue by routeone34** [l3tnun/EPGStation#225]
### 環境
* Version of EPGStation: `1.4.0`
* Version of Mirakurun: `2.8.3`
* Version of Node: `v10.15.0`
* Version of NPM: `6.4.1`
* OS: Ubuntu 18.04
* Architecture: x64

バージョン1.4.0にアップデートしようとしたところ
npm run buildがエラー137で終了しました。（ログを文末に）
node_modulesを削除したり、新規インストールを試しましたが変化なし。

エラーコードで検索したところメモリ不足の可能性があるとの情報があったので、メモリを1GB→2GBに増やし、動作中のサービスを全て止めたところ正常にbuildできました。
また、build中のtopを見ていると<anonymous>のあたりでgulpのメモリ消費が急激に増加し1GB付近まで上がったように見えました。

当方ではmirakurunとepgstationは同一サーバですが、メモリ1GBで十分動作します。
仮想なのでbuild時だけメモリを増やすのは容易ですが、稼働時よりもビルド時にリソースが必要というのはちょっとすっきりしません。

回避策はあるので緊急性は低いと思いますが、何かエラーを回避する術はないでしょうか。
node.js系には全く詳しくないのですが、何かビルドにオプションを指定できるとか。

ご検討よろしくお願いします。

=======================================================
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle EPGStation@1.4.0~prebuild: EPGStation@1.4.0
6 info lifecycle EPGStation@1.4.0~build: EPGStation@1.4.0
7 verbose lifecycle EPGStation@1.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle EPGStation@1.4.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kuwa/EPGStation/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle EPGStation@1.4.0~build: CWD: /home/kuwa/EPGStation
10 silly lifecycle EPGStation@1.4.0~build: Args: [ '-c', 'gulp build --env production' ]
11 silly lifecycle EPGStation@1.4.0~build: Returned: code: 137  signal: null
12 info lifecycle EPGStation@1.4.0~build: Failed to exec build script
13 verbose stack Error: EPGStation@1.4.0 build: `gulp build --env production`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid EPGStation@1.4.0
15 verbose cwd /home/kuwa/EPGStation
16 verbose Linux 4.15.18-10-pve
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 137
22 error EPGStation@1.4.0 build: `gulp build --env production`
22 error Exit status 137
23 error Failed at the EPGStation@1.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
=============================================================

**Comment by routeone34** [comment]
ログがおかしくなったのでファイルで添付します。

[log.txt](https://github.com/l3tnun/EPGStation/files/2816407/log.txt)

**Comment by routeone34** [comment]
たびたび失礼。

＞また、build中のtopを見ているとのあたりでgulpのメモリ消費が急激に増加し1GB付近まで上がったように見えました。

「build中のtopを見ているとanonymousのあたりで」の誤りです。

**Comment by l3tnun** [comment]
調査に時間がかかりそうなのでしばらくお待ち下さい。
再現するか検証します。

**Comment by routeone34** [comment]
了解しました。こちらは特に急ぎません。
再現する環境のスポットバックアップを残してあるので、何か協力できることがあれば指示ください。

**Comment by routeone34** [comment]
再現させたところOOM Killerが動いてgulpを殺していました。
syslog該当箇所を添付します。

npm run build実行前にfreeで確認したところ900MB程度空いていたので、それでは不足するということと思われます。
メモリ増で回避できることも確認済なので、純粋にbuildに必要なメモリ量と考えるべきなのかもしれません。

とりあえずご参考まで。

[syslog_oom.txt](https://github.com/l3tnun/EPGStation/files/2821276/syslog_oom.txt)

**Comment by routeone34** [comment]
何度も失礼します。
調査協力というより半ば個人的な勉強になっていますが。

package.jsonを少しいじって、オプションとして
--max_old_space_size=512
をgulpに与えると回避できました。

"build": "gulp build --env production",
↓
"build": "gulp build --max_old_space_size=512 --env production",

gulpの実体はJavaScriptで、ガーベージコレクションの閾値を512MBにしてメモリ消費しすぎないようにする
というような意味と勝手に理解しました。

（ここまでに間違いがなかったとして）適正値は環境依存な感じなので、
buildエラー時の回避策としてだけFAQ的に情報があればいいかと思いました。
node界隈では「そんなもん当たり前」な話なのかもしれませんが。

では。

**Comment by l3tnun** [comment]
色々とありがとうございます。

gulp周りは3.xから4.xにアップデートするときに結構雑に対応したので、
そのせいでメモリがモリモリ使用されるのだと思います。
いい機会ですので、今回きちんと対応したいと思います。

--max_old_space_size の件はまさにそのとおりで、gulp は node で動いています。

**Comment by routeone34** [comment]
回答ありがとうございます。
何かお役に立ったならうれしい限りです。

**Comment by l3tnun** [comment]
gulp の見直しと、念の為 gulp 実行時に --max_old_space_size オプションを追加するように修正しました。

根本的に修正することは難しいですね。

**Comment by routeone34** [comment]
対応ありがとうございます。
こちらの環境ではVer1.4.1のbuildに問題ありませんでした。

何が抜本対策かというのは難しい話ですが、
メモリ1GBでmirakurunは動かしながらのbuildでOKだったので
ひとつの目安というか最小構成要件みたいなものと思っていいのでは。

最近はラズパイで録画サーバみたいなのも多そうなので
メモリpoorな環境には地味に効くものと思われます。
