### ISSUE TITLE
正常稼働後しばらくするとEPGStationへのアクセスが不可なります

### ISSUE THREAD

**Issue by legnum** [l3tnun/EPGStation#227]
Version of EPGStation: 1.3.8
Version of Mirakurun: 2.8.4
Version of Node: v10.15.1
Version of NPM: 6.4.1
OS:Windows10
Architecture: x64

お世話になります。
EPGStationを稼働後しばらく時間が経過すると、EPGStationへのアクセスができない状態になります。
その場合EPGStationを再起動させるしか手がありません。
ファイアーウォールは無効にしても変化がありませんし、稼働後しばらくは全く正常に利用できます。
なおアクセスできなくなった状態の際、プロセスは可動しておりポートもLISTENINGとなっております。
system.logにもエラーらしきものは無く手詰まりです。なにかアドバイスをいただけませんでしょうか。

よろしくお願いします。

**Comment by l3tnun** [comment]
うーん、windowsで長期間運用したことが無いので分かりませんが、その様な症状は初めて聞きました。

Webサービスを提供する、ServiceExecutor.jsは起動していますか？

**Comment by legnum** [comment]
お世話になります。
不勉強で申し訳ありません。ServiceExecutor.jsの起動はどのようにして確認できますか。
tasklist /svc等では確認できないようですので、お手数ですがご教示いただけますでしょうか。

よろしくお願いします。

**Comment by l3tnun** [comment]
windows のことを聞かれても私には分かりませんので、
申し訳ないですがご自分でお調べになってください。

**Comment by l3tnun** [comment]
特に進展もないようなので閉じます

**Comment by legnum** [comment]
ご連絡しておらず申し訳ありませんでした。
結局、確定的なことは何もありません。1点だけわかったことはライブ閲覧さえしなければ
アクセス不可になることはありませんでした。ライブ閲覧を行うと遅くとも1日以内にアク
セス不可になります。
そういうわけで、こちらのソフトは録画専用にすることで、トラブルを回避することにしました。
それでは失礼します。

**Comment by l3tnun** [comment]
@legnum 最新の master にて修正されたので確認してみてください。
