### ISSUE TITLE
【質問】エンコードファイルのデフォルトの置き場について

### ISSUE THREAD

**Issue by mage999** [l3tnun/EPGStation#228]
### 環境
* Version of EPGStation: `1.4.1`
* Version of Mirakurun: `2.5.4`
* Version of Node: `v8.11.3`
* Version of NPM: `6.7.0`
* OS:CentOS Linux release 7.5.1804
* Architecture: x64

### Issue
エンコードしたファイルを保存するデフォルトのフォルダを指定する方法はありますか？
番組表から録画予約をする際、詳細でエンコードでディレクトリを指定すればいいのはわかるのですが、ルールで決めて録画する場合にはこまらないのですが、急遽で録画した場合、
ディレクトリの指定をし忘れた場合に、少し困っております。
番組表から予約した場合に、
/recorded   → .ts
/recorded/mp4 → .mp4 
上記にように録画ファイルデフォルトでディレクトリ分けする方法はありますでしょうか？
enc.sh の $OUTPUTをすこしいじればいいのかと思い試してみたのですがダメでした。

何か方法があれば教えて欲しいです。

**Comment by l3tnun** [comment]
現状そのような事を想定したオプションは存在しません。
機能追加を検討します。
（いつ実装できるか分かりませんが）

**Comment by mage999** [comment]
****
ご検討ありがとうございます。
実装していただけると期待して、お待ちしております。

**Comment by l3tnun** [comment]
```config.json``` に ```recordedTSDefaultDirectory``` と ```recordedEncodeDefaultDirectory``` を追加して対応しました。

**Comment by ohmsa** [comment]
似たような（？）話ですが、「録画済み」画面からencodeを実行する際毎回「元ファイルと同じ場所に保存」「TS削除」にチェックを入れています。

録画済み画面の設定（現在はlist表示のオン・オフ）辺りに、検索画面の設定にあるような「元ファイルと同じ場所に保存」「TS削除」をデフォルトにするスイッチを追加することは可能でしょうか。

**Comment by mage999** [comment]
ご対応ありがとうございます。
本当に助かります。

**Comment by l3tnun** [comment]
@ohmsa 違う話なので新しくisuee建てて下さい。（issueの管理が面倒なので）
