### ISSUE TITLE
【要望】外部からの接続のみBasic認証を要求する設定

### ISSUE THREAD

**Issue by gifuhabu** [l3tnun/EPGStation#230]
### 環境
* Version of EPGStation: `1.2.7`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS: Linux
* Architecture: x64

### Issue
お世話になっております。
内部ネットワークからも外部ネットワークからも接続できるようにしたいのですが、外部ネットワークからのときだけBasic認証を要求するということは技術的に可能でしょうか？
AllowedIPsという設定がありますが、ここにないIPから接続が来た場合のみにBasic認証を要求して、接続を許可する、内部ネットワークからはAllowedIPsに記載されていたら接続許可
のような設定ができるようにできないでしょうか。
以上よろしくお願いいたします。

**Comment by l3tnun** [comment]
EPGStationを外部ネットワークに公開してはいけません。
vpn, リバースプロキシ等を利用しましょう。

**Comment by gifuhabu** [comment]
ご指摘ありがとうございます。
やはりそうですよね。リバースプロキシを検討してみます。
