### ISSUE TITLE
メインメニューの「検索」は？

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#232]
先程インストールして、少し使ってみました。素晴らしいですね。Chinachuをずっと使ってきましたが、録画予約のUIに少し問題がありました。

TVRockの検索からのルール作成が素晴らしかったので、あれを再現して欲しかった。

EPGStationは、さらにルール作成が洗練されてます。素晴らしい。

リクエストとしては、メニュー名が「検索」というより、「ルール作成」、そして「ルール」は、「ルール編集」の方が分かりやすい、と思うのです。

これから、こちらをメインに使ってみますので、よろしくお願いします。

**Comment by advancedbear** [comment]
「ルールの作成を検索ページから行う」という導線は確かにUI上の問題だとは思いますが、検索ページはルール作成ページではない（単発番組の検索にも利用するし番組情報を調べるだけの場合もある）ですし、ルールページもルール編集ページではない（ルールにより録画された番組の絞り込み機能は編集ではない）というような観点もあるかと思います。

単にタブの名称を変更することは、より一層の混乱を生むだけかと思いますが・・・。

**Comment by simplelife0530** [comment]
再度考えてみたら、新たなアイディアが浮かびました。

「検索」ページの下の方のルール作成を取ってしまう。
「ルール」のページの中に、「ルール作成」というボタンを作ってもらい、現在の「検索」のページのような、ルール作成ができるページに飛ぶというふうにすれば、混乱はなくなると思います。

特にリクエストという話ではなく、私の感覚ではこうするというだけで、好みですから。
EPGStationで検索をかけた時、たまたま読んだ記事が、「ルール」のページを開けたけど空白で使えない、というものだったので、気になっただけです。

**Comment by advancedbear** [comment]
「 **ルールページからルールの作成が出来ない** 」という点についてはsimplelife0530さんが読まれた記事や https://github.com/l3tnun/EPGStation/issues/158 で上がっているような混乱を招きがちな点だとは思うので、

>「ルール」のページの中に、「ルール作成」というボタンを作ってもらい、現在の「検索」のページのような、ルール作成ができるページに飛ぶ

といったアイデアはありではないかな？と思います。

フローティングボタンでルール追加ボタンを表示し、リンク先として単に検索画面 (/search) に飛ぶだけでも前述のような勘違いは起きにくくなりそうですね。

----
>「検索」ページの下の方のルール作成を取ってしまう。

ただ、ここについては余り軽率に行うべきではないと思います。
ありとあらゆるプロダクトに言えることではありますが、「今出来ていることを出来なくする」にはそれ相応の理由が必要です。

----
> 特にリクエストという話ではなく、私の感覚ではこうするというだけで、好みですから。

Github の Issues はご意見ボックスや掲示板ではなく、「課題管理機能」です。
OSSの課題点を提起し、課題に対する開発者の考え方や、コミッタが知る解決手法の共有などを行う場です。（だからこそ [ISSUE_TEMPLATE](https://github.com/l3tnun/EPGStation/blob/master/.github/ISSUE_TEMPLATE.md) が準備されています）
「こうした方がより良くなる」というテーマであれば、是非自信をもって「こうするべき」と提案すべきです。
決して「個人の好みを表明するだけ」に留めないほうがよろしいかと。

**Comment by l3tnun** [comment]
ルールページの役割は advancedbear さんのおっしゃるとおりですね。
検索とルール作成 & 編集を兼任しているページとなります。
そのため名称変更はしません。

ルールページにルール作成ボタンを追加するアイディア良いですね。

> フローティングボタンでルール追加ボタンを表示し、リンク先として単に検索画面 (/search) に飛ぶだけでも前述のような勘違いは起きにくくなりそうですね。

実装するならこの方法になりますね。

simplelife0530さんのルール作成ボタンの削除の話は、検索とルールのページを完全に分離してほしいという事だと思っていますが、分けるだけのメリットが実装のコストに見合わないので多分やらないです。

**Comment by advancedbear** [comment]
>フローティングボタンでルール追加ボタンを表示し、リンク先として単に検索画面 (/search) に飛ぶだけ

簡単にですが実装してみました。
操作性（とMaterial UI的に右下がベターかな？という感じもあるのですが）を鑑みて右下配置にしましたが、ルールのトグルスイッチと被りそうな感じもあるので検索ページ等の「トップへ戻る」のように左下の方が良いんでしょうかね？

**Comment by l3tnun** [comment]
ありがとうございます。
タブレット表示とスマホ表示ではトグルの位置が違うので迷いますね。
ちょっと弄って考えます。

検索ページの場合は検索ボタンに被ってしまうので左下に配置しています。

**Comment by l3tnun** [comment]
advancedbearさんの変更をマージしたので閉じます
