### ISSUE TITLE
【質問】config.jsonのrecordedFormatについて

### ISSUE THREAD

**Issue by Ahilu** [l3tnun/EPGStation#235]
### 環境
* Version of EPGStation: `1.4.1`
* Version of Mirakurun: `2.8.4`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS: Windows 10 pro
* Architecture: x64

### Issue
PC新調を機に、録画環境をEPGStationに移行させたいと思い、試行錯誤でようやっと動くようになりました。大変ありがたく思っております。
さて、一つ質問なのですが、

**"recordedFormat": "%TITLE%_%YEAR%%MONTH%%DAY%",**

と設定した場合に、録画ファイル名が、『**タイトル_20190215(1).ts**』
と『(1)』が末尾に付加されてしまい、%INPUT%と実際のファイル名に違いができてしまっているのか、録画ファイルのStreaming再生ができないです。録画ファイルの『(1)』をマニュアル作業で消すと、Streamingができるようになりました。
また、recordedFormatのデフォルト設定のときは、『(1)』は付加されないで、streamingもそのままできました。
これは、当方の特有(環境依存等?)の問題なのでしょうか？なにか、設定がなにか間違ってますでしょうか？

関係あるかどうかわかりませんが、保存先も
**"recorded": "D:\\TS_File",**
のように他のドライブに保存するようにしております。

**Comment by l3tnun** [comment]
ファイルパスの指定が正しくないです。
修正しましょう。

https://github.com/l3tnun/EPGStation/blob/master/doc/windows.md#パス名区切り文字

**Comment by advancedbear** [comment]
config全部が掲載されてるわけではないので推測ですが、 `recordedTmp` と `recorded` が同じパスになってないですかね？

ファイル末尾に(1)が付くのはこの辺の挙動がベースだと思うので。
https://github.com/l3tnun/EPGStation/blob/491686712bd630ab895b19bae5d92bb6944d7bfb/src/server/Model/Operator/Recorded/RecordedManageModel.ts#L696-L698

**Comment by Ahilu** [comment]
すみません。記載ミスです。
**"recorded": "D:\\TS_File",**
正しくとしてあります。

**Comment by l3tnun** [comment]
解決したようなので閉じます。
