### ISSUE TITLE
[雑談]とりあえずエンコードまでできました。

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#236]
要望でも質問でもありません。
使ってみた感想をどこにかけばいいのかわからないので、タイトルに[雑談]と入れました。
ほかに適切な場所があれば、ご教授ください。

エンコードまでできることが確認できたので、とりあえずchinachuと同じことをするために、映画、ドラマのルールを再現してみました。

ルールに関しては、chinachuよりいいところもあれば、もう少しというところもあります。でも、工夫すれば同じことはできます。epgstationの方が、放送局名がでるだけでも、優れてると思います。

エンコードの設定がとても簡単で、いいです。再生もTS、H264の両方選べて、まったく問題ありません。

これから十分使って、いろいろリクエストさせてください。

とりあえず、気になったのは、以下の２点です。

（１）録画中の番組が一覧でわからない。
ライブで赤枠表示、だけが確認できました。
できれば、番組表や予約でも、赤い薄塗りでわかると、安心できます。

（２）検索からのルール設定が下にありすぎ。
これは、検索で20件以上マッチすると、るーる設定の画面まで、かなりスクロールします。
例えば、ドラマで18時から9時間でGRとか設定すると、100は必ず越えます。
できれば、検索結果は、1番組1行で、ルール設定は、検索結果の上でもいいかなと思います。
あるいは、検索の場合は、ルール設定が検索結果の下に、今後できるかもしれないルール作成から飛ぶ画面では、検索した後、ルール設定が検索結果の上でも、いいかもしれません。

上記2点に関しては、既に使っている方の意見をお伺いしたい。

**Comment by l3tnun** [comment]
ここは雑談をする場所ではありませんので、感想等はブログやtwitterにでも書いてください。
あくまで課題管理を行う場であり、簡潔にお願いします。

> （１）録画中の番組が一覧でわからない。

明示的に表示する機能はありません。

録画ページのサムネイルが表示されていなもの ≒ 録画中の番組

となります。
予約ページで recording マークなどを付けて録画中か分かるようにするなんて事は良いかもしれません。


>（２）検索からのルール設定が下にありすぎ。

これは検索結果を確認してもらい、ルール作成をしてもらう事を目的として下に置いてあります。
最大300件表示される仕様ですが、
検索結果の良いページネーション ui が思い付かなかったため現状のような仕様となっています。

**Comment by simplelife0530** [comment]
githubは開発者チーム向けのプラットフォームなので、感想などを挙げるようなところじゃありませんね。chinachuでも、Issuesではなく、別にslackなどで雑談していました。
（１）は、予約ページで録画がマーキングされると良いでですね。トップページでも、「録画済み」と「予約」の両方に出ていることで録画中らしきことがわかりますが、同じようにマーキングされるとわかりやすいと思います。
（２）は、タイトルと放送日時だけでも十分ですし、詳細ボタンをつけて詳細表示ができれば完璧だと思います。
