### ISSUE TITLE
【要望】PC環境での番組表のドラッグスクロール

### ISSUE THREAD

**Issue by gifuhabu** [l3tnun/EPGStation#237]
### 環境
* Version of EPGStation: `1.2.7`
* Version of Mirakurun: `2.7.5`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS: Debian
* Architecture: x64

### Issue
お世話になっております。
番組表でドラッグを用いたスクロール機能が非常にほしいです。
Chinachuだとこの機能がありますが、EPGStationだとできません。
チルトホイールに対応していないマウスを使用している人は横スクロールができないので
いちいち下のスクロールバーを動かす必要があり煩わしいと思われます。
それと、番組表で文字を選択する必要性はあまりないと思うので、スクロールのほうが便利だと思います。

自分でも実装しようと[dragscroll.js](https://github.com/asvd/dragscroll)というライブラリを使用してみましたが何故かスクロールができなくなってしまったのでこの度このIssueを立てました。
ご検討いただけたら幸いです。

**Comment by l3tnun** [comment]
macのトラックパッドでの操作でしていたので気が付かなかったです。
たしかにドラックできると嬉しいですね。

番組表のスクロール周りは複雑なので実装できるかはわかりませんが、検討してみます。

**Comment by l3tnun** [comment]
最新の master にて番組表でのドラッグスクロールが可能になりましたので閉じます。

**Comment by gifuhabu** [comment]
ご実装していただき、ありがとうございました。
