### ISSUE TITLE
【要望】エンコードオプションの映像/音声分離

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#238]
### 環境
* Version of EPGStation: `1.2.5`
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Winfows 10
* Architecture: x64

### Issue
エンコードの【設定】ですが、元々は主音声/副音声の設定として作られたものと考えております。

一方で「これはHDリマスターだから480pに圧縮」「これは元々720/24p製作だから720/24pで圧縮」「映画は5.1ch番組だから音声は無圧縮」の様に、動画圧縮のパラメータ切り替えとして便利に使わせていただいております。

現在は映像パラメータと音声パラメータそれぞれで作っているのですが、映像パラメータと音声パラメータを別々で指定できれば選択肢が減ってやりやすいです。

UI上は設定となっているところを左右に分割して映像/音声とすれば入りそうではあります。

映像：1080i　※720/24p　480p　音声：※Main Sub Copy
（※はデフォルト）

・「字幕を保存しない」の様な選択肢もあると便利そうですが、そもそもMirakurunだと字幕取れないのでしょうか（EDCBの時はあった気がします）

・エンコパラメータをWeb上で設定できる（設定文字列をアップロードできる）と面白そうですが、需要が低すぎるかもしれません。

勿論喫緊ではないので、お手すきの際に検討いただけますと幸いです。

**Comment by l3tnun** [comment]
管理が大変なため、エンコード時のパラメータを増やす予定はありません。

字幕に関しては Mirakurun 側の問題ですのでここでは取り扱いません。
