### ISSUE TITLE
【要望】「録画済み」画面からのエンコードについて

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#241]
### 環境
* Version of EPGStation: `1.4.0`
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS:Windows10
* Architecture: x64

### Issue
「録画済み」画面からencodeを実行する際毎回「元ファイルと同じ場所に保存」「TS削除」にチェックを入れています。

「録画済み」画面の「設定（現在はlist表示のオン・オフ）」辺りに、検索画面の「設定」にあるような「元ファイルと同じ場所に保存」「TS削除」をデフォルトでオンにするスイッチを追加することは可能でしょうか。

**Comment by l3tnun** [comment]
最新の master にて手動エンコードの以下の選択を記録するようになりました。

・設定
・元ファイル
・同じ場所に保存とTS削除

要望の機能とは異なりますが、代用可能だと思いますので閉じます。
