### ISSUE TITLE
[要望]検索画面の構成について

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#242]
先週から使い始め、mp4のエンコードがqsvでできるように設定できました。
ルールごとに、エンコードのオプションと保存ディレクトリの設定ができるのは、すごく便利です。

１点要望があります。

**検索画面で、検索を行った後の画面で、検索結果の上に「ルール設定」というボタンを表示する。**

これは、今まで使っていて、検索結果件数が多いときに、一番下までスクロールしないと、ルール設定ができない不便さを解消するものです。

検索条件を決めて検索した結果、ヒットした件数を確認したら、すぐにルール作成に入りたい（せっかちなのかもしれませんが）ので、そこで、「ルール作成」ボタンを押すと、ルールの条件が表示される（同じ画面の中で展開されるイメージ）と、操作が非常に楽になります。

ご検討よろしくお願いいたします。

**Comment by l3tnun** [comment]
なるほど、良いですね。
検討します。

**Comment by l3tnun** [comment]
最新の master にてヒット件数の横にリンクボタンを設置しました。
クリックするとルール設定カードの位置までスクロールします。
