### ISSUE TITLE
[番組表]MirakurunにCSのチャンネル未登録時、CS番組表に遷移するとローディングが終わらない。

### ISSUE THREAD

**Issue by Velgail-HSP** [l3tnun/EPGStation#243]
### 環境
* Version of EPGStation: `1.4.3`
* Version of Mirakurun: `2.8.4`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS: Windows10 Pro
* Architecture: x64
(Mirakurun/EPGStationは同一マシンにて構成しています)

### Issue
MirakurunにCSチャンネルを一つも登録していないとき、CS番組表のタブを選択するとローディングが終わらず他の番組表等に遷移できない。（Issue発行理由）
同じく、MirakurunからBSチャンネルをすべて削除したとき、BS番組表のタブを選択するとローディングが終わらず他の番組表に遷移できないことを確認しました。（追加検証）

### 改善案
1. 上記ローディング待機の修正
1. Mirakurunのチャンネルリスト等で各type:GR,BS,CS にチャンネルが1つもない場合に、そのタブは表示しない修正

以上です。

**Comment by l3tnun** [comment]
あー確かに番組情報が空だとローディングが終了しない仕様になっていますね。修正します。

番組表のGR, BS , CSのリンクはMirakurunのチューナ情報から生成しているので、
CSを使用していないのであればMirakurun側で無効化してもらえれば表示されなくなります。

**Comment by Velgail-HSP** [comment]
なるほど、2.の方はtuners.ymlからCSを削除することで実現できるということですね。承知しました。

**Comment by l3tnun** [comment]
最新の master にて番組データが空のときに番組表のローディングの表示が終わらない問題に対応しました。
