### ISSUE TITLE
デフォルトのffmpegオプション修正

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#247]
Related #244 
### Issue
`/config/enc.sh` 及び `/config/enc.js` に標準で記載されているffmpegのエンコードオプションについて、以下のような問題点がある。

1. `-dual_mono_mode`が指定されているが、ステレオ多重音声の番組では効果がない。
    - 上記オプションはデュアルモノ音源 (`AUDIOCOMPONENTTYPE`が`2`の場合)にしか効果がないため。
1. `-analyzeduration`指定がないため、Mirakurunの設定によっては間違った解析が行われる。
    - デフォルトの`-analyzeduration`は5秒であるため、録画開始マージン(Mirakurunにおける`maxBufferBytesBeforeReady`による設定)が5秒以上ある場合は前番組の情報でエンコードを開始してしまう。
1. `-probesize`指定がないため、TSファイルによっては間違った解析が行われる。
    - デフォルトの`-probesize`は約5MBであるため、録画開始マージンや動画ビットレートなどの条件によっては本番組開始前に容量上限に達してしまい、前番組の情報でエンコードを開始してしまう

以上のような点により、前番組と本番組で音声ストリームが異なる場合などにエンコードが失敗したり、エンコード結果が適切でない場合がある。

### Solution
デフォルト設定として、より適切なffmpegオプションを選定する

**Comment by l3tnun** [comment]
適切なissueありがとうございます。
要点がまとめられていて非常に分かりやすいです。

**Comment by advancedbear** [comment]
`-s` オプションでリサイズ処理を行っているのも個人的にはどうなのかなぁと思っています。
ビデオフィルタとして `-vf` オプションの`sclae`機能を使って `-vf yadif,scale=-2:720` のように指定したほうが、1440x1080番組は960x720のDAR=16:9に、1920x1080番組は1280x720のDAR=16:9になるので変換時の速度も速く、なおかつファイル容量も抑えられるかなぁと思います。

#### scaleフィルタの場合
>ffmpeg ^
-analyzeduration 30M ^
-probesize 30M ^
-dual_mono_mode main ^
-i %INPUT% ^
-sn -dn -ignore_unknown ^
-vf yadif,**scale=-2:720** ^
-preset veryfast ^
-c:v libx264 -crf 23 ^
-c:a aac -ar 48000 -ab 192k -ac 2 ^
-f mp4 %OUTPUT%
>
>frame=17987 **fps=199** q=-1.0 **Lsize=   83048kB** time=00:10:00.06 bitrate=1133.8kbits/s dup=18 drop=0 **speed=6.65x**

#### -s オプションの場合
>ffmpeg ^
-analyzeduration 30M ^
-probesize 30M ^
-dual_mono_mode sub ^
-i %INPUT% ^
-sn -dn -ignore_unknown ^
-vf yadif ^
**-s 1280x720** ^
-preset veryfast ^
-c:v libx264 -crf 23 ^
-c:a aac -ar 48000 -ab 192k -ac 2 ^
-f mp4 %OUTPUT%
>
>frame=17987 **fps=191** q=-1.0 **Lsize=  105547kB** time=00:10:00.06 bitrate=1440.9kbits/s dup=18 drop=0 **speed=6.37x**

時間短縮としては約4%、容量削減としては約20%くらいのパフォーマンス向上になりますね。
ただ、上記は8C16TなRyzen7 1700マシンでエンコードしているので、低スペックな環境だと差は縮まると思いますし、必ずしも速くなるとは言えないかもしれません。

**Comment by l3tnun** [comment]
feature-247 ブランチにて修正しました。
修正点は以下の通りです。

1. ```config.sample.json``` の ```encode``` を修正。
　・```enc.sh``` から ```enc.js``` へ変更
　　理由は ```enc.sh``` と ```enc.js``` 両方のメンテが面倒なためです。

2. ```enc.js``` で ```ffmpeg``` に与えるオプションを修正
　・引数 ```main``` と ```sub``` の廃止
　・```-dual_mono_mode```. ```-analyzeduration```, ```-probesize``` の見直し
　・```-vf yadif,scale=-2:720``` でリサイズを行うように変更

他に何かあれば言ってください。

> そして何より、趣味レベルのパラメータ微調整をデフォルト設定に組み込む程のことか？という点はつきまとうかと思うので、必要最低限レベルにすべきかどうかの方針だけでも頂ければなと思っています。

明確な線引きはありませんがデフォルトの設定 (=config.sample.jsonほぼそのまま) で、それなりに不満なく使えたらなあと思っていますので、汎用的にパラメータを詰める分には良いと思います。

**Comment by advancedbear** [comment]
エンコード設定の変更、ありがとうございます。

前番組の関係で本番組の主音声・副音声が入れ替わってしまう問題や、ステレオ多重音声放送については、ffprobeで取得した情報をもとにmapし直す必要があるのですが、EPGStationはffprobeを必須としていないこともあるので、ffmpegで-iだけを指定した際の標準エラー出力から情報を取得して…という方法が必要そうです。

```javascript
// これより手前で AUDIOCOMPONENTTYPE が 2 で無いことを確認する
let child = spawnSync(ffmpeg, ['-i', input]);
if((String)(child.stderr).match(/Audio: aac/g) >= 2) {
    if(process.argv[2] === 'main'){
         Array.prototype.push.apply(args, ['-map', '0:v:0', '-map' '0:a:0']);
    } else if (process.argv[2] === 'sub'){
         Array.prototype.push.apply(args, ['-map', '0:v:0', '-map' '0:a:1']);
    }
}
```

----
また、

| オプション | 内容 |
| --- | --- |
| `-sn` | ffmpegで解析可能な字幕ストリームがある場合でも無視する |
| `-dn` | ffmpegで解析可能なデータストリームがある場合でも無視する |
| `-ignore_unknown` | ffmpegで解析不可能なストリームは無視する |
| `-movflags faststart` | ストリーミング再生最適化のためにメタ情報をファイル先頭に置く |

あたりをオプションとして含めると良いかなと思います。
（上３つはMP4エンコードではあまり必要性はなさそうですが、、、）

**Comment by l3tnun** [comment]
最新の master にて enc.js の修正を反映させました。
音声の再マップについては #249 の影響で修正が難しいため行いません。
