### ISSUE TITLE
[要望]ルールの作成の一部拡張

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#250]
現在ルールの作成を行っていますが、大量に作成しなければならず、ルール入力の省力化を考えています。方法としては、以下の２つを考えました。
（１）録画終了時の外部コマンドとして作成、
（２）現在のルールの一部拡張、

ここでは、（２）の方法に関して要望として書いてみます。

現在、大量に書いているルールは、以下のようなものを、番組ごとに作成しています。

![ルール編集](https://user-images.githubusercontent.com/8540097/54183511-ae111500-44e7-11e9-933c-e425d2491b6e.png)

なぜ、このようなルールを書いているかと言えば、plex media serverのTV番組のネーミングルールに従ったディレクトリ、ファイル名の設定を自動で実現するためです。

TV Shows/ShowName/Season XX/ShowName – YYYY-MM-DD.ext
上記の形式でファイル名を付けると、以下のように表示が可能となります。
![news7の画面](https://user-images.githubusercontent.com/8540097/54187858-c7b75a00-44f1-11e9-99b3-418b35750028.JPG)

これを実現するために、2つの仕様追加が必要と考えています。

（１）%TITLE%に加えて、例えば%NAME%のような番組名という変数を追加する。
番組情報には、以下のようなものがあるようですが、
"title":"情熱大陸",
"fullTitle":"情熱大陸【ときど／東大卒のプロゲーマー！賞金２７００万円大激闘に完全密着!!】[字]",

%TITLE%は、上記"fullTitle"に対応しています。"title"に相当する番組名の変数を追加してほしい。

（２）エンコードのディレクトリ設定で、変数の記述を使いたい。
例えば、以下のような記述ができると助かります。
/documentary/%NAME%/"Season 01"/

当面は、一つ一つ作成すれば可能ですが、上記が実現すれば、複数のキーワードを入れても一つのルールで記述が可能となります。

よろしくお願いいたします。

**Comment by l3tnun** [comment]
ディレクトリ指定部分でもファイル名形式のような記述で、番組名に応じてディレクトリ名を動的に変更させたいということですね？

変数として何を使いたいか↓のような表にまとめて下さい。
https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#recordedformat

**Comment by l3tnun** [comment]
ああ、別にまとめてもらう必要はないですね。

↓に追加したいものがあればまとめて下さい。
https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#recordedformat

**Comment by simplelife0530** [comment]
以前、ルールが一杯できるから、まとめて削除できるようにしたいという要望がありました。

アプローチは違いますが、ルールを一杯作らないで、キーワードの一部削除という形で実現できれば、解決策になると思います。また、場合によっては、クールごとにルールを作成しなくても、自動で運用できるようになる場合もあることでしょう。ドラマなら時間枠設定だけでいけるかもしれません。

**Comment by simplelife0530** [comment]
> ああ、別にまとめてもらう必要はないですね。
> 
> ↓に追加したいものがあればまとめて下さい。
> https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#recordedformat

了解しました。
最初は、「番組名　%NAME%」だけで良いかと思いましたが、
ジャンル、日付などがあれば、もっと使えそうです。
ドラマのシーズンや話数なども取れるならばほしいところですが、
番組情報としてどこまで取れるのか、理解できていません。
とりあえず、録画ファイル名の変数一覧の形式で、追加する変数の希望一覧を作成してみます。
２日ほど考えてみます。

**Comment by simplelife0530** [comment]
番組情報の中を調べてみました。
例えば、「家売るオンナの逆襲」の最終回からピックアップすると、以下のような情報です。

番組情報
"category":"drama",
"fullTitle":"家売るオンナの逆襲#10[終][解][字][デ]　留守堂の逆襲!!今夜衝撃のラストショーが開幕!"
"title":"家売るオンナの逆襲",
"subTitle":"留守堂の逆襲!!今夜衝撃のラストショーが開幕!",
"episode":10,
"flags":["終","解","字","デ"],

"fullTitle"は、既に%TITLE%で変数としてあります。
ファイル名やディレクトリ名で追加使用したいのは、以下の４つではないでしょうか。
"category"
"title"
"subTitle"
"episode"

これが使えれば、plex media serverのネーミングルールは問題なさそうです。

**Comment by l3tnun** [comment]
あーこれって chinachu の番組情報ですか？
EPGStation の情報は /api/debug から確認してください。

**Comment by simplelife0530** [comment]
EPGStationのディレクトリの中を探しましたが、/api/debugがどこにあるか、わかりませんでした。

chinachuの情報は、番組表から独自に抽出したものも含まれているんですね。

plexの名前ルールに従えば、ディレクトリに番組名を変数として入れられれば、まずは十分です。

が番組名だけ取れないということなんでしょうね。%TITLE%には、サブタイトルに相当する部分が含まれています。これだと使えないし、サブタイトル部分を除くのは、難しいかもしれません。

**Comment by l3tnun** [comment]
readme を読みましょう

https://github.com/l3tnun/EPGStation/blob/master/doc/webapi.md

**Comment by simplelife0530** [comment]
なるほど。swaggerですか。中見てみます。

**Comment by simplelife0530** [comment]
大分勉強になりました。
/schedule/detail/{id}「program id を指定して番組詳細を取得する」
を参照してみましたが、nameとdescriptionでは、私のアイディアは実現できないようです。
なんで、nameとdescription以外に、番組名、サブタイトル、話数を別のフィールドとして追加するだけで、かなり便利になりますが、いろいろな事情があるのかもしれません。

と思ったら、もっと簡単に実現するアイディアがありました。
検索でマッチした文字列を、ディレクトリ指定の中の変数として定義できれば、かなり便利です。
これは、録画とエンコードのディレクトリの両方で、使えるといいと思います。

この機能があれば、今まで番組ごとにルールを作っていた人が、一つのルールで複数記述できるようになります。

現状であれば、　AAAという番組を/record/AAA、BBBという番組を/record/BBB、CCCという番組を/record/CCCに書き込む場合、３つのルールが必要になります。

例えば、マッチする文字列を%MATCH%という変数にできれば、
キーワードを正規表現で、AAA|BBB|CCC　と書いたとすると、
ディレクトリの指定に、/record/%MATCH%のように書けるかもしれません。
エンコードのディレクトリでも同じです。

もし問題なければですが、ファイル名の変数に%MATCH%のようなものを追加できて、
ファイル名でもディレクトリでも使えれば、さらに汎用性が増すかもしれません。

ご検討のほどを。

**Comment by l3tnun** [comment]
なんの情報をマッチさせるのでしょうか？曖昧でよく分かりません。

**Comment by simplelife0530** [comment]
「情報をマッチさせる」のではないですね。
検索時というかルール設定時の、キーワードの文字列そのものを、変数として定義できればいいと思いますよ。

**Comment by l3tnun** [comment]
要件が散乱していて、実装要点が不明なので閉じます。
