### ISSUE TITLE
[要望]重複排除に放送局の条件を追加

### ISSUE THREAD

**Issue by ykym** [l3tnun/EPGStation#251]
### 環境
* Version of EPGStation: `1.4.5`
* Version of Mirakurun: `2.9.0`
* Version of Node: `v10.15.3`
* Version of NPM: `6.4.1`
* OS:Debian 9.8 (docker-mirakurun-epgstation)
* Architecture: x64

### Issue
重複判定に、指定した放送局に絞るかどうか選択できるようにすることはできないでしょうか。

CSの番組で1週間のうちに何度も再放送がされるものを重複排除機能で排除しているのですが、
CSよりも先に地上波等他局で同一番組名の放送があった場合、CS局での予約がすべて重複扱いに
なってしまい、1回も録画されなくなります。

希望としては、地上波・CS初回放送分をそれぞれ録画したいので、ルール設定で同一局内のみでの
重複判定が行えると助かるのですが、ご検討いただけないでしょうか。

**Comment by l3tnun** [comment]
現行の仕様では重複検出のために番組名しか記録していないため、今すぐには難しいですね。
検討します。

**Comment by ykym** [comment]
ご検討ありがとうございます。

一旦運用で対応していこうと思っているのですが、重複用に番組名を保持している情報へ
アクセスできるような API はございますか？
/api/debug を確認してみたのですが、そのようなものは見当たりませんでした。
見落としていたら申し訳ありません。
無いようであればテーブルを直接参照するか録画済みの情報を元に対応してみます。

**Comment by l3tnun** [comment]
そのような API は用意されていないですね。

**Comment by ykym** [comment]
了解です。ありがとうございます。

**Comment by l3tnun** [comment]
最新の master にて対応しました
互換性のため放送局情報が無い番組履歴データでも重複判定となります
(今後新規でルール録画される録画履歴には放送局情報が付加されます)
古い録画履歴が消えるまで待つか、/api/debug にて録画履歴をすべて削除する api を実行し録画履歴をすべて削除してください
