### ISSUE TITLE
[提案]ルール拡張フィールドその他。

### ISSUE THREAD

**Issue by Takunsyo** [l3tnun/EPGStation#256]
### 環境
* Version of EPGStation: `1.4.8`
* Version of Mirakurun: `2.10.0`
* Version of Node: `v8.11.4`
* Version of NPM: `5.6.0`
* OS: Microsoft Windows 10, Ver. 1803 Build 17134.590
* Architecture: x64
### Issue
...
何時もEPGStation愛用しております、素敵なソフトを作っていただいて感謝しております。

半年の間使わせて頂いておりますが、何点か提案があります。

1．発見した問題
　Windows環境でNode.jsが不安定なところがあります、たまにMirakurunのプログラムデータ(Programs.json)が壊れることがあります。
　その場合、Mirakurunが全ての番組情報をなくしますが、EPGStation
がMirakurunの番組情報収集の作業完了する前に立ち上げれば、ルールで確立した予約以外、失われます。このようなことを2回ほど確認しています。
　一回だけEPGStationの<reserves.json>が千の風のなったことがありまして、0xffで充填されていました。
　これはたぶん自分のPCが悪いのですが、近日Mirakurunの番組表が死ぬことを友人のPCからも確認されました、同じくルール予約以外全部死にました。
2．提案その一
　ルールに関しますが、私の場合シーズンごとに新しいルールを番組情報がTSで流れる前にルール登録することが多いです。登録の時期が早いから検索で出てきませんので、別途excelを使って放送日付けなどを記録してこまめに確認しています。
　もしできれば、ルールの元にコメントフィールドを用意して頂ければ結構便利です。
3．提案その二
　同じくルールに関するものですが、ルールが作用する期間があれば助かります。
　例えば番組Aのシーズン1が3月25日まで再放送されますが、3月26日からはシーズン2が始まるといいます。シーズン1だけ必要な時は【25日まで】と設定ができ、シーズン2だけ必要は【26日から】とかあればありがたいです。

　ご検討をお願い申し上げます。

**Comment by l3tnun** [comment]
1 について
Mirakurunから番組情報が得られない場合、その番組は消滅したと判断し削除していますので仕様となります。
EPG取得が完了したなどの情報が Mirakurun から取れないので対策は難しいです。

reserves.json が 0xff で埋められる理由は分からないです。windows特有の現象かと思います。
予約情報を DB へ移せば根本的な解決になりますが、すぐには難しいですね。（いつかはやりたいですが）

2, 3 について
あると便利そうな機能ですね。検討します。
（issueの溜まり具合を見れば分かると思いますが作業時をなかなか確保できないため、いつ実装できるかは分かりません）

**Comment by Takunsyo** [comment]
ご返答ありがとうございます。

0xffで埋め尽くされる件は、たぶんWindowsがクラッシュの時書き込みに使われているファイルストリームがフラッシュされていなかったからファイルがダメになったと思われます。かなり珍しいイベントですので…対策は不要かと思います。

EPGが一時的に消えると予約情報が削除される仕様が良く理解できました。可能であれば削除する前20分～1時間ほどの執行猶予があれば…　勝手にEPGがアップデートされます。（ロジックが複雑になるでしょうか？）

**Comment by l3tnun** [comment]
> 可能であれば削除する前20分～1時間ほどの執行猶予があれば…

通常のEPG更新時に放送直前に変わる可能性があるため即時反映の仕様となっています。一時的に消えただけなのか EPGStation 側で判断することは難しいです。

**Comment by Velgail-HSP** [comment]
>通常のEPG更新時に放送直前に変わる可能性があるため即時反映の仕様となっています。一時的に消えただけなのか EPGStation 側で判断することは難しいです。

EPG更新時の直前変更の場合はMirakurunのプログラムデータって局の全データを消去して再生成しているのでしょうか？　それとも直前の変更で必要な部分だけを修正しているのでしょうか？

以下Mirakurun側から取得できるEPG情報をMirakurun-EPG、EPGStation側が保持している（予約用のデータ）はEPGStation-EPGとして書きます。

仮に後者の場合は、例えば各Ch毎に3日先までのMirakurun-EPGが存在しない場合で、且つEPGStation-EPGはそれ以上未来の番組情報を持っている場合に限って当該ChのEPGStation-EPG更新を反映しない　といった機能はいかがでしょうか。

また前者の場合でも、EPGStation-EPGが未来の情報を持っていて、且つMirakurun-EPGが番組情報なしの場合には一旦EPGStation-EPG情報を保持する（これも各Ch毎）という仕様である程度カバーができるのではないでしょうか？

ソースコードを読んでいないためEPGStation-EPG自体がないとかでしたらすみません。

**Comment by l3tnun** [comment]
> EPG更新時の直前変更の場合はMirakurunのプログラムデータって局の全データを消去して再生成しているのでしょうか？　それとも直前の変更で必要な部分だけを修正しているのでしょうか？

前者になります。

なるほど明らかに Mirakurun 側のデータに欠落がある場合更新しないという処理ですね。
検討します。

**Comment by Velgail-HSP** [comment]
* reserves.json の0xff問題について
再現性はそこまで高くありませんが、例えばBSODなど瞬間的に落ちる事象に遭遇すると発生しやすい模様です。
発生するとEPGStationのサービスが起動できないという重大な問題になってしまう（発生すれば常時）ので、reservers.jsonが読み込めない場合は**諦めて破棄して再生成**する機能が必要かもしれません。
（2020年3月頃のバージョン（バージョン番号失念）でも遭遇したので、今あらためて記述します）

**Comment by l3tnun** [comment]
破棄 & 再生成処理は手動予約情報が消えるので避けていたのですが、サービスそのものが起動しないよりはましと考えれば悪くないかなあと思いました。
時間があるときに実装しようと思います。

v2.0 では予約情報をすべてDBにしますので、将来的には解消される予定です。

**Comment by l3tnun** [comment]
v2.0で予約情報が全てDBへ保存されるようになりました。
よって、reserves.jsonが破壊される問題は解決しました。

また、mirakurunからの番組情報を取得する方法が変更された影響で、
mirakurun側のprograms.jsonが破壊されたときのリカバリー実装は不可能となりました。

対応可能なものは対応しましたので閉じます、
