### ISSUE TITLE
起動時にエラーが発生する

### ISSUE THREAD

**Issue by Marron0421** [l3tnun/EPGStation#257]
### 環境
* Version of EPGStation: `1.4.8`
* Version of Mirakurun: `2.1.0`
* Version of Node: `v8.x.x`
* Version of NPM: `x.x.x`
* OS:CentOS
* Architecture: x64

### Issue
起動時に、下記のようなエラーが発生してしまい、起動できません
```
[root@localhost ~]# pm2 start dist/server/index.js --name "epgstation"
[PM2][ERROR] script not found : /root/dist/server/index.js
script not found : /root/dist/server/index.js
```

...

**Comment by l3tnun** [comment]
```npm start``` or ```node dist/server/index.js``` でも立ち上がらない状態ですか？

**Comment by Marron0421** [comment]
個人的に解決しました
