### ISSUE TITLE
 ルール編集で、除外が削除になっている。

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#259]
### 環境
* Version of EPGStation: `1.4.8`
* OS: CentOS 7.4
* Architecture: x64

### Issue 除外が削除になっている。

ルール編集画面で、キーワードで検索した結果の中から、必要ないものをスキップする時、
「削除」になっている。

しかし、「削除」したものを、再度解除しようとすると、「除外解除」というメニューが出る。

統一されていないことと、実際には「削除」していないことを考慮すると、
「削除」→「除外」もしくは「スキップ」「スキップ解除」などに
変更したほうが、良いのでは？
...
![除外が削除](https://user-images.githubusercontent.com/8540097/55793551-25918e80-5afe-11e9-86e9-47c0d4d30e6a.JPG)
![除外解除](https://user-images.githubusercontent.com/8540097/55793562-2aeed900-5afe-11e9-8a5d-9fc6ec0e45b7.JPG)

**Comment by l3tnun** [comment]
文字数の関係でそのような仕様になっています。(iPhone SE等)
変更予定はありません。

**Comment by advancedbear** [comment]
文字数の関係は理解できますが、「削除」のoppositeとなる動作を発生させるボタンが「除外解除」なのは違和感を感じます。
削除の対は復元でしょうし、除外解除の対は除外でしょう。

「この録画予約を削除する」という意味での「削除」であることは分かりますが、動作としては「ルールによる自動録画予約対象から除外する」というものですし、「除外」ボタンのほうが適切かなと私も思います。

**Comment by advancedbear** [comment]
と思いましたが、コードを見る限りだと検索画面での番組情報表示は他画面とコンポーネントを共通化させてるんですね。

https://github.com/l3tnun/EPGStation/blob/d819ecb91ddfe65b35729f613445f8de53af32dc/src/client/Component/Program/ProgramInfoActionComponent.ts#L61-L75

getReserveOptionRuleId()辺りを呼び出して、該当番組がRuleIdを持っているかチェックしたうえで、Ruleによって予約された番組の場合だけ「削除」ではなく「除外」にするとかですかね……。

**Comment by l3tnun** [comment]
ああ、すいません「削除」→「除外」を見落としていました
これは良いと思います

**Comment by l3tnun** [comment]
最新の master にて削除から除外に変更しました。
