### ISSUE TITLE
ブラウザでの再生が開始しない（Windows環境）

### ISSUE THREAD

**Issue by subdiox** [l3tnun/EPGStation#260]
### 環境
* Version of EPGStation: `1.4.8`
* Version of Mirakurun: `2.10.1`
* Version of Node: `v10.15.3`
* Version of NPM: `6.4.1`
* OS: Windows 10 Professional 2018 October Update
* Architecture: x64

### Issue
[doc/windows.md](https://github.com/l3tnun/EPGStation/blob/master/doc/windows.md)の通りにEPGStationをセットアップしたのですが、Google Chromeで http://localhost:8888 を開いてWebMでライブ視聴をしようとしても `500 Internal Server Error(StartStreamError)` が発生します。これはHLSやM2TSなどを選んでも同じ内容のエラーでした。
ちなみに、 `config\config.json` は以下のようになっています。
```
{
    "readOnlyOnce": false,
    "serverPort": "8888",
    "mirakurunPath": "\\\\.\\pipe\\mirakurun",
    "dbType": "sqlite3",
    "ffmpeg": "D:\\FFmpeg\\ffmpeg.exe",
    "ffprobe": "D:\\FFmpeg\\ffprobe.exe",
    "maxEncode": 2,
    "encode": [
        {
            "name": "H264",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe D:\\TV\\EPGStation\\config\\enc.js main",
            "suffix": ".mp4",
            "default": true
        },
        {
            "name": "H264-sub",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe D:\\TV\\EPGStation\\config\\enc.js sub",
            "suffix": "-sub.mp4"
        }
    ],
```
（これ以降は `config\config.sample.json` と同じ）

FFmpegのパスは正しい上に上記のコマンドをコマンドプロンプト上で自分で実行するときちんと再生できたことから、行き詰まってしまいました。
そこで、エンコードのログを見るために `config\operatorLogConfig.json` と `config\serviceLogConfig.json` を以下のようにログレベルを細かくする編集を加えたのですが、ライブ視聴しようとしても `logs\Operator\stream.log` にも `logs\Service\stream.log` にも、一切ログは追加されませんでした。
```
    "categories": {
        "default": { "appenders": [ "console", "stdout" ], "level": "trace" },
        "system": { "appenders": [ "system", "stdout" ], "level": "trace" },
        "access": { "appenders": [ "access", "stdout" ], "level": "trace" },
        "stream": { "appenders": [ "stream", "stdout" ], "level": "trace" }
    }
```

EPGStationのライブ視聴機能/録画視聴機能がWindows 10で動作していると記しているブログやウェブサイトは多いため不具合ではないと思うのですが、どうあがいても動くようにならないのでIssueを立てた次第です。解決方法を提示していただけると助かります。

**Comment by l3tnun** [comment]
```serviceLogConfig.json``` 変更後に EPGstation の再起動はしましたか？
config.json の ffmpeg の設定が正しくできていれば何らかのログが残るはずです。

ffmpegが正しく動作しているか怪しいので、適当な動画ファイルを用意して以下のコマンドを実行して見てください。
これが動くのであれば M2TS でのライブ視聴は問題ないはずです。

ffmpeg  -re -dual_mono_mode main -i input.ts -c:a aac -ar 48000 -ab 192k -ac 2 -c:v libx264 -s 1280x720 -preset veryfast -aspect 16:9 -vb 3000k -f mpegts out.ts

**Comment by l3tnun** [comment]
あと、```logs\Service\system.log``` に何か出ていれば教えて下さい。

**Comment by subdiox** [comment]
大変申し訳ありません、config.jsonのffmpegのパスが間違っておりました。
何度も確認したつもりだったのですが…。ffmpegのパスをきちんと設定したらログもきちんと出るようになり、ライブ視聴もできるようになりました。
ありがとうございます。
