### ISSUE TITLE
【要望】ライブでの放送局ロゴの表示

### ISSUE THREAD

**Issue by unlimish** [l3tnun/EPGStation#261]
### Idea
ライブ(チャンネル一覧)のリストに放送局ロゴを表示することで直感的にチャンネルを認識できるようにしていただけると助かります。

**Comment by l3tnun** [comment]
Mirakurunからロゴ取得時に Cache-Control がないので、いつ更新されたかわからないなーと悩み実装していないのが現状ですね。
検討します。

**Comment by l3tnun** [comment]
v2.0で表示されるようになりました。
そのため、閉じます。
