### ISSUE TITLE
検索条件に複数のチャンネルやジャンルを指定

### ISSUE THREAD

**Issue by aaaiuoeraga** [l3tnun/EPGStation#264]
ブラウザから設定したところ、ルール毎に一つのチャンネルやジャンルを指定できたのですが、
直接設定ファイルを編集して複数チャンネルやジャンルに対応できますか？

**Comment by l3tnun** [comment]
データベースの構造上不可能です。
実装が面倒なので割り切ってそのような仕様になっているだけですね。

**Comment by l3tnun** [comment]
v2.0で対応しました。
