### ISSUE TITLE
storageLimitActionの挙動

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#265]
### 環境
* Version of EPGStation: `1.4.6`

### Issue
config.jsonの設定に関して

"recorded": "/home/media"というディレクトリを指定しています。
これは、SSDで140GBの空き容量があります。

この/mediaの下に、以下のシンボリックリンクとフォルダがあります。
/home/media/tv 　　　　フォルダ
/home/media/drama 　　シンボリックリンクで/mnt/data1/dramaに

tsファイルを/tvの下に保存しています。そして、エンコード後自動削除にしているので、空き容量は100GB以下になっていませんでした。

空き容量が18GB以下になる時、自動的に/tv配下のtsファイルを削除しようと思い、以下の設定をしてみました。
"storageLimitAction": "remove"
"storageLimitThreshold": 18000

ところが、この設定をした後、なぜか/home/media/dramaのリンク先にあるファイルが少しづつ自動的に削除されるという現象が発生しました。

いまだ、関連性は定かではありませんが、設定する前（4月24日）までは起こっていませんでした。本日4月9日から4月17日までのファイルが削除されていることに気が付き、とりあえず
"storageLimitAction": "remove"
"storageLimitThreshold": 18000
は削除して、epgstationを1.4.9バージョンアップしてみました。

ストレージ空き容量は、epgstationの表示でも140GBあり、muninで確認してみましたが、24日以降100GBを下回ったことはありません。18GB以下になり、この削除アクションが実行されたことはないと思います。

まだ、他に原因があるかもしれませんので、
"storageLimitAction": "remove"
"storageLimitThreshold": 18000
をconfigから削除した状態で運用し、再度発生するか確認し、また報告します。

**Comment by l3tnun** [comment]
recorded で設定したディレクトリの配下に、シンボリックリンクを配置した場合の挙動は何も顧慮されていません。
そのようなディレクトリ構成はやめましょう。
