### ISSUE TITLE
番組詳細で文字列のドラッグが出来ない

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#271]
### 環境
* Version of EPGStation: `1.5.1`
* Version of Mirakurun: `2.10.1`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* OS: Windows Server 2016 / CentOS 7.5
* Architecture: x64
* Browser: Google Chrome| 74.0.3729.157 (Official Build) （64 ビット）

### Issue
番組をクリックした際に表示されるバルーンにおいて、番組名、番組情報等は文字列のドラッグが出来るが、番組詳細だけがドラッグできない。(下記GIF参照)
開発者ツールで見ていると、バルーン全体に対して何らかのイベントがハンドラされており、バルーン内のどこかでmouseupされた際にclass=extendが再描画されている（結果範囲選択が解除される）ように見られる。

![gif1](https://user-images.githubusercontent.com/9246266/57972950-30ccb980-79dc-11e9-96a1-a390d52119d6.gif)

結果として、リンク化されないURL（http～で始まらないもの）や、Twitterアカウント名（@～～～だけ記載のもの）について右クリックからリンクを開いたりコピーしたりという操作に支障が生じる。

**Comment by l3tnun** [comment]
最新の master にて修正完了しましたので閉じます。
