### ISSUE TITLE
長時間稼働でEPGStationが番組情報取得できなくなる

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#272]
### 環境
* Version of EPGStation: `1.4.9`
* Version of Mirakurun: `2.10.1`
* Version of Node: `v8.16.0`
* Version of NPM: `6.4.1`
* OS:Ubuntu 18.04.2 LTS
* Architecture: x64

### Issue
▼概要
長時間稼働させているとEPGStationが番組情報を取得できなくなっていることがあります
またそれに伴い、以降の録画ができなくなります

▼症状
・EPGStation WebUI上で「ライブ/GR/BS/CS」のタブが表示されなくなります、「録画済み」タブはアクセスできます
・今回は試すのを忘れてしまいましたが、以前発生した際は「検索」で全件検索しても何も表示されなかったと思います
・直近の録画予約が失敗しています(epgstation-error.log, epgstation-out.logに
  チューナーがオープン出来なかったなどのログは記録されていません)
・epgstation-error.log, epgstation-out.logは最後に成功した録画以降のログは何も記録されていません
・Mirakurunへは別のWindows機からBonDriver_Mirakurun経由でアクセスできています
・ディスクの空き容量は十分に余裕があります
・この時点でEPGStation/Mirakurun共にonlineになっています
user@hostname:~$ sudo pm2 status
┌──────────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name         │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├──────────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ epgstation       │ 1  │ 1.4.9   │ fork │ 1460 │ online │ 0       │ 19D    │ 0%   │ 210.8 MB   │ root │ disabled │
│ mirakurun-server │ 2  │ 2.10.1  │ fork │ 3119 │ online │ 1       │ 2D     │ 0.3% │ 303.7 MB   │ root │ disabled │
└──────────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘

・EPGStationを再起動させようとすると、起動に失敗します
user@hostname:~$ sudo pm2 restart 1
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [1](ids: 1)
[PM2][ERROR] Process 1 not found
┌──────────────────┬────┬─────────┬──────┬──────┬─────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name         │ id │ version │ mode │ pid  │ status  │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├──────────────────┼────┼─────────┼──────┼──────┼─────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ epgstation       │ 1  │ 1.4.9   │ fork │ 1460 │ errored │ 1       │ 0      │ 0%   │ 0 B        │ root │ disabled │
│ mirakurun-server │ 2  │ 2.10.1  │ fork │ 3119 │ online  │ 1       │ 2D     │ 2.8% │ 303.6 MB   │ root │ disabled │
└──────────────────┴────┴─────────┴──────┴──────┴─────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘

・Mirakurunを再起動した後EPGStationを再起動しようとしても相変わらずerroredステータスのままです

user@hostname:~$ sudo pm2 restart 2
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [2](ids: 2)
[PM2] [mirakurun-server](2) v
┌──────────────────┬────┬─────────┬──────┬──────┬─────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name         │ id │ version │ mode │ pid  │ status  │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────────────┼────┼─────────┼──────┼──────┼─────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ epgstation       │ 1  │ 1.4.9   │ fork │ 1460 │ errored │ 1       │ 0      │ 0%  │ 0 B       │ root │ disabled │
│ mirakurun-server │ 2  │ 2.10.1  │ fork │ 5020 │ online  │ 2       │ 0s     │ 0%  │ 25.0 MB   │ root │ disabled │
└──────────────────┴────┴─────────┴──────┴──────┴─────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘

user@hostname:~$ sudo pm2 start 1
[PM2] Applying action restartProcessId on app [1](ids: 1)
[PM2][ERROR] Process 1 not found
┌──────────────────┬────┬─────────┬──────┬──────┬─────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name         │ id │ version │ mode │ pid  │ status  │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────────────┼────┼─────────┼──────┼──────┼─────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ epgstation       │ 1  │ 1.4.9   │ fork │ 1460 │ errored │ 1       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ mirakurun-server │ 2  │ 2.10.1  │ fork │ 5020 │ online  │ 2       │ 7s     │ 0%  │ 125.1 MB   │ root │ disabled │
└──────────────────┴────┴─────────┴──────┴──────┴─────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘

・OSごと再起動すると復旧します
user@hostname:~$ sudo pm2 status
┌──────────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬───────┬────────────┬──────┬──────────┐
│ App name         │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu   │ mem        │ user │ watching │
├──────────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼───────┼────────────┼──────┼──────────┤
│ epgstation       │ 1  │ 1.4.9   │ fork │ 1303 │ online │ 0       │ 15s    │ 3%    │ 49.0 MB    │ root │ disabled │
│ mirakurun-server │ 2  │ 2.10.1  │ fork │ 1310 │ online │ 0       │ 15s    │ 24.4% │ 126.3 MB   │ root │ disabled │
└──────────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴───────┴────────────┴──────┴──────────┘

・復旧後にepgstation-error.log, epgstation-out.logを確認してもerroredステータスに関するログ等は記録されていません

▼所感
・症状が発生するまでの期間は正確にはわかりませんが、概ね2週間～1ヶ月以内くらいだと思います
・録画成功しているタスクのうち、最後の数件は"recordedEndCommand"に登録されているシェルスクリプトが
  ログ上では"recording fin process is fin"しているにもかかわらず、実際の処理が実行された形跡が
  ありませんでした(ファイルのリネーム、ファイルの移動、TwitterへのPOSTなど)
・記憶にある限り1.4.6頃から当該症状は発生していたと思いますが、それまでに長時間稼働していたかなどの
  実績が曖昧な為、後天的エンバグや依存パッケージアップデートに伴う影響かどうかなどはわかりません
・取り急ぎEPGStation: 1.5.2にアップデートは実施しました

以上、よろしくお願いします。

**Comment by l3tnun** [comment]
まず、EPGStation のログは Readme に書いてあるとおり、[ここ](https://github.com/l3tnun/EPGStation#%E3%83%AD%E3%82%B0%E3%81%AE%E7%A2%BA%E8%AA%8D) に記録されていますので、そちらを確認しましょう

**Comment by tokohito** [comment]
返信ありがとうございます、確認してみました

***
/logs/Operator/access.log
/logs/Operator/stream.log
***
ログの記録はありません

***
/logs/Operator/system.log
***
問題発生被疑時間の前後でこれといったおかしなログはありませんでした。

>[2019-05-25T01:30:04.409] [INFO] system - save recorded history: この素晴らしい世界に祝福を!2 第7話「このふてぶてしい鈍らに招待を!」
>[2019-05-25T01:30:04.410] [INFO] system - recording fin process run: /home/username/git/EPGStation/bin/epgstation-recordedend.sh
>[2019-05-25T01:30:05.091] [INFO] system - start update rule: 207
>[2019-05-25T01:30:05.109] [INFO] system - update rule: 207 done
>[2019-05-25T01:30:13.731] [ERROR] system - create thumbnail failed: 3072
>[2019-05-25T01:31:50.780] [INFO] system - recording fin process is fin
>[2019-05-25T01:34:46.993] [INFO] system - preprec: 323912360827171 立花館To Lieあんぐる #7「流星群とバケツ」[再]
>[2019-05-25T01:35:03.531] [INFO] system - recording: 323912360827171 立花館To Lieあんぐる #7「流星群とバケツ」[再]
>[2019-05-25T01:35:03.532] [INFO] system - recording stream: /mnt/nfsclient/recorded/立花館To Lieあんぐる #7「流星群とバケツ」[再]-20190525[ＴＯＫＹＯ　ＭＸ１].ts
>[2019-05-25T01:35:03.532] [INFO] system - add recorded: 323912360827171 立花館To Lieあんぐる #7「流星群とバケツ」[再]
>[2019-05-25T01:35:04.011] [INFO] system - push thumbnail: 3073
>[2019-05-25T09:17:18.591] [INFO] system - ServicesDB created
>[2019-05-25T09:17:18.596] [INFO] system - ProgramsDB created
>[2019-05-25T09:17:18.752] [INFO] system - RulesDB created
>[2019-05-25T09:17:18.754] [INFO] system - RecordedDB created
>[2019-05-25T09:17:18.781] [INFO] system - EncodedDB created
>[2019-05-25T09:17:18.783] [INFO] system - RecordedHistoryDB created
>[2019-05-25T09:17:19.924] [INFO] system - start Updater pid: 2031
>[2019-05-25T09:17:20.479] [INFO] system - mirakurun -> services: 52
>[2019-05-25T09:17:20.715] [INFO] system - insert Services done
>[2019-05-25T09:17:21.095] [INFO] system - mirakurun -> programs: 11495
>[2019-05-25T09:17:22.368] [INFO] system - insert Programs done.

※朝07:00台にWebUIを確認して表題の症状になっていました
※09:17台にDB再作成されているのは、恐らくver.1.5.2にアップデートした時のものと思われます

***
/logs/Service/access.log
***

問題が発生している間も、アクセスのログ自体は記録されていました

>[2019-05-25T00:30:03.584] [INFO] access - ::ffff:172.16.0.193 - - "GET /api/streams/info HTTP/1.1" 200 2 "http://192.168.0.254:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
>[2019-05-25T07:42:50.613] [INFO] access - ::ffff:172.16.0.193 - - "GET / HTTP/1.1" 200 718 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"

***
/logs/Service/stream.log
***

問題発生中はストリームにアクセスできない事もあり、有意なログはありません

>[2019-05-23T21:13:54.354] [INFO] stream - start stream: 0
>[2019-05-23T21:14:09.444] [INFO] stream - stop stream: 0
>[2019-05-25T09:20:11.444] [INFO] stream - start stream: 0
>[2019-05-25T09:20:24.700] [INFO] stream - stop stream: 0

***
/logs/Service/system.log
***

OS再起動直後と思われるログが記録されていました

>[2019-05-05T11:06:17.030] [INFO] system - SocketIo Server has started.
>[2019-05-05T11:06:17.034] [INFO] system - listening on 8888
>[2019-05-25T09:17:31.223] [INFO] system - SocketIo Server has started.
>[2019-05-25T09:17:31.228] [INFO] system - listening on 8888

全体的にこれといった手掛かりは無い印象を受けましたが、何か分かりますでしょうか？
以上、よろしくお願いします。

**Comment by l3tnun** [comment]
> ・EPGStation WebUI上で「ライブ/GR/BS/CS」のタブが表示されなくなります、「録画済み」タブはアクセスできます
> ・今回は試すのを忘れてしまいましたが、以前発生した際は「検索」で全件検索しても何も表示されなかったと思います

これらの症状から 録画担当 の Operator 側のプロセスが何らかの理由で落ち、Web UI 側のプロセス (Service) が起動したままになっているのだと思います。
(Operator 側が落ちると有効な放送波を Service 側で検知できないため)
通常であれば pm2 が再起動を行うと思いますが、何らかの理由でそれが出来ていないようです。

pm2 の再設定等で改善するかもしれません。
あと、何もしないと pm2 側のログがたまり続けると思いますので、pm2-logrotate の設定も必要かもしれません。

> ログ上では"recording fin process is fin"しているにもかかわらず、実際の処理が実行された形跡が
ありませんでした(ファイルのリネーム、ファイルの移動、TwitterへのPOSTなど)

この挙動を見る限り OS のプロセス生成に何らかの問題が発生していそうなので、OSの設定の見直しが必要かもしれません。

**Comment by tokohito** [comment]
返信が遅くなり申し訳ありません。

>あと、何もしないと pm2 側のログがたまり続けると思いますので、pm2-logrotate の設定も必要かもしれません。

前回省いてしまっていましたが、pm2-logrotateは導入しています

> username@hostname:\~$ sudo pm2 status
> ┌──────────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
> │ App name         │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
> ├──────────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
> │ epgstation       │ 1  │ 1.5.2   │ fork │ 1407 │ online │ 0       │ 2D     │ 0.2% │ 132.3 MB   │ root │ disabled │
> │ mirakurun-server │ 2  │ 2.10.1  │ fork │ 1409 │ online │ 0       │ 2D     │ 8.3% │ 205.7 MB   │ root │ disabled │
> └──────────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘
> Module
> ┌───────────────┬────┬─────────┬──────┬────────┬─────────┬──────┬───────────┬──────┐
> │ Module        │ id │ version │ pid  │ status │ restart │ cpu  │ memory    │ user │
> ├───────────────┼────┼─────────┼──────┼────────┼─────────┼──────┼───────────┼──────┤
> │ pm2-logrotate │ 0  │ 2.6.0   │ 1397 │ online │ 0       │ 0.3% │ 88.3 MB   │ root │
> └───────────────┴────┴─────────┴──────┴────────┴─────────┴──────┴───────────┴──────┘
>  Use `pm2 show <id|name>` to get more details about an app

> username@hostname:\~$ sudo pm2 get pm2-logrotate
> == pm2-logrotate ==
> ┌────────────────┬─────────────────────┐
> │ key            │ value               │
> ├────────────────┼─────────────────────┤
> │ max_size       │ 10M                 │
> │ retain         │ 30                  │
> │ compress       │ false               │
> │ dateFormat     │ YYYY-MM-DD_HH-mm-ss │
> │ workerInterval │ 30                  │
> │ rotateInterval │ 0 0 * * *           │
> │ rotateModule   │ true                │
> └────────────────┴─────────────────────┘
> username@hostname:\~$ sudo cat /etc/logrotate.d/mirakurun
> /usr/local/var/log/mirakurun.stdout.log
> /usr/local/var/log/mirakurun.stderr.log
> {
>   daily
>   compress
>   rotate 31
>   missingok
>   notifempty
> }

pm2側のログも特に問題なくローテートされているように見えます。
> username@hostname:\~$ ls -alh /home/username/.pm2/logs/epgstation-*
> -rw-r--r-- 1 root root  142 May  1 00:00 /home/username/.pm2/logs/epgstation-error__2019-05-01_00-00-00.log
> -rw-r--r-- 1 root root    0 May  1 00:00 /home/username/.pm2/logs/epgstation-error.log
> -rw-r--r-- 1 root root 4.8M Apr 28 00:00 /home/username/.pm2/logs/epgstation-out__2019-04-28_00-00-00.log
> -rw-r--r-- 1 root root 4.9M Apr 29 00:00 /home/username/.pm2/logs/epgstation-out__2019-04-29_00-00-00.log
> -rw-r--r-- 1 root root 4.8M Apr 30 00:00 /home/username/.pm2/logs/epgstation-out__2019-04-30_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May  1 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-01_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  2 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-02_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  3 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-03_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  4 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-04_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May  5 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-05_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  6 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-06_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  7 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-07_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  8 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-08_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May  9 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-09_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 10 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-10_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 11 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-11_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 12 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-12_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 13 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-13_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 14 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-14_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 15 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-15_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 16 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-16_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 17 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-17_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 18 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-18_00-00-00.log
> -rw-r--r-- 1 root root 4.8M May 19 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-19_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 20 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-20_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 21 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-21_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 22 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-22_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 23 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-23_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 24 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-24_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 25 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-25_00-00-00.log
> -rw-r--r-- 1 root root 3.3M May 26 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-26_00-00-00.log
> -rw-r--r-- 1 root root 4.9M May 27 00:00 /home/username/.pm2/logs/epgstation-out__2019-05-27_00-00-00.log
> -rw-r--r-- 1 root root 4.3M May 27 20:52 /home/username/.pm2/logs/epgstation-out.log

>pm2 の再設定等で改善するかもしれません。

具体的に関係がありそうな設定個所はありますでしょうか？

以上、よろしくお願いします。

**Comment by l3tnun** [comment]
> 具体的に関係がありそうな設定個所はありますでしょうか？

私はpm2を使って運用していないのでこれと言って挙げられる点はないです。

ログに何も残っていないと正直お手上げです。

**Comment by tokohito** [comment]
わかりました。
EPGStationのlog4js設定をdebugレベルまで上げてしばらく様子を見てみたいと思います。

**Comment by l3tnun** [comment]
特に進展がないようなので閉じます
問題があれば再度オープンしてください

**Comment by tokohito** [comment]
既にdockerへ移行しており本ISSUEの発端となった環境は既に無いのですが、移行前の経過観察から推察するに、録画先ディレクトリにNFSサーバを指定していたのが問題だったと考えています。
EPGStationとNFSサーバは同一物理サーバ上のVMとホストの関係にあり、物理ネットワークを介しての書き込みはしていなかったのですが、
録画先ディレクトリをNFSから同一サーバ上の仮想HDDに変更したところ、ピタリとトラブルが止みました。
ログが残っていないので相変わらず真相は闇の中ですが、一応ご参考まで。
