### ISSUE TITLE
[要望] 外部コマンドでパイプを使いたい

### ISSUE THREAD

**Issue by masnagam** [l3tnun/EPGStation#273]
### 環境
* Version of EPGStation: `1.5.2`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.15.3`
* Version of NPM: `x6.4.1`
* OS: armbian (debian stretch) running as a Docker container
* Architecture: aarch64

### Change Request

`recordedEndCommand`を以下のように設定したところ，動作しませんでした．

```
  "recordedEndCommand": "/path/to/cmd1 | /path/to/cmd2",
```

`spawn`に`shell: true`を渡せば，`recordedEndCommand`をそのまま`spawn`に渡すことができ，パイプ（`|` ）が含まれていても動作します．

```js
// macOSで動作確認済み
const spawn = require('child_process').spawn;
const cmd = spawn('ls -1 | head -2', { shell: true });  // リダイレクトも動作します
cmd.stdout.on('data', (data) => console.log(data.toString()));
```

EPGStationとして仕様・セキュリティ上の問題がなければ，以下のモデルを修正しようと考えています．

* RecordedExternalProcessMode
* ProgramExternalProcessModel

他にも修正したほうがよいモデルがあるなど指摘がありましたらお願いします．

変更すべきでないと判断された場合には，PRは送りません．

本件とは別件ですが，`PATH`が正しく設定されていても，コマンドを絶対パスで指定しないと以下のエラーが発生します．

```
epgstation    | [2019-05-25T01:08:49.662] [ERROR] system - Error: CmdBinIsNotFound
epgstation    |     at Object.ProcessUtil.parseCmdStr (/opt/epgstation/dist/server/Util/ProcessUtil.js:55:19)
epgstation    |     at RecordedExternalProcessModel.<anonymous> (/opt/epgstation/dist/server/Model/Operator/RecordedExternalProcessModel.js:34:50)
epgstation    |     at Generator.next (<anonymous>)
epgstation    |     at /opt/epgstation/dist/server/Model/Operator/RecordedExternalProcessModel.js:7:71
epgstation    |     at new Promise (<anonymous>)
epgstation    |     at __awaiter (/opt/epgstation/dist/server/Model/Operator/RecordedExternalProcessModel.js:3:12)
epgstation    |     at push (/opt/epgstation/dist/server/Model/Operator/RecordedExternalProcessModel.js:30:35)
epgstation    |     at QueueProcessBaseModel.queue.add (/opt/epgstation/dist/server/Model/Operator/QueueProcessBaseModel.js:16:20)
epgstation    |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

これは仕様ということでしょうか？

ドキュメントでも絶対パスで記載されていますし，[コード](https://github.com/l3tnun/EPGStation/blob/master/src/server/Util/ProcessUtil.ts#L57)も意図的なものだと思っています．

提案している修正を行った場合，コマンド文字列に対して`ProcessUtil.parseCmdStr`を呼び出さなくなるので（`%NODE%`の置換のみどこかで行う），`PATH`が正しく設定されていればコマンド名だけで実行可能になります．

**Comment by l3tnun** [comment]
パイプでのコマンド実行は考慮していませんでした。
生成したプロセスを殺す必要が出てきた場合、
(現状そのようなことはありませんが)
親の shell プロセスは殺せると思いますが、その下で実行される子プロセスが殺せなくなると思いますのであまり好ましくないかなと思います。
（コードを書いて検証したわけではないでの間違っていたらすいません）

> 本件とは別件ですが，環境変数PATHが正しく設定されていても，コマンドを絶対パスで指定しないと以下のエラーが発生します．
> これは仕様ということでしょうか？

仕様です。PATHを通し忘れによるエラーを避けるためです。
（上級者には不便な仕様だと思いますが）

**Comment by masnagam** [comment]
回答ありがとうございます．

> 親の shell プロセスは殺せると思いますが、その下で実行される子プロセスが殺せなくなる

確認してみます．

> 仕様です。PATHを通し忘れによるエラーを避けるためです。

了解です．

**Comment by masnagam** [comment]
試す必要なかったですね．[ドキュメント](https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_subprocess_kill_signal)に書いてありました．

> On Linux, child processes of child processes will not be terminated when attempting to kill their parent. This is likely to happen when running a new process in a shell or with the use of the shell option of ChildProcess

**Comment by l3tnun** [comment]
なるほど、そのような仕様であれば EPGStation としては好ましくないため、外部コマンドでのパイプ対応を見送ろうと思います。

**Comment by masnagam** [comment]
了解です．

自分の環境では必要なので，ローカルで改造して使うことにします．
必要になったらPRを送りますので連絡をください．

**Comment by l3tnun** [comment]
わかりました。issue は閉じますね。

**Comment by masnagam** [comment]
以下，記録のためのコメントです．

`recordedEndCommand`に指定したスクリプト内でサブプロセスを作成し，これらのstdinとstdoutを繋げばいいだけだと気が付きました．

この方法ならスクリプトがkillされたとしても，スクリプト内で適切に処理すればサブプロセスをkillできます．
