### ISSUE TITLE
[質問] 外部コマンド実行時の環境変数にPATHが含まれていない

### ISSUE THREAD

**Issue by masnagam** [l3tnun/EPGStation#274]
### 環境
* Version of EPGStation: `1.5.2`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.15.3`
* Version of NPM: `x6.4.1`
* OS: armbian (debian stretch) running as a Docker container
* Architecture: aarch64

### Issue

仕様なのかどうか回答をお願いします．

`PATH`が含まれていないため，以下のようなスクリプトが動作しません．

```json
  "recordedEndCommand": "/bin/sh script.sh",
```

```sh
# script.sh
nodejs-script arg
```

```js
#!/usr/bin/env node

// nodejs-script
```

Node.jsスクリプトで現象を確認していますが，他のスクリプトファイルでも同じ問題が発生する可能性があると思われます．

仕様ということでしたら，混乱を避けるためドキュメントに記載したほうがよいと思います．

### 再現コンテンツ

`PATH`を渡さないと問題が発生することは，以下のような簡単なコードで確認できます．macOS上で確認済みです．

```sh
$ node spawn.js  # success.txtが作成されない
```

test:
```js
#!/usr/bin/env node

const fs = require('fs');
fs.writeFileSync('success.txt', '');
```

spawn.js:
```js
const spawn = require('child_process').spawn;
spawn('./test', {
  env: {}
});
```

### 解決方法１

`spawn`の`env`に`process.env['PATH']`を渡すと，Shebangが機能し，`test`が正常に動作します．

```js
const child = spawn(cmds.bin, cmds.args, {
  stdio: 'ignore',
  env: {
    PATH: process.env['PATH'],  // これなら動く
    ...
  }
});
```

この方法の採用はEPGStationを修正することを意味します．

### 解決方法２

外部コマンドとして指定したスクリプト内で`PATH`を定義することでも解決できます．

```shell
export PATH="/usr/local/bin:/usr/bin:/bin"

# 別のコマンドやスクリプトを呼び出す
```

### 解決方法３

外部コマンド内で絶対パスでコマンド・別スクリプトを呼び出す方法でも解決できる場合があります．

```shell
/path/to/command
```

この方法は，呼び出し先でさらに別のスクリプトファイルを実行しているような場合は問題を解決できない場合があります．

**Comment by l3tnun** [comment]
```PATH``` が含まれないのは仕様です。
いろいろと不便だと思いますので、EPGStation 側を修正するのが良いかなと思います。
今から修正しますので、終わったら確認お願いします。

**Comment by l3tnun** [comment]
feature-274 ブランチにて修正をしたので、確認してみてください。
問題なければ master へマージします。

**Comment by masnagam** [comment]
対応ありがとうございます．

feature-274 ブランチの修正が機能することを確認しました．確認は`recordedEndCommand`でのみ行いました．

互換性が損なわれる可能性があったため， f5529cea1060375c3f8199d1fd1f9e1f8c737e20 の該当箇所にコメントを付けました．最終判断はお任せします．

**Comment by l3tnun** [comment]
ご指摘の点を修正して master へ反映させました。
問題があれば再度 open してください。
