### ISSUE TITLE
BS/CS の単局表示時に番組詳細が表示できない

### ISSUE THREAD

**Issue by ykym** [l3tnun/EPGStation#275]
### 環境
* Version of EPGStation: `1.5.2`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.15.3`
* Version of NPM: `6.4.1`
* OS: Debian GNU/Linux 9.7
* Architecture: x64

* クライアント macOS Mojave 10.14.5 / Chrome 74.0.3729.169

### Issue
1.5.2 へアップデートしたところ、BS/CS の単局表示時に番組をクリックしても番組詳細が表示されなくなりました。
1.5.1 へ戻すと正常に表示されます。
GR の単局表示時の番組詳細は 1.5.2 でも問題なく表示されるようです。

**Comment by l3tnun** [comment]
こちらでも確認出来ました。
修正します。

**Comment by l3tnun** [comment]
修正を master へ反映させました。
問題があれば再度 open してください。

**Comment by ykym** [comment]
改善確認できました。ご対応ありがとうございます。
