### ISSUE TITLE
最新のkodi(18.3)にSTREAMタブからkodi配信ができない

### ISSUE THREAD

**Issue by takeru** [l3tnun/EPGStation#279]
### 環境
* Version of EPGStation: `master (docker-mirakurun-epgstationの中のepgstation)`
* Version of Mirakurun: `2.11.0` 別ホスト
* Version of Node: `v10.16.0`
* Version of NPM: `6.9.0`
* OS: Linux 4b721115c624 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux
* Architecture: x64

### Issue
最新のkodi(18.3)にSTREAMタブからkodi配信ができないようです。
あたらしい18.3はダメでしたが、ひとつ古い17.6にするとOKでした。

Android TVのkodiにkodi配信ができなかったので、調べました。
mac版のkodi(18.3)を試したがダメ、mac版のkodi(17.6)でOK。

AndroidTVのアプリストアからインストールできるものは新しいものだけなので、
自動更新をOFFにしてadbで17.6のapkをインストールしたところOKでした。

**Comment by l3tnun** [comment]
手元の環境で試していないので推測ですが、おそらくHarekaze/pvr.chinachu#30 と同じ現象だと思います。
http2 に対応していない事が原因と考えられるので、http2 の対応を検討します。

お急ぎの場合は tinyproxy 等で自力で対応してください。

**Comment by l3tnun** [comment]
最新の master にて対応しました。

試行錯誤の結果 Socket.IO 通信用のポートを追加する形になりました。
