### ISSUE TITLE
npm start時にエラー

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#280]
### 環境
* Version of EPGStation: `1.5.4`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v8.11.3`
* Version of NPM: `6.10.2`
* OS:Windows 10
* Architecture: x64

### Issue
EPGStation1.5.4に上げた後EPGStationサービス起動時にこけるようになりました。
npm start時には以下の表示でエラーとなります（ログファイル添付いたします）。

どうやら日付を取得する際に"1"とのみ返ってきた結果日付としてパースできない、というエラーのようです。

環境起因のものかもしれませんが……

[2019-07-29T06_30_51_625Z-debug.log]

(https://github.com/l3tnun/EPGStation/files/3440534/2019-07-29T06_30_51_625Z-debug.log)

PS C:\EPGStation> npm start

> EPGStation@1.5.4 start C:\EPGStation
> node dist/server/index.js

[2019-07-29T15:21:50.771] [INFO] system - upgrade 8 => 9
C:\EPGStation\node_modules\date-format\lib\index.js:168
  throw new Error(
  ^

Error: String '1' could not be parsed as '-yyyy-MM-dd'
    at extractDateParts (C:\EPGStation\node_modules\date-format\lib\index.js:168:9)
    at Function.parse (C:\EPGStation\node_modules\date-format\lib\index.js:178:10)
    at _.sortBy.n (C:\EPGStation\node_modules\streamroller\lib\RollingFileWriteStream.js:203:24)
    at C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:3727:18
    at arrayMap (C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:639:23)
    at C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:3726:24
    at C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:3543:27
    at C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:4881:15
    at baseMap (C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:3542:7)
    at baseOrderBy (C:\EPGStation\node_modules\streamroller\node_modules\lodash\lodash.js:3725:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EPGStation@1.5.4 start: `node dist/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EPGStation@1.5.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myRecServer\AppData\Roaming\npm-cache\_logs\2019-07-29T06_21_50_787Z-debug.log

**Comment by ohmsa** [comment]
デバッグのため、extractDateParts函数に受け取った値を表示する行を追加してみました。
追加個所は以下となります。

function extractDateParts(pattern, str, missingValuesDate) {
  console.log(pattern);
  console.log(str);
  console.log(missingValuesDate);
  var matchers = [
    {

この状態で起動すると以下のように、受け取った値がエラーの前に出てきました。

[2019-07-29T16:03:47.666] [INFO] system - upgrade 8 => 9
-yyyy-MM-dd
-2019-01-29
undefined
-yyyy-MM-dd
-2019-02-02
undefined
-yyyy-MM-dd
-2019-02-05
undefined
-yyyy-MM-dd
-2019-02-07
undefined
-yyyy-MM-dd
-2019-02-09
undefined
-yyyy-MM-dd
-2019-02-10
undefined
-yyyy-MM-dd
-2019-02-13
undefined
-yyyy-MM-dd
-2019-02-14
undefined
-yyyy-MM-dd
-2019-02-17
undefined
-yyyy-MM-dd
-2019-02-20
undefined
-yyyy-MM-dd
-2019-02-22
undefined
-yyyy-MM-dd
-2019-02-23
undefined
-yyyy-MM-dd
-2019-02-26
undefined
-yyyy-MM-dd
-2019-02-28
undefined
-yyyy-MM-dd
-2019-03-03
undefined
-yyyy-MM-dd
-2019-03-04
undefined
-yyyy-MM-dd
-2019-03-18
undefined
-yyyy-MM-dd
-2019-03-25
undefined
-yyyy-MM-dd
-2019-03-26
undefined
-yyyy-MM-dd
-2019-03-27
undefined
-yyyy-MM-dd
-2019-04-05
undefined
-yyyy-MM-dd
-2019-04-10
undefined
-yyyy-MM-dd
-2019-04-11
undefined
-yyyy-MM-dd
-2019-04-17
undefined
-yyyy-MM-dd
-2019-04-18
undefined
-yyyy-MM-dd
-2019-04-20
undefined
-yyyy-MM-dd
-2019-04-23
undefined
-yyyy-MM-dd
-2019-04-25
undefined
-yyyy-MM-dd
-2019-05-01
undefined
-yyyy-MM-dd
-2019-05-02
undefined
-yyyy-MM-dd
-2019-05-04
undefined
-yyyy-MM-dd
-2019-05-05
undefined
-yyyy-MM-dd
-2019-05-07
undefined
-yyyy-MM-dd
-2019-05-23
undefined
-yyyy-MM-dd
-2019-06-10
undefined
-yyyy-MM-dd
-2019-06-11
undefined
-yyyy-MM-dd
-2019-06-12
undefined
-yyyy-MM-dd
-2019-06-13
undefined
-yyyy-MM-dd
-2019-06-19
undefined
-yyyy-MM-dd
-2019-06-23
undefined
-yyyy-MM-dd
-2019-06-27
undefined
-yyyy-MM-dd
-2019-06-29
undefined
-yyyy-MM-dd
-2019-07-19
undefined
-yyyy-MM-dd
-2019-07-26
undefined
-yyyy-MM-dd
1
undefined
C:\EPGStation\node_modules\date-format\lib\index.js:171
  throw new Error(
  ^

ここで、受け取ったstrが"-2019-08-02"となるべきところが"1"となっていることがわかりました。
strを生成しているところを追ってみます。

**Comment by ohmsa** [comment]
つづいてbaseOrderByがiteratee(value)を返しているようなのでvalueの値を出力してみました。箇所は以下となります。

function baseOrderBy(collection, iteratees, orders) {
      var index = -1;
      iteratees = arrayMap(iteratees.length ? iteratees : [identity], baseUnary(getIteratee()));

      var result = baseMap(collection, function(value, key, collection) {
        var criteria = arrayMap(iteratees, function(iteratee) {
          console.log(value);
          return iteratee(value);
        });


この状態でnpm startすると
{ fileName: 'Operatorsystem.log.-2019-07-19.1',
  index: 1,
  date: '-2019-07-19',
  isCompressed: false }
{ fileName: 'Operatorsystem.log.-2019-07-26.1',
  index: 1,
  date: '-2019-07-26',
  isCompressed: false }
{ fileName: 'Operatorsystem.log.1',
  index: 0,
  date: '1',
  isCompressed: false }

valueの値が化けています。この変数valueをセットしているところを追っていますが、数が多くなかなか追えておりません。

**Comment by ohmsa** [comment]
（プログラミングは勉強中なのでデバッグとしては的外れかもしれませんが……）

**Comment by advancedbear** [comment]
>どうやら日付を取得する際に"1"とのみ返ってきた結果日付としてパースできない、というエラーのようです。

log4js側の問題だとは思うのですが、ログ出力設定でdateFile設定している場合に指定している日時フォーマットに一致しないファイルが存在するとそのファイルが原因でlog4jsがコケるようです。
logsフォルダ内にある、~~~~.1のようなファイルを削除ないしは正しいDateフォーマットに名前変更すれば直ると思いますが。

**Comment by ohmsa** [comment]
>>advancedbear様

それでした。いつもありがとうございます。
