### ISSUE TITLE
[要望] 録画ファイル(.ts/mp4)が削除されたら録画済み一覧も削除

### ISSUE THREAD

**Issue by yoshioki** [l3tnun/EPGStation#281]
EPGStationをCentOS7にインストールし、録画ファイル(.ts/mp4)をSambaでファイル共有をして OSMC(Kodi)で再生をするという環境で利用しています。
Kodiでは、テレビリモコンを使って再生の操作ができる他に、録画ファイルの削除も行うことができます。
この機能を利用して、視聴し終わったファイルは、テレビリモコンから削除したいと考えています。

録画済みの一覧を表示するタイミングで構いませんので、録画ファイルが削除されて存在しなくなったものは、録画済みの一覧からも自動的に削除される機能を実装しいていただけませんでしょうか。

よろしくお願いいたします。
...

**Comment by l3tnun** [comment]
[plugin.video.epgstation](https://github.com/l3tnun/plugin.video.epgstation) にて既に実装されています
また、録画ファイルがなくなったものは EPGStation の録画済みページのメニュー -> クリーンアップ で手動で削除できます

EPGStation の api 叩く以外の方法で削除された録画ファイルの検知機能を実装する予定はありません

**Comment by simplelife0530** [comment]
> また、録画ファイルがなくなったものは EPGStation の録画済みページのメニュー -> クリーンアップ で手動で削除できます

クリーンアップは、便利な機能ですね。録画済みの画面が整理できて、すっきりします。
一つ予想外の事象として、ファイル名を変更したファイルも削除されてしまいました。
データベースの中身をクリーンにするだけでなく、ファイルの削除をすることもあるようです。

**Comment by l3tnun** [comment]
> 一つ予想外の事象として、ファイル名を変更したファイルも削除されてしまいました。

DBに記録されているファイルとディレクトリ以外のものは削除される仕様となっています

**Comment by simplelife0530** [comment]
> DBに記録されているファイルとディレクトリ以外のものは削除される仕様となっています

DBの情報の削除に加えて、登録外の実体ファイルを削除する時は、ゴミ箱に入るとか、「登録外のファイルを削除しますか？」と聞いてくれると、いくらか親切かな、とは思います。

**Comment by l3tnun** [comment]
クリーンアップ実行時に

録画ディレクトリにある EPGStation の管理外ファイル、ディレクトリを削除します。実行しますか?

と表示が出るのでそれで十分かと思います

ゴミ箱機能は実装が複雑になるので考えていません

**Comment by simplelife0530** [comment]
> クリーンアップ実行時に
> 録画ディレクトリにある EPGStation の管理外ファイル、ディレクトリを削除します。実行しますか?
> と表示が出るのでそれで十分かと思います

そうなんですか。メッセージをちゃんと読んでいませんでした。残念。
1000ファイルほど消してしまいましたが、自業自得です。
