### ISSUE TITLE
EPGStation 1.5.5にて、HLS再生開始に時間がかかる

### ISSUE THREAD

**Issue by shirow-github** [l3tnun/EPGStation#283]
### 環境
* Version of EPGStation: `1.5.5`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v8.16.1`
* Version of NPM: `6.4.1`
* OS: Vine Linux Seed
* Architecture: x86

### Issue
自宅の無線LAN環境にて、スマホ(Xperia XZ Premium)の5Ghz 866Mbpsで接続して
地デジのライブ放送を視聴しています。

以前のバージョン 1.5.4では、HLS 720x480（または1280x720）を選択して
待つこと約20秒程度でライブ放送が視聴出来ていました。

今回1.5.5へ変更したところ、待つこと約2分30秒程度してライブ放送が視聴出来ました。

試しに、スマホのChrome 76.0.3809.111のキャッシュを消しても改善せず…。

あと、ffmpegを4.2にしていたので、4.1.4に戻しても変わらず…。

しょうがないので、git reset --hard 81a779dをして1.5.4に戻したところ改善しました。

また、PCからのHLSのライブ視聴の場合も同様な状況です。

特に急ぎでは無いですので、よろしくお願いします。

**Comment by l3tnun** [comment]
socket.io の接続が正しく出来ていないことが問題でした

最新の master にて修正しましたので閉じます
