### ISSUE TITLE
Socket.ioで使用するポートについて

### ISSUE THREAD

**Issue by hiyuki2578** [l3tnun/EPGStation#284]
### 環境
* Version of EPGStation: `1.5.7`
* Version of Mirakurun: `2.10.0`
* Version of Node: `v10.16.3`
* Version of NPM: `6.11.2`
* OS: ArchLinux
* Architecture: x64

### Issue
リバースプロキシからのHTTPS使用時に、ポート指定せずhttps://example.net などといったようなURLで接続すると、Socket.IOの接続でポート81番が使われてしまうのですが、ポートをconfigなどから指定する方法などはないのでしょうか？

**Comment by l3tnun** [comment]
> ポートをconfigなどから指定する方法などはないのでしょうか？

現状ないですね
リバースプロキシを挟んだ場合どのポートが使用されるのか EPGStation 側から検知出来ないので config に設定があっても意味がないかと思います

https 時に 81 番ポートが使用されてしまうのは、web クライアント側のバグですね（というか https 使用時の想定不足です）
来週にでも修正します

**Comment by l3tnun** [comment]
修正しましたので閉じます
