### ISSUE TITLE
 除外キーワードの正規表現が効かないのは設定不備のせい？

### ISSUE THREAD

**Issue by Higomon** [l3tnun/EPGStation#287]
### 環境
* Version of EPGStation: `1.5.8`
* Version of Mirakurun: `2.11.0`
* Version of Node: `10.15.2`
* Version of NPM: `5.8.0`
* OS: Raspbian Buster Lite July 2019
* Kernel: 4.19.66-v71+
* Raspberry Pi 4B (RPi4) 

### Issue
先日からお世話になっております。お陰様で順調に録画まで至っております。

さて、検索 and/or ルール作成時（添付画像）に
正規表現で特定の番組を除外しようとすると私の環境ではうまく動作しません。

Issue #150 "除外キーワードの正規表現が効かない" on 1 Sep 2018
を参照すると、既に解決済みとのことですが、
うまく動作しないのは、私の設定不備のせいでしょうか？
それとも、上記のような特殊な環境のせいでしょうか？

お知恵を拝借したいです。
どうぞよろしくお願い致します。

---
#### 検索画面
（例）入力ワード
- キーワード: 松本人志
- 除外キーワード: なう|ガキ
- 結果: 
理想 ===
  1 ダウンタウンDX
  2 ワイドナショー
実際 ===
  1 ダウンタウンDX
  2 ダウンタウンなう
  3 ワイドナショー
  4 ダウンタウンのガキの使いやあらへんで!

<img width="592" alt="スクリーンショット 2019-09-16 16 49 04" src="https://user-images.githubusercontent.com/30855384/64941712-542c4600-d8a2-11e9-8225-4bd1de8be481.png">

---
### 参考にしたRaspbian Buster Lite へのインストール手順
- 手順1) 「PX-W3U4 driver → B25 → recpt1構築」は以下を参考
https://qiita.com/tatsuya_info/items/3583182ac104a4958eac

- 手順2) 「Mirakurun構築 → EPGStation構築」は以下を参考
https://qiita.com/unsigned-tamanegi/items/c87b1230f8633b05511b

上記サイト EPGStation構築より、以下のように修正
$ sudo npm install --unsafe-perm=true --allow-root
   --> $ npm install
$ sudo npm run build
   --> $ npm run build

**Comment by l3tnun** [comment]
Readme にありますが [SQLite3 使用時の正規表現での検索の有効化について](https://github.com/l3tnun/EPGStation/blob/master/doc/sqlite3-regexp.md) は実行しましたか？

**Comment by Higomon** [comment]
早速のご返答ありがとうございます。

初心者質問で大変失礼しました。
力不足で理解できず、docを読み飛ばしておりました。

下記サイトを参考にやってみましたが、
config.json parse errorで未だうまく行っていません。
只今、格闘中ですが、取り急ぎのご報告です。

---
### 実施内容
参考URL
https://note.mu/ad3sq/n/ne1ef9ec1a258

#### SQLite3の導入
$ sudo apt install -y sqlite3

#### SQLite3使用時の正規表現での検索の有効化
$ wget https://www.sqlite.org/2019/sqlite-amalgamation-3270200.zip
$ wget https://www.sqlite.org/2019/sqlite-src-3270200.zip 
$ unzip sqlite-amalgamation-3270200.zip
$ unzip sqlite-src-3270200.zip

#### regexp.cのコピー
$ cp sqlite-src-3270200/ext/misc/regexp.c sqlite-amalgamation-3270200

#### ビルドしてファイルのコピー
$ cd sqlite-amalgamation-3270200
$ gcc -g -fPIC -shared regexp.c -o regexp.so
$ sudo cp regexp.so /home/pi/EPGStation/data/

#### 正規表現での検索の有効化
<img width="382" alt="スクリーンショット 2019-09-16 17 29 08" src="https://user-images.githubusercontent.com/30855384/64943980-1e8a5b80-d8a8-11e9-90cc-6ab7722203f5.png">
