### ISSUE TITLE
ドロップチェック有効時のログの詳細表示ができない

### ISSUE THREAD

**Issue by ykym** [l3tnun/EPGStation#288]
### 環境
* Version of EPGStation: `1.5.9`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.16.3`
* Version of NPM: `6.9.0`
* OS: Debian GNU/Linux 10 (buster)
* Architecture: x64

### Issue
1.5.9 へアップデートしたところ、ドロップチェック有効時のログの詳細表示が
「ログファイルがありません」となってしまいます。
.log ファイル自体は出力されており、中身も正常に記録されているようです。
1.5.8 へ戻すと正常に表示されます。

**Comment by l3tnun** [comment]
症状再現できました
修正します

**Comment by l3tnun** [comment]
修正完了しました
Mitrhil.js の仕様変更が原因でした
