### ISSUE TITLE
エンコードの画素数に関して

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#289]
### 環境
* Version of EPGStation: 7363a5d
* Version of Mirakurun: `2.11.x`
* Version of Node: `v10.16.3`
* Version of NPM: `6.9.0`
* OS:5.3.1-arch1-1-ARCH
* Architecture: x64

### Issue
issueというか単純な疑問なのですが、デジタル放送の画素数は1440x1080(BS HDなどを除く)が大体の最大画素数だと思うのですが、エンコードのデフォルトのenc.jsが1280x720が最大なのは何故でしょうか。

**Comment by l3tnun** [comment]
特に理由はありません。
CPU負荷と画質のバランスがそこそこ取れた設定として enc.js に書いています。

**Comment by 5ym** [comment]
早急な回答ありがとうございます。
納得いたしました。
