### ISSUE TITLE
再生速度の変更について

### ISSUE THREAD

**Issue by ykym** [l3tnun/EPGStation#291]
### 環境
* Version of EPGStation: `1.6.0`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.16.3`
* Version of NPM: `6.9.0`
* OS: Debian GNU/Linux 10 (buster)
* Architecture: x64

* Client: macOS Catalina 10.15 + Google Chrome 77.0.3865.90

### Issue
再生速度の変更がうまく動いていないようです。
x0.9 以下を選択すると再生が停止し、x1.0〜x1.9 を選択すると x1.0 になり、x2.0 を選択すると x2.0 で再生されるようです。
1.5.8 まで Version を戻すと選択した速度での再生が可能でした。

**Comment by l3tnun** [comment]
症状こちらでも再現しました。
土日に修正します。

**Comment by l3tnun** [comment]
最新の master にて修正完了しましたので、閉じます。
