### ISSUE TITLE
HLSの再生が始まらない

### ISSUE THREAD

**Issue by whitesause28** [l3tnun/EPGStation#292]
### 環境
* Version of EPGStation: `1.6.0`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.16.3`
* Version of NPM: `6.9.0`
* OS: Ubuntu 19.04
* Architecture: x64

### Issue
EPGStationをサブディレクトリ付きでリバースプロキシ経由で運用しています。バージョンを1.5.4から1.6.0に上げたところ、HLSの再生が開始されなくなりました。
新たにsocket.io用のポートもプロキシするよう設定は行いましたが、socket.ioへのリクエストのみがサブディレクトリなしでのアクセスになって404になります。（他のリクエストについては問題ありません）

**Comment by l3tnun** [comment]
リバースプロキシを通した確認はしていませんが、socket.io 接続時にサブディレクトリの設定が正しく反映されていないことを確認しました。
修正するのでお待ち下さい。

**Comment by l3tnun** [comment]
@whitesause28 fix-292 ブランチで修正しましたので確認お願いします。問題なければ master へ反映させます。

**Comment by whitesause28** [comment]
fix-292にて動作確認しました問題ありません。対応ありがとうございます。

**Comment by l3tnun** [comment]
確認ありがとうございます。
#291 の修正が完了次第 master へ反映させます。

**Comment by l3tnun** [comment]
master に反映したので閉じます。
