### ISSUE TITLE
npm start での config.json parse error について

### ISSUE THREAD

**Issue by polo1kani** [l3tnun/EPGStation#295]
### 環境
* Version of EPGStation: `1.6.1`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v8.9.4`
* Version of NPM: `5.6.0`
* OS:windows8.1 HOME
* Architecture: x64
* powershellは管理者権限
* config.jsonはマニュアル通り、最低限の編集済

### Issue
npm start で config.json parse error がでて実行出来ません。
powershellは以下の通りです。

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> cd C:\EPGStation
PS C:\EPGStation> npm start

> EPGStation@1.6.1 start C:\EPGStation
> node dist/server/index.js

[2019-11-02T17:10:58.050] [FATAL] system - config.json parse error
PS C:\EPGStation>

config.jsonの内容です。
[config.txt](https://github.com/l3tnun/EPGStation/files/3800269/config.txt)

**Comment by l3tnun** [comment]
考えられそうなのは以下くらいですかね
* エラーの通りconfig.jsonが正しく書けていない
* ファイルが何らかの理由で読めない
* そもそもファイルが存在しない

**Comment by l3tnun** [comment]
特に進展もないようですので閉じます
