### ISSUE TITLE
【要望】毎週録画機能の追加

### ISSUE THREAD

**Issue by Nisetai** [l3tnun/EPGStation#296]
録画をよくし忘れてしまうので…

予約時に毎週録画という項目を追加して「選択段階の時間、選択した番組の番組時間」を保存し
それにあった番組があれば勝手に録画してくれる、という機能があれば嬉しいのですがいかがでしょうか？
番組時間を参照すれば特番などで潰れてしまっても誤って録画することはないと思いますが、
難しいようでしたら単純に毎回同じ時間録画でも構いません。
またEPG番組の取得が私の環境では弱く次の日の番組が空欄の場合があるので、もし実装していただけるのであれば毎日自動録画の判定を行ってくれると嬉しいです。

**Comment by l3tnun** [comment]
v2 にて実装予定となっています。
現行のv1に機能追加する予定はありませんので、当面は別の予約ソフトで凌いでください。

**Comment by l3tnun** [comment]
EPGStationに毎週予約という概念はありません。

> 予約時に毎週録画という項目を追加して「選択段階の時間、選択した番組の番組時間」を保存し
それにあった番組があれば勝手に録画してくれる、という機能があれば嬉しいのですがいかがでしょうか？

 ルールの対象時刻の指定でほぼ可能かと思います。

> 番組時間を参照すれば特番などで潰れてしまっても誤って録画することはないと思いますが、

キーワード等で条件を絞らないと EPGStation 側で判別不能です。

> またEPG番組の取得が私の環境では弱く次の日の番組が空欄の場合があるので

そもそもそのような環境を想定していませんので環境を改善しましょう。

**Comment by Nisetai** [comment]
v2にて対処予定なことと、対象時刻の指定で可能との話なのでクローズいたします。
ご検討ありがとうございました。
