### ISSUE TITLE
番組情報が一部歯抜け状態になります。

### ISSUE THREAD

**Issue by masa09214** [l3tnun/EPGStation#297]
### 環境
* Version of EPGStation: `1.6.1`
* Version of Mirakurun: `2.12.0`
* Version of Node: `v10.17.0`
* Version of NPM: `6.11.3`
* OS:CentOS 7.7.1908
* Architecture: x64
### Issue
番組情報の一部が歯抜け状態になり困っています。
深夜帯ではなく18時頃の番組情報が表示されず空白になっています。
DBをmysqlにすると起動してすぐerroredになってしまいEPGStationにアクセスできなくなるので、sqlite3で使っています。
どのようなことが考えられますでしょうか？
よろしくお願いいたします。

**Comment by l3tnun** [comment]
> 深夜帯ではなく18時頃の番組情報が表示されず空白になっています。

Mirakurun 側の番組情報をクリアして再度取得させれば治ると思います。
多分[ここら辺](https://qiita.com/masnagam/items/e71a234f2e66b1246a37#eit%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%A8sub-table)の仕様が原因かと思いますので、Mirakurun 側のかと思います。

> DBをmysqlにすると起動してすぐerroredになってしまいEPGStationにアクセスできなくなるので、

MySQL の設定、ログ等がないので何もわかりません。

**Comment by l3tnun** [comment]
@masa09214 Mirakurun@2.13.0 にて修正が入ったので、それで様子を見てください
