### ISSUE TITLE
[要望]モバイル端末でもプレイリストを表示してほしい

### ISSUE THREAD

**Issue by hmy2001** [l3tnun/EPGStation#298]
現在pc用サイトを表示してプレイリストのurlをコピーし、
vlc mobileで視聴しています。

この流れをプレイリストをタッチするだけで
vlc mobileに遷移できるようにしていただけますか？

**Comment by l3tnun** [comment]
ios or android なら config.json で録画再生時のアプリを変更できますが、それで駄目のでしょうか?

**Comment by hmy2001** [comment]
デフォルト値だったのでvlcの設定に直しました
すみませんでした
