### ISSUE TITLE
Kodiから接続ができない。

### ISSUE THREAD

**Issue by Rihy** [l3tnun/EPGStation#299]
### 環境
* Version of EPGStation: `1.5.9`
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.13.0`
* Version of NPM: `6.4.1`
* OS:Windows Server 2019
* Architecture: x64

### Issue
KodiのIPTV Simple Clientを使用しライブTVを視聴することができません。

18.1 RC-1までは動くため、https://github.com/l3tnun/EPGStation/issues/279 https://github.com/Harekaze/pvr.chinachu/issues/30 
このあたりの原因と一緒のような気がします。

Tinyproxyを使用して回避しようとしましたが、うまく動きませんでした。

**Comment by l3tnun** [comment]
その問題は #279 で解決済みのはずです。
kodi のバージョンはなんでしょうか?

**Comment by Rihy** [comment]
18.1以降全てです。
書き忘れましたがパソコンでは正常に動き、Android版Kodiだと繋がらなくなります。

Kodiのgithubにもissueを書きましたが、お手上げ状態です。

**Comment by l3tnun** [comment]
xbmc/xbmc#16730 読みました。
これはお手上げです。
nginx 等でリバースプロキシを挟んで Kodi と接続すれば解決するかもしれません。
(Tinyproxy がうまく行かなかったようなので望み薄ですが)

**Comment by Rihy** [comment]
こちらの設定が悪かったようです。
nginxでは、チャンネルが表示されました。
ですが、ひとつひとつのチャンネルがnginx通す前のURLになってしまい再生はできませんでした。

**Comment by l3tnun** [comment]
それはおそらくnginxの設定が間違っています。
Hostヘッダを書き換えないように設定してみてください。

**Comment by Rihy** [comment]
調べてみましたが、わかりませんでした。
EPGStationと直接関係ない話ですがもし宜しければ設定方法を教えてほしいです。

**Comment by l3tnun** [comment]
こんな感じでできるかと思います。

https://www.xmisao.com/2013/10/17/nginx-proxy-host-header.html

私もnginxについて大して詳しくないので、これ以上は頑張って調べるか、EPGStation 側のソースを修正してください。
