### ISSUE TITLE
subDirectory + リバプロ環境で、iOSでの録画済み再生が出来ない

### ISSUE THREAD

**Issue by masahiko-imai** [l3tnun/EPGStation#301]
### 環境
* Version of EPGStation: `1.6.1`
* Version of Mirakurun: `2.13.0`
* Version of Node: `10.18.0`
* Version of NPM: `6.13.4`
* OS: Ubuntu 18.04.3 LTS
* Architecture: x64
* Infuse Pro 6.2.5(2888)

### Issue
お世話になります。
現象としては主題の通りです。
config.jsonのrecordedViewrの部分で、httpが決め打ちにされているためかと思い、httpsに一時的に変更しましたが、infuseでエラーが発生しました。
外部環境のPCからブラウザ（Chrome）でアクセスすると、問題なく再生できることが確認できているため、リバプロの設定やその他に問題はないと考えます。

お手数ですが、ご確認＆ご対応のほどよろしくお願いします。

**Comment by l3tnun** [comment]
config で ```"ios" ://x-callback-url/play?url=http://ADDRESS",``` と書かれていると思うので、http の部分を https にしてください

**Comment by masahiko-imai** [comment]
残念ながらすでにそれは試していまして、Infuseでエラーとなりました。

**Comment by l3tnun** [comment]
BASIC認証とか入れてますか？

**Comment by masahiko-imai** [comment]
BASIC認証ではないですが、OpenID Connectの認証を入れてます。

**Comment by l3tnun** [comment]
OpenID Connect使ったことがないので分からないのですが、その認証がinfuse側で突破できていないのではないでしょうか？

PC側でURL Scheme使用した視聴が動作するか分かりますか？

**Comment by l3tnun** [comment]
```
https://[HostIP]:8888/api/recorded/1/file?encodedId=1
```

適当な録画ファイルのidを調べて上記のurlがinfuseで開けるか確認してくださいの
開けなければ使えないと思います

上記は recorded id = 1, encoded id = 1 の例になります

各id は ```http://[HostIP]:8888/api/recorded``` で調べられます
詳しくは ```http://[HostIP]:8888/api/debug``` で確認してください

**Comment by masahiko-imai** [comment]
まだPCでは試してないですが、恐らく同じ症状になりそうです。仰るとおり認証が突破出来てないので、アクセストークンも含めてurlを渡す必要がありそうです。もうちょっと考えてみます。

**Comment by l3tnun** [comment]
やはりそうですか

現状アクセストークンを config.json or web の設定 -> ライブ視聴のURL設定 の URL 部分に埋め込むしかないです

**Comment by masahiko-imai** [comment]
了解です。
トークンを埋め込んでも、リフレッシュトークンの扱いとかを考えるとちょっと無理かと思うので、いったん諦めます。どうしても必要な時はVPN経由にします。
ありがとうございました。
