### ISSUE TITLE
uid, gidを指定すると、録画指定および削除実施時にエラーが発生する

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#302]
### 環境
* Version of EPGStation: `1.6.1`
* Version of Mirakurun: `2.13.0`
* Version of Node: `v8.9.4`
* Version of NPM: `不明`
* OS: Debian stretch(docker) on Ubuntu 18.04
* Architecture: x64

### Issue
EPGStationのconfig.jsonに"uid": "username","gid": "username",を追加すると確かに録画ファイルの
所有権が指定したユーザーのものになるのですが、WebUIから番組を指定録画/削除した際に
「予約失敗」「削除失敗」のメッセージが表示されます。
予約開始時は「予約失敗」のメッセージが表示されるものの録画自体は開始されます。
ただし予約削除の場合は「削除失敗」が表示され、実際に進行中の録画を中断することができませんでした。
"uid": "username","gid": "username",を指定しない場合(デフォルトのroot:video)、上記の問題は発生しません。

logs配下のファイルを確認してみましたが、上記操作時のイベントは特に何も記録されていませんでした。
以上、よろしくお願いします。

...

**Comment by l3tnun** [comment]
docker で動かしているのであれば EPGStation の config.json の設定を使用するのではなく、docker のコンテナ実行時に uid, gid の指定ができますのでそちらを試したほうが良いのではないでしょうか?

私は docker + docker-compose 環境で実行しますが、uid と gid の指定は docker-compose.yml で指定するようにしています。

エラー再現確認についてですが、再現環境を用意しているので少しお待ちください。

**Comment by tokohito** [comment]
docker-compose内指定の方法は先に試してまして、ホストの/etc/groupと/etc/passwdを
コンテナ側にマウントしてdocker-composeでuid, gid指定をしてみたのですが、
サービスは立ち上がるものの番組情報が表示されなかったので断念しました。
.envを使ったのが良くないのかもしれませんが、具体的な設定例を示していただけると助かります。

$ cat .env
UID=1000
GID=1000

$ cat docker-compose.yml
    mirakurun:
        user: "${UID}:${GID}"
    epgstation:
        user: "${UID}:${GID}"

**Comment by l3tnun** [comment]
まず、Mirakurun は root でないと実行できません。

> .envを使ったのが良くないのかもしれませんが、具体的な設定例を示していただけると助かります。


[docker-mirakurun-epgstation](https://github.com/l3tnun/docker-mirakurun-epgstation) を参照してください。

epgstation コンテナの user オプションがコメントアウトされていますが、もとに戻してもらえればOKです。

---
uid, gid 設定時にエラーがあ発生するかですが、こちらの環境では確認できません。

**Comment by tokohito** [comment]
ありがとうございます。デフォルトのdocker-compose.ymlにコメント形式で入ってましたね、失礼しました。
uid, gid 設定時にエラー発生しない旨も承知しました。

後日再度検証してご報告します。

**Comment by tokohito** [comment]
docker-composeのepgstationセクションのみuser設定を有効化してみたところ、今度はちゃんと番組表が表示されました。

ただ指定録画/削除した際の挙動はconfig.jsonで設定した場合と同じで、「予約失敗」メッセージで録画開始、「削除失敗」メッセージで中断不能になります。

保存先ディレクトリの所有権はepgstationセクションで指定したユーザーと同じuid/gidです。

**Comment by l3tnun** [comment]
うーん、何らかの理由で Web サーバの Service と 本体の Operator がうまく通信できていないのだと思います。
詳細なエラーが知りたいので、ブラウザの開発者ツールを開いて予約や予約削除、録画削除時のレスポンス内容を確認してほしいです。

chrome であれば ```メニュー -> その他のツール - デベロッパーツール -> Nerwork タブ``` に通信内容が記録されるので確認できるはずです。

**Comment by tokohito** [comment]
確認したところ以下の通り不正なリターンコードが出力されてました。

▼予約時
{"code":500,"message":"Internal Server Error","errors":"EACCES: permission denied, open '/usr/local/EPGStation/data/reserves.json'"}

▼削除時
{"code":500,"message":"Internal Server Error","errors":"IPCTimeout"}

最初に立ち上げる時点でデフォルトのrootで実行していた為、新規に作成されるファイルの所有権がrootになっていたんですね。
なのでdockerディレクトリのうちepgstation以下のファイルをuid:1000のユーザーにchownして
docker-composeの再起動をしたところ、今度は正常に予約と削除ができました。
ありがとうございました。
