### ISSUE TITLE
[確認]h.265で録画するとchrime

### ISSUE THREAD

**Issue by sato5322** [l3tnun/EPGStation#303]
epgstationの問題でない気がするのですが確認させて下さい。
h.265で録画し、chromeでepgstationのwebUIを開いて再生すると、音しか出ないのは、chromeがh265をサポートしていないからでしょうか？
(safari(macos)では正常に再生できるのですが。)

**Comment by l3tnun** [comment]
それはchromeがh.265の再生に対応していないためです
safariくらいしか対応ブラウザは存在しません

**Comment by sato5322** [comment]
よくわかりました！ありがとうございます。

**Comment by ohmsa** [comment]
今更ですが、Microsoft Edge＋Microsoft store にある120円のHEVC拡張機能を使うとh265動画を視聴することが出来ました。
ChromiumブラウザであるVivaldiでは視聴できませんでした。
