### ISSUE TITLE
[要望]録画番組の字幕抽出と検索

### ISSUE THREAD

**Issue by unicode45** [l3tnun/EPGStation#304]
### 環境
* Version of EPGStation: `1.6.2`
* Version of Mirakurun: `2.13.0`
* Version of Node: `v12.14.1`
* Version of NPM: `6.13.4`
* OS: Ubuntu server 18.x
* Architecture: x64

### Issue
HLS再生に字幕表示が追加され、大変重宝していますが、
字幕抽出機能を拡張して録画後に走らせるTsselectのように字幕を抽出し、
「録画済み」番組から字幕も検索できるようにするのはいかがでしょうか？
現在EPGベースの番組名や詳細情報以外に番組内容からも検索できるようになるとニュース番組などから必要な情報を見つけやすくなると思います。

ご検討のほど、お願いいたします。

**Comment by l3tnun** [comment]
非常に面白い機能ですが、労力の割に得られるものが少ないため実装する予定はないです。

EPG 情報より遥かに多い文字列を検索することなると思いますが、like 検索ではとても速度が出ませんので全文検索用に各 DB に応じた設計が必須になります。
MySQL, SQLite3, PostgresSQL 各 DB の全文検索について調べてもらえればわかると思いますが、なかなか大変です。

Solr や ElasticSearch などを使うという手もありますが Node.js で動かないですし、手間がかかりすぎます。

Node.js で動く Lunr.js というものもありますが、大量のデータを扱うようには出来ていませんので使用できそうにはないです。

以上の理由から字幕抽出及びその検索機能の実装は行いません。
(プルリクは受けますが、v1とv2では DB 周りがかなり違うのでおすすめはしません)
