### ISSUE TITLE
番組検索結果の表示上限について

### ISSUE THREAD

**Issue by Connie-Wild** [l3tnun/EPGStation#307]
https://github.com/l3tnun/EPGStation/blob/master/src/server/Model/Api/ScheduleModel.ts#L201

この箇所にて上限を300としていますが、任意の値で実行できるようにすると問題が生じますでしょうか。

**Comment by l3tnun** [comment]
あまりにも表示件数が多いとブラウザが重くなりますが、基本的には問題ないです

**Comment by Connie-Wild** [comment]
回答ありがとうございました！
コンフィグで変更できるように対応してみました。 #309

**Comment by l3tnun** [comment]
最新の master に反映されたので閉じます。

お疲れ様でした。

**Comment by Connie-Wild** [comment]
ご対応ありがとうございました。
