### ISSUE TITLE
subDirectory + HTTPSリバースプロキシ環境において、Socket.ioのCORSエラーが発生する

### ISSUE THREAD

**Issue by kenichi-ogawa-1988** [l3tnun/EPGStation#308]
### 環境
* Version of EPGStation: `1.6.3`
* Version of Mirakurun: `2.13.0`
* Version of Node: `v12.15.0`
* Version of NPM: `6.13.4`
* OS:  Debian 10 (Buster) `Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
* Architecture: x64

### Issue
Google Chrome (macOS 79.0.3945.130) で、subDirectory + HTTPSリバースプロキシ環境のEPGStationを開くと、Socket.ioの通信でCORSエラーが発生しています。

エラーメッセージ（ドメインはフェイクです）
```
Access to XMLHttpRequest at 'https://example.com:444/epg/socket.io/?EIO=3&transport=polling&t=N0wlX12' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

おそらく、Expressでsocket.ioからのレスポンスに `Access-Control-Allow-Origin` ヘッダを追加し、 `https://example.com` (HTTPSの場合) からのAjaxリクエストを許可する必要があるように見えます。

ご確認お願いいたします。

**Comment by l3tnun** [comment]
報告ありがとうございます。

修正する時間が取れないので1,2週間ほどお待ち下さい。

**Comment by kenichi-ogawa-1988** [comment]
こちらの
https://github.com/l3tnun/EPGStation/blob/195d83d21b2e7bb98c8d9cd0811a91b422c81668/src/server/Model/Service/SocketIoManageModel.ts#L28
２つ目の引数のオブジェクトに、 `{ origins: '*:*' }` を追加すればいけそうです。

参考: https://stackoverflow.com/a/38749535/11890023

**Comment by l3tnun** [comment]
環境が用意できなかったので効果の程は不明ですが、 https://github.com/l3tnun/EPGStation/commit/fd1e2e16ac6514434a67383afe5421065dedff4a にて修正をかけました。

動作確認お願いします。

socket.io 周りのポートの設定項目を `config.json` に追加 & 挙動が変化しているので注意してください。

- `socketioPort` socket.io 通信で使用するポート
- `clientSocketioPort` web クライアントがアクセスしに行く socket.io のポート (リバースプロキシ使用時は変更が必須です)

もし、CORSエラーが改善されていなかった場合は、config.json の `serverPort` と `socketioPort` を同じものに設定してもらえば解消できるかと思います。

**Comment by l3tnun** [comment]
もしかしたら `fix-308` で修正できているかもしれません、時間があれば確認お願いします。

**Comment by kenichi-ogawa-1988** [comment]
`fix-308` ブランチで、以下の設定においてCORSエラーが発生しないことを確認しました。

- `serverPort` 8888
- `socketioPort` 8888
- `clientSocketioPort` 443 (リバースプロキシのポートと同一)

しかし、Websocketの最初のメッセージが以下のようになっており、接続はできたものの機能していない可能性はあります。
![image](https://user-images.githubusercontent.com/16537354/75110488-5c628b80-5661-11ea-9055-238e028bc9ad.png)
![image](https://user-images.githubusercontent.com/16537354/75110497-80be6800-5661-11ea-933b-710c81226260.png)

（別件かもしれないので、こちらでコメントするかどうか迷いましたが・・・）

**Comment by l3tnun** [comment]
確認ありがとうございます。

なるほど、transports の順番を変えるとためでしたか。
軽く調べてみたところ、Nginx に以下のような設定が必要なようですね。

http://uorat.hatenablog.com/entry/2016/09/19/203939

これで確認してもらえますか？

**Comment by l3tnun** [comment]
https://github.com/l3tnun/docker-mirakurun-epgstation reverse-proxy-test ブランチにて、nginxでの https リバースプロキシ環境で Websocket にて socket.io で通信できることが確認できました。

(`serverPort` と `socketioPort` が異なる環境は用意できなかったので CORS エラーが解消できたかは不明ですが。)

特に問題なければ master にマージしてこの issue を閉じようかと思います。

**Comment by l3tnun** [comment]
進展が無いようなので閉じます
