### ISSUE TITLE
録画視聴でMPEG2形式でのエンコード視聴ができない

### ISSUE THREAD

**Issue by gifuhabu** [l3tnun/EPGStation#310]
### 環境
* Version of EPGStation: `1.6.3`
* Version of Mirakurun: `2.12.0`
* Version of Node: `v12.15.0`
* Version of NPM: `6.13.4`
* OS: Ubuntu Server
* Architecture: x64

### Issue
<img width="403" alt="Screen Shot 2020-02-18 at 21 11 47" src="https://user-images.githubusercontent.com/46297605/74735624-67e63900-5294-11ea-8c6e-790b453e08fb.png">
お世話になっております。
ライブ視聴ではM2TSというプルダウンメニューがあるので問題なくできますが、録画済み視聴では何故か写真の通り左のプルダウンメニューにmpeg2の項目がなくエンコードしながら視聴ができない状態です。
(このモーダル画面は録画番組クリック→INFOタブのTSボタンをクリックして出てくるものです。)

これは仕様なんでしょうか？無変換ボタンを押せばMPEG2無変換視聴ができますが、エンコード視聴ができなくて困っております。

サンプルの設定ではrecordedStreamingのmpegTsという項目で設定がありますが、こちらに追加しているのにそれに対応するどのプルダウンメニューにも出てこない状態です。
(INFO, DOWNLOAD, STREAMタブ全てを探しましたがありませんでした)
https://github.com/l3tnun/EPGStation/blob/master/config/config.sample.json#L125

以上よろしくお願いいたします。

**Comment by l3tnun** [comment]
ブラウザで MPEG2 は再生できません。

**Comment by 5ym** [comment]
横からすみません録画済み画面だとこの無変換というボタンと

**Comment by l3tnun** [comment]
ちなみに recordedStreaming の設定は VLC 2.x 用のものです。
現状使い物にならないので、機能はしません。
api経由で VLC 2.x で使用可能です。

**Comment by gifuhabu** [comment]
ブラウザで観たいのではなくて、無変換ボタンを押した時と同じ挙動でエンコード視聴がしたいのですが無理でしょうか？
(recordedViewer, mpegTsViewerで指定されているアプリで視聴するやり方です）
https://github.com/l3tnun/EPGStation/blob/master/config/config.sample.json#L18

この設定をして無変換ボタンを押した時の方法です
https://github.com/l3tnun/EPGStation/blob/master/doc/win-url-scheme.md

**Comment by l3tnun** [comment]
@5ym 同一ではないですよ

**Comment by 5ym** [comment]
手元の環境ですと双方全く同じ内容のストリーミングファイルがダウンロードされるだけなのですが、設定などで別々のものにできるのでしょうか

**Comment by l3tnun** [comment]
@gifuhabu 
> ブラウザで観たいのではなくて、無変換ボタンを押した時と同じ挙動でエンコード視聴がしたいのですが無理でしょうか？

シークの対応が出来ませんので無理です。（シークに合わせて変換する必要があるので）
ライブはシークが不要なため実装されました。

@5ym おそらく URL Scheme の設定がされていないのだと思いますが、設定されていれば URL Scheme で指定したアプリ等で再生します。
無指定の場合は TS ブラウザで再生できないためダウンロードされます。

**Comment by gifuhabu** [comment]
@l3tnun 
そういう障害があったんですね。なるほどです。
これができると、どの端末でも回線が遅くてもリモートに設置されてあるサーバーから快適に視聴できるので非常にありがたかったのですが残念ですね…

**Comment by l3tnun** [comment]
録画が完了しているものであれば Stream タブから HLS 配信してみてはどうでしょうか？

iOS を除く OS で hls.js が使用可能なのでシークができます。HW エンコードと組み合わせるとすぐ変換されるのでそこそこ使えるかと思います。

**Comment by gifuhabu** [comment]
HLSはやったことなかったですね。HWエンコードの環境構築してみて試してみようかと思いますー。
この度は色々とありがとうございました。
