### ISSUE TITLE
HLS形式でのライブ視聴について

### ISSUE THREAD

**Issue by regppe** [l3tnun/EPGStation#312]
### 環境
* Version of EPGStation: `1.6.5`
* Version of Mirakurun: `2.7.4`
* Version of Node: `v8.9.4`
* Version of NPM: `6.4.1`
* OS:Debian 9.9 Linux 4.9.0-9-amd64  SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
* Architecture: x64

### Issue
私の環境のせいか分からないのですが、以下のような現象が発生しています。
・HLS形式でのライブ視聴を行おうとするが再生されず(ブラウザの画面は待機状態のまま)、その状態でブラウザのリロードを行うと再生される。WebM形式ではリロードせずにライブ視聴可能。

クライアント環境はMacOSのsafari,chrome及び、Windows10のIE,chromeで同一現象を確認してます。
ちなみに、旧バージョン(バージョン番号は失念してしまいました・・)ではリロードせずにライブ視聴出来ていました。

**Comment by l3tnun** [comment]
おそらく socket.io のポートにアクセスできていないのだと思います。

[conf-manual](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#socketioport) を参考に socket.io のポートを設定し、そのポートで通信できるようにファイヤーウォールの設定等をしてあげて下さい。

**Comment by regppe** [comment]
socketioPort と clientSocketioPort の設定、ファイアーウォールの穴あけでリロードしなくてもライブ視聴できるようになりました。
ありがとうございました。
