### ISSUE TITLE
MySQL環境において、Boolean値が正しく渡されない

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#319]
### 環境
* Version of EPGStation: `1.6.6`
* Version of Node: `v12.16.1`
* Version of NPM: `6.14.4`
* Version of MySQL: `5.7` and `8.0`
* OS: Windows Server 2016
* Architecture: x64

### Issue
#317 で、`enable` が `true` であるものを検索するためにconvertBoolean(true)を指定しましたが、MySQL環境ではこれが文字列としての `'true'` が渡されるため誤った結果が帰ってきます。

![image](https://user-images.githubusercontent.com/9246266/77843326-f379b080-71d6-11ea-94b6-8b0e14b73dce.png)

```
mysql> select keyword,id,enable from Rules where enable = 'true' order by id asc limit 0, 2;
+-----------------------+----+--------+
| keyword               | id | enable |
+-----------------------+----+--------+
| ゲゲゲの鬼太郎        |  4 |      0 |
| ワンパンマン          | 82 |      0 |
+-----------------------+----+--------+
2 rows in set, 1 warning (0.00 sec)

mysql> select keyword,id,enable from Rules where enable = true order by id asc limit 0, 2;
+--------------------+----+--------+
| keyword            | id | enable |
+--------------------+----+--------+
| タモリ倶楽部       |  1 |      1 |
| 鉄腕 DASH          |  2 |      1 |
+--------------------+----+--------+
2 rows in set (0.00 sec)
```

**Comment by l3tnun** [comment]
自分で指摘しておいて間違えるとは...
申し訳ない。

どうやら過去のソースを見る限り ```convertBoolean()``` は SQL の中に含んで使うことしか想定していないようですね。
修正方法考えます

**Comment by l3tnun** [comment]
```convertBoolean()``` で boolean or number を返すようにして修正しました。

修正完了しましたので閉じます。
