### ISSUE TITLE
二か国語で主音声・副音声の分離について質問

### ISSUE THREAD

**Issue by trimethia** [l3tnun/EPGStation#320]
epgstationでのffmpeg設定について質問です。

二か国語対応番組をライブ視聴する際、dual_mono_modeの設定で主音声(main)・副音声(sub)を選択できることを確認できましたが、主音声・副音声を異なるAudio Streamに分離することが可能でしょうか？

よろしくお願いいたします。

**Comment by trimethia** [comment]
補足させてください。

`-filter_complex channelsplit` で分離できることを確認できましたが、このoptionが常に付けていると、dual_monoではない番組も分離されてしまいますね。

必要な時だけ（dual_monoである番組に対してのみ）channelsplitを行うことが可能でしょうか?

**Comment by l3tnun** [comment]
ffmpeg の詳しい機能については私もよく知りません。
ffmpeg の機能の話は EPGStation とは関係ありませんのでここでは扱いません。

> 必要な時だけ（dual_monoである番組に対してのみ）channelsplitを行うことが可能でしょうか?

エンコードの話であれば https://github.com/l3tnun/EPGStation/issues/244#issuecomment-468928770 を参照してください

**Comment by l3tnun** [comment]
ライブ視聴の場合はコマンドが切り替えられませんので音声の分離は無理です

**Comment by trimethia** [comment]
> ライブ視聴の場合はコマンドが切り替えられませんので音声の分離は無理です

なるほど、ありがとうございます。
