### ISSUE TITLE
recordedTmp内の保存ディレクトリについて

### ISSUE THREAD

**Issue by lynlea2501** [l3tnun/EPGStation#321]
録画ルールで保存ディレクトリ(例：hoge)を指定した場合、
録画中は recordedTmp/hoge/fuga.ts が作成されますが
録画完了後に空のrecordedTmp/hogeが残ったままになります。
この空ディレクトリを自動で削除してもらえると嬉しいです。

**Comment by l3tnun** [comment]
現状それは仕様となります。

そのうち削除処理を実装するかもしれません。

**Comment by l3tnun** [comment]
v2.0でrecordedTmp内にディレクトリを生成しないように変更されました。
よってこの問題は解決しました。
