### ISSUE TITLE
【要望】macOSのSafariでのライブ視聴について

### ISSUE THREAD

**Issue by moja2** [l3tnun/EPGStation#324]
### 環境
* Version of EPGStation: `1.6.5`
* Version of Mirakurun: `2.15.2`
* Version of Node: `v10.19.0`
* Version of NPM: `6.13.4`
* OS: Ubuntu 18.04.4 LTS
* Architecture: x64

### Issue
[Mac でのカスタム URL Sceheme の設定](../blob/master/doc/mac-url-scheme.md)を参考に、URL Schemeの変更とWeb設定を利用することでmacOSのSafariでも録画視聴できるようにしました。

しかし同様の方法でライブ視聴しようとすると、m3u8ファイルがダウンロードされます。原因は[CreateStreamLink.ts L21](https://github.com/l3tnun/EPGStation/blob/0c50028a5f4547073c268959c3b6abd0d92304dc/src/client/ViewModel/Stream/CreateStreamLink.ts#L21)によりmacOSのSafariではWeb設定の「ライブ視聴のURL設定」が適用されないためと思います。

macOSのSafariでの「ライブ視聴のURL設定」の適用、もしくconfig.jsonのmpegTsViewer, recordedViewer, recordedDownloaderにおいてmacOS Safariも適用対象に含めることを検討していただけないでしょうか？

---
macOSのSafariでの録画視聴は [Mac でのカスタム URL Sceheme の設定](../blob/master/doc/mac-url-scheme.md) に対して下記変更を施すことでできるようになりました。

1. config.json の設定 →macOSのSafariではm3u8 ファイルのダウンロードになるため、Web設定の「録画視聴のURL設定」で以下を設定
```
cvlc://ADDRESS
```

2. 「アプレットの作成」での記述内容を以下に変更
```
on open location url_scheme
	(*デリミタで文字列抽出*)
	set AppleScript's text item delimiters to {"cvlc://"}
	set txt_items to text items of url_scheme
	set AppleScript's text item delimiters to {""}
	set scheme_txt to txt_items as Unicode text
	
	tell application "VLC"
		OpenURL "http://" & scheme_txt
		activate
		set zoomed of window 1 to true
	end tell
end open location
```

**Comment by l3tnun** [comment]
対応したいのですが macOS の safari だけ、URL Scheme を正しく解釈してくれないので無理です。
(iOS のSafari は正しく解釈してくれます)

Chrome, Firefox等をお使いください。

ただ、私が昔 macOS のsafari で確認した際にそのような挙動になっていただけで、最新の safari では修正されているかもしれません。
(私の手元に macOS が動作する環境が無いため確認不能)
もしそうであれば修正します。

該当部分はご指摘どおり下記の部分になります。

https://github.com/l3tnun/EPGStation/blob/0c50028a5f4547073c268959c3b6abd0d92304dc/src/client/ViewModel/Stream/CreateStreamLink.ts#L21

```!(Util.uaIsMac() && Util.uaIsSafari()) &&``` を削除して macOS の safari で問題なく動作するのであれば教えていただきたいです。

**Comment by moja2** [comment]
ご返答ありがとうございます。
URL Schemeに `http://` を含めないようにするとmacOSのSafariでもうまく動きました。

確認の手順は以下で行いました。macOSのバージョンは`10.15.4`で確認しています。

1. `CreateStreamLink.ts`から`!(Util.uaIsMac() && Util.uaIsSafari()) &&`を削除
2. `npm run build`したのち、EPGStationを再起動
3. macOSのSafariからEPGStationのWeb設定で「録画視聴のURL設定」に`cvlc://ADDRESS`と設定
4. [Mac でのカスタム URL Sceheme の設定](../blob/master/doc/mac-url-scheme.md)の「AppleScript でのカスタム URL Scheme アプリの作成」の手順に従ってURL Schemeを受けとるアプレットを作成。ただしスクリプトの内容は以下に置き換えています。

```
on open location url_scheme
	(*デリミタで文字列抽出*)
	set AppleScript's text item delimiters to {"cvlc://"}
	set txt_items to text items of url_scheme
	set AppleScript's text item delimiters to {""}
	set scheme_txt to txt_items as Unicode text
	
	tell application "VLC"
		OpenURL "http://" & scheme_txt
		activate
		set zoomed of window 1 to true
	end tell
end open location
```
スクリプトの変更点は、(1)アプレットの中で`http://`をURL Schemeで受け取った文字列に付加するようにした。(2)`do shell script`でVLCを起動すると「アクセシビリティアクセス（イベント）」のメッセージダイアログ（[参考](https://knowledge.shade3d.jp/knowledgebase/macos-mojave%E7%92%B0%E5%A2%83%E3%81%A7%E7%89%B9%E5%AE%9A%E3%81%AE%E6%93%8D%E4%BD%9C%E3%82%92%E8%A1%8C%E3%81%86%E3%81%A8%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B7%E3%83%93%E3%83%AA%E3%83%86%E3%82%A3)）が表示され、システム環境設定で許可設定しても何故か消えないので、`tell application`での起動に変更することで回避、の2点です。

5. macOSのSafariからEPGStationの「ライブ」画面から適当な番組をクリック、M2TS, 無変換を選択し視聴をクリック→「このページで"cvlc.app"を開くことを許可しますか?」ダイアログ→許可
6. VLCが起動しライブ再生開始。VLCのウィンドウタイトルは「mpegts?mode=2」と表示。

またChromeでも上記内容でライブ視聴、録画視聴ともにできております。

**Comment by l3tnun** [comment]
詳細な動作確認ありがとうございます。
手が空き次第修正しますのでしばらくお待ちください。

**Comment by l3tnun** [comment]
修正完了しましたので、閉じます。
ありがとうございました。

**Comment by moja2** [comment]
修正ありがとうございました。
迅速なご対応に感謝いたします。
