### ISSUE TITLE
タイミング依存で録画に失敗する可能性がある

### ISSUE THREAD

**Issue by masnagam** [l3tnun/EPGStation#326]
### 環境
* Version of EPGStation: `1.6.9`

### Issue

Mirakurunの`/api/programs/{id}/stream`は，EITの内容をチェックし，録画対象の番組が現在放送中の番組になるまでパケットを送り返さないようになっています．

* https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/TSFilter.ts#L271
* https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/TSFilter.ts#L554

そのため，[ストリーム取得後５秒以内](https://github.com/l3tnun/EPGStation/blob/master/src/server/Model/Operator/Recording/RecordingManageModel.ts#L379)に上記EITを受信できないと以下のようなエラーが発生するものと考えられます．

```
[ERROR] system - recording failed: ...
[ERROR] system - preprec failed: ...
```

多くの場合成功しているようなのですが，極稀に上記エラーが発生することがあり，理由が分からずにいたのですが，おそらく上記EITが５秒以内に到着しない場合があるのではないかと推測しています．

問題の性質上，問題発生時に再現データを保存することが困難であるため，残念ながらエビデンスはありません．

安全のため，（１５秒-経過時間）だけ待つようにしたほうがいいのではないかと考えています．

**Comment by l3tnun** [comment]
今ソースを見る元気がないので土日まで待ってください。

**Comment by masnagam** [comment]
エビデンスがないと書きましたが，番組境界付近でEITがどのあたりで更新されるか確認すれば，上記予想が正しいかどうか確認できることに気が付きました．調べてみます．

調査結果によっては予想が誤っているという結論になるので，結果が出るまでは何も対応していただかなくて問題ありません．

**Comment by masnagam** [comment]
どうも私の勘違いのようでした．お騒がせしました．

MirakurunはEITが来るまで，HTTPレスポンスを一切返さないようです．EITはほぼ番組開始直前に送られるので，レスポンスが返ってくるまで
https://github.com/l3tnun/EPGStation/blob/master/src/server/Model/Operator/Recording/RecordingManageModel.ts#L289
でほぼ１５秒待ってから，`doRecord`に入るようです．`doRecord`に入った時点でデータがくることはほぼ確定しているので，５秒のタイマーで十分です．

仮に，HTTPレスポンスヘッダーを先に送り返すような実装になっていると，何からのレスポンスボディを５秒以内に送り返さないとタイムアウトします．この点に注意してmirakcを実装することにします．
