### ISSUE TITLE
録画済みの検索対象フィールドについて

### ISSUE THREAD

**Issue by split-n** [l3tnun/EPGStation#330]
録画済み番組のキーワード検索時に、現在の動作ではタイトル・概要(name/description)が検索対象となり、詳細(extended)は検索対象ではないようです。
こちらが検索対象から外れているのは性能上の理由等なのでしょうか。

https://github.com/l3tnun/EPGStation/blob/cf6d6895998b25d2346ef4cce85d97dabda9a944/src/server/Model/DB/RecordedDB.ts#L803

**Comment by l3tnun** [comment]
extended まで対象にすると検索結果に意図しないものが含まれることが多いと感じたので、わざと検索対象から外しています。
性能的な理由によるものでは無いです。
