### ISSUE TITLE
m2tsに字幕データを残す方法について

### ISSUE THREAD

**Issue by lynlea2501** [l3tnun/EPGStation#331]
### 環境

Version of EPGStation: 1.2.5(?)
Version of Mirakurun: 2.15.2
Version of Node: v6.14.4
Version of NPM: 6.14.4
OS: Ubuntu 20.04
Architecture: x64

### Issue

録画されたm2tsファイルに字幕データが残りませんが
残すような設定は可能でしょうか。

**Comment by l3tnun** [comment]
そこは Mirakurun 次第なので特に感関知していませんが、残っているはずです。
そうでないと b24.js で字幕表示できませんので。

**Comment by lynlea2501** [comment]
過去chinachuで録画したデータからは、Linux上でassdumperを使い字幕が抽出できましたが
最近epgstationで録画したデータからは字幕抽出ができませんでした。
（どちらも[字]があるファイルです）
このためepgstationは字幕データを削除していると早とちりしていました。
HLSでの字幕対応は知っていましたので、通常の録画(m2ts保存)では字幕を消すような処理があるのかなぁと。

WindowsでC-Catsを使ってみたところ字幕を抽出することができました。
また、ffprobeを見たところ「Subtitle」ストームを確認しました(先にやるべきでした)。
よって、私が録画したmt2sにassdumperが対応していなかっただけでした。
お騒がせして申し訳ありませんでした。

**Comment by l3tnun** [comment]
解決したようで何よりです。
