### ISSUE TITLE
`thumbnailPosition`の大きさに依存し，サムネイル生成時間が伸びる

### ISSUE THREAD

**Issue by masnagam** [l3tnun/EPGStation#332]
### 環境
* Version of EPGStation: `1.6.9`

### Issue

サムネイル生成時に指定している`-ss`オプションは，コマンドライン上の位置に依存して異なる動作となります．
https://trac.ffmpeg.org/wiki/Seeking

現在，`-ss`は`-i`の後に指定されているため，"Output Seeking"となり，`-ss`に指定した位置までデコードを行いフレームを破棄します．これは意図した動作なのか確認したいです．

"Input Seeking"にするとキーフレームを使ってシーク位置まで移動するため，短時間・低CPU使用量で処理が完了します．実際に試してみると分かりますが，同じような位置のサムネイルが生成されます．

"Output Seeking"だと，`thumbnailPosition`の設定値に強く依存してリソースを消費してしまうので，特別な理由がないのでしたら，"Input Seeking"に変更したほうが良いだろうと思っています．

PRを送ろうかとも思いましたが，一行だけの修正なので，以下にdiffを貼り付けておきます．

```diff
diff --git a/src/server/Model/Operator/Thumbnail/ThumbnailManageModel.ts b/src/server/Model/Operator/Thumbnail/ThumbnailManageModel.ts
index 889f8fd..2dba741 100644
--- a/src/server/Model/Operator/Thumbnail/ThumbnailManageModel.ts
+++ b/src/server/Model/Operator/Thumbnail/ThumbnailManageModel.ts
@@ -127,7 +127,7 @@ class ThumbnailManageModel extends Model implements ThumbnailManageModelInterfac
         }

         // create thumbnail
-        const cmd = (`-y -i %INPUT% -ss ${ thumbnailPosition } -vframes 1 -f image2 -s ${ thumbnailSize } ${ thumbnailPath }`).split(' ');
+        const cmd = (`-ss ${ thumbnailPosition } -y -i %INPUT% -vframes 1 -f image2 -s ${ thumbnailSize } ${ thumbnailPath }`).split(' ');
         for (let i = 0; i < cmd.length; i++) {
             cmd[i] = cmd[i].replace(/%INPUT%/, filePath);
         }
```

PRの方が良いということであれば，作成します．

**Comment by l3tnun** [comment]
詳しい解説ありがとうございます。
意図した動作ではないですので修正します。
