### ISSUE TITLE
reverse proxy使用時に/api/debugのAPIのURLが内部用のURLになってしまい、APIが実行できない

### ISSUE THREAD

**Issue by todcxtr** [l3tnun/EPGStation#335]
### 環境
* Version of EPGStation: `1.7.1`
* Version of Mirakurun: `3.2.0`
* Version of Node: `v12.18.2`
* Version of NPM: `6.14.5`
* Version of nginx: `1.19.1`
* OS: `Windows 10 Pro`
* Architecture: `x64`

### Issue
以下のような設定でリバースプロキシを構成してEPGStationにアクセスできるようにしています。
このとき、/api/debug (/api-docs/) にアクセスしたとき、画面上に表示される Base URL が内部のURL(192.168.1.1:8888/epg/api) になっています。
実際にAPI を実行してみるとリバースプロキシを介さない192.168.1.1:8888 にアクセスしていて、そのポートは外部には開いていないためAPIは失敗します。（そもそもレスポンスが返ってこない）
これについて解決する方法はないでしょうか。

```
config.json (EPGStation)
  "serverPort": 8888,
  "socketioPort": 8888,
  "clientSocketioPort": 9999,
  "subDirectory": "epg",
```

```
nginx.conf
  server {
    listen 9999;
    location /epg {
      proxy_pass http://192.168.1.1:8888/epg;
```

**Comment by l3tnun** [comment]
検証用の環境を用意するのが面倒なのと時間が取れなくて雑な回答になってしまいますが、

[linux-nginx.md](https://github.com/l3tnun/EPGStation/blob/master/doc/linux-nginx.md)と見比べてみてください。

**Comment by todcxtr** [comment]
ありがとうございます。
linux-nginx.md の設定をすべて追加し、ポート番号を変えていたので
`    proxy_set_header Host $host;`
を以下のようにしたところ正常に動作するようになりました。
`    proxy_set_header Host $host:$server_port;`
