### ISSUE TITLE
設定ファイルをJSON以外の形式にする

### ISSUE THREAD

**Issue by doc382x** [l3tnun/EPGStation#336]
### Issue
現在設定ファイルで用いられているJSONは人間が直接編集しづらいファイルフォーマットであると思うため、以下のいずれかを提案します。

* TOMLやINIのような直接編集しやすい形式に変更する
* TUI(もしくは番組表のようなWebベース)のフロントエンドを作成し、直接JSONを触らなくても設定を変更できるようにする

どうでしょうか。

**Comment by l3tnun** [comment]
薄々そう思っていましたので v2 では全ての設定ファイルが yaml になっています。
現行の v1 に大きな更新を加える気が無いので変更の予定は無いです。

**Comment by doc382x** [comment]
> 薄々そう思っていましたので v2 では全ての設定ファイルが yaml になっています。

いいと思います👍

> 現行の v1 に大きな更新を加える気が無いので変更の予定は無いです。

承知いたしました。
