### ISSUE TITLE
【要望】録画済みの未視聴か視聴済みかがわかる機能

### ISSUE THREAD

**Issue by 53JIlLenWe11** [l3tnun/EPGStation#337]
### Idea
録画済み一覧で一般的なレコーダーにあるような視聴済みか未視聴なのかわかるようにアイコンなり、
動画の一覧を上と下で未視聴と使用済みでセパレート分けるなどしてわかるようにほしいです｡

付け加えるなら、視聴済みを一括で削除する機能や、保護して削除対象から省く機能もあるととても便利になるかと思いました｡

ご検討よろしくおねがいします。

**Comment by l3tnun** [comment]
iOS, Android ではデフォルトで URL Scheme を使用して外部アプリを使用して動画の再生をしているため、epgstation 側ではどこまで再生されたのか検知する事ができません。
(web の video player で再生すればこの限りではないですが)

ですので未視聴、視聴済みで分類することは難しいです。


> 保護して削除対象から省く機能

こちらについては v2 で実装可能かもしれません。

**Comment by ohmsa** [comment]
>> 保護して削除対象から省く機能
逆にごみ箱機能みたいな、削除フラグを付けて後で一括で／容量が足りなくなったら古いのから消すみたいな機能もあると便利かもしれません。

**Comment by l3tnun** [comment]
@ohmsa 良い機能だと思いますが、全く違う機能なので必要であれば新しい issue を建ててください。

**Comment by l3tnun** [comment]
v2.0で保護機能ついかしました。
残りは対応不可能なので閉じます。
