### ISSUE TITLE
[要望]ライブビューフォマード選ぶ時外部プレイヤー/m3u8オプションを追加

### ISSUE THREAD

**Issue by kamayuji** [l3tnun/EPGStation#338]
### Idea

外でテレビを見る時通信量節約のため時々raw m2tsの代わりにmp4をエンコードします。なので、外でもよくパソコンを使うから、その時ウエブプレイヤーの代わりに無変換と同じ外部プレイヤー(VLCなど)を使いたいです。今MP4とHLSもウエブプレイヤーしか使えないですが、もしライブテレビを見る時apiのmp4/hlsのリンクはm3u8/xspfをつくれば便利と思います。

大体これような感じです。

https://i.imgur.com/TnBQhr2.png
...

**Comment by l3tnun** [comment]
圧縮して視聴したいだけであれば m2ts の設定で x264 や x265 にエンコードしてあげれば十分だと思うのですが、どうでしょうか？
m3u8のリンクが必要な理由がいまいちわからないのですが、外部プレイヤーを起動するために必要なだけであれば URL Scheme を設定してあげれば Window, macOS, Linux いずれのOSでも m2ts 視聴時には外部プレイヤーが起動します。

あと、hls での視聴の場合はほかの視聴方法とは違い手動でストリームの開始/停止をする必要があるので、m3u8 のリンクは事前に用意することはできません。

**Comment by l3tnun** [comment]
情報が足りませんので閉じます
