### ISSUE TITLE
録画したもののストリーミング再生時に一時停止してしばらくして再開すると続きから再生できない

### ISSUE THREAD

**Issue by 53JIlLenWe11** [l3tnun/EPGStation#339]
### 環境
* Version of EPGStation: `1.7.1`
* Version of Mirakurun: `3.2.0`
* Version of Node: `v12.18.3`
* Version of NPM: `6.14.6`
* OS: Linux raspberrypi 5.4.51-v8+
* Architecture: x64

### Issue
Windows上のFirefoxでEPGStationを開き、VLCプレーヤーでストリーミング再生をしているのですが、
10分ほど再生を一時停止したあとに再生をすると、何秒間か再生されたあとに再生が完全に止まってしまいます。
そうなるとブラウザの録画済みにある対象動画を開きなおし、見た箇所まで早送りするのがめんどいです。
ある程度の時間の一時停止後も問題なく再生できるようにできないでしょうか?
または、一時停止後の再生までの待機時間などがあるのでしたら、そこを調整できるようにできないでしょうか。

以上です、ご検討よろしくお願いします｡

**Comment by l3tnun** [comment]
そのような現象は初めて聞きましたが、epgstation は vlc から要求されたデータをただ返しているだけですので vlc 以外の再生ソフトを使用した場合解決するかもしれません。(mpv等)

ちなみに vlc のバージョンはいくつでしょうか？

**Comment by 53JIlLenWe11** [comment]
VLCはx64 3.0.11 になります。

**Comment by l3tnun** [comment]
平日に時間が取れないので検証はまだ出来ませんが、恐らく vlc 側の問題だと思いますので mpv 等の他の再生ソフトを試してみてください。

**Comment by 53JIlLenWe11** [comment]
こちらでも検証して見たところ、
VLCプレーヤーはx86もx64でも一時停止して10分経過後に再生すると数秒再生後に止まってしまいました。
MPC-BEで検証したところ、一時停止後も問題なく再生できました。
もしかしたらVLCプレーヤー特有の事象かもしれません。

もし解消方法ご存知の方がいらしたら、ご教授お願いします。

**Comment by l3tnun** [comment]
本日時間が取れましたので windows 10 x64 + vlc x64 3.0.11環境で確認しましたが、発生しませんでした。
ネットワークの切断が原因かと思い、一時停止後にネットワークを切断 -> 10分ほど放置 -> ネットワーク再接続後に再生 としてみましたが問題なく再生可能でした。
環境依存のなんらかの原因があるかもしれません。

**Comment by l3tnun** [comment]
v2.0で多々変更がありましたので、一度閉じます。
v2.0環境でも再現するのであれば、再度開いてください、
