### ISSUE TITLE
ffmpeg 実行時のプロセス優先度を変更したい

### ISSUE THREAD

**Issue by tutiyama** [l3tnun/EPGStation#340]
### 環境
* Version of EPGStation: `1.6.9`
* Version of Mirakurun: `3.1.1`
* Version of Node: `v14.5.0`
* Version of NPM: `6.14.5`
* OS:CentOS 7.5.1804
* Architecture: x64

### Issue
半年ほど前から非常に便利に利用しています。
素晴らしいソフトを作っていただき、大変感謝しています。

要望なのですが、
非力なマシンを利用しているため、ffmpeg のプロセス優先度を下げたいと考えています。
たとえば、config.json で nice の -n パラメータを指定できたら便利だと感じました。

ご検討よろしくお願いします。

**Comment by l3tnun** [comment]
現行の v1 で機能追加の予定はありませんので、v2にて検討します。
ffmpeg はサムネイル作成、エンコード、ライブ視聴、録画ストリーミング視聴に使用されていますが、どれのことを指していますか？

各コマンドは config.json で変更可能なので以下のように指定してあげれば現状でも動作するかもしれません。

* mpegTsStreaming での例
```json
{
    "name": "720p",
    "cmd": "nice -n 10 %FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -y -f mpegts pipe:1
},
```

**Comment by tutiyama** [comment]
返信ありがとうございます。
特にエンコードについて希望しています。

mpegTsStreaming はいただいた方法で対応できました。
エンコードについても、もし何か方法があればヒントをいただけると助かります。

よろしくお願いします。

**Comment by l3tnun** [comment]
エンコードでも呼び出されるエンコードコマンド内で同様のことをしてあげれば問題ないはずです。

enc.js を例にすると

下記 args に引数を渡し、

https://github.com/l3tnun/EPGStation/blob/93c5df5a215b83e193dcec36bfe1902ab636626e/config/enc.js#L17

下記部分で ffmpeg を実行していますので

https://github.com/l3tnun/EPGStation/blob/93c5df5a215b83e193dcec36bfe1902ab636626e/config/enc.js#L60

この部分を nice コマンド経由で実行するように書き換えれば動くはずです。

**Comment by tutiyama** [comment]
ありがとうございます！
取り急ぎ次の方法で解決できました。

```
// const args = ['-y', '-analyzeduration', analyzedurationSize, '-probesize', probesizeSize];
const args = ['-n 19', ffmpeg, '-y', '-analyzeduration', analyzedurationSize, '-probesize', probesizeSize];
```

```
//const child = spawn(ffmpeg, args);
const child = spawn('/usr/bin/nice', args);
```
