### ISSUE TITLE
【質問】エンコードパラメータの引継ぎについて

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#344]
### 環境
* Version of EPGStation: `1.7.5`
* Version of Mirakurun: `3.3.1`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* OS:Windows 10
* Architecture: x64

### Issue
推奨の方法ではないかもしれませんが、以前のconfig.jsonでは
`
        {
            "name": "H264",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe %ROOT%\\config\\enc.js main",
            "suffix": ".mp4",
            "default": true
        },
        {
            "name": "H264-sub",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe %ROOT%\\config\\enc.js sub",
            "suffix": "-sub.mp4"
        },
`
とすることでenc.js側でprocess.argv[2]にて引数を元にエンコード設定を場合分け出来ました。
元々はdualMonoの音声を切り替える為のようですが、例えば「720/24pで製作されているアニメは720/24pで」「SD放送時代の番組は480pで」のようにエンコードパラメータをルールごとに切り替えるのに使っていました。

サーバ新調に伴い、新サーバ（上述環境）セットアップ、旧サーバから録画・サムネイルデータコピー、config.json書き換え、新エンコード設定（h264_qsvからhevc_nvencへ）、dbレストアによる既録画番組の引継ぎ・再生、手動予約、エンコードまでは出来ました。しかしこの時、dbレストアで録画予約もレストアされていると思うのですが、録画予約ルールのエンコード設定が空欄になってしまいます。

”"name": "H264",”
の部分を一致させておけば引き継げると思っていたのですが、何度か試しても空欄のままなので困っています（新エンコード設定の条件分岐も反映されるまで何回かサービスの再起動が必要だったのでおま環かもしれませんが……）

ヒントだけでもいただけると幸いです。

**Comment by l3tnun** [comment]
> ”"name": "H264",”
> の部分を一致させておけば引き継げると思っていたのですが、

その前提が違います。

encode は配列になっていますが、ルールに記録されるのはその配列のインデックスになります。
そのため、name を同じものにしても何ら効果はありません。
新旧の config.json の encode の要素数を同一にすれば解決するかと思います。

※v1 から v2 に移行する場合は name の一致で確認しているので、name を同じものにすれば大丈夫です。

**Comment by ohmsa** [comment]
回答ありがとうございます。おかげさまで引き継げました。
