### ISSUE TITLE
サーバ移行時復元できない番組がある

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#346]
### 環境
* Version of EPGStation: 1.7.5
*Version of Mirakurun: 3.3.1
*Version of Node: v10.15.1
*Version of NPM: 6.4.1
*OS:Windows 10
*Architecture: x64

### Issue
PC：AからPC：Bにサーバを移しています。

1. PC：AからPC：Bに録画データ・サムネをコピー
2. PC：Aでデータベース書き出し
3. PC：Bにreserves.jsonとデータベースをコピー
4. PC：Bでデータベースレストア

という手順でほとんどの番組が移動できました。

が、一部の番組については「録画済み画面ではサムネイル付きで表示されるものの再生できない」という症状が出ております（PC：Aでは再生できます）。
DLしようとすると（サイズも表示はされる）
> {"code":500,"message":"Internal Server Error","errors":"ENOENT: no such file or directory, stat 'J:\\EPGStation\\DTV\\アズールレーン \\201910102330-アズールレーン episode 02「【激戦】鼓動の波、鋼鉄の翼」_ＢＳ１１イレブン-24p.mp4'"}
> {"code":500,"message":"Internal Server Error","errors":"ENOENT: no such file or directory, stat 'J:\\EPGStation\\DTV\\スレイヤーズTRY \\201904190000-スレイヤーズTRY  #26_カートゥーン-SD.mp4'"}
といったエラーが出ます。PC：Bの該当フォルダにデータ自体は存在するのですが、リンクが出来ていないようです。

どなたかお知恵を拝借いただけますと幸いです。

**Comment by scandium-j** [comment]
データベースのパスに半角スペースが入っているからではないでしょうか？
おそらくルールを作成するときにキーワードの末尾に半角スペースが入っていたのでしょう

**Comment by l3tnun** [comment]
エラーの通りファイルパスが変わっているのだと思います。
DB側を修正するか、実ファイル側を修正してください。

epgstation の問題ではないので閉じます。
必要なら再度オープンしてください。

**Comment by ohmsa** [comment]
ありがとうございます。npm run backupをしてログを開くとおっしゃる通り、

> {"id":24869,"recordedId":25680,"name":"QSV|720/24p","path":"アズールレーン \\202003132330-アズールレーン episode 11「【怪物】あまねく海に戦いを」_ＢＳ１１イレブン-24p.mp4","filesize":566608861}

パスに半角スペースが入っておりました。この場合、「"path":"アズールレーン \\20200～」の半角スペースを消してレストアすれば繋がるのでしょうか（DBいじるのが少々怖くて……）

質問ばかりで申し訳ないですが、お力お借りできれば幸いです。

**Comment by l3tnun** [comment]
> パスに半角スペースが入っておりました。この場合、「"path":"アズールレーン \20200～」の半角スペースを消してレストアすれば繋がるのでしょうか（DBいじるのが少々怖くて……）

実ファイルのファイルパスで半角スペースが存在しなければそれで大丈夫だと思います。
バックアップファイルに正しいファイルパスが記録されていれば問題ないです。

ファイルのコピー時にファイルパスが変わったのかなあと思っています。

**Comment by ohmsa** [comment]
VisualstudioCodeでctl+Hで置換できるので、「 \\」(半角スペースとバックスラッシュ二つ)を「\\」（バックスラッシュ二つ）にして保存しレストアすると治りました。

そう言えばこれらのファイルはコピーするときに「データがありません」と言われていた気がします（手でコピーしました）。予約情報（reserves.json）も今のうちに編集しておいた方がよさそうですかね。

重ね重ねありがとうございます。

**Comment by l3tnun** [comment]
reserves.jsonはルール予約の場合は勝手に更新されるのでいじらなくて良いです。
手動予約の場合は一度予約を削除して再度予約すると良いと思います。
