### ISSUE TITLE
単純に私は使い方がわからないか。予約した番組は録画をしない。

### ISSUE THREAD

**Issue by wailoktam** [l3tnun/EPGStation#350]
### 環境
* Version of EPGStation: `x.x.x`
* Version of Mirakurun: `x.x.x`
* Version of Node: `12.19`
* Version of NPM: `6.14`
* OS: Ubuntu
* Architecture: x64

### Issue
以下のページを従ってmirakurun and epgstationをインストールしました。
https://iroirotsumekomu.blogspot.com/2020/06/ubuntu.html

ブラウザでlocalhost:8888を開いて、ルールでいっぱい予約をしましたが、予約の時間のあとになっても、録画済のページになにもなく、epgstation/recordedの下になにもありません。

最初、configはhttps://iroirotsumekomu.blogspot.com/2020/06/ubuntu.htmlのようになります。recorded:"/home/xyz/EPGStation/recorded"を追加しても、状況が変わりません。

どなたが助けていただければうれしいです。よろしくお願いいたします。

**Comment by tomo0611** [comment]
1. まず、放映中のところから番組が視聴できますか?
番組名をクリックしてM2TS->無変換でやってみてください。
2. 番組表は正しく取得されていますか?
3. EPGStationは最新版ですか?
4. Mirakurunが最新版なら、Webのuiがありますので、 http://localhost:40772 に行ってエラー吐いてないか、チューナーが正しく認識されているか確認してください。

**Comment by l3tnun** [comment]
Mirakurun や EPGStation を動かしている環境の時刻はあっていますか？
もし合っていなかったら ntp 等で合わせてあげてください。

**Comment by wailoktam** [comment]
ご親切ありがとうございます。パソコンは離れているところにありますので、明日試してからここに報告します。よろしくお願いいたします

**Comment by l3tnun** [comment]
進捗がないので閉じます
