### ISSUE TITLE
ffmpegへオプションが正しく渡らない

### ISSUE THREAD

**Issue by R-Django** [l3tnun/EPGStation#355]
### 環境
* Version of EPGStation: `1.7.4`
* Version of Mirakurun: `3.3.1`
* Version of Node: `v10.18.1`
* Version of NPM: `6.14.8`
* OS: CentOS Linux release 7.7.1908 (Core)
* Architecture: x64

config.json の recordedHLS に設定したffmpeg のオプションの一部が上手く渡らず、ffmpeg の動作が停止してしまいます。
その際のエラーメッセージは下記の通りです。

> [2020-10-22T21:23:48.102] [DEBUG] stream - [hls @ 0x4983580] Invalid keyval "v:0
> [hls @ 0x4983580] Variant stream info update failed with status ffffffea
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:2 --

該当するオプションは下記の箇所です。

> -var_stream_map 'v:0,a:0 v:1,a:1'

spawnにオプションを渡す際にオプション内のカンマやスペースで区切られてしまう様でEncodeProcessManageModel.js を少し弄りオプションを配列ではなく文字列として渡してみたり、一重引用符を色々とエスケープしてみたりしましたが上手くいきません。

ご助言頂く事は出来ますでしょうか？

**Comment by l3tnun** [comment]
カンマで括ると駄目なのは確かなので、カンマを外せば通常は良いです。
ただ今回の場合引数の中にスペースがあるので駄目ですね。

現状 epgstation のコマンド引数解でスペースをエスケープする機能が無いのでそのオプションは渡せないですね。

何か策を考えます。

**Comment by l3tnun** [comment]
fix-cmd ブランチに対策を入れました。
```%SPACE%``` を半角スペースに置換して解釈できるよう変更しています。
そのため以下のように設定を変更すると動作するようになると思います。

```
-var_stream_map v:0,a:0%SPACE%v:1,a:1
```

問題なく動作しましたら master へマージしますので確認お願いします。

**Comment by R-Django** [comment]
ありがとうございます。

似たような事は試していたのですが、その上で一重引用符を省くという事を試せていなかったようです。
お手数を掛け申し訳ありません。

お陰様で問題のオプションが通る事を確認できました。

hls.js のアダプティブストリーミングというのを試行中に問題に行き当たったのですが、まずは表示出来ているようです。

ありがとうございました。

**Comment by l3tnun** [comment]
問題が解決したようで何よりです。のちほどマージします

**Comment by l3tnun** [comment]
master へマージしたので閉じます。
