### ISSUE TITLE
競合　の表示について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#358]
### 環境
* Version of EPGStation: 1.7.5
* Version of Mirakurun: 3.3.1
* Version of Node: 10.15.1
* Version of NPM: 6.4.1
* OS:Windows10
* Architecture: x64

### Issue
現在競合タブをクリックすると競合がある場合はその予約が表示されますが、競合がない場合何も表示されません。「まだ表示されてない」のか「競合がない」のかわからないので、「競合はありません」といった表示があるとありがたいです。

また、特にBS/CSで競合が発生している場合に「BSを押してその日付けに飛んで確認、なければCSを押してその日付に～」なので、「一発でその日付のその時刻に飛ぶ機能」「BSを横にずらしていくとCS番組表も見られる機能」もあると便利そうです。

**Comment by l3tnun** [comment]
1. まず競合の有無の表示について
トップページの予約カードのタイトル部分に競合がある場合、バッチで競合件数が表示されます。
ですので、これで十分かと思っています。
競合ページでの表示は合っても良いと思いますが、トップページで競合の有無がすぐわかるのでわざわざ見に行かないと思います。

2. 一発でその日付のその時刻に飛ぶ機能について
これはすでに存在します。(競合した予約に限った機能ではないですが)
予約情報をクリックして予約詳細ダイアログを表示し、時刻部分をクリックすると該当時刻の番組表に飛びます。
リンク化されていないので非常に分かりにくいですが。

3. BSを横にずらしていくとCS番組表も見られる機能について
現状の**v1**では番組表の描画負荷を考えて放送波毎に番組表を分割しています。故に現状では実装不可能です。
ただし、**v2**では1ページで全ての放送波の番組表を表示できるようになっていますので、それで十分だと思います。
