### ISSUE TITLE
【質問】複数のEPGStation

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#359]
### 環境
* Version of EPGStation: 1.7.5
* Version of Mirakurun: 3.3.1
* Version of Node: 10.15.1
* Version of NPM: 6.4.1
* OS:Windows10
* Architecture: x64

### Issue
質問なのですが、一つのPCにて複数のEPGStationをnpm startしてポートで制御するのは可能なのでしょうか。
地デジBS専用とCS専用で使い分けたり、ドキュメンタリーとアニメで分けたりできるのかなと思いまして。

**Comment by l3tnun** [comment]
チューナ割当管理をそれぞれの EPGStation で行うので注意が必要ですが、可能です。

**Comment by ohmsa** [comment]
ありがとうございます。例えば　地デジとBS　と　CSだけ　みたいな分け方は可能なのでしょうか。

**Comment by l3tnun** [comment]
適当にソースをいじればできますが、現状のままではチューナ情報は mirakurun から受け取ったものをそのまま使用するので不可能です。

下記部分で必要なチューナだけ渡すようにすれば良いかなと思います。
https://github.com/l3tnun/EPGStation/blob/4b783410de15db18089bcfa3e5e21d209ab081dd/src/server/Model/Operator/Callbacks/EPGUpdateFinModel.ts#L41-L42

**Comment by ohmsa** [comment]
ありがとうございます。
