### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#368]
### 環境
* Version of EPGStation: `2.0.0`
* Version of Mirakurun: `3.4.1`
* Version of Node: `14.15.3`
* Version of NPM: `x.x.x`
* OS:alpine
* Architecture: x64

### Issue
下記の個所に誤字があります。
せっかくならこちらで修正をと思ったのですが、フロントの文言を管理している場所がわからなかったのでissueたてさせていただきます。  
`元ファイルをと同じ場所に保存する`  
![image](https://user-images.githubusercontent.com/13718335/104131231-82e3ff00-53b8-11eb-9df0-e956a3655884.png)

**Comment by l3tnun** [comment]
ご指摘ありがとうございます。
これはお恥ずかしい。修正しておきます。

**Comment by l3tnun** [comment]
修正されましたので、閉じます。
