### ISSUE TITLE
Nginxのリバースプロキシでの使用において「設定ダウンロードに失敗しました」のエラー

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#378]
### 環境
* Version of EPGStation: `2.0.3`
* Version of mirakc: `0.16.1`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS: Debian Buster
* Architecture: Raspberry Pi 4
* Nginx: `1.19.0`
### Issue
...
Nginxのリバースプロキシ下で使用すると「設定ダウンロードに失敗しました」のエラーが表示されます。この場合、録画ファイルのPLAYはできるもののSTREAMINGのボタンが表示されません。また「放映中」のメニューも表示されません。

また、下記の設定を行っていることも影響しているかもしれません。
```
subDirectory: epgstation
```

**Comment by piloppe** [comment]
https://github.com/l3tnun/EPGStation/blob/322fe463791de9d99818e56850b1e0195500ca10/src/model/service/api.ts#L174

nginxのリバースプロキシ時に追加するヘッダ項目「 X-Forwarded-Proto 」が、EPGSTationにて「 x-forwarded-proto 」しか検査していないようです。

**Comment by tobitti0** [comment]
`subDirectory: epgstation`
を設定してnginxでリバースプロキシ運用していますが、正常に作動しています。
nginxの設定が問題と思われます。
nginxのconf内容を投稿しましょう。

**Comment by l3tnun** [comment]
02e4fde466a5b5983091e6164cec6b99dfa10c9a にて ```X-Forwarded-Proto ``` 追加しました。
リバースプロキシ環境が手元に無いので効果があるかはわかりません。

**Comment by epgdatacapbon** [comment]
皆様
コメント、修正ありがとうございます。
```
proxy_set_header X-Forwarded-Proto $scheme
```
を
```
proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto
```
に変更してうまくいきました。
