### ISSUE TITLE
【要望】encode時に渡される環境変数の拡充

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#381]
encode時に子プロセスに渡される環境変数について、いくつか追加していただくことは可能でしょうか？
対象は"startAt","endAt","errorCnt","dropCnt","scramblingCnt"です。
現在はapi経由で取得できているので大きな問題ではありませんが、環境変数で渡されればより助かるかと思いました。
ご検討よろしくお願いします。

**Comment by l3tnun** [comment]
v2ブランチにて環境変数拡充しました。masterに反映されるまでお待ちください。

**Comment by l3tnun** [comment]
masterへマージしたので閉じます。
