### ISSUE TITLE
再生ボタンの設置

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#383]
### 環境
* Version of EPGStation: `2.0.2`
* Version of Mirakurun: `x.x.x`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:alpine(Docker)
* Architecture: x64

### Issue

すごく個人的な要望なのですが、録画したデータは視聴して消すだけでエンコードを行ったり番組詳細をほとんど利用しないので録画済み一覧ページから直接各録画ファイルを閲覧できるように再生ボタンの設置もしくは…クリック時のサブメニューに再生ボタンの設置の検討をお願いいたします。

**Comment by l3tnun** [comment]
ボタンの設定は難しそうですが、設定で録画番組クリック時の挙動を選択できるようにすれば実現できそうですね。
手が空いたら実装します。

**Comment by ohmsa** [comment]
v2になってUIがだいぶ変わりましたが、v1の時のUIもだいぶ使いやすかったです。
設定で録画一覧のUXをv1風にするというのも実現方法の一環かもしれません。

**Comment by 5ym** [comment]
into #521
