### ISSUE TITLE
二ヶ国語放送（デュアルモノ、ステレオ）を判別して、エンコードしたい

### ISSUE THREAD

**Issue by shirow-github** [l3tnun/EPGStation#388]
### 環境
* Version of EPGStation: `2.0.5`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS:Ubuntu 20.04 LTS
* Architecture: x64

### Issues
今、enc3.jsを使って二ヶ国語放送（デュアルモノ、ステレオ）をmp4へエンコードしようと試みています。
デュアルモノは初めから対応してるので、ステレオの場合を検討しています。
とりあえず、以下の様に書いてみました。

```
if` (isDualMono) {
    Array.prototype.push.apply(args, [
        '-filter_complex',
        'channelsplit[FL][FR]',
        '-map', '0:v',
        '-map', '[FL]',
        '-map', '[FR]',
        '-metadata:s:a:0', 'language=jpn',
        '-metadata:s:a:1', 'language=eng',
    ]);
    Array.prototype.push.apply(args, ['-c:a', 'ac3', '-ar', '48000', '-ab', '256k']);
} else {
    // audio dataをコピー
    Array.prototype.push.apply(args, [
        '-map', '0:0',
        '-map', '0:1',
        '-map', '0:2',
        '-metadata:s:a:0', 'language=jpn',
        '-metadata:s:a:1', 'language=eng',
    ]);
    Array.prototype.push.apply(args, ['-c:a', 'aac', '-ac', '2']);
}
```
英語と日本語が流れてくるニュースや、ディズニーアニメ等は変換できました。
しかし、これだと日本語だけのステレオ放送だとエンコードが出来ません。
それで、エンコード時に番組名に**[二]**があれば上記スクリプトを実行したいのですがどうすればよいのでしょうか？
また他に、何か良い方法があればご教授ください。

**Comment by tomo0611** [comment]
実行時に渡される環境変数[HALF_WIDTH_NAME](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#encode)を使ってタイトルに[ニ]があるかで分岐してあげればいいと思います


一応、[ニ]が無い副音声なども(あるかは知りませんが)含めたければ [Ubuntu ffmpegでTSファイルの複数音声(２ヶ国語)を処理する](http://82.hatenablog.com/entry/2016/03/15/170304) の記事が参考になると思います

**Comment by l3tnun** [comment]
https://github.com/l3tnun/EPGStation/issues/244#issuecomment-468928770 を参照してください

**Comment by shirow-github** [comment]
とりあえず、こういう感じに書いてみました。

```
// 二ヶ国語放送
if (name.indexOf('[二]') != -1) {
    if (isDualMono) {
        Array.prototype.push.apply(args, [
            '-filter_complex',
            'channelsplit[FL][FR]',
            '-map', '0:v',
            '-map', '[FL]',
            '-map', '[FR]',
            '-metadata:s:a:0', 'language=jpn',
            '-metadata:s:a:1', 'language=eng'
        ]);
    } else {
        Array.prototype.push.apply(args, [
            '-map', '0:0',
            '-map', '0:1',
            '-map', '0:2',
            '-metadata:s:a:0', 'language=jpn',
            '-metadata:s:a:1', 'language=eng'
        ]);
    }
}

// audio dataをコピー
Array.prototype.push.apply(args, ['-c:a', 'ac3', '-ar', '48000', '-ab', '256k']);
```
二ヶ国語放送(デュアルモノ、ステレオ)と、日本語放送(ステレオ)の3パターンで試した所、とりあえず期待通りの動作となりました。
このまま暫く様子を見てみます。
ありがとうございました。

**Comment by l3tnun** [comment]
解決したようなので閉じます
