### ISSUE TITLE
録画終了時に実行する外部コマンドにて環境変数RECPATHが正しく取得できない

### ISSUE THREAD

**Issue by vonvonhero** [l3tnun/EPGStation#390]
### 環境
* Version of EPGStation: `2.0.5`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS: Ubuntu 18.04 LTS
* Architecture: x64

### Issue
recordingFinishCommand を設定し、録画終了時にシェルスクリプトを実行していますが、
スクリプト内で環境変数RECPATHを参照すると "[object Promise]"と返ってきてしまいます。

該当のスクリプトはv1の時から同じものを使用しており、v1では意図通り動作していましたが
v2導入以降にRECPATHが取得できなくなってしまいました。

録画ファイルのフルパスの環境変数名はv1->v2で変更ないようですが、取得のタイミング等なにか制限があるのでしょうか？

なお、別件のプルリクエストの"recordingStartCommand実行時の環境変数一覧"でも同様に"RECPATH": "[object Promise]",　となっているように見え、私の環境依存ではないように思えたため質問させていただきました。
https://github.com/l3tnun/EPGStation/pull/384

**Comment by l3tnun** [comment]
バグですね。
修正します。

**Comment by l3tnun** [comment]
修正完了しましたので閉じます。
