### ISSUE TITLE
[質問] v2でのAPIによる番組検索結果を取得方法について

### ISSUE THREAD

**Issue by pluto-charon83** [l3tnun/EPGStation#391]
### 環境
* Version of EPGStation: `2.0.5`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS: Ubuntu 16.04 LTS
* Architecture: x64

### Issue

APIの​/schedules​/searchを使って番組検索結果を取得しようとしているのですが、うまくいかないため質問させてください。
V1で使っていたcurlコマンドがV2では動作しなかったため、http://<hostname>:<port>/api/debugを参照しながら仕様の違いを理解しようとしていますが、うまく理解できていません。

つきましては、検索結果無しとなっても構わないので、debug等適当な検索ワードでエラーなく番組検索結果を取得できるcurlコマンドの例を教えてもらえないでしょうか？

現状では、http://<hostname>:<port>/api/debugにある下記コマンド例をそのまま実行すると"code":500,"message":"Internal Server Error","errors":"ER_PARSE_ERRORとなります。

curl -X POST "http://localhost:8888/api/schedules/search" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"option\":{\"keyword\":\"string\",\"ignoreKeyword\":\"string\",\"keyCS\":true,\"keyRegExp\":true,\"name\":true,\"description\":true,\"extended\":true,\"ignoreKeyCS\":true,\"ignoreKeyRegExp\":true,\"ignoreName\":true,\"ignoreDescription\":true,\"ignoreExtended\":true,\"GR\":true,\"BS\":true,\"CS\":true,\"SKY\":true,\"channelIds\":[0],\"genres\":[{\"genre\":0,\"subGenre\":0}],\"times\":[{\"start\":0,\"range\":0,\"week\":0}],\"isFree\":true,\"durationMin\":0,\"durationMax\":0,\"searchPeriods\":[{\"startAt\":0,\"endAt\":0}]},\"isHalfWidth\":true,\"limit\":0}"

この原因はこのコマンド例のisHalfWidthのひとつ前の } が余計なのかと思い削除したのですが、今度はStatusCode=400で結果を取得できていません。必須ではないと思われるオプションを削る等試しているのですがうまくいっておりません。。

お手数ですがよろしくお願いいたします。

**Comment by l3tnun** [comment]
`/api/​/schedules​/search` についてですが、仕様が複雑なので OpenAPI(Swagger) では全てを適切に表現できていません。
そのため、入力されたパラメータについては独自にチェックをかけています。

パラメータの詳しい仕様はドキュメント化できていませんのでソースを読んでください。
該当する部分は下記になります。

https://github.com/l3tnun/EPGStation/blob/a75a65ef20500b4ab12928bd611deba7ab617d63/src/model/operator/ReserveOptionChecker.ts#L45-L148

一番確実なのは epgstation の検索ページで実際に検索し、その際の /api/​/schedules​/search をブラウザの開発ツールで見てみることです。
下記の画像は chrome のデベロッパーツールで確認した様子です。

![Screenshot from 2021-01-18 17-29-33](https://user-images.githubusercontent.com/16516088/104890353-cf2fd000-59b2-11eb-955b-55046dc4526a.png)

**Comment by l3tnun** [comment]
>つきましては、検索結果無しとなっても構わないので、debug等適当な検索ワードでエラーなく番組検索結果を取得できるcurlコマンドの例を教えてもらえないでしょうか？

忘れてました。

```sh
curl -X POST "http://localhost:8888/api/schedules/search" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"option\":{\"keyword\":\"news\",\"name\":true,\"GR\":true,\"times\":[{\"week\":127}]},\"isHalfWidth\":true,\"limit\":100}"
```

**Comment by pluto-charon83** [comment]
早速のご回答ありがとうございます、非常に助かりました。
取り急ぎ、教えていただいたコマンドとchromeのデベロッパーツールで検索結果を確認できました。

詳しい仕様の違いは該当部分のソースを確認してみます
