### ISSUE TITLE
【要望】非エンコードモード動作時の環境変数DIRについて

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#392]
自前のエンコードスクリプトにパラメーターを渡すため、v1では非エンコードモード時にdirectoryに設定した文字列が環境変数DIRに格納される機能を利用していました。
[【要望】録画後のコマンドについて](https://github.com/l3tnun/EPGStation/issues/73#issuecomment-381413559) 
しかしv2では非エンコードモード時に環境変数DIRが空白となってしまうため、必要なパラメーターを渡せなくなってしまいました。

v2でも非エンコードモード時にsub directoryに設定した文字列を環境変数DIRに格納するようにしてもらえませんでしょうか？
ご検討よろしくお願い致します。

**Comment by l3tnun** [comment]
作り変えた時に完全に抜けていますね。
追加します。

**Comment by l3tnun** [comment]
再度機能が追加されたので閉じます。

**Comment by cuckoozero** [comment]
正常動作を確認しました。
素早い対応ありがとうございました！
