### ISSUE TITLE
npm run buildでnpm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by palayo** [l3tnun/EPGStation#396]
### 環境
* Version of EPGStation: `2.0.7`
* Version of Mirakurun: `3.5.0`
* Version of Node: `12.20.1`
* Version of NPM: `6.14.11`
* OS: Raspbian GNU/Linux 10
* Architecture: arm (Raspberrypi4 4GB)

### Issue
npm run buildでエラーになります。
rm -rf node_modules package-lock.json
を実行して再度npm installしましたが、結果は変わらず、
対応方法が分かりません。
原因と対処が分かりましたら教えてください。

### 実効コマンドとエラー
[コマンド&エラー.txt](https://github.com/l3tnun/EPGStation/files/5839611/default.txt)

## ログ </home/pi/.npm/_logs/2021-01-20T01_24_58_642Z-debug.log>
[2021-01-20T01_24_58_642Z-debug.log](https://github.com/l3tnun/EPGStation/files/5839614/2021-01-20T01_24_58_642Z-debug.log)

**Comment by tobitti0** [comment]
関係性は不明ですけど、Node古くないですか。
`Node.js : ^14.6.0`
とReadme.mdに記載されています。
上げて試してみてはどうでしょうか。

**Comment by l3tnun** [comment]
@tobitti0 さんのおっしゃる通りで、まず node のバージョンを上げましょう。

> rm -rf node_modules package-lock.json

`node_modules` を削除して再インストールするのは良いですが、`package-lock.json` を削除するのはやめてください。
何を見てこのような対処に至ったのでしょうか？

**Comment by palayo** [comment]
早いご回答ありがとうございます。
その後Node.jsのバージョンを上げて再実施したのですが同じエラーが発生しております。
一度OSのインストールからやり直したのですが、それでも同じ結果になりました。
対処が分からず困っておりますが、何かお分かりになりましたらご回答いただけないでしょうか。

[log.txt](https://github.com/l3tnun/EPGStation/files/5846438/log.txt)
[2021-01-21T02_24_15_873Z-debug.log](https://github.com/l3tnun/EPGStation/files/5846475/2021-01-21T02_24_15_873Z-debug.log)
[2021-01-21T02_24_15_939Z-debug.log](https://github.com/l3tnun/EPGStation/files/5846440/2021-01-21T02_24_15_939Z-debug.log)

なお、package-lock.jsonはエラーの対処をググっている中で下記のような情報がありましたので、
削除を行いました。削除すべきではないと理解しましたので、OS再インストール後は触らないようにしています。
<<https://qiita.com/wafuwafu13/items/2fe43414aa6e1899f494>>
<<https://qiita.com/mdrq/items/b815bd360d46d22ea6d8>>  package-lock.json（場合によっては node-gyp も）を削除
<<https://qastack.jp/programming/42308879/npm-err-code-elifecycle>>  package-lock.jsonファイルも削除します。

**Comment by palayo** [comment]
現在のバージョンは以下の通りです。
pi@r14:~/EPGStation$ node -v
v14.15.4
pi@r14:~/EPGStation$ npm -v
6.14.10

**Comment by masnagam** [comment]
@palayo 
多くの場合，エラーログに問題の詳細やヒントが存在します．エラーログをよく確認する習慣を身につけることで，いくつかの問題は自力で解決できるようになると思います．

エラーログを確認するとわかりますが，同じエラーではありません．

default.txt
```text
src/model/service/ServiceServer.ts(160,46): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'RequestHandler<Response<never, never, number>>' is not assignable to parameter of type 'Application'.
...
```

これは恐らくnode.jsのバージョンが古いことが原因で問題が起きています．

log.txt
```text
sh: 1: vue-cli-service: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
...
```

node.jsのバージョンを更新したので最初の問題は解消したようですが，別の問題が起きています．
メッセージを見る限りvue-cli-serviceが存在していないため，ビルドが止まったようです．
vue-cli-serviceがなぜ存在しないのかを調べていけば，問題は解決するだろうと思います．

推測ですが，clientフォルダー内で，`npm install`を実行していないのではないでしょうか？
https://github.com/l3tnun/EPGStation/blob/master/doc/linux-setup.md#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97 には以下のように書かれています．

```text
$ git clone https://github.com/l3tnun/EPGStation.git
$ cd EPGStation
$ npm run all-install  # これを実行すると，clientフォルダー内でnpm installが実行される
$ npm run build
```

実際，以下のように実行したら，同じエラーになりました．

```console
$ docker run --rm -it --entrypoint=bash node:14
# 以下，コンテナー内で実行
$ git clone --depth=1 https://github.com/l3tnun/EPGStation.git
$ cd EPGStationi
$ npm i --no-save
$ npm run build
...
> epgstation-client@2.0.7 build /EPGStation/client
> vue-cli-service build

sh: 1: vue-cli-service: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
...
```

個人的には，インストール手順の間違いを回避する意味でも，可能な限りDockerを使用したほうが良いだろうと思います．
https://github.com/l3tnun/docker-mirakurun-epgstation/blob/v2/epgstation/alpine.Dockerfile のように自力でffmpegをビルドすることも，https://github.com/mirakc/mirakc/blob/master/docker/testbed/epgstation/Dockerfile のように出来合いのパッケージを使うことも可能です．デバイスファイルもコンテナーにマップ可能なので，ハードウェアでデコードすることも原理的には可能です（試したことはありませんが）．

**Comment by masnagam** [comment]
@palayo 
あと，`ELIFECYCLE`で検索すると類似もしくは関連問題が見つかります．
https://github.com/l3tnun/EPGStation/issues?q=is%3Aissue+ELIFECYCLE+is%3Aopen

Raspberry Pi 4 (4GB)なので発生しないと思いますが，メモリーの少ない環境にインストールする場合には，クローズ済みの #374 に注意してください．この問題は自力でビルドする場合に発生する問題なので，ビルド済みDockerイメージを使用する場合には発生しません．

**Comment by stu2005** [comment]
横から失礼します
docker使うのであればラズパイの場合ubuntu server 20.04.1 LTS arm64の方がいいと思います。mariadbのdockerイメージがarm64にしか対応していないからです。

**Comment by masnagam** [comment]
@stu2005 
確かにofficial imageのmariadbは64bit cpuしかサポートしていませんが，[linuxserver/mariadb](https://hub.docker.com/r/linuxserver/mariadb)はlinux/armをサポートしています．私は使用したことはありませんが，100M以上pullされているので，多分問題なく動くものと思われます．

**Comment by stu2005** [comment]
なるほど。armhf用のがありましたか。

**Comment by masnagam** [comment]
Dockerfileを確認していないので分かりませんが，armhf（hard-float）ではなくarmel（soft-float）かもしれません．Raspberry Pi 4はどちらのバイナリーでも実行可能なので，多分動くだろうと思っています．

**Comment by l3tnun** [comment]
概ね .@masnagam のおっしゃる通りで、正しい方法でインストールしてください。
readmeの内容が正しく理解できていれば、osのサイズまで手戻りが発生することもないはずです。
あと、私個人としましても docker を使用する事をおすすめします。

**Comment by stu2005** [comment]
linuxserver/mariadbで動作することを確認しました。現在も安定稼働しています。

**Comment by l3tnun** [comment]
おそらく解決していると思われますので閉じます
