### ISSUE TITLE
【提案】OS連動のダークテーマ設定

### ISSUE THREAD

**Issue by sckemu** [l3tnun/EPGStation#404]
### 環境
* Version of EPGStation: `2.0.8`
* Version of Mirakurun: `3.5.0`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS: Ubuntu 20.10
* Architecture: x64

### Issue
いつも便利に使わせていただいております。
ダークテーマのデフォルト設定をOSと連動させるのはどうでしょうか。
CSSの[prefers-color-scheme](https://developer.mozilla.org/ja/docs/Web/CSS/@media/prefers-color-scheme)が利用できそうです。

ドクターストップとのことで、お大事になさってください。

**Comment by l3tnun** [comment]
実装上難しいこともないので、手が空いたら実装したいですね。

**Comment by l3tnun** [comment]
#421 にて対応されたので閉じます。
