### ISSUE TITLE
【質問】enc.jsにて生成されるargsの確認方法

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#406]
### 環境
* Version of EPGStation: `1.7.5`
* Version of Mirakurun: `3.5.0`
* Version of Node: `10.15.0`
* Version of NPM: `6.4.1`
* OS: Windows10
* Architecture: x64

### Issue
あまりにも初歩的過ぎて申し訳ないのですが、エンコードパラメータの切り替えについてどなたかご教示ください。
現在は

config.jsonにて
```
    "encode": [
        {
            "name": "H265",
            "cmd": "C:\\PROGRA~1\\nodejs\\node.exe  C:\\EPGStation\\config\\enc.js HD24p",
            "suffix": ".mp4"
        },
```
と記述し、
enc.jsにて
```
if (process.argv[2] == 'HD24p'){
 Array.prototype.push.apply(args,[
           'A', 'B',
           'C', 'D'
        ]);
}
```
のようにパラメータを分岐させています。

ffmpegへ渡すエンコードパラメータとして
`.\ffmpeg.exe -y -i test.ts -ignore_unknown -c:v hevc_nvenc -b_ref_mode 2 -filter_complex "dejudder,fps=30000/1001,fieldmatch,decimate,scale=1280:720,fps=24000/1001" -g 1200 -b:v 0 -cq 27 -rc-lookahead 32 -c:a copy output.mp4`
を渡したいばあい、
`-ignore_unknown -c:v hevc_nvenc -b_ref_mode 2 -filter_complex "dejudder,fps=30000/1001,fieldmatch,decimate,scale=1280:720,fps=24000/1001" -g 1200 -b:v 0 -cq 27 -rc-lookahead 32 -c:a copy`
とすればよいのでしょうか。エンコードパラメータ自体はffmpegに与えて出力を確認済みですが、エンコードが始まりません。

重ね重ね初歩的で恐縮ですが、
-実際にffmpegに与えられるargsの値をlog出力
する方法ありますでしょうか。

[enc.js.txt](https://github.com/l3tnun/EPGStation/files/5925550/enc.js.txt)

[2021-02-04T20:26:38.319] [INFO] system - SocketIo Server has started.
[2021-02-04T20:26:38.321] [INFO] system - server listening on 8888
[2021-02-04T20:26:38.322] [INFO] system - SocketIo listening on 8889
[2021-02-04T20:27:01.355] [INFO] system - push encode: C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ.ts 4
[2021-02-04T20:27:01.357] [INFO] system - encode start: C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ.ts QSV|720/24p
[2021-02-04T20:27:01.366] [INFO] system - create new encode child: 1612438021366
[2021-02-04T20:27:01.475] [INFO] system - code { code : 1, signal: null }
[2021-02-04T20:27:01.475] [ERROR] system - encode failed: C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ-24p.mp4
[2021-02-04T20:27:01.475] [INFO] system - delete encoding file: C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ-24p.mp4
[2021-02-04T20:27:02.485] [ERROR] system - delete encoding file error: C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ-24p.mp4
[2021-02-04T20:27:02.485] [ERROR] system - ENOENT: no such file or directory, unlink 'C:\EPGStation\recorded\2020年11月01日22時49分00秒-プレマップ-24p.mp4'

**Comment by masnagam** [comment]
私はenc.jsを使っていないので間違っているかもしれませんので，参考程度に読んでいただければと思います．

まず，GitHubにあるenc.jsのサンプルコードにも添付されているenc.js.txtにも，以下のようなコードが見つかります．
https://github.com/l3tnun/EPGStation/blob/master/config/enc.js#L58

つまり，`args`の内容がどこかにerrorレベルのログとして出力されているように見えます．
それが「どこ」なのかは，残念ながら私には分かりません．
多分，@ohmsa さんのログ設定にも依存するだろうと思います．

もし，`console.error()`の出力先が分かれば，以下のようなコードを追加することで，`process.argv`の内容を見ることができ，問題の１つが解決できると思われます．

```js
console.error(process.argv);
```

最後に，`args`に追加している引数についてです．なお，以下は`process.argv[2]`が`'fHD24p'`であると仮定して説明していますが，上記のような方法で確認してみないことには，私にはあっているのかどうか分かりません．

```js
    if (process.argv[2] == 'fHD24p'){
        Array.prototype.push.apply(args,[
            '-filter_complex', ' "dejudder,fps=30000/1001,fieldmatch,decimate,fps=24000/1001" '
        ]);
```

これだと多分，以下のようなコマンドラインと同等になると思われます．

```shell
ffmpeg (略) -filter_complex ' "dejudder,fps=30000/1001,fieldmatch,decimate,fps=24000/1001" '
```

このコマンドが動作するかどうかは，私は確認していません．
もし，動かないなら，以下のようにするのが正しいと思います．

```js
    if (process.argv[2] == 'fHD24p'){
        Array.prototype.push.apply(args,[
            '-filter_complex', 'dejudder,fps=30000/1001,fieldmatch,decimate,fps=24000/1001'
        ]);
```

シェルやcmd.exeなどのコマンドインタープリターは，コマンドラインを解析し，配列（process.argvのような）に結果を格納します．そのときに，`"..."`のように引用符で囲われたものは１つの文字列として扱われます．

配列`args`の要素はコマンドライン解析後の配列と同じなので，`' "..." '`のように引用符を含める必要はないものと思われます．

**Comment by cuckoozero** [comment]
自分もffmpegで四苦八苦しています。
ffmpegのオプションで"-report"を付けるとログファイルが生成されますよ。
ログの冒頭付近にエンコードオプションが記録されていたように思います。

**Comment by ohmsa** [comment]
返信ありがとうございます。おっしゃるように変更しましたが、エンコードされないですね……
Log関係のマニュアルもありますが、Encodeがこちらの環境では入っておらず、おそらくはv1系のマニュアルではないようです。
https://github.com/l3tnun/EPGStation/blob/master/doc/log-manual.md
困りました。

**Comment by regppe** [comment]
v1系のマニュアルを見たいのであれば、そのサイトにあるブランチを「master」から「v1」に切り替えれば見られます。
ちなみに、私もv1系の時にffmpegで四苦八苦してまして、その時にEPGStationのログの設定を以下のようにしてました。
カテゴリー"system"のレベルを"debug"にすればffmpegのログが表示されるようになるかと思います。

```
{
    "appenders": {
        "system": {
            "type": "file",
            "maxLogSize": 10485760,
            "backups": 10,
            "filename": "%ServiceSystem%",
            "pattern": "-yyyy-MM-dd"
        },
        "access": {
            "type": "file",
            "maxLogSize": 1048576,
            "backups": 3,
            "filename": "%ServiceAccess%",
            "pattern": "-yyyy-MM-dd"
        },
        "stream": {
            "type": "file",
            "maxLogSize": 10485760,
            "backups": 10,
            "filename": "%ServiceStream%",
            "pattern": "-yyyy-MM-dd"
        },
        "console": { "type": "console" },
        "stdout": { "type": "stdout" }
    },
    "categories": {
        "default": { "appenders": [ "console", "stdout" ], "level": "info" },
        "system": { "appenders": [ "system", "stdout" ], "level": "debug" },
        "access": { "appenders": [ "access" ], "level": "info" },
        "stream": { "appenders": [ "stream", "stdout" ], "level": "debug" }
    }
}
```

**Comment by scandium-j** [comment]
`const args = '-y';`
↓
`const args = ['-y'];`

`'-rc-lookagead'`
↓
`'-rc-lookahead'`

配列になっていないのとタイプミスが原因じゃないかと思いますがどうでしょうか？

**Comment by scandium-j** [comment]
失礼。
ログに関してでしたね。
[ここ](https://github.com/l3tnun/EPGStation/tree/v1#epgstationlogsservice)を見るとエンコードのログはServiceの`system.log`に出力されるみたいなので`config/serviceLogConfig.json`のSystemのlevelを`trace`にすると詳細がわかるかもしれません。

**Comment by l3tnun** [comment]
enc.js に渡される引数は `process.argv` を確認してください。
enc.js 内で `ffmpeg` に渡される引数については以下の部分にログにて出力されます。

https://github.com/l3tnun/EPGStation/blob/899541f2b6d716453a30b9c1589c76602b8d902a/config/enc.js#L54-L58

ログの出力設定については .@regppe さんのおっしゃるとおり
`config/serviceLogConfig.json` の `system` のレベルを debug に変更すると `logs/Service/system.log` に出力されるようになっています。

`ffmpeg` に引数を正常に渡せない要因としてよくあることは .@masnagam さんが以下でおっしゃった通りです。

> シェルやcmd.exeなどのコマンドインタープリターは，コマンドラインを解析し，配列（process.argvのような）に結果を格納します．そのときに，`"..."`のように引用符で囲われたものは１つの文字列として扱われます．
> 
> 配列`args`の要素はコマンドライン解析後の配列と同じなので，`' "..." '`のように引用符を含める必要はないものと思われます．

これ以上の情報は epgstation としてありませんので、この issue を閉じます。

**Comment by ohmsa** [comment]
皆さま、ありがとうございました。
””で囲わずべた書きすることでうまくいきました。

` "cmd": "%FFMPEG% -y -i %INPUT% -ignore_unknown -c:v hevc_nvenc -b_ref_mode 2 -filter_complex dejudder,fps=30000/1001,fieldmatch,decimate,scale=1280:720,fps=24000/1001 -g 1200 -b:v 0 -cq 27 -rc-lookahead 32 -c:a aac -ar 48000 -ab 192k -ac 2 %OUTPUT%",`

他の人の参考になるように残しておきます。
（&& powercfg /s sheme_maxとか追加しておくとエンコード終了後省電力モードに切り替わったりしませんかね）
