### ISSUE TITLE
【質問】sqliteで正規表現モジュールを使用しない場合のconfig.yml

### ISSUE THREAD

**Issue by paramounttom** [l3tnun/EPGStation#410]
### 環境
* Version of EPGStation: `2.0.8`
* Version of Mirakurun: `3.5.0`
* Version of Node: `v10.23.3`
* Version of NPM: `6.14.1`
* OS:CentOS 7
* Architecture: x64

### Issue
conf-manual.md について

comfig.ymlの書き方で sqliteの設定をする際、
正規表現モジュールを使用しない場合はextensionsがいらないので、
この子プロパティについて必須=yesではないと思いますがいかがでしょうか。
結局extensionsの指定を外すとcomfig.ymlが解釈され起動できました。

**Comment by l3tnun** [comment]
あーなるほど、conf-manual.md には `SQLite3 の接続設定（SQLite3 使用時は必須）`と書いてありますが、実際は違いますね。
ご指摘の通り、このプロパティや子プロパティは必須ではないです。
修正しますね。

**Comment by l3tnun** [comment]
v2ブランチにて修正しました。
master への反映は少々お待ちください。

**Comment by paramounttom** [comment]
早速のご対応ありがとうございました。

**Comment by l3tnun** [comment]
master へ反映したので閉じます。
