### ISSUE TITLE
【要望】番組表の初期入力フォーカスについて

### ISSUE THREAD

**Issue by sandhill2000** [l3tnun/EPGStation#415]
### 環境
* Version of EPGStation: `2.0.7`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.25.4`
* Version of NPM: `6.14.10`
* OS: UbuntuServer 20.04LTS
* Architecture: x64
※docker-mirakurun-epgstationを使用

### Issue
ノートPC上のChromeブラウザでEPGStationの番組表を利用しています。
画面にタッチパネル機能がない場合、カーソルキーでスクロールさせるのが
番組表を使いやすいのですが、最初の入力フォーカスが番組表にないので
毎回番組表かスクロールバーをクリックしてフォーカスを移す必要があります。

番組表の描画直後に、番組表に入力フォーカスを設定するようにできないでしょうか。
また予約等のダイアログ表示を操作した直後も番組表にフォーカスが戻るようになると
良いかと思います。

タッチパネルメインの場合や、マウスがメインのユーザなら現状で問題ないと思いますが・・

**Comment by l3tnun** [comment]
対応しましたので閉じます。

**Comment by sandhill2000** [comment]
迅速な対応に感謝です！
