### ISSUE TITLE
ルール登録時の不具合

### ISSUE THREAD

**Issue by retriever-wanwan** [l3tnun/EPGStation#416]
### 環境
* Version of EPGStation: `2.0.12`

### Issue

ルール登録時に不具合がありましたので修正箇所をお知らせします。
お手すきの際に反映していただけると助かります。

```
# cd client/src/model/state/search
# diff SearchState.ts SearchState.ts.org
418c418
<                 keyCS: !!searchOption.ignoreKeyCS,
---
>                 keyCS: !!searchOption.ignoreKeyRegExp,
```

**Comment by l3tnun** [comment]
報告ありがとう御座います。
ここまでわかっているのであればプルリクでも大丈夫ですよ。
今回はこちらで修正しますね。

**Comment by l3tnun** [comment]
修正完了しましたので閉じます。

**Comment by retriever-wanwan** [comment]
ご対応ありがとうございました。
githubはさわったばかりでしたので機会があれば追々プルリクなども
使わせていただきたいと思います。
EPGStationは便利に使わせていただいていますので今後も期待して
います。
