### ISSUE TITLE
recordedTmpからRecordedにファイル移動する際、ファイルコピー&削除でなくファイル移動してほしい

### ISSUE THREAD

**Issue by sandhill2000** [l3tnun/EPGStation#417]
### 環境
Version of EPGStation: 2.0.7
Version of Mirakurun: 3.5.0
Version of Node: 14.25.4
Version of NPM: 6.14.10
OS: UbuntuServer 20.04LTS
Architecture: x64
※docker-mirakurun-epgstationを使用

### Issue
録画中ディレクトリ(recordedTmp)と録画済みディレクトリ(Recorded)が同一HDDドライブの条件で、録画が同時に複数走っている状況では録画1本終了した際に起こるファイルコピー&削除のドライブ負荷が大きいです。
同一ドライブ下ではファイルコピーせず移動で済ませられる指定ができるようにならないでしょうか。

**Comment by l3tnun** [comment]
現状、recordedTmp を同一ドライブで使用することを想定して作られていないです。
ぼちぼち変更します。

**Comment by l3tnun** [comment]
最新の master にて対応されました。
rename -> copy & delete と試行するように変更されています。

**Comment by sandhill2000** [comment]
ありがとうございました。
