### ISSUE TITLE
除外キーワードを含まないが、詳細情報の無い番組が検索除外されてしまう

### ISSUE THREAD

**Issue by nanamaki** [l3tnun/EPGStation#422]
### 環境
* Version of EPGStation: `2.1.1`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.0`
* Version of NPM: `6.14.11`
* OS: Ubuntu 20.04.2
* Architecture: x64
* docker-mirakurun-epgstation を利用

### Issue
詳細情報に出演者を書いている番組をルール予約するために検索オプションで詳細もチェックしており、
例えばSTU48の出演する番組を録画したくてSTUという検索キーワードを設定した際、詳細まで含めていると
STUDIO 等よく使われるような英単語を入れている番組も引っかかってしまうため、除外キーワードに
入れて運用しようとしています。

実際に上記のようなキーワードで検索すると、除外キーワードの詳細オプションを選択した場合、
extended の無い(と思われる)番組が、除外キーワードを含んでいないにも関わらず検索対象から
外れたような挙動に見えました。
下記pic1で除外キーワードの詳細オプションをチェックしていないときに検索対象になった
「[HV]STU48 イ申テレビ シーズン1【リクエスト】#3」が、除外キーワードの詳細オプションを
チェックした際にはpic2のように検索対象から外れました。

除外キーワードを含んでいなければ、詳細情報の有無は関係なく検索対象になって欲しいのですが、
動作についてご確認いただけますでしょうか。

pic1: 
![SearchWithoutExtended](https://user-images.githubusercontent.com/20396021/109516836-ff0edf00-7aeb-11eb-9007-e3af9283e9bd.png)
予約情報をAPIで取得した時の該当番組部分
```
    {
      "id": 121,
      "isSkip": false,
      "isConflict": false,
      "isOverlap": false,
      "allowEndLack": true,
      "isTimeSpecified": false,
      "isDeleteOriginalAfterEncode": false,
      "channelId": 3239123608,
      "startAt": 1614792900000,
      "endAt": 1614793800000,
      "name": "せとチャレ!STU48",
      "ruleId": 8,
      "programId": 323912360812245,
      "description": "番組の危機!緊急チャレンジ 第1弾",
      "extended": "◇番組内容①\nせとチャレ!最大の危機!\r\n予定していた「旅ロケ」が中止になり、たった1日で広島にて撮影をしなければならない事態に…。\r\n緊急招集されたのは、STU48のMC「そらは」に「沖ちゃん」、そしてゲストのシンガーソングライター・HIPPYさん!\r\n事情を聞きつけたHIPPYさんが持ち込み企画を用意し、3本分の撮り切るチャレンジを敢行します!\n◇番組内容②\n1本目のチャレンジは、あの番組リスペクト企画。\r\nSTU48の新曲リリースを記念して、メンバー同士でインタビューを決行!何か気づけばHIPPYさんがボタンを押してVTRを強制ストップし、その場で公開反省会がスタートする…というどこかで聞いたことのある収録が行われます!\r\n果たして、無事にSTU48の新曲の魅力をお届けできるのか…?そして、そもそも企画は成立するのか…??\n◇出演者\n【出演】\r\nSTU48(MC信濃宙花・沖侑果)\r\n【ゲスト】\r\nHIPPY",
      "genre1": 5,
      "subGenre1": 2,
      "videoType": "mpeg2",
      "videoResolution": "1080i",
      "videoStreamContent": 1,
      "audioSamplingRate": 48000
    },
    {
      "id": 122,
      "isSkip": false,
      "isConflict": false,
      "isOverlap": false,
      "allowEndLack": true,
      "isTimeSpecified": false,
      "isDeleteOriginalAfterEncode": false,
      "channelId": 700293,
      "startAt": 1614794400000,
      "endAt": 1614796200000,
      "name": "[HV]STU48 イ申テレビ シーズン1【リクエスト】#3",
      "ruleId": 8,
      "programId": 70029351840,
      "description": "STU48メンバーたちが番組からの愛のムチ=「ムチャぶり」を通じて地元瀬戸内の魅力を伝えます!",
      "genre1": 5,
      "subGenre1": 15,
      "videoType": "mpeg2",
      "videoResolution": "1080i",
      "videoStreamContent": 1,
      "audioSamplingRate": 48000
    },
```
pic2:
![SearchWithExtended](https://user-images.githubusercontent.com/20396021/109516848-03d39300-7aec-11eb-8d65-74930de4ed2d.png)

**Comment by l3tnun** [comment]
報告ありがとうございます。
こちらの環境でも現象の確認できました。

原因が謎ですが、検索時の SQL のクエリーが何か間違っているのかなあと思います。
修正までしばしお待ちください。

**Comment by retriever-wanwan** [comment]
SQLを確認しましたところ、
`((((((halfWidthName like '%STU%')))) or((((halfWidthDescription like '%STU%')))) or((((halfWidthExtended like '%STU%'))))))`
で抽出されたレコードに対して
`((not ((((((halfWidthName like '%STUDIO%')))) or((((halfWidthDescription like '%STUDIO%')))) or((((halfWidthExtended like '%STUDIO%'))))))))`
をandで実行する際に、extendedが存在しない場合はhalfWidthExtendedがNULLとなっており、NULLに対して実行するとレコードが抽出されなくなるようです。ちなみに、halfWidthExtendedが""だと正常に抽出されるようです。
コードの修正までは追いきれなかったためお知らせまで。

**Comment by nanamaki** [comment]
現象確認ありがとうございます。

私も素人ながらに色々調べてみたのですが、ルールにマッチする番組検索のクエリーで
https://qiita.com/daisei-yoshino/items/08bd1c936c33c5e5c10a
こちらのような状況になっていて、retriever-wanwanさんが仰るような抽出されない状態に
なっているのではないかと思います。

流石に name が無い番組は見つからなかったので、description が無く extended にのみ情報を
載せている番組で除外キーワードの概要オプションにチェックを入れたところ、同じように
意図せず検索除外されました。halfWidthDescription も考慮する必要がありそうです。

**Comment by tobitti0** [comment]
おそらくですが、下記該当部分にてnullを格納しているので、そこを変更すれば検索自体はできるようになりそうです。

ただ、他のコードではhalfWidthExtendedやhalfWidthDescriptionがnullであるかどうかで分岐しているところがあるので、単純にnullを""にする場合は他の部分のコード修正も必要ですね。

https://github.com/l3tnun/EPGStation/blob/4017a22b840671a4defa668dbb9c3139bb6eca95/src/model/db/ProgramDB.ts#L186-L204

**Comment by l3tnun** [comment]
あーなるほど、v1でも同じ症状に悩まされた記憶あります。
どうやって解決したか忘れてましたが、確かに null な事が原因でした。

**Comment by nanamaki** [comment]
正規表現マッチングでも not likeと同様に検索除外されたので、その部分も含めてSQLクエリで
比較対象の null を空文字にするようにしてみました。
上記修正を適用したDockerイメージをビルドしなおして手元の環境で確認してみましたところ、
イメージ入れ替え前後で少なくとも予約の減少は無く、除外キーワードも意図した検索動作に
なっているように見えます。

ご確認お願いします。

**Comment by l3tnun** [comment]
master へ反映させたので閉じます。
お疲れ様でした。
