### ISSUE TITLE
/api/iptv/epg.xml内の文字エラー

### ISSUE THREAD

**Issue by shun-sa** [l3tnun/EPGStation#425]
### 環境
* Version of EPGStation: [`docker-mirakurun-epgstation`](https://hub.docker.com/layers/l3tnun/epgstation/master-debian/images/sha256-9f875cdd85ff725a0cdfe1207ee8c7771381be61b48df33989c35924a9748963?context=explore)
* Version of Mirakurun: `-`
* Version of Node: `-`
* Version of NPM: `-`
* OS:ubuntu20.04
* Architecture: x86_64

### 質問
xteveからXMLEPGを取得していますが、フォーマットエラーにより取得に失敗します。(3/10 0時ごろから現在にかけて)
APIを直接確認すると、文字� (バイト列 efbfbd) に対してのエラーを見つけました。ブラウザで見る限りはxmlとして破損しているような表示です。
変換する文字がない場合に割り当てるようですが、EPGStationで解消するか、xteveでうまく扱うかどう考えるべきでしょうか？

### 再現方法
1. http://<サーバのIP>:8888/api/iptv/epg.xml にアクセス
2. 以下のようなエラーが表示される

```
This page contains the following errors:
error on line 11525 at column 39: PCDATA invalid Char value 26
Below is a rendering of the page up to the first error.
```

APIの応答: [epg.xml.txt](https://github.com/l3tnun/EPGStation/files/6115666/epg.xml.txt)

### EPGStationでの見え方
エラーなく表示されています。
<img width="427" alt="Screen Shot 2021-03-10 at 21 28 07" src="https://user-images.githubusercontent.com/13623491/110629545-9b6d6b80-81e7-11eb-86f7-617bbf978818.png">

**Comment by l3tnun** [comment]
詳細な報告ありがとうございます。

>EPGStationで解消するか、xteveでうまく扱うかどう考えるべきでしょうか？

ブラウザでエラーも出ていますし、基本的には epgstation 側で対処すべきかなあと思います。
xml に準拠した結果を返すまでが epgstation の仕事ですね。

**Comment by shun-sa** [comment]
以下の行に 「� 」(バイト列 efbfbd)の文字があれば、半角の「?」に置換するコードを入れようと思います。削除してもいいですね。
置換文字はEPGUpdateManageModel内に、DATA_FORBIDDEN_STRINGとして定義しようと思っています。
コミットは初めてですが、修正イメージあっていますか？

https://github.com/l3tnun/EPGStation/blob/bea3bede0e4550d05d7b02452f0d4df627355913/src/model/epgUpdater/EPGUpdateManageModel.ts#L205

**Comment by l3tnun** [comment]
xteve 環境が無いのでプルリクを投げてもらえるのであれば助かります。

修正するのであれば、下記部分を修正するほうが良いかと思います。

https://github.com/l3tnun/EPGStation/blob/bea3bede0e4550d05d7b02452f0d4df627355913/src/model/api/iptv/IPTVApiModel.ts#L124-L131

影響範囲が ```/api/iptv``` 下に限定されます。

**Comment by shun-sa** [comment]
確認していると�ではなく、その後の制御文字（SUB）が入っていたことが原因でした。
手元のDBで再現を行い、当該APIにアクセスしxmlのフォーマットエラーが消えていることを確認しました。
レビューよろしくお願いします。

**Comment by l3tnun** [comment]
修正ありがとうございました。
助かりました。

マージして問題が解決したと思いますので、閉じます。
