### ISSUE TITLE
検索で、検索後除外キーワードを削除すると、検索結果がおかしくなる。

### ISSUE THREAD

**Issue by simplelife0530** [l3tnun/EPGStation#426]
Version of EPGStation: docker-mirakurun-epgstation
    　　　versionを確認する方法を教えてください。v2です。
　　　　Mirakurunのように、UIのタイトル脇に表示されると便利です。
    Version of Mirakurun: -3.5.0
    Version of Node: -
    Version of NPM: -
    OS:　ubuntu　20.04
    Architecture: 　x86_64

　　検索で、検索後除外キーワードを削除すると、検索結果がおかしくなる。

　　症状例　（１）キーワード   　　新日本風土記
　　　　　　　　　除外キーワード   [再]
　　　　　　（２）検索結果　　　　１件表示
　　　　　　（３）除外キーワードを削除する。
　　　　　　（４）検索結果　　　　０件表示
　　　　　　（５）除外キーワード　　x
　　　　　　（６）検索結果　　　　２件表示

　　また、ルールでも同様の症状が発生する。
　　　　　　
　　なお、EPGStation v1では上記症状は発生しない。
　　
　　以上

**Comment by l3tnun** [comment]
まず、epgstation の version と、 使用しているデータベース(sqlite3意外であればバージョンも)を明示してください。
epgstation の version は `package.json` や `/api/debug` 等を参照してください。

最近 #422 等の修正で挙動が変わっていますので、最新のバージョンでも発生するようでしたらこのissue を再度オープンしてください。

**Comment by simplelife0530** [comment]
Version of EPGStation: 2.1.2 でした。
