### ISSUE TITLE
【要望】検索画面の初期入力フォーカス

### ISSUE THREAD

**Issue by sandhill2000** [l3tnun/EPGStation#432]
### 環境
Version of EPGStation: 2.0.7
Version of Mirakurun: 3.5.0
Version of Node: 14.25.4
Version of NPM: 6.14.10
OS: UbuntuServer 20.04LTS
Architecture: x64
※docker-mirakurun-epgstationを使用

### Issue
細かい使い勝手の要望ですみません。
表題のとおり、検索画面を出した際にキーワード入力欄にフォーカスを自動で設定いただけるとすぐ入力できて使いやすいかと思います。
番組検索画面のほか、「録画済み」画面の検索機能も同様です。
ご検討ください。
...

**Comment by l3tnun** [comment]
最新の master にて実装が完了したので閉じます。
