### ISSUE TITLE
npm run build でerror 

### ISSUE THREAD

**Issue by mage999** [l3tnun/EPGStation#434]
### 環境
* Version of EPGStation: `2.1.3`
* Version of Mirakurun: `1.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS: Ubuntu 20.04.1 LTS
* Architecture: x64

### Issue
...
2.1.6へアップデートをしようとしたところ、npm run build を実行中
[12:57:26] Starting 'eslint'...
[12:57:35]
../EPGStation/src/model/api/stream/StreamApiModel.ts
  322:97  error  Insert `?・・・・・・・・・・・・・・・・`  prettier/prettier

? 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

[12:57:35] 'eslint' errored after 8.85 s
[12:57:35] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 1 error
Details:
    domainEmitter: [object Object]
    domainThrown: false

[12:57:35] 'build' errored after 8.92 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
とerror

2台ubuntuの環境があり、両方の環境で発生しています。

**Comment by MISONLN41** [comment]
その場凌ぎ的な方法ですが、gulpfile.js の `.pipe(eslint({ useEslintrc: true }))` となっている箇所を `.pipe(eslint({ useEslintrc: true, fix:true }))` として ESLint に fix させればとりあえずビルドは通るようになります。

**Comment by l3tnun** [comment]
あー昨日の更新でやらかしましたね。
修正するので夜までおまちくだたい。
修正内容は @MISONLN41 さんのおっしゃるとおりです。

**Comment by mage999** [comment]
ご確認ありがとうございます。
私はの方は @MISONLN41 さん の指摘の修正して対応を行いたいと思います。

**Comment by l3tnun** [comment]
最新版で修正されましたので閉じます。
