### ISSUE TITLE
録画済み表示に時間がかかる

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#436]
### 環境
* Version of EPGStation: `1.7.5`
* Version of Mirakurun: `3.5.0`
* Version of Node: `10.15.0`
* Version of NPM: `6.4.1`
* OS:Windows10
* Architecture: x64

### Issue
PC入れ替えに伴い1.7．5にて新規に入れ直し、録画フォルダの移動とDBレストアを行いました。
その後、録画番組の表示に1分ほどかかるようになりました。

表示後は、録画番組の再生はすぐに始まります。GRやBS、予約、ルール等録画番組以外は即座に表示されます。
録画番組の検索等、録画番組表示がらみが大変重いです。

原因に思い当たりがなく、何を提示すればいいかもわかりませんがどなたかお知恵を拝借できませんでしょうか。

**Comment by l3tnun** [comment]
DB に何を使用しているかわかりませんのでなんとも言えませんが、
v1.x は開発が終了しておりサポートを行う予定はありません。
 (MITライセンスなので元から無保証ですが)

> GRやBS、予約、ルール等録画番組以外は即座に表示されます。
> 録画番組の検索等、録画番組表示がらみが大変重いです。

DB に異様な負荷がかかっていないか調べてみると良いかと思います。

申し訳ないですが、ご自身の手で解決てください。

**Comment by ohmsa** [comment]
リロードをかけてもMySQLはCPU使用率0.4％、メモリ使用量180MBで変わらず。
DB切り分けるためにMYSQLからSQLITEに変える場合は
EPGStation停止→DBバックアップ→config.json書き換え（MYSQLの箇所を消す）→DBレストア→EPGStation開始
でよろしいでしょうか。

**Comment by ohmsa** [comment]
開発終了でした。申し訳ございません。
