### ISSUE TITLE
「ルール画面」ルールが０件の際に追加ボタンが表示されない

### ISSUE THREAD

**Issue by teandt** [l3tnun/EPGStation#437]
### 環境
* Version of EPGStation: `2.1.7`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.0`
* Version of NPM: `6.14.11`
* OS:Ubuntu 20.04.2 LTS
* Architecture: x64
※docker-mirakurun-epgstation使用

### Issue
ルールが０件の場合、ルール画面の右下に表示される追加のボタンが表示されません。（検索画面に遷移するボタン）
１件でも追加するとボタンが現れ、それを削除すると再び消えます。

**使用ブラウザ**

- Windows10 Chrome 89.0.4389.90
- Ubuntu Linux 20.04 LTS Firefox 86.0

どちらも同じ挙動となりました。

![image](https://user-images.githubusercontent.com/50020829/112602170-b03c3700-8e56-11eb-9c90-228b8a7b7f89.png)
![image](https://user-images.githubusercontent.com/50020829/112602187-b500eb00-8e56-11eb-9ff9-b4fe0bad21b3.png)

**Comment by l3tnun** [comment]
立て直してありがとうございます。
明日修正します。

**Comment by l3tnun** [comment]
最新の master にて対応しましたので閉じます。
