### ISSUE TITLE
[質問] libx264でエンコードした時の字幕の表示方法について

### ISSUE THREAD

**Issue by trimethia** [l3tnun/EPGStation#439]
### Issue
EPGStationで無変換のStreamを見ると字幕が表示されますが、以下のコマンドでffmpeg(v4.3,  --enable-libaribb24でビルド)を使ってlibx264でh264に変換すると、字幕が見れなくなっているようです。字幕が表示されない理由はご存知しますしょうか？

```
ffmpeg -re -dual_mono_mode main -i pipe:0 -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1 -threads 2 -ignore_unknown -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v libx264 -preset fast -map 0 -c:s copy -c:d copy -ignore_unknown -f mpegts pipe:1
```

**Comment by l3tnun** [comment]
一体どんな方法で無変換の stream を再生し、どんな方法で変換後の動画を再生したのかわかりません。
情報を整理して、必要であれば再度オープンしてください。

m2ts 形式でのライブ視聴での話であれば、再生するソフト側の問題になりますので、ここでは取り扱いません。
再生ソフトに合わせて ffmpeg で変換してください。
