### ISSUE TITLE
デフォルトの字幕表示方法に関する質問

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#441]
### 環境
* Version of EPGStation: `x.x.x`
* Version of Mirakurun: `x.x.x`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64

### Issue

このあたりそもそもどのように動いているか理解していないので的外れでしたら申し訳ないのですが、下記設定項目のデフォルトというのはそもそも字幕に関するライブラリを使用しないということでしょうか。
常時使用にしておくと何か弊害がありますでしょうか。ないようならばそもそもaribb24.jsかb24.jsのどちらかをデフォルトとして現在のデフォルトの項目自体を削除したほうが便利だとおもうのですが、いかがでしょうか。

![image](https://user-images.githubusercontent.com/13718335/112794041-3c419f00-90a1-11eb-821b-20078e6dac41.png)

**Comment by l3tnun** [comment]
>そもそも字幕に関するライブラリを使用しないということでしょうか。

そのとおりです。ffmpeg が aribb24 に対応し vtt を使用して字幕を表示出来るようになったため、epgstation v2 ではそれをデフォルトとし、
v1 でサポートしていた hls-b24.js + b24.js による字幕表示機能を落としました(ffmpeg 4.1.xまでしか使用できなかったため)

aribb24.js が最近作られたことにより aribb24.js, b24.js による字幕表示が追加されました。(node-arib-subtitle-unrecognizer により最新の ffmpeg も対応された)
MSE に非対応 + ネイティブで HLS 再生に対応している環境(iOS等)に非対応 であること、
vtt による実装の方が先にあった為にデフォルトが vtt による字幕表示となっています。

>常時使用にしておくと何か弊害がありますでしょうか。

現状では MSE に非対応 + ネイティブで HLS 再生に対応している環境で aribb24.js or b24.jsが動作しないので、できません。
ただし、aribb24.js 1.0.0  (現状は0.3.6) では、そのような環境でも対応したとのことなので(#440)、
将来的には aribb24.js に全て統合し、字幕表示の設定項目自体削除する予定です。

**Comment by 5ym** [comment]
ご丁寧に回答ありがとうございました。そういう事情だったのですね理解いたしました。
一様blinkベースのedgeでは字幕を表示できていることを確認しています。
宜しくお願い致します。
