### ISSUE TITLE
【要望】UI改善点の要望

### ISSUE THREAD

**Issue by sandhill2000** [l3tnun/EPGStation#442]
### 環境
Version of EPGStation: 2.1.8
Version of Mirakurun: 3.5.0
Version of Node: 14.15.4
Version of NPM: 6.14.11
OS: UbuntuServer 20.04.2 LTS
Architecture: x64
※docker-mirakurun-epgstation使用

### Issue
また細かい使い勝手要望ですみません。
・録画済み画面のレイアウト選択について
　テーブル表示とサムネイル表示の切替は設定画面でなく録画済み画面上ですぐ切替えられると便利です。
・ダークテーマ時の番組表の配色
　非ダークテーマ時の番組表の配色は落ち着いたよい色と思うのですが、
　ダークテーマの番組表配色はちょっと色味がきついと感じています(勿論個人差ありますが)
　また予約番組の枠も特に映画番組など同系色なので私のような色弱者には見にくいです。
　(世の中には20人に1人色弱者がいるといわれています。)
　EPGStationの画面全体としてはダークテーマを使いたく、背景がダークテーマのまま
　番組表配色を非ダークテーマと同じに選択できると助かります。

以上、ご検討いただけますと幸いです。
...

**Comment by l3tnun** [comment]
> テーブル表示とサムネイル表示の切替は設定画面でなく録画済み画面上ですぐ切替えられると便利です。

設定項目を設定ページ外に分散させたくないので、今は現状のままとします。

> ・ダークテーマ時の番組表の配色

こちらは実装できましたので閉じます。

**Comment by sandhill2000** [comment]
実装確認できました。ありがとうございました。
背景がダーク＋非ダーク配色の番組表を実際に見ると、色合いそのままで気持ち番組表の輝度を落としたい気もしますが、十分見やすいです！
