### ISSUE TITLE
【質問】encode時の環境変数であるDIRについて

### ISSUE THREAD

**Issue by konikoni428** [l3tnun/EPGStation#443]
### 環境
* Version of EPGStation: `2.1.4`
* Version of Mirakc: `0.15.0`
* Version of Node: `14.16.0`
* Version of NPM: `6.14.11`
* OS: Ubuntu 18.04
* Architecture: arm64

### Issue
エンコードの環境変数であるDIRはdocsに以下のように記述されています。

変数名 | 種類 | 説明
-- | -- | --
DIR | string | 予約時に設定した directory 文字列

これより私は指定したサブディレクトリ文字列が渡されると考えました。
しかし実際の動作はサブディレクトリを指定してもしなくてもOUTPUTと変わらない文字列が渡されるので調査しました。

```ts
// EncodeManageModel.ts 243-250

// DIR
let dir: string = '';
if (typeof encodeCmd.suffix === 'undefined' && typeof queueItem.directory !== 'undefined') {
    dir = queueItem.directory;
} else if (outputFilePath !== null) {
    dir = outputFilePath;
}
```

該当の箇所がここだったのですが、なぜifで`typeof encodeCmd.suffix === 'undefined'`での分岐を行っているのでしょうか？
この変数は`.mp4`などが入り、`undefined`になることはほぼないと思われます。
バグなのか意図的なのか判別がつかないため質問させていただきました。

ここからは提案になってしまうのですが、DIRの動作について

- サブディレクトリの指定がある -> DIRにその値がセットされる 
- サブディレクトリの指定がない -> DIRは空文字もしくはundefined

の動作にするのはどうでしょうか？

以上よろしくお願いいたします。

**Comment by tobitti0** [comment]
#392 による条件分岐のようです。

ただ、エンコード時、非エンコード時に関わらず設定した文字列を渡すようにするのは理想的な処理だと思います。

**Comment by konikoni428** [comment]
過去issue探すの失念していました。
ありがとうございます。

#392 を見る限り過去から環境変数DIRではourputDirを出力しており、特定の場合（suffixが存在しない非エンコードモード）にはサブディレクトリを渡すという動作が標準だったように思われます

昔からこの動作が正しいのであれば、変更による影響を考慮して新しい環境変数SUBDIRを導入し、そちらにはエンコード時、非エンコード時にかかわらずサブディレクトリの情報を入れてもいいかもしれません

**Comment by l3tnun** [comment]
doc の 環境変数 DIR の説明が紛らわしかったですね。
@takuo さんのおっしゃるとおりで、#392 による修正で、v1 の頃の挙動に合わせました。

> 変更による影響を考慮して新しい環境変数SUBDIRを導入し、そちらにはエンコード時、非エンコード時にかかわらずサブディレクトリの情報を入れてもいいかもしれません

とても良いと思います。
プルリクがあれば受け入れます。

**Comment by l3tnun** [comment]
プルリクありがとうございました。
マージしましたのでクローズします。
