### ISSUE TITLE
ルール編集画面で表示されるエンコードモードが実際に設定されているものと異なる

### ISSUE THREAD

**Issue by kyori19** [l3tnun/EPGStation#449]
### 環境
* Version of EPGStation: `2.1.9`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.0`
* OS: alpine (Docker) on Ubuntu 20.04
* Architecture: x64

### Issue

コンフィグに2つのエンコードを登録して、「H.264 (JLSE)」で問題なく登録されているのですが、表示だけ「H.264」になってしまうようです。
きちんと「H.264 (JLSE)」に変更して更新すれば問題なく更新されるようですが、変更せずそのままの状態で更新してしまうと設定が「H.264」に変更されてしまうようです。

#### ルール編集画面
![image](https://user-images.githubusercontent.com/27999567/114185486-bebf3e00-9980-11eb-9499-406433174905.png)

#### ルールのAPIレスポンス
![image](https://user-images.githubusercontent.com/27999567/114185511-c4b51f00-9980-11eb-9b80-da10b60192a9.png)

#### コンフィグ
![image](https://user-images.githubusercontent.com/27999567/114185657-ed3d1900-9980-11eb-8746-986bd5849461.png)

**Comment by l3tnun** [comment]
epgstation のルール編集に使用しているブラウザとOSのバージョンを教えてもらえますか？
Ubuntu 20.04 + Chrome (89.0.4389.114) or Firefox (87.0) で確認できませんでした。

現象としては以下の手順で再現できますか？

1. 検索ページ (#/search) でルール作成。エンコード1 の mode1 指定を2つ目に設定する
2. ルールページ (#/rule) から、作成したルールの編集ページ (#/search?rule=xx) へ飛ぶ
3. エンコード1 の mode1 の指定が正しく無いことを確認

**Comment by kyori19** [comment]
手順はそのとおりで再現できます。

メインで使っている環境で必ず発生するので環境依存ないものかと思っていましたが、結構不思議な条件で発生するようです。

再現する環境2つでもシークレットモードにしたら再現できなくなったので条件が結構謎ですね
Vivaldiで拡張機能をすべて切っても治らなかったので別の環境要因があるかもしれません

## 再現する環境

* Windows 10 Version 2009 (Build 19042.906) + Vivaldi 3.7.2218.52 (Chrome 89.0.4389.116相当)
* Android 10 + Chrome 89.0.4389.105

## 再現しない環境

* Windows 10 Version 2009 (Build 19042.906) + Chrome 89.0.4389.114
* Windows 10 Version 2009 (Build 19042.906) + Firefox 86.0
* Windows 10 Version 2009 (Build 19042.906) + Firefox 87.0
* Android 11 + Chrome 89.0.4389.105

**Comment by l3tnun** [comment]
なるほど...

>Android 10 + Chrome 89.0.4389.105

こちらにも同じ環境が有ったので試してみましたが、再現しないですね。

怪しいところがないかソース見てみます。

**Comment by l3tnun** [comment]
それは良い情報ですね、これで解決するのであればこの issue は閉じようかなと思います。

**Comment by l3tnun** [comment]
scimmia9286 さんのご指摘のとおりでした。
大変助かりました。ありがとうございます。

修正内容が master へ反映されたらこの issue を閉じます。

**Comment by l3tnun** [comment]
最新の master に反映されたので閉じます
