### ISSUE TITLE
複数チャンネルで同一TSIDを共有するチャンネル録画において映像音声破綻が起こる

### ISSUE THREAD

**Issue by sandhill2000** [l3tnun/EPGStation#450]
### 環境
* Version of EPGStation: `2.1.8`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.11`
* OS: Ubuntu Server 20.04.2 LTS
* Architecture: x64

### Issue
表題の件、特定の条件で録画データの破損が起こります。
発生条件：
・複数チャンネルで同一TSIDを共有しているチャンネルの録画中に起こる。
　※スターチャンネル2&3で確認
・チャンネルAで5.1ch放送中に並行でチャンネルBでモノorステレオ放送を録画していて
　チャンネルAの番組本編が終わり、番宣等のステレオ放送に切替わる瞬間に
　チャンネルBの録画の数十～数百におよぶTSのペイロード破損が発生、その後回復する。
　※現象が発生する音声切替わりパターンは他にもあるかもしれない

この現象で破損するTSパケットは、TSヘッダが全く正常なままTSペイロードだけが
そっくり別物になるという事象。TSヘッダが正常なのでTSパケットの体裁として正常と
見做されるようで、破損部分においてドロップログにはdropもerrorも現れない。
破綻を確認するには録画ファイルをTMPG SmartRenderer6を使用して再エンコード
箇所チェックをかけて、現れるはずのない所に現れた再エンコード箇所を編集画面で
確認すると破綻箇所が目視でき、同じ箇所をVLCやPS3で目視しても破綻が確認できる。

同時間の同番組をWindows＋EDCBで録画したものではこうした現象は起こらない。
EPGStationとEDCBで同時に録画したTSからMurdocCutterでM2Vパケットだけを取り出して
比較した結果、EPGStation側で破損したデータ部分において
・TSヘッダは両者で完全一致(つまりTSヘッダは正常)
・TSペイロードが全く別物
ということが判明。

複数チャンネルで同一TSIDを共有するチャンネルは他にBSの民放キー局チャネル等が
あるものの(BS朝日1/2/3など)、スターチャンネル2/3のように普段から全然違う番組を放送
したり、かつ5.1chとモノ/ステレオ放送が両チャンネル個別に頻繁に変わることがないので
気付く人が少ないだろうと思われます。
恐らくEPGStationのTSフィルタ処理に、今回の条件下で起こる問題が内在しているのでは
と思います。
自分はスターチャンネル3の海外ドラマ一括放送を録画していてフレーム破綻に困り
対策のためスターチャンネル2/3に限ってEBCDでも録画するようにしましたが、
両方のTSが得られ折角なので今回の比較をしてみました。

環境的になかなか再現・解決が難しいケースかもしれませんが、対処の上で必要な情報が
ありましたら提供しますのでよろしくお願いします。
...

**Comment by l3tnun** [comment]
現象は理解できましたが、これは Mirakurun 側で対処すべきことではないでしょうか？
epgstation は Mirakurun からストリームを受け取り、ただそれを保存しているだけです。

>恐らくEPGStationのTSフィルタ処理に、今回の条件下で起こる問題が内在しているのでは
>と思います。

epgstation でしているフィルタ処理としては aribts によるドロップカウントしかありません。
そのため、config.yml で isEnabledDropCheck を true にした場合のみ発生するのであれば、
 epgstation 側の処理が原因と考えられます。
そうでないのであれば Mirakurun 側が原因かと思われます。

**Comment by sandhill2000** [comment]
回答ありがとうございます。なるほど了解しました。
MirakurunとEPGStationの役割の境界を理解できておらずすみません。
Mirakurunの方で投げかけてみます。
ありがとうございます。
