### ISSUE TITLE
Windows上のEPGStationで録画先を外部の共有フォルダにしたい

### ISSUE THREAD

**Issue by kand382** [l3tnun/EPGStation#452]
### 環境
* Version of EPGStation: `2.x.x` 確認方法分からず(2/1導入)
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS:windows10
* Architecture: x64

### Issue
素晴らしいソフトウェアの公開ありがとうございます。
表題の件ですが、Windows上のEPGStationにて録画先を外部の共有フォルダにしたいのですが上手くいきません。¥¥の指定はどうすれば良いでしょうか。

■やりたいこと
保存先を¥¥192.168.1.1¥¥shareにしたい
■やったこと
config.ymlのrecorded:のpathを
①'¥¥¥¥192.168.1.1¥¥share¥¥'
②'¥¥¥192.168.1.1¥¥share¥¥'
と指定
■結果
①②どちらもC:¥192.168.1.1¥share¥に保存されてしまう
■ログ(Operator¥system.log)確認結果
①②どちらも保存先が¥192.168.1.1¥¥share¥になっている
■その他
ちなみに¥¥192.168.1.1¥¥shareをネットワークドライブZとして割当し、
'¥¥Z:¥¥'とするとダッシュボードの予約にタスクが入った後、しばらくすると録画されずに消えてしまいます。system.logにはpreprec faildが出ます。
BonRecTest.exeでoutputをZ:¥test.tsにするとCould not open outputと怒られるのでそもそもネットワークドライブに対応してないと考えます。

**Comment by cuckoozero** [comment]
windows上でEPGStationを実行していて、エンコードしたファイルをNASに投げようとして引っかかったことがあります。
EPGStationのサービスがSystemユーザーによって実行されている場合はNASにはアクセスできないかもしれません。
#87 を参照してください。

**Comment by l3tnun** [comment]
windows環境についてサポートするつもりはありません。
(windows環境の維持とそれ用の検証に時間を割きたくないため)
ですのでご自身で試行錯誤してみてください。
ネットワークドライブとして割り当てて、Z:¥¥hoge みたいな指定で動くような気はしますが検証する予定はありません。

node.jsでネットワークドライブにファイルが出力できるような、簡単なプログラムが書ければ理解が深まるかと思います。

**Comment by kand382** [comment]
> windows上でEPGStationを実行していて、エンコードしたファイルをNASに投げようとして引っかかったことがあります。
> EPGStationのサービスがSystemユーザーによって実行されている場合はNASにはアクセスできないかもしれません。
> #87 を参照してください。

ありがとうございます。
EPGStationのサービスをシステムからユーザーに変えてみましたが変化ありませんでした。

**Comment by kand382** [comment]
> windows環境について積極的にサポートするつもりはありません。
> (windows環境の維持とそれ用の検証に時間を割きたくないため)
> ですのでご自身で試行錯誤してみてください。
> ネットワークドライブとして割り当てて、Z:¥¥hoge みたいな指定で動くような気はしますが検証する予定はありません。
> 
> node.jsでネットワークドライブにファイルが出力できるような、簡単なプログラムが書ければ理解が深まるかと思います。

5ちゃんねるでヒントをもらいました。
色々試行錯誤し、結果として対処ができたので書き留めておきます。

■対処内容
①Windowsにネットワークドライブを割当て
②mklinkで①のシンボリックリンクを作成
③EPGStationのpathに②のシンボリックリンクを指定

とりあえずこれで様子をみてみます。ありがとうございました。
node.jsの動きは気になるので試してみます。
