### ISSUE TITLE
【不具合】Linux上でマウントされたディスクに録画先を指定している場合、ストレージ情報が取得できない

### ISSUE THREAD

**Issue by key3946** [l3tnun/EPGStation#453]
### 環境
* Version of EPGStation: `2.0.8`
* Version of Mirakurun: `3.5.0`
* Version of Node: `v14.15.4`
* Version of NPM: `6.14.10`
* OS: Raspbian GNU/Linux 10 (buster)
* Architecture: armv7l(x32)

### Issue
/mnt/ディレクトリなどにマウントされている場所に録画先を指定すると、ストレージ情報が取得できません。

### 原因
npmパッケージのdiskusage-ngの不具合
現在EPGStationでは  1.0.0 を使用しているが、最新版の 1.0.1 を使用すると修正されている。

### 修正箇所
package.json
```package.json
"dependencies": {
        "diskusage-ng": "1.0.1",
},
```

**Comment by l3tnun** [comment]
#405 参照してください。
すでに適用済みです。

**Comment by key3946** [comment]
確認不足でした。ありがとうございます。
