### ISSUE TITLE
一瞬で終了する非エンコードコマンドを実行するとRunning Taskに残り続ける

### ISSUE THREAD

**Issue by scimmia9286** [l3tnun/EPGStation#454]
### 環境
* Version of EPGStation: `2.2.1`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.1`
* Version of NPM: `6.14.12`
* OS: Ubuntu-20.04 (Docker-debian)
* Architecture: x64

### Issue
一瞬で終了するシェルスクリプトを非エンコードコマンドとしてconfig.ymlに登録して実行すると、シェルスクリプト終了後もエンコード中タスクに残り続け、UI上でキャンセル操作をしても表示から削除できない。
(シェルスクリプトを数秒Sleepして回避している)

**Comment by l3tnun** [comment]
プロセスの終了が検知できないので残り続けるのかなあと思います。
修正します。

**Comment by l3tnun** [comment]
最新の master で修正されたので閉じます。
