### ISSUE TITLE
config.yml 詳細マニュアルの記載誤り

### ISSUE THREAD

**Issue by scimmia9286** [l3tnun/EPGStation#455]
### 環境
* Version of EPGStation: `2.2.1`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.1`
* Version of NPM: `6.14.12`
* OS: Ubuntu-20.04 (Docker-debian)
* Architecture: x64

### Issue
config.yml 詳細マニュアルのエンコード設定説明の記載に誤りがあるので訂正をお願いします。

誤)
-   `suffix` を**空欄**にした場合、非エンコードコマンドとして実行される

正)
-   `suffix` を**定義しなければ**、非エンコードコマンドとして実行される

**Comment by l3tnun** [comment]
確かにそのとおりです。
修正します。

**Comment by l3tnun** [comment]
最新の master で修正されたので閉じます。
