### ISSUE TITLE
recordingFinishCommandに渡される環境変数にDropカウントを追加

### ISSUE THREAD

**Issue by scimmia9286** [l3tnun/EPGStation#456]
### 環境
* Version of EPGStation: `2.2.1`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.1`
* Version of NPM: `6.14.12`
* OS: Ubuntu-20.04 (Docker-debian)
* Architecture: x64

### Issue
録画終了時にドロップカウントをチェックして、あるタスクを実行したいと考えています。
ログファイルのパスが渡されるので、スクリプトからログファイルを読めば良いのですが、実装可能でしたら環境変数でエンコードコマンドと同様にrecordingFinishCommandにも渡されると助かります。

**Comment by l3tnun** [comment]
最新の master にて対応したので閉じます。
