### ISSUE TITLE
isEnabledDropCheck が録画データと同階層内にドロップlogを吐いてくれない

### ISSUE THREAD

**Issue by lkfejleene** [l3tnun/EPGStation#459]
### 環境
Version of EPGStation: 2.2.1
Version of Mirakurun: 3.5.0
Version of Node: 14.16.1
Version of NPM: 6.14.12
* OS:Ubuntu-20.04 (Docker-debian)
* Architecture: x64

isEnabledDropCheck:ture としましたが録画データと同階層内にドロップlogを吐いてくれません。
ご確認願えますでしょうか。

**Comment by yt4687** [comment]
ログの吐き出し先を指定しない場合はEPGStationのカレントディレクトリのdropフォルダ内に落ちますね。
それ以外の場所に落とすときは下の方法でできますよ。でもEDCBみたいに録画先の移動に追従してはできなさそうですが。

https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#droplog

**Comment by lkfejleene** [comment]
確認しました。>dropディレクトリ

下記ツイートがあったので録画先に出来るものだと思ってました。
https://twitter.com/l3tnun/status/1023167967058522112
ただ、jsonとありますからv1のみの仕様で、v2では録画先の移動に追従してくれないのでしょうか。

**Comment by l3tnun** [comment]
v2 からは DB の構造が複雑になるので、録画データと同階層内にドロップログを出力する設定は廃止されました。
詳細は yt4687 さんがおっしゃるとおりです。
