### ISSUE TITLE
mpegts.jsでの字幕表示の仕方

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#463]
### 環境
* Version of EPGStation: `v2.2.2`
* Version of Mirakurun: `x.x.x`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64

### Issue

mpegts.js対応お疲れ様でした。
こちら質問なのですが、m2tsで視聴時に字幕を表示するためにはffmpegのパラメータのほうどう変更すればよろしいでしょうか。

また、こちら無変換のm2tsをブラウザで視聴する方法はありますでしょうか。
確認よろしくお願いいたします。

**Comment by l3tnun** [comment]
まだ #433 での作業が完了していないため、まだ字幕表示は出来ないです。もう少し待ってください。

> また、こちら無変換のm2tsをブラウザで視聴する方法はありますでしょうか。

残念ながらありません。

**Comment by 5ym** [comment]
ご回答ありがとうございます。字幕のほう承知いたしました。
無変換の視聴ができないのは技術的な理由になりますでしょうか。

**Comment by xqq** [comment]
日本のテレビ放送に使われている mpeg2video/h262 の codec がかなり古いので、それを支援するブラウザが無いのです。
asm.js/webassembly でブラウザ上で ffmpeg を利用し、それを再生するのは技術的可能ですが、
（Mirakurun の作者はそのような実装を作ってきたが、公開していなかったようです）
js/wasm によるソフトウェアでデコードするため、パフォーマンスが課題になります。CPU 使用率が高騰します。

**Comment by 5ym** [comment]
初歩的な質問で申し訳ないのですが、M2TSで720pを選択してブラウザで視聴している際はmpeg2ではないのですか？

**Comment by xqq** [comment]
https://github.com/l3tnun/docker-mirakurun-epgstation/pull/26/files#diff-dfd1f81f42c41cc82285612ea2f9b38679d14378ba06e0aa2d259d74eb6bfe44L61

`-c:v libx264`

**Comment by 5ym** [comment]
こちらですね正確にはm2tsではないのですね把握いたしました。
https://github.com/l3tnun/docker-mirakurun-epgstation/blob/v2/epgstation/config/config.sample.yml#L60

**Comment by xqq** [comment]
mpeg2ts/m2ts はあくまで container/format/トランスポート方式なので、codec は mpeg2 に限定するわけではないのです。

**Comment by xqq** [comment]
ちなみにですが、`.m2ts` 拡張子は一般的に BDAV/BDMV を指し、BDAV/BDMV の TSパケットサイズが 192 bytes なので、
放送ストリームの 188 bytes のパケットサイズをそのまま `.m2ts` の拡張子で保存するのは、ある程度不適切だと思われます。

**Comment by 5ym** [comment]
色々とありがとうございます。
また追加でご質問なのですが、録画データでも同一の視聴方法を使うことはできますでしょうか。

**Comment by xqq** [comment]
技術的に h264 の ts ファイルは視聴可能ですが、現時点ではシークがまだ未実装のため、シークができません。
