### ISSUE TITLE
v1からの移行で、ルールの除外キーワードの正規表現が引き継がれない

### ISSUE THREAD

**Issue by akikuchi3913** [l3tnun/EPGStation#464]
### 環境
* Version of EPGStation: `2.2.2`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.0`
* Version of NPM: `6.14.11`
* OS: Ubuntu 18.04.5
* Architecture: x64

### Issue
本体の話しでは無く恐縮なのですが…
v1からの移行で、v2 環境に v1 環境のルールのデータを反映させる際、
除外キーワードの正規表現のチェックが移行されませんでした。

移行済みのため再度確認できませんが、
V1MigrationTool.tsの228行、229行の

        if (oldRule.keyRegExp !== null) {
            searchOption.keyRegExp = oldRule.keyRegExp;
             　↓
        if (oldRule.ignoreKeyRegExp !== null) {
            searchOption.ignoreKeyRegExp = oldRule.ignoreKeyRegExp;

と思われます。　以上、ご確認下さい。
...

**Comment by l3tnun** [comment]
報告ありがとうございます。
ご指摘のとおりですね。
他と合わせて修正しますので、しばらくお待ちください。

**Comment by l3tnun** [comment]
最新の master に修正しましたので閉じます。
