### ISSUE TITLE
config.sample.yml が見つからないときのログ表示が紛らわしい

### ISSUE THREAD

**Issue by kyori19** [l3tnun/EPGStation#468]
低遅延配信のサポート関連のコミットで `config.sample.yml` を読み込む変更が入っているかと思うのですが、 `config.sample.yml` を置いていない環境でこのようなエラーを確認しました。

```
epgstation_1  | [2021-05-09T10:13:25.693] [FATAL] system - config.yml is not found
```

ログを吐く箇所でメッセージがファイルパスに関わらず決め打ちされているようだったので、ファイル名に合わせてログを変更していただけると助かります。

**Comment by l3tnun** [comment]
確かに紛らわしいですね。
修正します。

**Comment by sandhill2000** [comment]
私もハマりました。
sampleファイルは最初の設定の参考用元ファイルと認識しており、システムから参照される想定はなかったということもありました…

**Comment by kyori19** [comment]
> > sampleファイルは初期設定時の参考用ファイルと認識していてシステムから参照される想定がなく…
> 
> git で管理されているファイルですので、削除されると git pull コマンドで更新時にコンフリクトが発生する場合があります。
> そのため、積極的に削除されることは想定していません。

Dockerで運用しているとイメージだけpullすればリポジトリ全体をクローンする必要がないので、 `docker-compose.yml` と必要なコンフィグ類をまとめた最小限のリポジトリを用意して環境の再現性を確保していたりしますね…(`config.yml` をgit管理するためのリポジトリがあってそこに `config.sample.yml` が入っていなかったということです)

**Comment by sandhill2000** [comment]
名に「.sample」「.default」などがついた参考設定ファイルは伝統的に大事だと思われない気がするので、今回システムから参照されるようになったことを機に「.template」とか「.sysdefault」などとするのもありかと思いました。

**Comment by l3tnun** [comment]
最新の master にて `config.sample.yml` から `config.yml.template` に変更されました。
それと、`config.yml.template` が存在しない場合はログに警告を残すだけになりました。
以上で対応完了なので閉じます。
