### ISSUE TITLE
Swaggerの/channels/{channelId}/logoで誤記

### ISSUE THREAD

**Issue by akikuchi3913** [l3tnun/EPGStation#476]
### 環境
* Version of EPGStation: 2.3.2
* Version of Mirakurun: 3.5.0
* Version of Node: 14.16.0
* Version of NPM: 6.14.11
* OS: Ubuntu 18.04.5
* Architecture: x64

### Issue
Swaggerの/channels/{channelId}/logoで表記間違えがあります。

/src/model/service/api/channels/{channelId}/logo.ts　のtypoと思われます。
　27行　summary: '放送局ログ取得',　→　summary: '放送局ロゴ取得',
　29行　description: '放送局のログを取得する',　→　description: '放送局のロゴを取得する',
　37行　description: '放送局のログを取得しました'　→　description: '放送局のロゴを取得しました'

ご確認いただきたくお願いします。
...

**Comment by l3tnun** [comment]
ご指摘のとおりです。修正します。

**Comment by l3tnun** [comment]
修正しましたので閉じます。
