### ISSUE TITLE
誤植

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#477]
### 環境
* Version of EPGStation: `2.3.3`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.17.0`
* Version of NPM: `6.14.13`
* OS:Windows 10
* Architecture: x64

### Issue
...
「元ファイルを同じ場所に保存する」
⇒「元ファイルと同じ場所に保存する」

元ファイルは既にあるので、新しいエンコードファイルを「元ファイルと同じ場所に保存する」ということで。

![image](https://user-images.githubusercontent.com/36388669/118487201-72240b00-b755-11eb-91c1-ae8b083bb461.png)

**Comment by l3tnun** [comment]
ご指摘のとおりですね。修正します。

**Comment by l3tnun** [comment]
修正しましたので閉じます。
