### ISSUE TITLE
[検討依頼]番組表の1週間分のスクロール

### ISSUE THREAD

**Issue by gifut** [l3tnun/EPGStation#479]
### 環境
Version of EPGStation: 2.3.4
Version of Mirakurun: 3.5.0
Version of Node: 14.16.1
Version of NPM: 6.14.12
OS: Ubuntu 20.04.1 LTS
Architecture: x64

### Issue
毎度のアップデートありがとうございます。大変感謝しております。
私が得意な使い方をしているだけかもしれませんし、また、技術的な難易度もわかりませんので、すでにご検討いただけていた場合、不要ないしエフォートに見合わないと判断された場合はクローズしてください。

ルールで予約している番組以外で、単発で面白そうな番組を1週間分まとめて予約することが多いのですが、1週間分の番組表をスクロールダウンのみ（日付を切り替えせずに）閲覧するようなことは可能でしょうか。

例えば
・スクロールして表示限界まで来た場合、翌日の番組表が自動で読みみ、そのままスクロールダウンして翌日以降の番組表も見られる
・もしくは24時間以上の表示を可能にする。。。

など。ご検討いただけたら幸いです。

<img width="944" alt="Capture" src="https://user-images.githubusercontent.com/83166510/118647676-e3a99b00-b7e1-11eb-9513-b85093685fcb.PNG">

**Comment by l3tnun** [comment]
なかなか検討することが多くて、難しいですね。
描画する要素が多くなると恐ろしく遅くなるので、かなり工夫がいります。

特に iOS/iPadOS の対応が難しいですね。
要素の描画を抑えるためにスクロール時に見えている範囲だけ逐次表示を切り替えると、スクロールがぶるぶるするので。
(現状 iOS/iPadOS は CPU のシングルスレッド性能が高いのでゴリ押しで全要素描画して対応しています)

iOS/iPadOS は別としても、描画方法を根本的に見直さないといけないので実装難易度はかなり高いです。

**Comment by gifut** [comment]
ご検討ありがとうございました。クローズさせていただきます。
現状でも十分に素晴らしいプロダクトなので、私のリクエストよりももっとコアなところに注力されてください。
いつも本当にありがとうございます。
