### ISSUE TITLE
MX Playerのバージョンについて

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#481]
### 環境
* Version of EPGStation: `2.3.3`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.17.0`
* Version of NPM: `6.14.13`
* OS:Windows10
* Architecture: x64

### Issue
EPGStation v1にてエンコードした番組をAndroid(iPhoneは未検証)で再生しようとするとMX Playerのインストールを促され、インストールされていない場合はPlayStoreに飛びます。

EPGStation v2で同じくエンコード番組を再生しようとすると、580円のMX Player Proに飛ばされます（MX Playerはインストール済み）。

まだconfig.jsonの記述を詳しく追ってはないですが、まずはご報告まで。
...

**Comment by l3tnun** [comment]
Pro 版になってますね。直します。

**Comment by l3tnun** [comment]
修正したので閉じます。
