### ISSUE TITLE
%FFMPEG%

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#482]
### 環境
* Version of EPGStation: `2.3.3`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.17.0`
* Version of NPM: `6.14.13`
* OS:Windows10
* Architecture: x64

### Issue
エンコードコマンドについて、現在のconfig.ymlは
cmd: '%NODE% %ROOT%/config/enc.js'
となっています。下のstreamでは
'%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -y -f mpegts pipe:1'
となっております。

cmd内で使える環境変数は
%NODE% 　node のファイルパス
%INPUT%　入力ファイルパス
%OUTPUT%　出力ファイルパス
%ROOT%　 EPGStation の root パス
ということで、%FFMPEG%は使えなさそうです。
実際、
`
"encode": [
    {
        "name": "H264",
        "cmd": "%FFMPEG% -y -dual_mono_mode main -i %INPUT% -ignore_unknown -c:v hevc_nvenc -filter_complex dejudder,fps=30000/1001,fieldmatch,decimate,scale=1280:720,fps=24000/1001 -g 1200 -b:v 0 -cq 27 -rc-lookahead 32 -c:a aac -ar 48000 -ab 192k -ac 2 %OUTPUT%",
        "suffix": ".mp4",
        "default": true
    }
`
は駄目で
`
"encode": [
    {
        "name": "H264",
        "cmd": "C:\\EPGStation\\bin\\ffmpeg.exe -y -dual_mono_mode main -i %INPUT% -ignore_unknown -c:v hevc_nvenc -filter_complex dejudder,fps=30000/1001,fieldmatch,decimate,scale=1280:720,fps=24000/1001 -g 1200 -b:v 0 -cq 27 -rc-lookahead 32 -c:a aac -ar 48000 -ab 192k -ac 2 %OUTPUT%",
        "suffix": ".mp4",
        "default": true
    }
`
はOKでした。

streamの方はOKでencodeは駄目というか、直下に似たような構文があってわかりづらい気もします。
%FFMPEG% FFMPEGのファイルパス
は使えても良い気もします（理由があってそうしているのでしたらすみません）
...

**Comment by l3tnun** [comment]
encode で `%FFMPEG%` が置き換えられない理由は無いですが、
正確に言うと encode で直接 ffmpeg を呼び出すことは想定されていないため、このような仕様になっています。

**Comment by ohmsa** [comment]
なるほど。仕様でしたか。
参考までに、encode指定時に直接ffmpegを呼び出さない理由は何かあるのでしょうか。

**Comment by l3tnun** [comment]
与えられた[環境変数](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#encode)を元に ffmpeg のパラメータを変更する等々を想定しています。

デフォルトの `enc.js` では  dual mono の設定や、720p 以上のものを 720p でエンコードするように振り分けています。

ffmpeg 自体万能ではないので、番組に応じた振り分けは必須であると思いますので、 encode で直接 ffmpeg を呼び出すことは想定していません。
