### ISSUE TITLE
NHK総合1・徳島 no

### ISSUE THREAD

**Issue by keroro9** [l3tnun/EPGStation#484]
すみません、キー操作をミスって空で投稿してしまいました。
### 環境
* Version of EPGStation: `2.0.8`
* Version of Mirakurun: `3.3.1`
* Version of Node(mirakurun側）: `10.22.0`
* Version of NPM(mirakurun側）: `6.14.6`
* OS: raspbian(mirakurun）+Ubuntu20.04LTS
* Architecture: x64
* mirakurunサーバーはraspberrypi,EPGStationはDocker-epgstation（https://github.com/l3tnun/docker-mirakurun-epgstation）
* 録画拡張しm2ts→TSへ変更済み
### Issue
表題の通り、なぜかNHK総合1・徳島の録画予約が失敗してしまいます。検索より検索しルール化した番組を自動録画した際、およそ7～8分程度で録画が停止しています。先頭から7分間でなく、番組中のどこかの7分間が切り取られたような挙動をしています。切り分けのためH264エンコードをやめ、TSのみの録画にしてみましたが状況は変わりません。先週1週間の録画では100%の再現性でしたが、昨日のテスト（手動での予約投入）では再現していません。また、NHK総合以外の民放の再現はありません。

EPGStationはVMWare ESXi上でホストしているため、システムクロックのズレを懸念し、JSTにあわせ、NTPでの同期も行うよう変更しましたが改善は見られない様子でした。

状況を報告しようにも、何せ示せるデータがない状況ですので、まず、logを確認し詳細を検討したいと考えております。どなたか、具体的に見るべきlogの場所をご教示いただけますと助かります....。

**Comment by l3tnun** [comment]
EPGStation は Mirakurun から stream を取得して保存しているだけですので、まずは、Mirakurun 単体で異常がないか確認してはどうでしょうか？
(programId 予約の場合、MIrakurun 側で番組の開始、終了を判定していますので)

>状況を報告しようにも、何せ示せるデータがない状況ですので、まず、logを確認し詳細を検討したいと考えております。どなたか、具体的に見るべきlogの場所をご教示いただけますと助かります....。

readme を読んでいただければ、わかると思いますが...

https://github.com/l3tnun/EPGStation#epgstationlogsoperator

まずは、epgstation より  mirakurun 単体で programId を指定して正常に録画できるか確認し、原因を切り分けてから epgstation の問題であれば、この issue を再度開いてください。
