### ISSUE TITLE
【要望】録画準備段階のドロップログを記録しない

### ISSUE THREAD

**Issue by scimmia9286** [l3tnun/EPGStation#491]
### 環境
* Version of EPGStation: `2.3.2`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.16.1`
* Version of NPM: `6.14.12`
* OS:Ubuntu 20.04
* Architecture: x64

### Issue
未契約有料チャンネルの無料番組を録画すると、録画準備段階(番組開始前15秒間)で発生したscramblingが記録されてしまいます。
このケースではログの件数が多くてサイズ制限のためかブラウザからログを参照できないので、サーバにログインして内容を確認する作業が必要になってしまします。

可能であれば、録画準備段階のログは記録・カウントしないよう変更していただけるとありがたいです。

**Comment by l3tnun** [comment]
>録画準備段階(番組開始前15秒間)で発生したscramblingが記録されてしまいます。

15秒ではなく mirakurun の`maxBufferBytesBeforeReady`と`eventEndTimeout`の各マージン部分がスクランブル解除できていないのではないでしょうか？
epgstation としては mirakurun から取得したストリームのどこまでが各マージンなのか判断できないので実装は難しそうです。
