### ISSUE TITLE
ドロップログ

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#493]
### 環境
Version of EPGStation: 2.3.3
Version of Mirakurun: 3.5.0
Version of Node: 14.17.0
Version of NPM: 6.14.13
OS:Windows10
Architecture: x64

### Issue
これまでのドロップログが亡くなるとどの番組を消すか等がわからなくなります。
ドロップログをv1→v2に引き継ぐ方法ありませんでしょうか。

**Comment by l3tnun** [comment]
v1とv2で保存方法が変化したため対応していません。
技術的に不可能ではないですが、リソースが足りないのと私の興味がないので実装予定はないです。

**Comment by ohmsa** [comment]
v1の頃の録画で失敗してるのを消したかったので残念です。
