### ISSUE TITLE
録画実行中に当該番組を含む予約ルールを作成すると二重で録画が実行される

### ISSUE THREAD

**Issue by airport-tengai** [l3tnun/EPGStation#494]
### 環境
* Version of EPGStation: `2.3.8`
* Version of Mirakurun: `3.5.0`
* OS: Ubuntu 20.04 (on Docker)
* Architecture: x64

### Issue
ある番組を録画実行中に、その番組が対象となるようなワードで新規ルールを作成します。
すると、録画中リストに、今録画実行中のものと同じ番組がもう一つ追加され、その時点から新規に録画実行し始めます。
（なお、実際に出来上がる録画ファイルは (1) が付加されており、実際に問題なく録画は完了します）

ルールを追加した際、その時点で録画中の番組がある場合は、それを除外して多重録画しないように修正していただけないでしょうか。

**Comment by l3tnun** [comment]
本来手動予約が優先されなければならないので、バグっぽいですね。
ちなみにルールを追加する前の予約って時刻指定の手動予約では無いですよね?

**Comment by airport-tengai** [comment]
はい、時間指定ではなく、番組表から選択して録画したものです。
ただ、今回遭遇したケースでは、事前予約ではなく番組放送開始後に番組表から予約し、即時録画開始しています。

**Comment by l3tnun** [comment]
回答ありがとうございます。
バグなので調査してみます。

**Comment by l3tnun** [comment]
最新の master で修正しましたので閉じます。
ルール更新時に影響のある予約情報を取り出して比較を行っているのですが、SQLのミスで手動予約が正常に取り出せていなかったことが原因でした。
