### ISSUE TITLE
エンコード後にサムネイルを再生成する機能

### ISSUE THREAD

**Issue by kyori19** [l3tnun/EPGStation#496]
### Issue

機能要望です。

現在、録画終了後にサムネイル生成コマンドが走り、エンコードが実行される仕様になっているかと思うのですが、エンコードが成功した後にエンコード後の動画ファイルを使用してサムネイルを生成し直す機能が欲しいです。

現在のサムネイル生成では、冒頭のかなりの時間がCMになっている番組ではCM部分がサムネイルになってしまいます。すべての番組でCMでない秒数を探すのは非常に困難です。
そこで、エンコードでCMカットを実行しているので、CMカット後のファイルでサムネイルを生成すればCM部分がサムネイルになることを避けられるだろうという意図です。

方法としては、エンコード成功時にサムネイル生成コマンドを再実行する設定を追加したり、エンコードコマンドにサムネイル生成に必要な環境変数を与えてエンコード処理の中で自由にサムネイルを生成できるようにしたりなどが考えられるかと思います。
検討お願いします。

**Comment by l3tnun** [comment]
最新の master にて以下の機能を追加しました。

* エンコード完了後にコマンドを実行する機能 ([encodingFinishCommand](#encodingfinishcommand))
* サムネイルの削除を行う api (DELETE: /api/thumbnails/{thumbnailId})
* サムネイルの追加生成を行う api (POST: /api/thumbnails/videos/{videoFileId})

以上で目的が達成できるかと思います。

**Comment by kyori19** [comment]
ありがとうございます。
以下の設定で問題なくサムネイル更新ができました。

config.yml
```yml
encodingFinishCommand: '/app/config/update-thumbnail.sh'
```

update-thumbnail.sh
```sh
#! /bin/sh

if [ "$MODE" = "H.264 (JLSE)" ]; then
  curl -sX DELETE http://localhost:8888/api/thumbnails/$(curl -sX GET http://localhost:8888/api/recorded/$RECORDEDID?isHalfWidth=true | jq .thumbnails[0])
  curl -sX POST http://localhost:8888/api/thumbnails/videos/$VIDEOFILEID
fi
```

最後に、ドキュメント内で環境変数 `MODE` が `NODE` になっていたのが気になったのでお伝えしておきます。
https://github.com/l3tnun/EPGStation/blame/b31633de17284fb13453c94701eee3c985667c52/doc/conf-manual.md#L789
