### ISSUE TITLE
【要望】config.yml に CORS ヘッダーを付与できる設定を追加してほしい

### ISSUE THREAD

**Issue by tsukumijima** [l3tnun/EPGStation#499]
### 環境
機能要望ですので省略します。
* Version of EPGStation: `x.x.x`
* Version of Mirakurun: `x.x.x`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64

### Issue
EPGStation をバックエンドとして利用する [elaina](https://github.com/ci7lus/elaina) という Web アプリがありますが、elaina を使う場合、フロントエンドのみで API である EPGStation との通信はブラウザ側の XHR で行うため、必然的に EPGStation 側に CORS ヘッダーを付与する必要があります。
実際に elaina を導入したのですが、どうやら同じホストでポートが異なるだけの場合でも CORS は適用されてしまうらしく、CORS エラーで EPGStation との API 通信ができない状態になってしまっていました。
elaina の README にもある通り、本来は前段に nginx などの Web サーバーを置いてそちらでヘッダーの設定をするのが正しいやり方だとは思うのですが、私はローカル内でしか使っておらず、さらに構築環境が Windows ということもあって、これだけのために nginx を入れるのが億劫でした。

そこで、私の方で EPGStation を少しだけいじり、CORS ヘッダー (Access-Control-Allow-Origin: *) を API レスポンスに付与できるようにして、（場当たり的ではありますが）ひとまず解決しました。
具体的には、

- `cors` ライブラリを `npm install cors` でインストールする
- [src/model/service/ServiceServer.ts](https://github.com/l3tnun/EPGStation/blob/master/src/model/service/ServiceServer.ts) に `import cors from 'cors';` を追加
- [src/model/service/ServiceServer.ts](https://github.com/l3tnun/EPGStation/blob/master/src/model/service/ServiceServer.ts) の `init()` に `this.app.use(cors());` を追加

のような変更を加えています。
もちろん設定を読み込むとなるともう少し手をいれることになると思いますが、それでも簡易な変更で実装できると思います。

もちろん CORS ヘッダーをすべて許可する事による諸々の危険性は理解しているつもりですし、全ての環境で CORS を許可するようにとは全く言いませんが、一つの選択肢として、config.yml でオプトインする形で CORS ヘッダーを EPGStation 側で付与できてもいいのではないかと思い、ご提案させていただきます。

**Comment by l3tnun** [comment]
config.yml での CROS の設定できるようにしたいと思います。

**Comment by l3tnun** [comment]
雑な対応ですが、最新の master にて対応しました。

`config.yml` に ```isAllowAllCROS: true``` と追記すればCORS ヘッダーをすべて許可します。
細かな制御が必要になったら別途対処します、

**Comment by hideo54** [comment]
失礼します。
諸々の名前が CROS になってしまっている他、[cors](https://www.npmjs.com/package/cors) ではなく [cros](https://www.npmjs.com/package/cros) という関係のないパッケージもインストールされてしまっています。**正しくは CORS です!** ご対応ください…!

**Comment by tsukumijima** [comment]
> config.yml に isAllowAllCROS: true と追記すればCORS ヘッダーをすべて許可します。
細かな制御が必要になったら別途対処します。

素早い対応ありがとうございます！
…が、すでに他の方が指摘されているように<s>まさかの</s> **CORS** が **CROS** になってしまっているので、そこだけ修正していただければと思います。

**Comment by l3tnun** [comment]
うわーやらかしました。
修正します。

**Comment by l3tnun** [comment]
修正しましたので完了とします。

**Comment by tsukumijima** [comment]
早速導入して試しましたが、isAllowAllCORS を true に設定しても CORS ヘッダーが付与されていませんでした。
ServiceServer.ts をいじって確認した所、どうやら `this.app.use(cors());` は `this.initOpenApi(api);` より前に実行しないと効果がないようです。
そのようにコードを変更して `npm run build-server` したところ、CORS ヘッダーが無事付与されるようになりました。
以上、申し訳ありませんが修正頂けると助かります。

**Comment by l3tnun** [comment]
これは失礼しました。
v2.4.2 で修正しましたので確認お願いします。

**Comment by tsukumijima** [comment]
Access-Allow-Control-Origin: * がヘッダーに付与されていることを確認できました。ありがとうございました。
