### ISSUE TITLE
「録画済み」一覧に録画されたファイルのサイズを表示したい

### ISSUE THREAD

**Issue by thorgeo** [l3tnun/EPGStation#50]
表題の機能の実装を考えていて、まずはrecordedテーブルにfilesizeカラムを追加しようと思ったのですが、
現在db migration相当の機能はありますか？
またなければ今後実装予定のもの（独自または既存のツールなど）がありましたら教えていただけるとありがたいです。

（EPGStationは例の新刊で知って、スマホのUIがよくてすごくワクワクしているので、今後の展開にも期待しています :+1: ）

**Comment by l3tnun** [comment]
db migration 相当の機能はないです。
ただテーブルへのカラムの追加などはそのうち必要になるだろうなとは考えていましたので、
テーブル定義更新のための仕組みを追加しようと思います。
作業量が多くなりそうなので気長にお待ち下さい。

新刊読んでいただけましたか！ありがとうございます。
Chinachu Air 登場までの繋くらいに考えていますので、期待せずに見守っていもらえたらなと思います。

**Comment by l3tnun** [comment]
@thorgeo devel ブランチにて実装しました。

DOWNLOAD タブにてサイズ表記を追加しました。
特に問題がなければ master へマージします。

![2018-01-28 14 11 44](https://user-images.githubusercontent.com/16516088/35479347-59a34380-0438-11e8-8d37-60a7a80365b5.png)

**Comment by thorgeo** [comment]
ありがとうございます！
早速 devel ブランチ試します

**Comment by l3tnun** [comment]
すいません、DBに不可逆な変更を加えるので注意してください

**Comment by thorgeo** [comment]
![2018-01-28 18 03 16](https://user-images.githubusercontent.com/1241156/35483106-789f00f0-0481-11e8-93d7-3ea17c44a1b0.png)

確認できました！しばらく運用してみます
ありがとうございました！！

**Comment by l3tnun** [comment]
master にマージしましたので閉じます
