### ISSUE TITLE
【要望】各 API の番組情報の extended（番組詳細）プロパティを見出しと本文に分割してほしい

### ISSUE THREAD

**Issue by tsukumijima** [l3tnun/EPGStation#500]
### 環境
機能要望ですので省略します。
* Version of EPGStation: `x.x.x`
* Version of Mirakurun: `x.x.x`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:
* Architecture: x64

### Issue
EPGStation をバックエンドに利用した、新しいテレビ視聴 Web アプリの開発を計画している者です。

<img width="1226" alt="748" src="https://user-images.githubusercontent.com/39271166/122270795-a5ef7d80-cf19-11eb-804c-b274a9863051.png">

さて、現在の EPGStation の番組情報が返る API のレスポンスはすべて、番組情報内の `extended`（番組詳細）プロパティが一つの文字列にまとめられていると思います。

<img width="1269" alt="746" src="https://user-images.githubusercontent.com/39271166/122255083-be0ad100-cf08-11eb-992c-ee32a6811ba3.png">

一方、Mirakurun 側の API レスポンスでは、画像の通り `extended` プロパティは見出し（`◇番組内容` `◇出演者` のようなもの）がキー、本文が値の連想配列の形で返ってきています。

<img width="641" alt="749" src="https://user-images.githubusercontent.com/39271166/122271940-f3b8b580-cf1a-11eb-9a0b-b36608cda71e.png">

現在計画中の新しいテレビ視聴 Web アプリでは、このデザイン（仮）のように番組詳細の表示を見出しと本文で分けたいと考えています。ですが、EPGStation 側の API で番組詳細がすべて一つの文字列になっているのが障壁です。
見出しが一緒になっていても番組詳細を確認する機能自体には支障しませんが、見出しと本文で分けられていた方が、画像の通りメリハリがあって見やすく分かりやすいと思っています。

Mirakurun 側の API を使えばなんとかなる問題ではあるのですが、情報の取得元の API はできれば統一したいですし、もし可能であれば、extended（番組詳細）プロパティを Mirakurun のように見出しと本文で分割していただけないでしょうか。
もちろん互換性などの兼ね合いもありますでしょうし、`extended` とは別のプロパティとして用意していただいても構いません。詳細な実装手法はそちらにおまかせします。

EPGStation 本体とあまり関係ない要望かつこちら側の勝手な要望で申し訳ないのですが、ご検討のほどよろしくお願いいたします。

**Comment by l3tnun** [comment]
おお、デザインカッコいいですね。

`extended` が分割されていない理由ですが、主に DB 側が原因です。
MySQL や SQLite3 で `extended` のような構造のデータを持ちにくいためです。

Mirakurun の `extended` を `JSON.stringify` にかけて丸々文字列として DB へ保存し、
api で返す際に `JSON.parse` で復元して返すという力技も出来ますが、
番組表データ取得時 (`/api/schedules`) にそれを行うのはデータ数が多くて無理があるなあと思った為です。
(実際に試していないので、実はそんなに負荷は重くないとかはあるかもしれませんが)

そのため、Mirakurun の extended を `JSON.stringify` にかけた文字列データを格納したプロパティを追加するくらいが落とし所かなぁと思いますがどうでしょうか?

**Comment by tsukumijima** [comment]
ありがとうございます。

>extended が分割されていない理由ですが、主に DB 側が原因です。
MySQL や SQLite3 で extended のような構造のデータを持ちにくいためです。

>Mirakurun の extended を JSON.stringify にかけて丸々文字列として DB へ保存し、
api で返す際に JSON.parse で復元して返すという力技も出来ますが、
番組表データ取得時 (/api/schedules) にそれを行うのはデータ数が多くて無理があるなあと思った為です。

たしかに RDB で階層構造のデータは持ちにくいですよね…
`JSON.parse()` することでそこまで負荷がかかるともあまり思えませんが、ラズパイなどの低スペックな環境だとパフォーマンスに影響することがもしかするとあるかもですね。

>そのため、Mirakurun の extended を JSON.stringify にかけた文字列データを格納したプロパティを追加するくらいが落とし所かなぁと思いますがどうでしょうか?

了解です。もともとこちらの勝手な要望ですし、JSON はこちら側でパースすればいいだけなので、文字列であることに関しては問題ありません。
よろしくお願いします。

**Comment by l3tnun** [comment]
最新の master にて対応しました。

以下の api で `rawExtended` というパラメータを追加しました。

* GET: /api/recorded
* GET: /api/recorded/{recordedid}
* GET: /api/recording
* GET: /api/reserves
* GET: /api/reserves/{reserveId}
* \*: /api/schedules*
* GET: /api/streams

Mirakurun の `extended` を `JSON.stringify` にかけた文字列データにする予定でしたが、api で返す際に `JSON.parse` で復元して返すようにしました。

なお、以下の api では query で `needsRawExtended` を true に指定しないと `rawExtended` が取得できないので注意してください。
(負荷が不明なのでデフォルトでは false になっています)

* GET: /api/schedules
* GET: /api/schedules/{channelId}

**Comment by tsukumijima** [comment]
素早い対応ありがとうございます！ まさかこんなに早く実装していただけるとは…

> Mirakurun の extended を JSON.stringify にかけた文字列データにする予定でしたが、api で返す際に JSON.parse で復元して返すようにしました。

>なお、以下の api では query で needsRawExtended を true に指定しないと rawExtended が取得できないので注意してください。

了解しました。フラグが付与されている時だけなら負荷の問題もなさそうですね。
早速更新させていただきます。

一つだけ、録画ファイルの情報を表示する API ( /api/recorded など) にも rawExtended の情報が含まれるとのことですが、以前に録画した録画ファイルの rawExtended はどのような値になるのでしょうか？
もっとも、開発中のテレビ視聴アプリでは指定フォルダ内の録画ファイルを直で検索し、ファイルが MP4 など TS 以外で番組情報が取得できなかった場合のみ EPGStation の API から番組情報を取得するつもりでいます。ですので、rawExtended が取得できなくてもそこまで問題はありません。

よろしくお願いします。

**Comment by l3tnun** [comment]
> 以前に録画した録画ファイルの rawExtended はどのような値になるのでしょうか？

データが生成できないので 各 api ではプロパティなし (=undefined) となります。

番組情報生成時に下記のように見出しの先頭に `◇` が存在しない場合、先頭に `◇` を追加しているので、
頑張れば `rawExtended` がない録画データでも `extended` から見出しと本文を分離したデータは取れるかもしれません。

https://github.com/l3tnun/EPGStation/blob/7d2aa78a37119d0bf7fd52e203ebd4a45cc48425/src/model/db/ProgramDB.ts#L240-L244

**Comment by tsukumijima** [comment]
> データが生成できないので 各 api ではプロパティなし (=undefined) となります。

了解です。プロパティ自体が存在しない形ですね。

> 番組情報生成時に下記のように見出しの先頭に ◇ が存在しない場合、先頭に ◇ を追加しているので、
頑張れば rawExtended がない録画データでも extended から見出しと本文を分離したデータは取れるかもしれません。

以前からその仕様なんですね。であれば先頭に ◇ がある行かどうかの判定である程度分離できそうです。
ありがとうございました！
