### ISSUE TITLE
openAPIへのPOSTリクエストで予約追加できない

### ISSUE THREAD

**Issue by soichiro-oda** [l3tnun/EPGStation#501]
### 環境
* Version of EPGStation: `2.3.10`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.17.1`
* Version of NPM: `6.14.13`
* OS:ubuntu 18.04LTS
* Architecture: x64

### Issue
swaggerのopenAPIにてブラウザから（またはdocker-composeのpythonのコンテナ内で実行しても）
http://localhost:8888/api/reservesに対してPOSTリクエストをするとエラーが出てしまう。
尚、http://localhost:8888/api/reserves/update（POST）やhttp://localhost:8888/api/channels（GET）はcode200が返ってくる。

* request body
{
      "allowEndLack": true,
      "tags": [0],
      "saveOption": {
        "parentDirectoryName": "recorded"
      },
      "encodeOption": {
        "mode1": "H.264",
        "encodeParentDirectoryName1": "recorded",
        "directory1": "encoded",
        "isDeleteOriginalAfterEncode": false
      },
      "timeSpecifiedOption": {
        "channelId": 3274101064,
        "startAt": 1624273200000,
        "endAt": 1624275000000
      }
}

* response(1回目の実行)
{
  "code": 500,
  "message": "Internal Server Error",
  "errors": "Cannot read property 'replace' of undefined"
}

* response(2回目以降の実行)
{
  "code": 500,
  "message": "Internal Server Error",
  "errors": "IPCTimeout"
}

**Comment by l3tnun** [comment]
timeSpecifiedOption に name (string) を追加してください。
すいません、/reserves の schema 定義に漏れていました。
後で修正します。
あと、tagは UI の準備ができていないので注意してください。

あと、２回目以降 IPCTimeout エラーとなってしまうのは、不正な予約処理側のロックが掛かっているように見えますね。
バグっぽいので調査します。

**Comment by soichiro-oda** [comment]
ご確認ありがとうございます。
timeSpecifiedOptionにnameを加えたら予約追加できました。

取り急ぎのご報告にて失礼します。
引き続きよろしくお願い致します。

**Comment by soichiro-oda** [comment]
五月雨に失礼致します。

予約時のオプションで
録画したm2ts、mp4データのファイル名を指定するキーはございますでしょうか。
（timeSpecifiedOptionのnameはファイル名ではないと存じます）

恐れ入りますが、ご確認いただけますと幸いです。

**Comment by l3tnun** [comment]
POST: /reserves の schema の定義を読んでください。
saveOption の recordedFormat が一番近いかと思います。

**Comment by l3tnun** [comment]
最新の master にて修正完了しましたので閉じます。

**Comment by soichiro-oda** [comment]
schema確認させていただきます。
ご返信およびご対応いただきありがとうございました。
