### ISSUE TITLE
【要望】CSの番組表のチャンネルソート基準をserviceIdにしてほしい

### ISSUE THREAD

**Issue by airport-tengai** [l3tnun/EPGStation#502]
### Issue

CS 番組表のチャンネル順が `channel.id` 順になっており、一部放送局で隣り合わせにならないケースがあります。
具体的には、TBSチャンネル1、2で、それぞれ

* TBSチャンネル1
  * channel.id: 600296
  * channel.serviceId: 296
* TBSチャンネル2
  * channel.id: 700297
  * channel.serviceId: 297

となっており、同一事業者の両チャンネルの間に多数の放送局が割り込まれて表示されます。

https://github.com/l3tnun/EPGStation/blob/5b3ac5fae6e1187933ce0d48528ffc10c347ebd1/src/model/db/ChannelDB.ts#L173
https://github.com/l3tnun/EPGStation/blob/5b3ac5fae6e1187933ce0d48528ffc10c347ebd1/src/model/db/ChannelDB.ts#L193

上記を見ると、地上波では `channel.remoteControlKeyId` 順でソートされるため問題ありませんが、CS では `channel.remoteControlKeyId` が NULL のため、次点の `channel.id` でソートされています。
（BS も同様ですが、channelId と sid のオーダーが同じため、影響は出ていません）
W/A として設定ファイルに `sidOrder` 項目を追記し、全サービス ID を指定する方法がありますが、件数が多いため、デフォルトの挙動であってほしいと思いました。

つきましては、ソート基準として `channel.serviceId` を `channel.remoteControlKeyId` の次点に追加することをご検討いただけないでしょうか。

**Comment by l3tnun** [comment]
詳しい説明ありがとうございます。

> つきましては、ソート基準として `channel.serviceId` を `channel.remoteControlKeyId` の次点に追加することをご検討いただけないでしょうか。

次のバージョンでそのように変更します。

**Comment by l3tnun** [comment]
最新の master にて対応しましたので、閉じます。
