### ISSUE TITLE
コマンド解釈の改善

### ISSUE THREAD

**Issue by kyori19** [l3tnun/EPGStation#506]
### 環境

* Version of EPGStation: `2.5.0`

### Issue

#355 でも少し問題が発生していたようですが、 `config.yml` で表現するのが困難なコマンドが多いので、全体的に解釈を改善していただきたいです。

- [ ] 実行ファイル内での `%ROOT%` の解釈
  `args` 内では `%ROOT%` がアプリケーションのルートに置換されますが、実行ファイルでは置換されないので `%ROOT%/config/hoge.sh` のように実行ファイルを指定することができません。
- [ ] `spawn` に `shell: true` パラメータの付与
  コマンド内で環境変数を利用したいときに `$RECORDEDID` などを文字列に加えても、環境変数として解釈されないので途中で別のシェルスクリプトなどを噛ませる必要があります。
  コマンド全体を `/bin/sh -c` に通すことでシェルに通すことはできますが、環境変数が引き継がれないので対策になりません。
  `shell: true` を設定すると実行するコマンドがシェル上で実行されるようになるので、コマンド内の環境変数が解釈されるのに加えて複数コマンドをパイプでつなぐこともできるようになるのでメリットは大きいと思います。
- [ ] コマンド入力を文字列ではなく配列に変更
  現在空白をコマンド文字列に加えるためには `%SPACE%` でエスケープする必要がありますが、 `sh -c` にコマンド文字列を渡そうとすると渡すコマンド内のスペースを全て `%SPACE%` にしなければならないので実用的ではありません。
  (複数コマンドを渡そうとするなどすると `sh -c touch%SPACE%%ROOT%/testfile1%SPACE%&&%SPACE%touch%SPACE%%ROOT/testfile2` などとする必要がある。)
  配列の区切りがわかればスペースで配列に分解する必要がなくなるので、DockerfileのCMDの書式( `CMD ["/bin/sh", "/opt/script.sh"]` )を参考にして配列で入力できるようにすることを提案します。

3番目を採用した場合、過去のバージョンのコンフィグファイル内の記述が使用できなくなってしまうので、文字列形式と配列形式の双方を受け入れるようにするか後方互換性を切るかのどちらかを選ばなければならないので、意見を伺いたいです。

**Comment by tobitti0** [comment]
横から出すみません。少し疑問に思ったので質問させてください。

個人的にconfig.ymlにすべてのコマンドを書くことはconfig.ymlの保守性が下がると思います。
複数のコマンドをつなげるのであればバッチファイルなりを作成したほうが良いのではと思いますが、EPGStationのコマンド解釈を大きく変えてまでもconfig.ymlにすべてのコマンドを記載するメリットとは何があるのでしょうか。

**Comment by kyori19** [comment]
@tobitti0 #496 の確認中にコマンドを設定しようと思ってコンフィグに複数行でコマンドを入れてみたらうんともすんとも言わなくて謎だったので色々調べてみたらそもそもこの形式でコマンド入力できなくないか？と思った次第です。

(当初設定していたコマンド)
```yml
encodingFinishCommand: |
  /bin/sh -c "if [ \"$MODE\" = \"H.264 (JLSE)\" ]; then
    curl -sX DELETE http://localhost:8888/api/thumbnails/$(curl -sX GET http://localhost:8888/api/recorded/$RECORDEDID?isHalfWidth=true | jq .thumbnails[0])
    curl -sX POST http://localhost:8888/api/thumbnails/videos/$VIDEOFILEID
  fi"
```

コンフィグファイルの保守性については個人の感覚の問題だと思うので議論して結論が出るようなものではないと思いますが、少なくとも自分は「これくらいなら別ファイルを切るほどでもなくない？」と思いますし、「コマンドっていうくらいだからこれで動くやろ」と判断しました。(保守性の話をするならFFmpegのコマンドの記述のほうが大概だと思います。)

質問に対する回答としては、「実行できるコマンドに制限があって、その仕様が明記されていない(どこかにあったらすいません)状態を改善することができる」「環境変数を利用して簡単な(1行程度の)コマンドを実行することができるようになる(今の状態では1本のcurlに環境変数を入れることすらできない)」などになるでしょうか。

コマンド解釈を変えたいとは言っても他のユーザーに迷惑を掛けることが目的ではないので、上2つの提案については変更しても既存の設定が壊れることはないと考慮して提案していますし、3番目については互換性を保つのが大変なので、互換性を保ちながら変更する方法を提案しながら「意見を伺いたい」としているつもりです。

**Comment by tobitti0** [comment]
@kyori19 丁寧にご教示いただきありがとうございます。
単純に疑問に思い質問させていただいただけでして、不快に思われたなら謝罪いたします。
自分としてはドキュメントに記載されている外部コマンド例がすべて外部スクリプトを呼び出すものですから、そういう使用用途を想定しているのだなと判断しています。
仕様が明記されていないという点については確かに記述があったほうが丁寧ではあると思います。

なお、EPGStationにおいては過去コマンドのパイプについては見送られた経緯があったと思い探しました。
こちら#273 になります。
V1の頃の話で、現在は問題がないかもしれませんが…
ご参考ください。

**Comment by kyori19** [comment]
@tobitti0 こちらこそ攻撃的な姿勢になってしまってすいませんでした。
過去の文脈は掴めていなかったので助かります。子プロセスを殺せないという問題は確かにあるかもしれませんね…

**Comment by l3tnun** [comment]
> - [ ] 実行ファイル内での `%ROOT%` の解釈

`args` とは `ProcessUtil` の `parseCmdStr` 関数を指していますか？
確かにそのとおりですね。これは置換されるように変更します。

> - [ ] `spawn` に `shell: true` パラメータの付与

基本的に外部スクリプトを呼び出すことしか想定していないです。
プロセスの扱いが変わりそうなので、実装できるかは不明です。

> - [ ] コマンド入力を文字列ではなく配列に変更

基本的に @tobitti0 のおっしゃるとおりで、#273 の問題は v2 でも健在です。
そのため、コマンドをパイプでつなぐことはできないです。
基本的に外部スクリプトと簡単な引数くらいしか想定していなかったので、今の仕様となっています。
技術的に配列化することは可能ですが、このような制約の下だとあまりメリットが無いかなあと思っています。

**Comment by kyori19** [comment]
子プロセスを殺すことができない問題を嫌うのであれば `shell: true` が適用できないので、この提案は全体的に無意味ですね。
nodeで走らせることが前提であれば実行ファイルパスで `%ROOT%` を解釈する必要もないと思うので無視して大丈夫です。
jsでスクリプトを書く文化を知らなかったために皆さんにはご迷惑をおかけしました。closeします。
