### ISSUE TITLE
mp4にエンコードした際の字幕格納に関して

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#511]
### 環境
* Version of EPGStation: `2.6.0`
* OS: alpine
* Architecture: x64

### Help

TSからmp4にエンコードした際字幕があるものはmp4にしても字幕を格納したいのですが，知識不足のため方法がわかりません
お手数ですが，サンプルのenc.jsファイルなど作成をお願いできないでしょうか

**Comment by l3tnun** [comment]
私もそこら辺の知識がなくてなんとも答えられないです。

字幕の表示方法によっても方法が異なりますが、一般的な動画再生ソフトで表示させる場合、
おそらくこちらの記事が参考になるかと思います。
https://nico-lab.net/libaribb24_with_ffmpeg/

ffmpeg で HLS 配信した際には以下の記事を参考に実装しました。
https://nico-lab.net/hls_with_aribb24sub/


EPGStation で表示させる場合は #485. #490 で一部対応可能です。
全然実装できていないので、先の話になりますが。

今すぐにという話であれば、monyone さんが上げてくれた以下のエンコードスクリプトを参考に、
mp4ではなくtsとしてエンコード（字幕をID3に変換）して、エンコードしたものを HLS 配信すれば実現できるかと思います。
HLS 配信時に video は copy でよいと思いますので、再生時の負荷はかなり少ないかと思います。

https://gist.github.com/monyone/2d1e9f3c764ea174e8b0714eea0c9dec

**Comment by 5ym** [comment]
情報ありがとうございます
参考にしてdockerの方で実行できるように検証してみます
動きましたら参考用にdockerのリポジトリの方にプルリクエスト送らせていただきますよろしくお願いします

**Comment by 5ym** [comment]
コマンドを直接実行した際は成功するのですが，enc.jsを介してエンコードしようとすると即時終了してしまい原因がわかりません
enc.js内をデバックする方法はありますでしょうか

**Comment by 5ym** [comment]
また追加で質問なのですが，isDualMonoのところの動作が正常位動作していないように見えるのですが，これはどういったものなのでしょうか
エンコード後のファイルを実際に視聴してみると同じ音声が再生されます
エンコード前<->エンコード後
![image](https://user-images.githubusercontent.com/13718335/126792226-c85802d5-c94c-4f4e-8c56-0d944478ed1f.png)
![image](https://user-images.githubusercontent.com/13718335/126792298-924b1bf7-6f58-40b6-9409-b461d7b35b84.png)

**Comment by l3tnun** [comment]
`enc.js` のデバッグ方法としては、enc.js 内で出力された標準エラー出力をログに残すことができるのでそれを活用します。
出力先は `logs/Service/encode.log` になります。

まず、`config/serviceLogConfig.yml` の `categories -> encode -> level` を `info` から `debug` に変更して epgstation を再起動してください。

次に`enc.js`で確認が必要なものを、標準エラーで出力するようにします。
下記のコードで `test` とログに出力されます。

```
console.error('test')
```

---

dualmono について

https://github.com/l3tnun/EPGStation/blob/899541f2b6d716453a30b9c1589c76602b8d902a/config/enc.js#L11

https://github.com/l3tnun/EPGStation/blob/899541f2b6d716453a30b9c1589c76602b8d902a/config/enc.js#L20-L22

これは epg 情報を元にセットされた環境変数 `AUDIOCOMPONENTTYPE` を使用して、
エンコードに使用する TS ファイルの音声がデュアルモノであるかを判定するロジックになっています。

`ffmpeg` の `-dual_mono_mode` の挙動なのですが、
`-dual_mono_mode main` とすると主音声が抽出され、
`-dual_mono_mode sub`とすると副音声が抽出されるようです。
なので、両方の音声を保持したいという場合は #244 の下記コメントのように処理してあげればよいです。
https://github.com/l3tnun/EPGStation/issues/244#issuecomment-468928190

ただし、#244 の下記コメントで言及されている通り、 ffmpeg/ffprobe と MPEG2-TS の問題があるので、実装は困難だと思います。
https://github.com/l3tnun/EPGStation/issues/244#issuecomment-469150758

**Comment by 5ym** [comment]
回答ありがとうございます
debianのdockerfileがまだできていませんが先ほどプルリクの方作成いたしました
その他の更新も含めていますが合わせて確認いただけると助かります

**Comment by l3tnun** [comment]
プルリクありがとうございます。
確認しますね。
