### ISSUE TITLE
「ストレージ」メニューを開こうとすると「ストレージ情報取得に失敗」と表示される

### ISSUE THREAD

**Issue by Mon4455** [l3tnun/EPGStation#513]
### 環境
* Version of EPGStation: `2.5.2`, `2.6.0`
* Version of Mirakurun: `3.6.0`, `3.7.0`
* Version of Node: `12.18.0`
* Version of NPM: `6.14.4`
* OS: Windows Server 2019 (1809)
* Architecture: x64
* EPGStation はWindowsサービス(winser)として稼働。Mirakurun は別PC(Linux上)で稼働。

### Issue
いつも大変お世話になっております。
EPGStationをv1時代から便利に利用させていただいております。
さて、先日、v2に新規に環境構築し直しさせていただきましたところ、タイトルの事象が発生しました。いろいろとネット上でも調べてみましたが、同様の問題が発生している事例が見当たらなかったため、こちらに投稿いたしました。
EPGStationのVer.アップ時も新規に環境構築（但し、config.ymlはv2.5.2を流用）しましたが、特に変化はみられませんでした。
録画データ自体は指定パスに正常保存されWebページ上での再生も問題ないため、ストレージ自体のファイルアクセスには問題ないようです。
v1では空き容量のグラフ表示も特に問題なかったため、もしお心当たりありましたらご教示ください。

[補足情報]
- config.ymlの指定
 recorded*関係項目で変更しているのは以下のみ。
"v"ドライブはローカルドライブ(NTFS)で、別のローカルドライブを指定しても症状変わらず。

```
recorded:
    - name: recorded
      path: 'v:\\recorded'
```

- 「ストレージ」をクリックした直後のブラウザのエラーコンソール情報 (Edgeで取得)
応答・・xhr.js:177 GET http://192.168.x.x:8888/api/storages 500 (Internal Server Error)
> Storages.vue:69   Error: Request failed with status code 500
>     at t.exports (createError.js:16)
>     at t.exports (settle.js:17)
>     at XMLHttpRequest.f.onreadystatechange (xhr.js:62)

どうぞよろしくお願いいたします。

**Comment by l3tnun** [comment]
おそらくですが、ディスク空き容量取得に使用している `diskusage-ng` が正しく動作していないことが原因だと思われます。
(v1 では `diskusage` を使用していたので問題がなかったのだと思います。)
そのため、空き容量取得以外には特に問題はありません。

申し訳ないですが、現状 Windows 環境で開発できる状態でない(& Windows環境を整備する気力がない)ので修正できる見込みはないです。

**Comment by Mon4455** [comment]
お忙しい中、ご返信いただきありがとうございました。
本件は他の方からの報告もないようですので、本件は`diskusage-ng`に関する当方の環境起因の固有問題と思います。
貴重なご意見ありがとうございました。

**Comment by Mon4455** [comment]
追伸；
本件の問題が生じる理由が判明しましたのでご報告いたします。

`diskusage-ng` v1.0.1 (win32.js) が内部実行しているWMICコマンドが返すドライブレター文字は半角大文字である一方、ライブラリ呼び出し元 (EPGStation側) から渡されるドライブレター文字列が大文字か小文字かを考慮せずそのまま評価しているようです。
そのため、config.yml の `recorded` 指定パスのドライブレターが小文字指定の場合、diskusage-ng` 側でドライブ名をマッチングできず、指定パスの対象ディスクを照会できないことがエラー原因のようです。

手動設定する場合は、以下のようにドライブレター部分を大文字で指定すれば正しくドライブのディスク使用量を参照できることがわかりました。
```
recorded:
    - name: recorded
      path: 'V:\\recorded'
```
※EPGStation側で設定される環境変数 `%ROOT%` のパスに含まれるドライブレターが仮に小文字表記となっている場合も同事象となると思われます。

パスの大文字小文字を区別しない仕様に関してはWindows環境固有の事象であり、修正対応いただくのは開発者様の重荷と推察しますので、同様の症状が発生した場合の対応策として、このIssue上での報告のみに留めさせていただきます。

以上です。

**Comment by l3tnun** [comment]
わざわざ調べていただきありがとうございます。

epgstation での対応は無しで issue を閉じさせて頂きます。
