### ISSUE TITLE
recordedテーブルのvideoComponentType列がnullになっている

### ISSUE THREAD

**Issue by scimmia9286** [l3tnun/EPGStation#515]
### 環境
* Version of EPGStation: `2.6.2`
* Version of Mirakurun: `3.7.1`
* Version of Node: `v14.17.4`
* Version of NPM: `6.14.14`
* OS: Ubuntu-20.04.1
* Architecture: x64

### Issue
外部コマンドへ渡されるVIDEOCOMPONENTTYPEが0になっていることで気付いたのですが、データベースのrecordedテーブルに格納されている全てのレコードにおいてvideoComponentType列がnullになっています。
ちなみにprogramテーブルのvideoComponentType列は正しい値が入っているようです。

**Comment by l3tnun** [comment]
報告ありがとうございます。
バグのようですね、確認します。

**Comment by l3tnun** [comment]
最新の master にて修正完了しました。
予約情報を生成するときに `videoComponentType` が抜け落ちていました。
