### ISSUE TITLE
誤字？

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#522]
### 環境
* Version of EPGStation: `2.6.5`
* Version of Mirakurun: `3.9.0`
* OS: Windows
* Architecture: x64

### Issue

細かい話ですし、こちらの勘違いかもしれませんが見つけましたので一応。
[2021-08-19T20:54:55.035] [ERROR] system - add recordgin error: 438

× recordgin → 〇 recording
ですかね。

...

**Comment by l3tnun** [comment]
報告ありがとうございます。
誤字ですね。次のバージョンで修正しますね。
