### ISSUE TITLE
【提案】すぐニュース機能

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#523]
### 環境
* Version of EPGStation: `2.6.5`
* Version of Mirakurun: `3.9.0`
* Version of Node: `v14.17.3`
* Version of NPM: `6.14.13`
* OS:Windows
* Architecture: x64

### Issue
せっかくEPGでジャンルがわかるので、緊急時等「なんでもいいからすぐにニュースが見たい」というときに
「放映中等の画面のアイコンをクリックすると、その瞬間のジャンル「ニュース・報道」が自動で選局されて視聴できる」
みたいなことが出来そうです。
・優先するチャンネルを設定可能（NHK＞地デジ＞BS＞CS）
・現在自動選局しているチャンネルのサムネイルがアイコン（30秒ごとに自動取得）
・視聴中に番組終了時は次点の優先チャンネルのニュースに選局
・視聴中も別のニュースをやっているチャンネルに選局可能
・トランスコード設定は一種類だけで、そのアイコンをクリックすれば自動的に再生が始まる
・（オプション）自動選局チャンネルは常にトランスコードされていて、クリックしたらすぐにみられる

他にも「天気予報だけダラダラ流したい」「今野球やってたよね」「なんかバラエティないかな」みたいな「とりあえずなんかやってないかな」に使えそうな気がします。

...

**Comment by l3tnun** [comment]
面白い機能ですが、実装負荷が高すぎるため epgstation では取り扱いません。
ご了承ください。
