### ISSUE TITLE
v1とv2のログ互換性

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#534]
### 環境
*Version of EPGStation: 2.6.11
*Version of Mirakurun: 3.9.0-beta
*Version of Node: 14.17.3
*Version of NPM: 6.14.13
*OS:Windows10
*Architecture: x64

### Issue
v1からv2に移行しようとしているのですが、ドロップしているかどうかの情報が引き継げたらと思っております。

同じ番組をv1とv2で録画してみたのですが、中身はほぼ同じなようです。移行した後にDropLogフォルダにうつしたらDropLogが見られたりしないでしょうか。

v1
`pid: 0x0000, error: 0, drop: 0, scrambling: 0, packet: 18073, name: PAT
pid: 0x0001, error: 0, drop: 0, scrambling: 0, packet: 181, name: CAT
pid: 0x0010, error: 0, drop: 0, scrambling: 0, packet: 903, name: NIT
pid: 0x0011, error: 0, drop: 0, scrambling: 0, packet: 9515, name: SDT/BAT
pid: 0x0012, error: 0, drop: 0, scrambling: 0, packet: 285402, name: EIT
pid: 0x0014, error: 0, drop: 0, scrambling: 0, packet: 362, name: TDT/TOT
pid: 0x0023, error: 0, drop: 0, scrambling: 0, packet: 334, name: SDTT
pid: 0x0024, error: 0, drop: 0, scrambling: 0, packet: 904, name: BIT
pid: 0x0401, error: 0, drop: 0, scrambling: 0, packet: 18073, name: -
pid: 0x0A01, error: 0, drop: 0, scrambling: 0, packet: 36145, name: -
pid: 0x1001, error: 0, drop: 0, scrambling: 0, packet: 12603058, name: MPEG2 VIDEO
pid: 0x1041, error: 0, drop: 0, scrambling: 0, packet: 180727, name: MPEG2 AAC
pid: 0x1051, error: 0, drop: 0, scrambling: 0, packet: 180727, name: MPEG2 AAC
pid: 0x1201, error: 0, drop: 0, scrambling: 0, packet: 2572, name: 字幕
pid: 0x1C13, error: 0, drop: 0, scrambling: 0, packet: 450, name: 字幕
pid: 0x1EA7, error: 0, drop: 0, scrambling: 0, packet: 120164, name: データカルーセル
`

v2
`pid: 0x0000, error: 0, drop: 0, scrambling: 0, packet: 18072, name: PAT
pid: 0x0001, error: 0, drop: 0, scrambling: 0, packet: 181, name: CAT
pid: 0x0010, error: 0, drop: 0, scrambling: 0, packet: 903, name: NIT
pid: 0x0011, error: 0, drop: 0, scrambling: 0, packet: 9515, name: SDT/BAT
pid: 0x0012, error: 0, drop: 0, scrambling: 0, packet: 285373, name: EIT
pid: 0x0014, error: 0, drop: 0, scrambling: 0, packet: 362, name: TDT/TOT
pid: 0x0023, error: 0, drop: 0, scrambling: 0, packet: 334, name: SDTT
pid: 0x0024, error: 0, drop: 0, scrambling: 0, packet: 904, name: BIT
pid: 0x0401, error: 0, drop: 0, scrambling: 0, packet: 18072, name: -
pid: 0x0A01, error: 0, drop: 0, scrambling: 0, packet: 36144, name: -
pid: 0x1001, error: 0, drop: 0, scrambling: 0, packet: 12602472, name: MPEG2 VIDEO
pid: 0x1041, error: 0, drop: 0, scrambling: 0, packet: 180719, name: MPEG2 AAC
pid: 0x1051, error: 0, drop: 0, scrambling: 0, packet: 180719, name: MPEG2 AAC
pid: 0x1201, error: 0, drop: 0, scrambling: 0, packet: 2572, name: 字幕
pid: 0x1C13, error: 0, drop: 0, scrambling: 0, packet: 450, name: 字幕
pid: 0x1EA7, error: 0, drop: 0, scrambling: 0, packet: 120159, name: データカルーセル
`
...

**Comment by l3tnun** [comment]
適切に DB に登録すれば見れます。
v2移行時にディレクトリの構成が変わったため、面倒なので対応しない事にしました。
