### ISSUE TITLE
HEVCにて再生がカクカクになる

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#536]
### 環境
* Version of EPGStation: `2.6.11`
* Version of Mirakurun: `3.9.0-beta.7`
* Version of Node: `14.17.3`
* Version of NPM: `6.14.13`
* OS:Windows
* Architecture: x64

### Issue
Edgeにて、h265（264はわかりません）視聴時に
0．数秒進む→逆再生→0．数秒進む→逆再生
というカクカク再生になります。
v1だと普通に再生できますし、該当番組をダウンロードして再生すると普通に再生できます。
mpeg2をライブだと滑らかに再生できます。

おま環である可能性は高いですが、V1では発生しないのと解消方法がわからないので
似たような現象が起きていた方や知見をお持ちの方いらっしゃいましたらお知恵を拝借したく。
...

**Comment by l3tnun** [comment]
issue として書くのであれば、再現確認ができるように手順を書いてください。

1. H.265の動画はどのように生成したものなのか? (録画した番組をエンコードしたものなのか、手動でアップロードしたものなのか)
2. 再生方法はなにか？webページでただ再生しているだけ(PLAY ボタンから再生)なのか、ストリーミングで変換して(STREAMING ボタンから再生)いるのか？

**Comment by ohmsa** [comment]
新規で作ったら出なくなりました。失礼しました
