### ISSUE TITLE
ffmpegを入れたdckerfileの扱い

### ISSUE THREAD

**Issue by 5ym** [l3tnun/EPGStation#541]
現状先日の更新でDockerfile.ubuntu-nvencを追加してると思うのですが，これだけffmpegを入れるのもおかしな話なので，docker-mirakurun-epgstationのプロジェクトのほうに移すのはいかがでしょうか

**Comment by kazuki0824** [comment]
あとから入れるというのがよく分かりませんが、マストな順序関係としては「ffmpegを入れるよりも前に入れないといけない」です。(ffmpegのビルドにCUDA専用のコンパイラnvccや付属のライブラリを使用するため)

イメージにバンドルされているものの話については、イメージの元になるDockerfileが公開されているので、既成のイメージに頼らずに自前でレシピを構築することも確かにできます。しかし、総ステップ数がそこそこあるのでFROMで持ってくる形にするのでいいんじゃないかと個人的には思っていました。

##補足
Dockerfileとしては3種類存在しています。順に入れ子になっていて、今回最も大きいdevelが必要です。(ffmpeg をビルドするため)
それぞれ中でNVIDIA公式のaptのリポジトリからdebを引っ張ってきてインストール、環境変数の設定という感じです。
これらを全部自分たちのリポジトリに書き写すのはナンセンスな気がしていたので、FROMでdevelを取ってくるという方法を採用しました

- [devel] https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.4.2/ubuntu2004/devel/Dockerfile
- [runtime] https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.4.2/ubuntu2004/runtime/Dockerfile
- [base] https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.4.2/ubuntu2004/base/Dockerfile

**Comment by 5ym** [comment]
情報ありがとうございます。
少し面倒ですが、既存のepgstationのイメージからビルド済みプロジェクトファイルだけ抽出してcudaのイメージ内で使用するというのはどうでしょうか

**Comment by 5ym** [comment]
下記のような感じです
```
FROM l3tnun/epgstation:master as build

FROM nvidia/cuda:11.4.1-devel-ubuntu20.04

COPY --from=builder /app /app/
```

**Comment by 5ym** [comment]
これなら記述を最小限でdocker-mirakurun-epgstationに統合できると思います

**Comment by l3tnun** [comment]
@kazuki0824 
EPGStation-nvenc-docker の作成ありがとうございます。
readme に反映させていただきました。

**Comment by kazuki0824** [comment]
とりあえず、それっぽい形になってきたので共有しておきます。

コンテナ単体をビルドするsingle-container.shとcomposeを使った環境を整えるsetup.shを用意しました。  
single-container.shは特に込み入った処理を行いませんが、  
setup.shでは内部的にdocker-mirakurun-epgstationをとってきて中身をコピーする処理が行われます。
https://github.com/kazuki0824/EPGStation-nvenc-docker
