### ISSUE TITLE
[質問]recordedFormatの仕様について

### ISSUE THREAD

**Issue by pinfort** [l3tnun/EPGStation#548]
### Issue
recordedFormatの仕様について質問です。現在私はchinachuを利用しており、EPGStationへの移行を考えています。現状、chinachuでは以下のようにrecordedFormatを設定して運用しており、可能であれば同等の設定をEPGStationに移行してからも維持したいと考えています。

```
"recordedFormat": "<category>/<title>/[<date:yymmdd-HHMM>][<type><channel>][<channel-name>]<title>#<episode>.m2ts"
```

例
```
hoge/recorded/anime/ラブライブ！虹ヶ咲学園スクールアイドル同好会/[210925-1735][GR26][ＮＨＫＥテレ１東京]アニメ　ラブライブ！虹ヶ咲学園スクールアイドル同好会（２）▽Ｃｕｔｅｓｔガール[字]#n.m2ts
```

これについてレポジトリ内の[設定マニュアル](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md)などを確認したところ、二点懸念があります。

 - recordedFormatに`/`を記入することによるフォルダ分けはできない認識でよろしいでしょうか？
   - 禁止文字エスケープ処理でエスケープされそうに見えました。
 - recordedFormatでcategory変数またはそれと同等のものは利用できない認識で正しいでしょうか。

**Comment by libnumafly** [comment]
@pinfort 
issueの時期が経過しておりますが、以下ご参考になれば幸いです。

上で masnagam さんが指摘されているのを含めてchinachuからの運用をそのまま持ち込むのはできないものかとは思われます。

ただ、予約の詳細設定を行うページで保存先のディレクトリとサブディレクトリを変更することは可能です。
その際にサブディレクトリ入力欄に`あいう/えお`と入力した場合は
━(保存先ルート)
　┗あいう
　　┗えお
のフォルダ階層が作成されて`えお`に保管されることとなります。

これはルール自動録画をする設定作成画面でも入力できますので、今までのフォルダ階層を崩したくない場合は
`anime/ラブライブ！虹ヶ咲学園スクールアイドル同好会`
のようにサブフォルダを設定すればよろしいかと。

**Comment by pinfort** [comment]
> @pinfort issueの時期が経過しておりますが、以下ご参考になれば幸いです。
> 
> 上で masnagam さんが指摘されているのを含めてchinachuからの運用をそのまま持ち込むのはできないものかとは思われます。
> 
> ただ、予約の詳細設定を行うページで保存先のディレクトリとサブディレクトリを変更することは可能です。 その際にサブディレクトリ入力欄に`あいう/えお`と入力した場合は ━(保存先ルート) 　┗あいう 　　┗えお のフォルダ階層が作成されて`えお`に保管されることとなります。
> 
> これはルール自動録画をする設定作成画面でも入力できますので、今までのフォルダ階層を崩したくない場合は `anime/ラブライブ！虹ヶ咲学園スクールアイドル同好会` のようにサブフォルダを設定すればよろしいかと。

ありがとうございます！その方法はよさそうですね。参考にします。
