### ISSUE TITLE
ReferenceError: AbortSignal is not defined

### ISSUE THREAD

**Issue by hinaloe** [l3tnun/EPGStation#551]
### 環境
* Version of EPGStation: `2.6.12`
* Version of Node: `v14.18.1`
* Version of NPM: `8.1.2`
* OS: Linux
* Architecture: x64

### Issue
今バージョンでmirakurun(APIクライアントとしての利用)が3.9.0-beta.17となっていますが、表題のようなnode v14と互換性のない変更が含まれてしまっているようです。(実際にはEpgStation上では`check mirakurun`のメッセージで無限ループします)

[3.9.0-beta.18で対処されている](https://github.com/Chinachu/Mirakurun/commit/ec0a93e56bee31846e4c0efc4c48f86c549789ac)ようなのでアップデートで解決します。

**Comment by l3tnun** [comment]
報告ありがとうございます。
修正します。

**Comment by l3tnun** [comment]
2.6.13 で修正しましたので閉じます。
