### ISSUE TITLE
api/videosが500エラー

### ISSUE THREAD

**Issue by hide74** [l3tnun/EPGStation#552]
### 環境
* Version of EPGStation: `2.6.12`
* Version of Mirakurun: `3.9.0-beta.18`
* Version of Node: `16.13.0`
* Version of NPM: `8.1.2`
* OS: Debian 5.10
* Architecture: x64

### Issue
api/videosを呼び出すと以下のように500エラーとなります。そのため、録画ファイル(TS)の視聴が出来ません。
{
  "code": 500,
  "message": "Internal Server Error",
  "errors": "MimeTypeError"
}

**Comment by l3tnun** [comment]
ビデオの拡張子をm2ts もしくは ts 以外に設定されていますか？
そのような場合、発生しうるかと思います。

**Comment by hide74** [comment]
mtsを設定しています。
tsに変更したところ、エラーでなくなりました。

**Comment by l3tnun** [comment]
問題ないようでしたらビデオの拡張子をm2ts もしくは ts で運用してください。

**Comment by hide74** [comment]
そのようにしたいと思います。
