### ISSUE TITLE
mac(Chrome)でm2ts(H.264)形式の録画ファイルの視聴ができない

### ISSUE THREAD

**Issue by hide74** [l3tnun/EPGStation#553]
### 環境
* Version of EPGStation: `2.6.12`
* Version of Mirakurun: `3.9.0-beta.18`
* Version of Node: `16.13.0`
* Version of NPM: `8.1.2`
* OS: Debian 5.10
* Architecture: x64

### Issue
mac上で録画ファイルのPlayボタンでH.264(m2tsファイル)にエンコードしたファイルを視聴しようとすると、プレイヤー画面に遷移しますが、再生が開始されません。
iPad及びAndroidのスマホでは、urlschemeで設定した外部アプリで視聴可能です。
mac上でも同様の挙動にできないでしょうか？

**Comment by hide74** [comment]
設定に「webでの再生を優先する」というスイッチがありましたね。
それをオフにしたところ、期待動作になりました。

**Comment by tobitti0** [comment]
@hide74 
自己解決したならご自身でISSUEをcloseされるのが良いと思います。
