### ISSUE TITLE
Picture-in-Pictureモードについて

### ISSUE THREAD

**Issue by MichaelHsu170** [l3tnun/EPGStation#556]
### 環境
* Version of EPGStation: `2.6.15`
* Version of Mirakurun: `3.9.0-beta.19`
* Version of Node: `x.x.x`
* Version of NPM: `x.x.x`
* OS:Ubuntu 20.04
* Architecture: x64

### Issue
プレヤーのPicture-in-pictureモードはいま視聴ページでしか使えないらしいです。もし番組表などの他のページで操作しながら、Picture-in-pictureモードで引き続きリプレーできればすごく使いやすくになると思います。この機能を実装することは可能でしょうか？

**Comment by l3tnun** [comment]
可能か不可能かで言いますと、技術的には可能です。
ただ、実装負荷が高いので実装される目処は立っていないです。

**Comment by MichaelHsu170** [comment]
ご説明ありがとうございます。
ちなみに、録画済みのビデオを再生するときに主音声と副音声の選択機能が２ヵ国語のビデオにとっていい機能と思います。ご検討ください。:-D
