### ISSUE TITLE
EPGStation v2.6.12 - v.2.6.15 が Windows環境 ＋ Node.js 14 でインストールに失敗する

### ISSUE THREAD

**Issue by daig0rian** [l3tnun/EPGStation#558]
素晴らしいプロジェクトを公開していただきありがとうございます。
表題のとおり直近のEPGStationのバージョンでWindows環境へのインストールがうまくいかなくなっているようでしたので報告させていただきます。

### 環境
* Version of EPGStation: `v2.6.12` - `v.2.6.15`
* Version of Mirakurun: `3.9.0-beta.21`
* Version of Node: `node@v14.18.1` 
* Version of NPM: `npm@6.14.15`
* OS: win32 (Windows 10 Pro / Vesion 21H1 / Builed 19043.1348)
* Architecture: x64

### Issue
Windows + Node.js14 + EPGStation v2.6.12 - v.2.6.15 では、[Windows 用 セットアップマニュアル](https://github.com/l3tnun/EPGStation/blob/master/doc/windows-setup.md)  の手順でインストールを試みても成功しないようです。
具体的には npm run all-install　実行中に以下のようなエラーが出て失敗します。
```
> npm run all-install
```
```
> epgstation@2.6.15 all-install C:\Users\daigorain\EPGStation
> npm i --no-save && cd client && npm i --no-save

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\@chinachu\packages\napi-ts-crc32" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daigorain\AppData\Roaming\npm-cache\_logs\2021-11-18T17_48_00_325Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epgstation@2.6.15 all-install: `npm i --no-save && cd client && npm i --no-save`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epgstation@2.6.15 all-install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daigorain\AppData\Roaming\npm-cache\_logs\[021-11-18T17_48_00_364Z-debug.log
PS C:\Users\daigorain\EPGStation> cd ..
PS C:\Users\daigorain> npm run all-install -b v2.6.11
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\daigorain\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\daigorain\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daigorain\AppData\Roaming\npm-cache\_logs\2021-11-18T17_53_52_394Z-debug.log
```
[2021-11-18T17_48_00_364Z-debug.log](https://github.com/l3tnun/EPGStation/files/7565064/2021-11-18T17_48_00_364Z-debug.log)
[2021-11-18T17_53_52_394Z-debug.log](https://github.com/l3tnun/EPGStation/files/7565065/2021-11-18T17_53_52_394Z-debug.log)

EPGStation `v2.6.11`までは問題なくインストールができるようで、EPGStation の package.json でdependencies　に mirakurun 3.9.0-beta.18 を指定しているバージョン`v2.6.12` - `v.2.6.15`で発生しているようです。
```
    "dependencies": {
        "mirakurun": "3.9.0-beta.18",
```

また、EPGStation v.2.6.15 で package.json のdependencies　の mirakurunを以下のバージョンに書き換えたときには問題なくインストールが完了することを確認しています。
   -  `"mirakurun": "3.9.0-beta.1”`
   -  `"mirakurun": "3.9.0-beta.17”`
   -  `"mirakurun": "3.9.0-beta.19”`
   -  `"mirakurun": "3.9.0-beta.20”`

よろしくお願いいたします。

**Comment by l3tnun** [comment]
確認してみましたが、おそらく `package-lock.json` の依存関係の設定が windows の場合うまく機能していないようです。
これ用に修正するのは骨が折れるので以下のようにして対処してください。

```
cd EPGStation
npm i --no-save mirakurun@3.9.0-beta.18 ← `package.json の dependencies と同じものを指定してください
npm run all-install
```

これで動作することが確認できました。

**Comment by is984** [comment]
Linux( Oracle Linux 8 aarch64 /w Raspberry Pi 4B) でも同様にエラーになるようです
既に提示されているワークアラウンドで問題は回避できますが、念のため報告だけ。

環境

- Version of EPGStation: 2.6.15
- Version of Mirakurun: 3.9.0-beta.24
- Version of Node: 14.18.2
- Version of NPM: 6.14.15
- OS: Linux(Oracle Linux Server 8.5/ kernel 5.4.17-2136.302.6.1.el8uek.aarch64)
- Architecture: aarch64(ARM64)


```
> epgstation@2.6.15 all-install /opt/tvs/EPGStation
> npm i --no-save && cd client && npm i --no-save

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/@chinachu/packages/napi-ts-crc32" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-23T07_44_08_886Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epgstation@2.6.15 all-install: `npm i --no-save && cd client && npm i --no-save`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epgstation@2.6.15 all-install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-23T07_44_08_994Z-debug.log
```

**Comment by l3tnun** [comment]
v.2.6.16 で修正されましたのでクローズします。
