### ISSUE TITLE
削除ダイアログのデフォルト状態改善の提案

### ISSUE THREAD

**Issue by ore0** [l3tnun/EPGStation#565]
### 環境
* Version of EPGStation: `2.6.17`

### Issue
いつも大変お世話になっております。
現在の録画データ削除ダイアログが、ユーザーへの認知負荷が高い故に誤操作を招き易いインタフェースになっていると考えられるため、改善の提案をさせて下さい🙏

#### As-Is
![image](https://user-images.githubusercontent.com/2234100/147850290-03ab280b-e7d5-4134-996d-adc3d5487166.png)

現在は同一番組における全ての録画データにチェックが付いた状態でダイアログが展開されます。
例えばこの際、TSファイルを削除するためにダイアログを展開したユーザーは、TSファイル以外の項目のチェックボックスを操作する必要があります。

このようなUIは「意識の対象（削除したいファイル）」と「操作の対象」が異なるため、ユーザーへの認知負荷が非常に高いと考えられます。
上記の例の続きとして考えられる懸念が、削除したいファイル（意識の対象）であるTSファイルのチェックボックスを操作してしまい、削除する予定ではなかったTSファイル以外の録画データを削除してしまうという誤操作が発生することです。

#### To-Be
![image](https://user-images.githubusercontent.com/2234100/147850084-82215644-5523-4f58-b8be-9dc3e5707c4f.png)

上記の課題の解決策として、削除ダイアログを展開する際に、全ての録画データにチェックを付けずにユーザーへ提示する修正が考えられます。
初期状態で録画データにチェックが付いていないことによって、例えばTSファイルを削除するためにダイアログを展開するユーザーはTSファイルのチェックボックスを有効化して削除を行うという操作フローになります。
この修正によって「意識の対象」と「操作の対象」が一致するため、ユーザーにとって認知負荷が少ない状態でインタラクションを行うことができるようになります。

また、「録画データの削除」という機能がユーザーにとって破壊的アクションであることから、「チェックボックスを操作しないと削除を行うことができない」というインタラクション設計自体も、誤操作によるデータ消失リスクの回避に繋がると考えられます。

#### Remarks
ユーザーは基本的に間違えやすい生き物であるという前提でUIを設計すると、更により良い体験を提供できるようになると思います。
とはいえ、今回提示した課題は私の操作体験に基づくN=1な物であり、マイノリティな意見である可能性があることもご留意していただけると幸いです。
また、私が行った削除に関する操作がEPGStation設計時の想定と異なるケースも十分に存在することを承知しております。その際はお手数をおかけしますがIssueのCloseをお願い致します。

どうぞよろしくお願い致します。

**Comment by l3tnun** [comment]
issue の意図よくわかりました。
個人的にデフォルトでチェックが入っていない場合、操作がまどろっこしくも感じられます。
そのため、設定で変更できるようにしようと思います。
デフォルトは誤操作防止の観点から false にしようと思います。

**Comment by l3tnun** [comment]
https://github.com/l3tnun/EPGStation/commit/8f126344e434167fe0e14d93c1a128af06bdb2ac にて実装しました。
master 反映までお待ち下さい。

**Comment by l3tnun** [comment]
master に反映されましたのでクローズします。
ご指摘ありがとうございました。
とても参考になりました。

**Comment by ore0** [comment]
ご対応ありがとうございました🙏
