### ISSUE TITLE
削除対象が0件の状態で削除ボタンを押下すると削除成功時のスナックバーが表示される

### ISSUE THREAD

**Issue by ore0** [l3tnun/EPGStation#567]
### 環境
* Version of EPGStation: `2.6.17`

### Issue
録画データ削除ダイアログにて、削除対象が0件の（チェックボックスが全てfalseになっている）状態で削除を実行した際に不具合と思わしき挙動が発生したため、Issueを立てさせていただきます。

#### As-Is
![Jan-01-2022 22-29-10](https://user-images.githubusercontent.com/2234100/147851735-d2c39f71-f4cd-49d3-975f-01b358a4df56.gif)

削除対象が0件の状態で削除ボタンを押下すると、ダイアログが閉じた後に削除成功時のスナックバーが表示されます。

#### To-Be
![Jan-01-2022 23-14-54](https://user-images.githubusercontent.com/2234100/147852558-c3419d1f-ea76-4184-bd73-ef8ce0fdda1a.gif)

削除対象が0件の状態で削除ボタンを押下しても、ダイアログが閉じるだけでスナックバーは表示されない挙動となることが望ましいと考えられます。

**Comment by l3tnun** [comment]
修正ありがとうございました。
master 反映までお待ち下さい。

**Comment by l3tnun** [comment]
master に反映されましたのでクローズ。
修正ありがとうございました。
