### ISSUE TITLE
IPTV Channels List on my website not working as required! 

### ISSUE THREAD

**Issue by Amberwatson** [l3tnun/EPGStation#57]
Hi there, 
I am having some problems with my WordPress based website and I think those problems are related to mentioned here. Currently, I do have an online store through which I offering Best IPTV Subscriptions in the world. My services cover almost all the geographical areas of the world including USA, Canada, UK, ASIA, Europe, Africa, Middle East and so on. I do have a list including  [IPTV for Canadian Channels ](https://myiptvhd.com/iptv-for-canadian-channels/) which is working fine. But the issue is Canada accepting people all over the world despite their languages and regions. Some of my clients are claiming that they can't read English and they want the text in their native languages. Is there any method available that I can apply on my blog and the person get the text converted into his/her native language?

**Comment by l3tnun** [comment]
Are you misunderstanding other software?

**Comment by Amberwatson** [comment]
Ok Thanks
