### ISSUE TITLE
インストール時、SQLiteのダウンロードに失敗(403)する。

### ISSUE THREAD

**Issue by lunae-f** [l3tnun/EPGStation#576]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.0-rc.0`
* Version of Node: `v16.3.2`
* Version of NPM: `8.1.2`
* OS:DietPiv8.0
* Architecture: aarch64

### Issue
　「[Linux / macOS 用 セットアップマニュアル](https://github.com/l3tnun/EPGStation/blob/master/doc/linux-setup.md#linux--macos-%E7%94%A8-%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB)」の通りに、GitHubからクローン→`npm run all-install`、という手順を踏みましたが、エラーが出てインストールに失敗しました。OSの再起動やOSを再インストールした場合も含めて5回以上はEPGStationのインストールを試しましたが、いずれの場合も失敗しました。
ログを見る限りSQLiteを取得しようとして403で弾かれていたので、`package.json`のSQLiteのに関連する部分を削除して`npm run all-install`を実行したところ、正常に終了しました。

　上記項目の削除前の`package.json`で`npm run all-install`した際のログと、削除後のログを貼っておきます。
[2022-01-18T23_50_36_833Z-debug.log](https://github.com/l3tnun/EPGStation/files/7893701/2022-01-18T23_50_36_833Z-debug.log)
[2022-01-19T02_19_43_240Z-debug.log](https://github.com/l3tnun/EPGStation/files/7893702/2022-01-19T02_19_43_240Z-debug.log)

issueを立てるのに慣れていないので不手際があるかもしれません。すみません。
よろしくお願いします。

**Comment by l3tnun** [comment]
version 2.7.0で対応予定です。
それまではdockerをご使用ください。
