### ISSUE TITLE
たまに recording 開始が少し遅れる

### ISSUE THREAD

**Issue by tokohito** [l3tnun/EPGStation#579]
### 環境
* Version of EPGStation: ` 1.6.1 `
* Version of Mirakurun: `2.13.0`
* Version of Node: `v10.17.0`
* Version of NPM: `x.x.x`
* OS: docker (host/Ubuntu20.04)
* Architecture: x64

### Issue
お世話になってます。

表題の通りですがたまに recording 開始タイミングが遅れて番組冒頭が欠ける事があります。
ログを確認する限り preprec はいづれも正常なタイミングで実行できています。
この場合、recording の開始タイミングが遅くなる原因としてどのような事が考えられるでしょうか？
 - 録画後のファイルに drop は発生していません
 - 冒頭が切れた番組時間帯の同時録画数はチューナー数を上回っていません（競合対象なし）

> [2022-02-08T01:04:47.542] [INFO] system - preprec: 323912360804215 理系が恋に落ちたので証明してみた。 #5「理系が恋に落ちたので会議してみた。」[再]
[2022-02-08T01:05:07.029] [INFO] system - recording: 323912360804215 理系が恋に落ちたので証明してみた。 #5「理系が恋に落ちたので会議してみた。」[再]

**Comment by tokohito** [comment]
mirakurun 側のログを見ると、preprec のタイミングでちゃんとチューナーのオープンはできているように見えます。

> 2022-02-08T01:04:47.545+09:00 info: TSFilter has created (serviceId=23608, eventId=4215)
2022-02-08T01:04:47.559+09:00 info: TunerDevice#2 process has spawned by command `recpt1 --device /dev/pt3video2 20 - -` (pid=3049)
2022-02-08T01:04:47.559+09:00 info: TunerDevice#2 streaming to user `172.20.0.3:37142` (priority=2)
2022-02-08T01:04:47.574+09:00 info: TunerDevice#2 > using device: /dev/pt3video2
pid = 3049

**Comment by hideo54** [comment]
同様の現象が私の環境でもたまに発生しています。Windows 環境であることやハードウェアの不調の可能性があることに鑑みて issue を報告していなかったのですが、Mirakurun や EPGStation の再起動で都度解決するので、何かソフトウェア的解決ができないかなとも思うところです。閉じられていますが、issue #578 も同様だったのかもしれません。

私の環境は次の通りです:
* Version of EPGStation: 2.6.20
* Version of Mirakurun: 3.9.0-rc1
* Version of Node: 16.13.0
* Version of NPM: 8.1.4
* OS: Windows 11 21H2
* Architecture: x64

**Comment by yuta2k** [comment]
別の原因かもしれないですが、当時 [docker-mirakurun-epgstation v2](https://github.com/l3tnun/docker-mirakurun-epgstation/tree/v2) の上で動かしていた環境で同様の問題が再現していました。  
同じく私の環境が原因だと思っていました....

* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `16.13.1`
* Version of NPM: `8.1.2`
* OS(ホスト): `Linux (Debian Bullseye) #1 SMP Debian 5.10.113-1 (2022-04-29)`
* Architecture: x64

BS11 にて 2022 年 10 月頃から放送されたアニメ「ぼっち・ざ・ろっく！」の録画にて、隔週程度の頻度で番組始めの数秒が切れています。

年始にハードを丸ごと変えたこともあり確証はないですが、[Mirakurun の Pull Request #67](https://github.com/Chinachu/Mirakurun/pull/67) を参考に Mirakurun の `server.yml` へ

```
maxBufferBytesBeforeReady: 16777216
```

を追記してみたところ、解決したような気がします。

**Comment by l3tnun** [comment]
preprecで Mirakurun へ接続を行い、Mirakurunから何らかのデータが降ってきた段階でrecordingへ移行します。
故にこれは Mirakurun もしくは チューナの問題となります。
