### ISSUE TITLE
iPad OS で録画ファイルをダウンロードできません

### ISSUE THREAD

**Issue by narumans** [l3tnun/EPGStation#591]
### 環境
* Version of EPGStation: `v2.26.20`
* Version of Mirakurun: `3.9.0`
* Version of Node: `v16.14.2`
* Version of NPM: `8.5.0`
* OS: 'almaLInux'
* Architecture: x64

以前にも似たような問題でご相談した不具合ですが、今までMacでの動作には問題ないのですが、最近iPadを購入しまして、そちらに録画ファイルをダウンロードして視聴しようとしたのですが、ダウンロードでvlcで開きますかとでて、OKしましてもダウンロードされません。
epgstationの設定で、ダウンロードURL SchemeをOFFにしてやってみると、どのブラウザでも
ファイル名が2とか3のようになり、ファイル容量は合っているのですが、視聴はできません。
よろしくお願いします。
...

**Comment by narumans** [comment]
なんとなく解決

他のブラウザは試していませんが、Safariで設定ダウンロードURL SchemeをOFFにし、
録画ファイルダウンロードしてみると、初めはファイルネーム数字21とか出る表示を✖️で消して
みると、新たに表示が正常に出ますので、そのままダウンロードをしますとOKでした。それと
iPad OSのSafari設定でダウンロード先をvlcに設定すると、完璧になりました。
やってみたことで、関連があるか分かりませんが、データベースをMariadbにしてみました。

**Comment by narumans** [comment]
問題を完全解決できました

何分に素人なので低レベルな書き込みで申し訳ありませんでした。
#607 Ry0さんの書き込みのとうりにしましたら、解決いたしました。

そこで、以下のように、://の部分を%3A%2F%2Fに変更して対応しています。
    m2ts:
+        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL%3A%2F%2FADDRESS
-        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://ADDRESS

このようにしましたらブラウザ Firefox でm2ts無変換vlcで再生及びvlcでダウンロードできました。
尚 safari ではできませんでした。

以上ご報告です。

**Comment by l3tnun** [comment]
解決方法まで記載ありがとうございます。
こちらVLCだけの問題かつ、修正が面倒なため config.yml.template の修正のみにとどめたいと思います。
version 2.7.0で反映させます。
