### ISSUE TITLE
フォーク削除リクエスト

### ISSUE THREAD

**Issue by YuenSzeHong** [l3tnun/EPGStation#594]
最近、あるgithubアカウン トが私を装って、あなたのリポジトリをフォ一クし、知らないユ一ザ一の実行中のepgstationsのIPアドレスを漏らしていることを発見しました。可能であれば、レポのrespecitve フォ-クを削除することを願っています。以下はレポのURLです:
https://github.com/yysub/EPGStation

**Comment by YuenSzeHong** [comment]
英語原文版、日本語版は翻訳です
recently i found that a github account has faked as me, forking your repository leakingIP addresses of running epgstations of unkown users, if possible, i hope you can takedown the respecitve fork of the repo. below isthe url of the repo:
https://github.com/yysub/EPGStationl

**Comment by RabbitJae** [comment]
btw, there is another one
https://github.com/mlzmz/EPGStation

**Comment by YuenSzeHong** [comment]
pls also remove that if possible Sent from Mail for Windows From: RabbitJaeSent: 2022年4月25日 12:39To: l3tnun/EPGStationCc: YuenSzeHong; AuthorSubject: Re: [l3tnun/EPGStation] フォーク削除リクエスト (Issue #594) btw, there is another onehttps://github.com/mlzmz/EPGStation—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by YuenSzeHong** [comment]
> btw, there is another one https://github.com/mlzmz/EPGStation

yes know that, so need to remove also

**Comment by 3242692624** [comment]
> 英文版、日文版は翻訳です 最近的地址是我的一个github帐户冒充，我的存储库发现未知用户的运行eppg的IP，可能的话，我希望你能删除repo。下面是repo的网址： https://github.com/yysub/EPGStationl

https://github.com/yysub/EPGStation

**Comment by l3tnun** [comment]
@YuenSzeHong 

thank you for reporting
I reported repository abuse to Github.

**Comment by YuenSzeHong** [comment]
> @YuenSzeHong 
> 
> thank you for reporting
> I reported repository abuse to Github.

I also reported abuse for that repo for abusing, waiting reply

**Comment by YuenSzeHong** [comment]
@l3tnun seems GitHub didn't remove the repo, if you need more information, feel free to contact me

**Comment by l3tnun** [comment]
こちらで対応できることはありませんので閉じます。
