### ISSUE TITLE
recordedFormatに %RECORDEDID%を追加

### ISSUE THREAD

**Issue by SpiralCut** [l3tnun/EPGStation#600]
### 環境
* Version of EPGStation: `x2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `16.6.1`
* Version of NPM: `8.3.1`
* OS: Windows 11
* Architecture: x64

### Issue
EPGStationのconfig.ymlのrecordedFormatに%RECORDEDID%のマクロを追加することは可能でしょうか。EPGSTATION内のエンコード後のバッチコマンドにしかRECORDEDIDが使えませんので、外部ソフトで動画ファイルを変換する場合は外部ソフトがrecordedidがわからなくてEPGStationのAPIから番組情報が取得できません。動画ファイル名にRecordedIDを埋め込むことができれば、エンコード後の最終処理でそのIDを利用して動画ファイルの情報が取得できます。

したいこと:
EPGSTATIONで録画→AMATSUKAZEでエンコード→AMATSUKAZEエンコード後のバッチファイルで番組のジャンル別のファイルソート＋名前変更

**Comment by PiedHarrier** [comment]
AmatsukazeTaskAddを使ってAmatsukazeでエンコードする方法がネットを調べればあるので調べて下さい。

**Comment by l3tnun** [comment]
環境変数で取得できますので、対応しません。
https://github.com/l3tnun/EPGStation/blob/31ee9265fbdc5e1bc02b0d586a18a8c9156acca9/doc/conf-manual.md#encode
