### ISSUE TITLE
「epg updater is disconnected」と表示され番組表が取得できない

### ISSUE THREAD

**Issue by Kuri0421** [l3tnun/EPGStation#606]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `16.15.1`
* Version of NPM: `8.13.1`
* OS:Ubuntu 20.04.4 LTS
* Architecture: x64

### Issue
手違いでホームディレクトリをすべて削除してしまいEPGStationを再インストールしたところ番組表が一向に表示されずログを確認したところ
```
1|epgstation        | [2022-06-28T01:45:21.668] [FATAL] system - epg updater is disconnected
1|epgstation        | [2022-06-28T01:45:21.672] [INFO] system - start epg updater pid: 2269
1|epgstation        | [2022-06-28T01:45:22.754] [FATAL] system - epg updater is disconnected
1|epgstation        | [2022-06-28T01:45:22.759] [INFO] system - start epg updater pid: 2276
1|epgstation        | [2022-06-28T01:45:23.825] [FATAL] system - epg updater is disconnected
1|epgstation        | [2022-06-28T01:45:23.830] [INFO] system - start epg updater pid: 2283`
```
と、アップデーターが切断されたというログが永遠と表示されます。

### 試したこと

- データベースをすべて削除し再生成をしました。

- Twitterなどの情報や「[Mirakurun 3.9.0-beta.24 以降の設定について](https://github.com/l3tnun/EPGStation/blob/master/doc/mysql-mirakurun-3.9.0-beta.24.md)」を参考にMySQLの文字コードを`utf8mb4`すると改善するということでしたのでphpMyAdminで文字コードを確認したところすべて`utf8mb4_bin`と表示されていました。

- OSを一から入れ直し、EPGStationを再インストールしました。

...

**Comment by Kuri0421** [comment]
[EPGStation](https://github.com/l3tnun/EPGStation)単体のDockerの場合、同様のエラーが出力されましたが、[docker-mirakurun-epgstation](https://github.com/l3tnun/docker-mirakurun-epgstation)で構築した場合正常に動作したのでひとまずCloseさせていただきます。

**Comment by simplelife0530** [comment]
Mirakurun: 3.8.0にすれば、動くかもしれません。

2022年6月28日(火) 2:05 栗本祐吾 ***@***.***>:
