### ISSUE TITLE
【質問】SQL高速化

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#609]
### 環境
* Version of EPGStation: `1.7.6`　
* Version of Mirakurun: `3.9.0-rc2`
* Version of Node: `14.19.0`
* Version of NPM: `6.14.16`
* OS:Windows10
* Architecture: x64

### Issue
v1で申し訳ありません。
数年EPGStationを使用しており、録画データが1672ページまで増大しました。
1ページ24番組なので、40000番組近く録画しています。
録画済みページの表示が極端に遅くなってしまい、開いて十数秒待たなければならなくなってしまいました。
恐らくはmySQLが遅いのではと思います。現在mySQL側のキャッシュを増やす等の対処を検索しておりますが、
EPGｓtation側で対策できることありますでしょうか。
また、v2でも極端に番組数が多いと遅くなりますでしょうか。

重ね重ねv1で申し訳ありません。

**Comment by l3tnun** [comment]
v1のサポートはいたしません。
