### ISSUE TITLE
録画管理用ページ

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#610]
### 環境
* Version of EPGStation: `1.7.6`　
* Version of Mirakurun: `3.9.0-rc2`
* Version of Node: `14.19.0`
* Version of NPM: `6.14.16`
* OS:Windows10
* Architecture: x64

### Issue
v2への移行ネタも旬をとうに過ぎているかもしれませんが……
以前の番組の録画管理（録画失敗番組を削除したり）にどうしてもv1が必要です。
今考えているのは「同じフォルダを参照して予約なしのv1と予約ありのv2に移行し、過去番組の削除をv1で行って新規録画はv2で見る」です。しかし、これではどちらかでクリーンアップを行うと「v1側はv2で録画した番組を消してしまう」「v2側はv1のドロップログを消去してしまう」が起こります。

・v2側でクリーンアップ時に特定の拡張子のファイルは消さない
・v1のドロップログを見てデータを削除するかどうかだけを判断する管理専用ページ（予約も再生も行わない）を用意する
みたいなことはできないでしょうか……

使用者のやりたいことに
・録画予約する
・録画視聴する
・番組を管理する
今は番組管理と番組視聴が兼ねられていてそれはそれで便利ですが、
管理特化ページがあると便利かもと思いました。

そもそもv1からv2への移行ルートがあること自体がありがたい話で、先にv1で失敗番組の削除を終わらせてからv2へ移行せよという話かもしれませんが……

**Comment by l3tnun** [comment]
v1のサポートはいたしません。
