### ISSUE TITLE
Webのユーザーインターフェイスで日本語と英語が混在している

### ISSUE THREAD

**Issue by ghost** [l3tnun/EPGStation#612]
### 環境
* Version of EPGStation: `2.6.20`
* OS: Debian 11
* Architecture: x64

### Issue
Web UIは基本的に日本語で書かれているのに、録画済みページ内の各録画済番組のメニューををクリックした際の表示が「search/protect/encode/delete」と英語になっています。日本語に翻訳する必要があるのではないでしょうか。

英語のUIに需要があるのなら、多言語化して切り替えられるようにするのも一つの手だと思います。

**Comment by tanaka332** [comment]
同様の問題は録画済番組のサムネイルをクリックした際に表示される「Play/Streaming/Encode」という箇所にもあります。

**Comment by l3tnun** [comment]
意図してそのようにしています。不満があるのでしたらご自身で変更してください。
