### ISSUE TITLE
IPTV Simple Client のチャンネル切替が非常に遅い

### ISSUE THREAD

**Issue by T414CSP** [l3tnun/EPGStation#613]
### 環境
* Version of EPGStation: `v2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `v16.17.0`
* Version of NPM: `8.15.0`
* OS: Ubuntu 18.04.5 LTS
* Architecture: x86

### Issue
[IPTV Simple Client との連携](https://github.com/l3tnun/EPGStation/blob/v2/doc/kodi.md#iptv-simple-client-%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA)を下記環境で試してみました。
* H/W: FireTV 4K
* KODI: Matrix 19.4 armeabi-v7a
* IPTV Simple Client: 19.2.2
* Inputstream FFmpeg Direct: 19.0.3

チャンネル切替(初回選択を含む)に40秒ほどかかりる現象が発生しました。KODI Leia 18.9とそのレポジトリからIPTV Simple Clientをインストールした場合には発生しません。

ログを確認しましたが、下記のようにTimeoutが発生しています。

```text
09-11 15:14:22.046  7246  7268 E Kodi    : 2022-09-11 15:14:22.046 T:7268    ERROR <general>: CCurlFile::Exists - Failed: Timeout was reached(28) for http://192.168.1.3:8888/api/streams/live/3274101064/m2ts?mode=2
```

[KODIのサポート](https://forum.kodi.tv/showthread.php?tid=368010&pid=3095694#pid3095694) で見つけた、m3u8の各エントリーに
```
#KODIPROP:mimetype=video/mp2t
```
を追加する方法で解決できました。約4秒でチャンネルが切り替わるようになりました。
後ほどPull requestを出す予定です。

[ffmpegdirectの説明](https://github.com/xbmc/inputstream.ffmpegdirect#using-the-addon)を読むと、パラメータでストリームの特性を明示することでさらに切替時間が短縮できる可能性もありますが、調査できていません。

**Comment by l3tnun** [comment]
#614 で頂いたマージリクエストをマージし、version 2.7.0 で反映されましたのでクローズします。
ご対応ありがとうございました。
