### ISSUE TITLE
ルールで管理された録画について、旧動画ファイルを新動画ファイルで上書きするような設定の仕方について

### ISSUE THREAD

**Issue by sakamossan** [l3tnun/EPGStation#621]
### 環境

* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `v16.13.1`
* Version of NPM: `8.1.2`
* OS: Linux
* Architecture: armv7l

[docker-mirakurun-epgstation](https://github.com/l3tnun/docker-mirakurun-epgstation) のDockerfile/設定周りに手を入れて RaspberryPi で動かしています。

### Issue

ありがたく利用させていただいてます。
「これ、オプション/設定でなんとかなったりしますか」という質問でissueをたてます。

### やりたいこと

ニュースなど毎日同様のコンテンツが放送されるような番組で、
前日のmp4ファイルを当日のmp4ファイルで上書きするような録画ルールをつくりたいなと考えています。

### ためしたこと

ルール作成にて

- `ファイル名形式` の欄に `%TITLE%`などの変数を使わず `今日のニュース` と定数だけを入れてルールを作成
- `今日のニュース.mp4` の翌日に `今日のニュース(1).mp4` と連番が振られた名前でファイルが生成されてしまった
- 期待する挙動としては前日の `今日のニュース.mp4` を当日の `今日のニュース.mp4` が上書き保存してほしかった

### 調べたこと

`recordedPreStartCommand` を利用するか、もしくは自分の使い方だとほぼ競合は発生しないので、この辺りコメントアウトすれば(無理矢理)動かせるのかなとも思ったのですが、

https://github.com/l3tnun/EPGStation/blob/c0e201b83231dfed73e5bea1b2ec54866fcfbbba/src/model/service/encode/EncodeFileManageModel.ts#L26-L28

そもそもデフォルトの `enc.js` だと ffmpeg に `-y` オプションをつけているので、そんなことをしないでも自分が知らないオプションで望む挙動が実現するのではないか、と思い質問させていただきました。

### 質問

ルールで管理された録画について、旧ファイルを新ファイルで上書きするような設定の仕方はありますでしょうか?

**Comment by l3tnun** [comment]
現時点で開発のリソースの余裕がないので、直近で対応する予定はありません。

**Comment by sakamossan** [comment]
解答ありがとうございます！

個人的には recordedPreStartCommand で何とかすればよいと思ったので、別段機能としての実装は不要だと思います。
