### ISSUE TITLE
【質問】タグ機能の操作

### ISSUE THREAD

**Issue by nanbuwks** [l3tnun/EPGStation#636]
### 環境
* Version of EPGStation: `2.6.20`
* Version of Mirakurun: `3.9.0-rc.2`
* Version of Node: `v16.13.1`
* Version of NPM: `8.1.2`
* OS:Ubuntu Linux 20.04
* Architecture: x64

### Issue

WebAPI の ドキュメントには 「tags」機能がありますが、これを使った関連付けや検索などは GUI 画面で操作できるのでしょうか? (使用している環境ではGUI中に見つけられませんでした。)

**Comment by l3tnun** [comment]
#166 のリクエストによって API は実装したのですが良い UI が思い浮かばず、現時点では GUI では操作できない状況です。
#166 に集約すべき内容ですのでクローズします。
