### ISSUE TITLE
needToReplaceEnclosingCharacters: Fails to replace multiple of the same character

### ISSUE THREAD

**Issue by TurtleWilly** [l3tnun/EPGStation#639]
### 環境
* Version of EPGStation: `v2.6.20`
* Version of Mirakurun: *(no idea)*
* Version of Node: *(no idea)*
* Version of NPM: *(no idea)*
* OS: Linux
* Architecture: x64

### Issue
If "needToReplaceEnclosingCharacters" is configured, then characters like `🈑` are replaced with easier to manage and more compatible strings like `[字]`. Generally this works fine.

In some rare cases some titles use one character (e.g. the "has subtitles" symbol) more than once. In such cases only the first symbol is replaced, the second is left as it with the less compatible plane 1 character, e.g.:

`【４週連続オムニバスＤＲＡＭＡ】＃３さよならの向う側[字]＆５分後に意外な結末🈑`

(**Note:** how there's `[字]` and `🈑` in the title now. It was one program with 2 dramas in the timeslot.)

**Comment by l3tnun** [comment]
version 2.7.0 で修正されました。
