### ISSUE TITLE
epgstation-v2.7.0 起動しません

### ISSUE THREAD

**Issue by narumans** [l3tnun/EPGStation#650]
### 環境
* Version of EPGStation: `-v2.7.0`
* Version of Mirakurun: `3.9.0-rc.4`
* Version of Node: `18.19.0`
* Version of NPM: `9.6.7`
* OS:Almalinux9.2
* Architecture: x64

EPGStationがバージョンアップしたので新規にインストールしようと思い、やってみますと
何回やっても起動しません。Mirakurunはブラウザから起動確認はできています。
それでネットを検索してみると、やっと見つけたページでも同じようなことが起こっていました様ですが、
解決策はまだでしたので、ここで聞いてみようと思いました。

でログをみますとやっぱりエラーが出ていました。記述します。

[FATAL] system - uncaughtException: TypeError: Cannot read properties of undefined (reading 'sync')
[FATAL] system - uncaughtException: Error: must call SocketIoManageModel initialize

このようなエラーです。よろしくお願いします。
### Issue
...

**Comment by koron393** [comment]
ちょっと見てみましたが再現しました。

```
[2023-08-04T04:32:56.175] [INFO] system - mkdirp: (install dir)/data/upload
[2023-08-04T04:32:56.178] [FATAL] system - uncaughtException: TypeError: Cannot read properties of undefined (reading 'sync')
[2023-08-04T04:32:56.383] [FATAL] system - uncaughtException: Error: must call SocketIoManageModel initialize

```

「(デフォルトでは) インストールディレクトリ直下の data/upload ディレクトリ」
(https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#uploadtempdir)
が存在しない場合に作りに行くようになっているようですが、このときにエラーになっているようです。

https://github.com/l3tnun/EPGStation/blob/master/src/model/service/ServiceServer.ts#L203

1. 先にディレクトリを手で作っちゃう ($ mkdir -p ./data/upload)
2. パッチを当ててビルドし直す (https://github.com/l3tnun/EPGStation/pull/651)

どちらかで解決することを確認しました。
なお import 文にカッコが要る理由、誰か教えてください。

**Comment by narumans** [comment]
ありがとうございました。無事起動しました。

でちょと余談ですが、
私このアップデートと同時にPCも新調したところ、
PLEXのドライバーがインストール出来ずに苦労しました。
で見つけた解決方法は、MB BIOS でsecure boot を切るということで、
やっとインストールできました。
で、PC構成はRyzen7000シリーズMB MSI X570-Pです。
このマザーボードコストパフォーマンス抜群です。
以上誰かの参考になれば幸いです。

駄文失礼いたしました。ありがとうございました。

**Comment by l3tnun** [comment]
@narumans 
バグ報告ありがとうございました。

@koron393 
修正のプルリクありがとうございました。マージさせて頂きました。
version 2.7.1に反映されます。
