### ISSUE TITLE
npm run build時にエラー

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#652]
### 環境
* Version of EPGStation: `2.7.1`
* Version of Mirakurun: `3.9.0`
* Version of Node: `14.17.0`
* Version of NPM: `6.14.13`
* OS: Windows10
* Architecture: x64

### Issue
Windows10セットアップ時にeslintでエラーが出るようです。
??=という記述で引っかかっているようです……
Windowsはもうサポートから外しているとのことですが、
どなたかお知恵を拝借したく……

'npm run build

> epgstation@2.7.1 build E:\EPGStation2\EPGStation
> npm run build-server && npm run build-client

> epgstation@2.7.1 build-server E:\EPGStation2\EPGStation
> npm run lint && npm run format && npm run compile

> epgstation@2.7.1 lint E:\EPGStation2\EPGStation
> eslint --fix --ext .ts src/

Oops! Something went wrong! :(

ESLint: 8.45.0

E:\EPGStation2\EPGStation\node_modules\@typescript-eslint\eslint-plugin\dist\util\getStringLength.js:16
    splitter ??= new graphemer_1.default();
             ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\EPGStation2\EPGStation\node_modules\@typescript-eslint\eslint-plugin\dist\util\index.js:24:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! epgstation@2.7.1 lint: `eslint --fix --ext .ts src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the epgstation@2.7.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PenGServ\AppData\Roaming\npm-cache\_logs\2023-08-18T05_46_57_888Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! epgstation@2.7.1 build-server: `npm run lint && npm run format && npm run compile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the epgstation@2.7.1 build-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PenGServ\AppData\Roaming\npm-cache\_logs\2023-08-18T05_46_57_911Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! epgstation@2.7.1 build: `npm run build-server && npm run build-client`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the epgstation@2.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PenGServ\AppData\Roaming\npm-cache\_logs\2023-08-18T05_46_57_931Z-debug.log
'

**Comment by l3tnun** [comment]
自分で解決してください。
