### ISSUE TITLE
録画ファイルの一括削除について

### ISSUE THREAD

**Issue by unicode45** [l3tnun/EPGStation#66]
（APIを見ても複数ファイルの削除には対応していないようで投稿します。）
録画予約やエンコードが楽な分、削除はファイルを一つずつサブメニューから「削除」を選択して行うため、削除が追いつかない状況です。録画ファイルを検索して削除したり、複数のファイルを選択して一括削除できるような機能があればありがたいです。

**Comment by l3tnun** [comment]
APIの追加は簡単にできますが、WebUI の方で作業が多いので実装に時間がかかりそうですね。
気長にお待ち下さい。

**Comment by unicode45** [comment]
ありがとうございます。応援しながら気長に待ちます！

**Comment by l3tnun** [comment]
master にて録画の複数削除に対応しました。
ご確認ください。

**Comment by unicode45** [comment]
迅速なご対応ありがとうございます。
「,」で区切った複数録画ファイルの削除に無事成功しました。
とりあえずご報告までに。
よろしくお願いします！

**Comment by l3tnun** [comment]
webUI にて対応していますよ。
録画済みの右上のメニュー -> 編集

**Comment by unicode45** [comment]
webUIには気がつきませんでした。
APIとwebUI両方問題なく削除できました。ありがとうございます。
