### ISSUE TITLE
Mirakurunとのコネクションを大量に張ってしまうため録画に失敗する。

### ISSUE THREAD

**Issue by Miutaku** [l3tnun/EPGStation#664]
### 環境
* Version of EPGStation: `2.7.3`
* Version of Mirakurun: `3.9.0-rc.4`
* Version of Node: `18.18.2`
* Version of NPM: (すみません確認漏れました…)
* OS: Latest docker image [2866cdcf6b36](https://hub.docker.com/layers/l3tnun/epgstation/latest/images/sha256-2866cdcf6b36e95109563fd1bdf146c27487da023eab3af5d89cabcc454a997b?context=explore)
* Architecture: x64
* HostマシンはDS-218+というSynologyのNASです。
```
~$ uname -a
Linux nas-server 4.4.302+ #69057 SMP Sat Sep 23 21:44:10 CST 2023 x86_64 GNU/Linux synology_apollolake_218+
```
* Dockerは以下の感じです。
```
~$ docker -v
Docker version 20.10.23, build 876964a
```

### Issue

EPGStationにて録画/視聴を開始の際、preprecが何度もMirakurunとコネクションを張っては切れる感じです。
こちらのstdoutのログにてメモリリークしたログが出ているのを確認できたので、共有します。↓
![image](https://github.com/l3tnun/EPGStation/assets/20499743/5c97ec03-210d-420e-b95b-064a5145c1ba)

実際に出ている `Operator/system.log` を控えておいたため共有いたします。
[v2.7.3-operator-system.log](https://github.com/l3tnun/EPGStation/files/13464797/v2.7.3-operator-system.log)

**Comment by Miutaku** [comment]
vaapiを使っているため、少しDockerfileを追記しているため、一応共有します
```
FROM l3tnun/epgstation:latest

ENV DEV="make gcc git g++ automake curl wget autoconf build-essential libass-dev libfreetype6-dev libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev pkg-config texinfo zlib1g-dev"
ENV FFMPEG_VERSION=4.2.4

RUN apt-get update && \
    apt-get -y install $DEV && \
    apt-get -y install yasm libx264-dev libmp3lame-dev libopus-dev libvpx-dev && \
    apt-get -y install libnuma-dev && \
    apt-get -y install libasound2 libass9 libvdpau1 libva-x11-2 libva-drm2 libxcb-shm0 libxcb-xfixes0 libxcb-shape0 libvorbisenc2 libtheora0 libaribb24-dev && \
    echo "deb http://http.us.debian.org/debian stable main contrib non-free" | tee -a /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y install i965-va-driver-shaders intel-media-va-driver-non-free vainfo && \
\
\
#ffmpeg build
    mkdir /tmp/ffmpeg_sources && \
    cd /tmp/ffmpeg_sources && \
    curl -fsSL http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 | tar -xj --strip-components=1 && \
    ./configure \
      --prefix=/usr/local \
      --disable-shared \
      --pkg-config-flags=--static \
      --enable-gpl \
      --enable-libass \
      --enable-libfreetype \
      --enable-libmp3lame \
      --enable-libopus \
      --enable-libtheora \
      --enable-libvorbis \
      --enable-libvpx \
      --enable-libx264 \
#      --enable-libx265 \
      --enable-version3 \
      --enable-libaribb24 \
      --enable-nonfree \
      --disable-debug \
      --disable-doc \
      --enable-vaapi \
    && \
    make -j$(nproc) && \
    make install && \
\
# 不要なパッケージを削除
    apt-get -y remove $DEV && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*
```

**Comment by Miutaku** [comment]
v2.7.2でも同じ現象が発生しました。
[system.log](https://github.com/l3tnun/EPGStation/files/13465007/system.log)

**Comment by scimmia9286** [comment]
`[2023-11-26T01:30:52.803] [ERROR] system - [Error: Unknown system error -122: Unknown system error -122, write] {
  errno: -122,
  code: 'Unknown system error -122',
  syscall: 'write'
}`

となってるので、mirakurunと接続できて映像を受信したがディスク(パーティション)に空きがなくて書けないのが原因のように思います。
番組開始時にmirkurunと接続できない時は5行間隔でリトライを試みますが、ディスクに書けなくて失敗した場合は間を置かずリトライを繰り返してしまうんでしょうね。

**Comment by Miutaku** [comment]
> `[2023-11-26T01:30:52.803] [ERROR] system - [Error: Unknown system error -122: Unknown system error -122, write] { errno: -122, code: 'Unknown system error -122', syscall: 'write' }`
> 
> となってるので、mirakurunと接続できて映像を受信したが~ディスク(パーティション)に空きがなくて~ディスククオータ制限によって書けないのが原因のように思います。 番組開始時にmirkurunと接続できない時は5行間隔でリトライを試みますが、ディスクに書けなくて失敗した場合は間を置かずリトライを繰り返してしまうんでしょうね。

この通りでしたね。クォータ調整で解決しました。
