### ISSUE TITLE
エンコードに失敗したとき元ファイルの自動削除の無効化

### ISSUE THREAD

**Issue by kumakuma55** [l3tnun/EPGStation#67]
録画予約時に「元ファイルの自動削除」にチェックを入れていると，エンコードが失敗したときでも元ファイルが削除されてしまいます．現状，少なくともサイズ0のファイルがOUTPUTファイとして作成されていると，エンコードが終了したと見なして，元ファイルが自動削除されるようです．

EncodeManageModel.tsを拝見すると，エンコードプログラムの終了コードは取得されているようです．この終了コードを利用して，エンコードプログラムの終了コード が0以外のときに「元ファイルの自動削除」を無効にすることはできないでしょうか．

**Comment by l3tnun** [comment]
master にて修正しました。
ご確認ください。

**Comment by kumakuma55** [comment]
修正ありがとうございます．
早速試してみます．
