### ISSUE TITLE
/api/configに対し、cloudflare access環境下においてアクセスを試みると500エラーになる。

### ISSUE THREAD

**Issue by Miutaku** [l3tnun/EPGStation#670]
いつもお世話になっております。
ゼロトラスト環境下における利用で、正しく設定が取得できない問題があるため起票いたします。

### 環境
* Version of EPGStation: `2.7.3`
* Version of Mirakurun: `3.9.0-rc.4 `
* Version of Node: `v18.18.2`
* Version of NPM: `9.8.1`
* OS: docker環境下。ubuntu 22.04のVMで動かしている。
* Architecture: x64

### Issue

cloudflare accessを利用し、https://hogehoge.huga にアクセスすることで、ゼロトラスト環境下においてEPGStationを利用可能にしたいのですが、EPGStationにアクセスすると、「設定ダウンロードに失敗しました」というエラーが出てしまいます。
現状の接続環境は、
1. 設定しておいたcloudflare accessのためのアドレス(https://hogehoge.huga) にアクセス
2. cloudflaredを動かしているコンテナ等からEPGStationが動いているポートに対してアクセスしに行く
となっています。
エラーの内訳としては、どうも、 https://hogehoge.huga/api/config を正しく取得できず、500になっているようです。

**Comment by l3tnun** [comment]
epgstationとしてvpn以外サポートする気はありませんので、ご自身で解決してください。
