### ISSUE TITLE
録画Playで「他のアプリで開く」でなく、ブラウザで開きたい。

### ISSUE THREAD

**Issue by rasumus** [l3tnun/EPGStation#673]
LAN内で、Android端末のFirefoxブラウザからPCで稼働するPGStation V2.7.3に接続しています。
録画済み番組を「Play」ボタンで再生しようとすると、「他のアプリで開く。Firefoxを離れてこのコンテンツを表示しますか？　[キャンセル]　[開く]」と尋ねられ、Firefoxで開くことができなくなりました。
「他のアプリで開く」のではなく、Firefoxで開くにはどうすればよいでしょうか？

**Comment by l3tnun** [comment]
intentでfirefoxで開くように設定してください。
できるかは知りませんがfirefox側が対応していればできるはずです。
