### ISSUE TITLE
一定間隔でnodeとmysqldのCPU使用率がスパイクする

### ISSUE THREAD

**Issue by b00t0x** [l3tnun/EPGStation#675]
### 環境
* Version of EPGStation: `2.8.0`
* Version of mirakc: `3.1.9`
* Version of Node: `v18.20.2`
* Version of NPM: `10.5.0`
* Version of MySQL: `8.3.0` ※ 関係しそうなので追記
* OS: Proxmox 8.2.2 + LXC debian-12-standard + Docker
* Architecture: x64

### Issue
約 10 秒 ~~( おそらくデフォルト値から変えていない `epgUpdateIntervalTime` ごと？ )~~ に 1 回、node と mysqld プロセスの CPU 使用率が以下のようにスパイクします。（追記: `epgUpdateIntervalTime: 15` などとしても 10 秒に 1 回は変わりませんでした）
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  91830 root      20   0   11.1g 317080  39680 R  65.4   3.8   1:36.01 node
  21529 999       20   0 2868964 300048  15232 S  50.5   3.6 229:12.07 mysqld
...
```
EPGStation v2.7.3 の Docker イメージに戻したら発生しなくなったので、#663 あたりが影響しているのかと思っているのですが、正確な原因はわかりませんでした。

**Comment by l3tnun** [comment]
ご指摘の通りのでバグでして、`mirakc`環境でのみ発生します。
`feature-mirakc` ブランチにて`mirakc`への正式対応および、バグの修正をしていますので少々お待ち下さい。
明日のお昼ごろにはリリースできるかと思います。(現在動作検証中)

お急ぐの場合は、`EPGUpdater.ts`の104行目と105行目の間に `this.lastUpdatedTime = now;` を差し込んで再ビルドしてください。
https://github.com/l3tnun/EPGStation/blob/325c6cd799ef147597a9a0553c4419613f998bcc/src/model/epgUpdater/EPGUpdater.ts#L104-L105

**Comment by b00t0x** [comment]
既にご対応中とのことで失礼いたしました。
mirakc のタイムシフト録画を併用しているため mirakc 正式対応いただけるのは大変ありがたいです。
ひとまず 2.7.3 で問題なく利用できていますので、リリースを待ちたいと思います。

**Comment by l3tnun** [comment]
v2.9.0にて対応完了しましたのでクローズします。

**Comment by b00t0x** [comment]
自分の環境でも 2.9.0 に更新し再現しないことが確認できました。ありがとうございました。

また、このような素晴らしいソフトウェアを開発してくださりありがとうございます。
あまり機会も無いのでこの場を借りて感謝申し上げます。
