### ISSUE TITLE
一時録画先の追加について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#71]
githubのこともよくわからない素人質問ですみません。

現在録画先を直指定していますが、細かい書き込みが多いようでHDDがカリカリ言ってて心配です。
SSDに録画終了まで書き溜め、録画が終了してエンコード後指定フォルダに移動といったことは可能でしょうか。

一応ソースコードは目を通したのですが、どこかを設定すれば可能なのか、その機能自体が無いのかからわからなくて……

**Comment by l3tnun** [comment]
EPGStation にそのような機能はありません。
機能追加を考えてみましたが修正範囲が多いため実装する予定は無いです。

録画後の管理を EPGStation で行うのは諦めて、エンコード時のスクリプトで行うしかないですね。

**Comment by l3tnun** [comment]
最新の master にて対応しました。
config.json に recordedTmp の記述を追加すると機能します。
録画完了後に recordedTmp から recorded へ移動します。

なお、エンコードの完了を検出することが構造上難しいため、
recorded への移動後、サムネイルの作成、エンコードキューへの追加が行われます。

また、recordedTmp で指定したディレクトリの空き状況は全く把握していないため、空き容量には十分注意してください。
