### ISSUE TITLE
【要望】録画後のコマンドについて

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#73]
TVRockからの移行を目指して試行錯誤しています。

視聴を主にTVのDLNAクライアントで行っている都合上、録画ファイルをNAS上にフォルダ分けして配置しています。
現状では録画後、自作のスクリプトにTVRockからパラメーターを投げてフォルダ作成・ファイル移動・重複排除などを行っているのですが、EPGStationでどのようにしてこれを実現したらよいのか悩んでいます。

今のところEPGStationでは予約ごとに個別の録画後コマンドを設定できないようですが、これができるようになりませんでしょうか?

ご検討よろしくお願いします。

**Comment by l3tnun** [comment]
TVRock を使用したことは無いのでよくわかりませんが

* recordedEndCommand で設定できるコマンドを1つではなく複数設定できるようにする
* 手動 or ルール予約時に recordedEndCommand から1つ選択できるようにする

ということですね？
改修範囲がかなりあるので実装に時間がかかりそうなので気長にお待ち下さい。

コマンド実行時に必要な変数があれば書いてください。
ファイルパスは追加します。

**Comment by cuckoozero** [comment]
お世話になります。

> - recordedEndCommand で設定できるコマンドを1つではなく複数設定できるようにする
> - 手動 or ルール予約時に recordedEndCommand から1つ選択できるようにする

おっしゃる通りです。
加えて言えば、手動 or ルール予約時に recordedEndCommand から1つ選択できるのみではなく、直接コマンドを記述することも可能であればさらにありがたいです。

変数は自分の用途としてはファイルパス・番組概要・番組詳細があれば大丈夫だと思います。
よろしくお願いします。

**Comment by l3tnun** [comment]
直接コマンドの記述は、万が一外部からの攻撃があった場合非常に危険なため実装しません。

**Comment by cuckoozero** [comment]
そういう理由があるのですね
了解しました

**Comment by cuckoozero** [comment]
※我ながら非常にニッチな要望であることは自覚していますので採用されなくとも当然だと思いながら

直接コマンドがありえない（いわれてみれば当然ですよね）とのことで、自分がそれで何を実現したいのかを考えました。
結果、自分としては作成するフォルダ名称や重複排除のモード決定、ファイルリネーム規則の３点において予約ルールごとに個別の設定を必要としていました。

そこで大変図々しい要望なのですが、手動 or ルール予約時に数個のユーザー記述変数を持たせることは如何でしょうか?
恐縮ですが、再度ご検討いただけますと幸いです。

**Comment by l3tnun** [comment]
複数個ユーザー記述変数を持たせるのはデータベースの構造上複雑になるため実装は難しいです。
ただ1つのユーザー記述変数を環境変数に含めるのは可能なので、コマンド側で分割処理をして1つの変数に複数の情報を載せることはできます。

**Comment by l3tnun** [comment]
話は変わりますが、recordedEndCommand は今の仕様では録画終了後すぐに実行されるようになっていて、録画が複数同時に終了すると録画の数だけコマンドが走るようになっています。
ただ、今回の要望の内容を考えると1つづつ実行されたほうがいいですよね？

**Comment by cuckoozero** [comment]
ありがとうございます。
これでスクリプト作成の目途が立ちます。

> ただ、今回の要望の内容を考えると1つづつ実行されたほうがいいですよね？

確かにそうですね。
一点確認ですが、recordedEndCommand は録画終了後すぐにとのことですが、これはエンコード前に実行され、ファイルパスもオリジナルのTSを投げてくるという認識で良かったでしょうか?

**Comment by l3tnun** [comment]
recordedEndCommand の現在の実装ではエンコードの設定をキューに投げた後実行されるようになっています。
recordedEndCommand の本来想定している機能と今回の要望の機能がかなりずれてしまうので、encode を修正して1つづつ処理できる形にしたいと思います。

**Comment by l3tnun** [comment]
devel ブランチにて実装が完了しました。
encode が拡張されています。

コマンドの追加は以下のように記述でき、suffix の有無でエンコード、非エンコードであるかを判定しています。

```
    "encode": [
        {
            "name": "H264",
            "cmd": "/bin/bash %ROOT%/config/enc.sh main",
            "suffix": ".mp4"
        },
        {
            "name": "copy-ts",
            "cmd": "/bin/bash /hoge/fuga.sh"
        }
    ],
````

あと、コマンド実行時の環境変数に

* RECORDEDID
* DIR
* NAME
* DESCRIPTION
* EXTENDED

が追加されました。

エンコードの設定毎にディレクトリの設定ができますが、非エンコードコマンドではユーザー記述変数として使用できます。
環境変数 DIR に格納されるので活用してください。

詳細は [config.md](https://github.com/l3tnun/EPGStation/blob/devel/doc/config.md#encode) に書いてあります。

時間があるときにでも試してください。
特に問題がなければ master へマージします。

**Comment by cuckoozero** [comment]
対応ありがとうございました。
試してみました。

powershellスクリプトを動かすのにかなり苦労しましたが、
```
{  
"name": "file-move",
"cmd": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe &'C:\\TV\\EPGStation\\recorded\\test.ps1' %INPUT%"
}
```
と、powershell.exeもスクリプトもフルパスで指定することで実行できました。

しかしやや困ったことに
test.ps1
```
Write-Output "current dir: $(convert-path .)" > C:\TV\EPGStation\recorded\testlog.txt
Write-Output "FilePath: $args[0]" >> C:\TV\EPGStation\recorded\testlog.txt
Get-ChildItem env: >> C:\TV\EPGStation\recorded\testlog.txt

Write-Output "RECORDEDID: $env:RECORDEDID" >> C:\TV\EPGStation\recorded\testlog.txt
Write-Output "DESCRIPTION: $env:DESCRIPTION" >> C:\TV\EPGStation\recorded\testlog.txt
Write-Output "EXTENDED: $env:EXTENDED" >> C:\TV\EPGStation\recorded\testlog.txt
Write-Output "FFMPEG: $env:FFMPEG" >> C:\TV\EPGStation\recorded\testlog.txt
```
の実行結果が以下の通り
```
current dir: C:\tv\EPGStation
FilePath: c:\TV\EPGStation\recorded\2018年04月16日18時10分00秒-クマロク!.ts[0]

Name                           Value                                           
----                           -----                                           
AUDIOCOMPONENTTYPE             3                                               
AUDIOSAMPLINGRATE              48000                                           
CHANNELID                      3185657344                                      
FFMPEG                         C:\PROGRA~4\ffmpeg-3.4.2-win64-shared\bin\ffm...
GENRE1                         0                                               
GENRE2                         9                                               
INPUT                          c:\TV\EPGStation\recorded\2018年04月16日18時10分00...
OUTPUT                         c:\TV\EPGStation\recorded\2018年04月16日18時10分00...
PATH                           C:\Windows\system32;C:\Windows;C:\Windows\Sys...
PathEXT                        .CPL                                            
PSMODULEPATH                   WindowsPowerShell\Modules;%ProgramFiles%\Wind...
SYSTEMDRIVE                    C:                                              
SYSTEMROOT                     C:\Windows                                      
TEMP                           C:\Windows\TEMP                                 
USERDOMAIN                     MAGI                                            
USERNAME                       REC-SERVER$                                     
USERPROFILE                    C:\Windows\system32\config\systemprofile        
VIDEOCOMPONENTTYPE             179                                             
VIDEORESOLUTION                1080i                                           
VIDEOSTREAMCONTENT             1                                               
VIDEOTYPE                      mpeg2                                           
WINDIR                         C:\Windows                                      


RECORDEDID: 
DESCRIPTION: 
EXTENDED: 
FFMPEG: C:\PROGRA~4\ffmpeg-3.4.2-win64-shared\bin\ffmpeg.exe
```
環境変数の一部しか取り込めないようで、これを解決できないでいます。
※`git branch devel`後に、`git pull` `npm update` `npm run build`でうまく更新できたと思っていたのですが、もしかして失敗しているのかも。Git and GitHub初心者でよく判っておらずすみません。

大変お手数ですが、お手すきの時にアドバイスを頂けないでしょうか？

**Comment by l3tnun** [comment]
Windows 環境を用意して上記の test.ps1 を実行しましたが、こちらの環境では正常に実行されました。

更新方法は正しいので、おそらく EPGStation の再起動をしていないのだと思います。

**Comment by l3tnun** [comment]
ああ、```git branch devel```
これが間違っていますね。

正しくは ```git checkout devel``` です。

**Comment by l3tnun** [comment]
手動予約でも可能ですよ。

詳細が追加されました。

![2018-04-16 23 31 03](https://user-images.githubusercontent.com/16516088/38815201-55bc4716-41ce-11e8-9a63-a50bdc099192.png)

![2018-04-16 23 31 17](https://user-images.githubusercontent.com/16516088/38815205-59ec0830-41ce-11e8-9d58-7f6eb9af2b00.png)

**Comment by cuckoozero** [comment]
あれ？
こちらでは詳細ボタンが表示されていません。
まだ何か間違えているようです。
![image](https://user-images.githubusercontent.com/35391643/38815685-80dc82a2-41cf-11e8-84f8-6a3dec692465.png)

**Comment by cuckoozero** [comment]
すみません解決しました！
ブラウザー側のリロードをしていませんでした。
失礼しました。

**Comment by cuckoozero** [comment]
まだまだ雑なものですがスクリプトを組んで試しています。
おかげさまでおおむね期待通りの機能が実現できています。

ひとつ気になったのが、手動予約で詳細設定を行った場合に、その後変更ができず、いったん削除して予約を取り直す必要があるのですね（もしあればすみません）。
ユーザーコマンドに間違いがないかどうかも確認ができないので、いったん成立した予約に対しても編集ができると助かると思います。

**Comment by l3tnun** [comment]
> ひとつ気になったのが、手動予約で詳細設定を行った場合に、その後変更ができず、いったん削除して予約を取り直す必要があるのですね（もしあればすみません）。

現在の仕様ではそのとおりです。
考慮することが色々あり面倒なので編集の実装はしていません。
そのうち実装しようかなとは思いますので、気長にお待ち下さい。

**Comment by cuckoozero** [comment]
了解しました。
ご対応ありがとうございます。

現在のところ問題なく動作しています。
こちらとしてはマージしていただいて大丈夫そうです。

**Comment by l3tnun** [comment]
遅くなりましたが、devel にて予約のオプション表示と手動予約の編集機能を追加しました。
暇な時にでも確認してみてください。
特に問題がなければ master へマージします。

なお reserves.json のデータ構造の変更があるため、
version 0.7.7 以降で手動予約のディレクトリとファイル名形式の指定が引き継がれません。
手動予約を一旦削除して再度予約することを推奨します。
（まあ別にやらなくても設定が無視されるだけで録画自体はされます。）

ルール予約に影響はありません。

あと、録画中の手動予約の編集はできない仕様になっています。

**Comment by cuckoozero** [comment]
手動予約の編集機能が正常に動作することを確認しました。
オプション表示は予約表示画面で表示されました。
問題なく動作していると思います。

こちらのスクリプトもやっと組みあがり、動作確認をしながら少しずつTVRockの予約ルールを移植していくところです。
大変丁寧に対応していただきとても感謝しています。
ありがとうございました！
さらなるご発展を期待しています。

**Comment by l3tnun** [comment]
マージしたので閉じます。

**Comment by cuckoozero** [comment]
すみません、close済みのIssueですが、新しく立てるほどのものではないと思うのでこちらに書きます。

追加して頂いたユーザー記述変数を便利に使わせていただいていますが、この中に"\"を記述すると保存されないことに気が付きました。
移動先のサブフォルダ指定に使いたいと思うのですが難しいでしょうか？
（またこちらの勘違いであったらすみません）

**Comment by cuckoozero** [comment]
上のコメントを書いてから"\\\\"とエスケープすればいいことに気が付いたのですが、予約ルールを再編集する際に、エスケープがなくなっているのでもう一度"\\\\"に修正して保存する必要があるようです。

**Comment by l3tnun** [comment]
devel ブランチにて修正しました。
```"hoge hoge"``` と入力して大丈夫なはずです。

**Comment by cuckoozero** [comment]
ご対応ありがとうございました。
"\\"がそのまま保存されていることを確認しました。
マージよろしくお願いします。
