### ISSUE TITLE
録画後エンコードがフォルダ分けに対応していない？

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#74]
お世話になっております。

現在Windows10pro x64にてEPGSTATIONを便利に使わせてもらっております。

シリーズ録画のために「\番組名フォルダ」に保存するようルールを作っているのですが、
tsファイルは「\番組名フォルダ」に入っているものの録画後のエンコード結果は「\番組名フォルダ」には入っていないようです。ルールでエンコードを設定せず、録画後手動でエンコード（同じフォルダに～にチェック入れる）すると同じフォルダに入っています。

期待する動きとしてはルール設定時に録画ディレクトリを指定する場合元ファイルもエンコ結果もそこに保存されていてほしいのですが……（設定を変えるだけで対処可能でしたら申し訳ありません。）

**Comment by l3tnun** [comment]
エンコードでもディレクトリ設定が必要です。

<img src="https://user-images.githubusercontent.com/16516088/38607553-ed8310f8-3db3-11e8-8480-d30e8e348059.png" width="320px">

**Comment by ohmsa** [comment]
ありがとうございます。
エンコード下の入力欄がディレクトリ指定だったのですね。気づきませんでした。
色々弄ってみます。

重ね重ねありがとうございます。
