### ISSUE TITLE
拡張子の変更について

### ISSUE THREAD

**Issue by ohmsa** [l3tnun/EPGStation#75]
何度も質問で申し訳ありません。

Googleバックアップと同期で録画フォルダをバックアップしたいのですが、拡張子が.tsだと容量無制限の対象外らしく.m2tsにする必要があります。デフォルトの方はconfig.jsonで変えられますが、すでに録画済みのものの場合
１．DBを書き出す
２、EPGstationを停止
３．DB内の.tsを.m2tsに書き換える
４．フォルダ内の.tsを.m2tsに書き換える
５．DB書き戻し
６．EPGstationを起動
で対処可能でしょうか。

**Comment by l3tnun** [comment]
> １．DBを書き出す
> ２、EPGstationを停止
> ３．DB内の.tsを.m2tsに書き換える
> ４．フォルダ内の.tsを.m2tsに書き換える
> ５．DB書き戻し
> ６．EPGstationを起動

上記手順で変更可能ですが動作の保証はできません。
