### ISSUE TITLE
ffmpeg h264_vaapi時のみread ECONNRESETで切断される

### ISSUE THREAD

**Issue by advancedbear** [l3tnun/EPGStation#78]
おま環っぽい感じもするのですが、OSやデバイスに関わらず発生するので一応Issueを建てさせていただきます。

Z3735Fを搭載したCentOS 7のマシンと、Athlon5350を搭載したWindowsServer2016マシンそれぞれでEPGStationを動かしております。
両者とも、自前でビルドをしたffmpeg 3.4.2を利用しており、vaapiを用いたHWエンコードを試みようとしております。
````
$ ffmpeg -hwaccels
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-16)
  configuration: --prefix=/home/epgstation/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/epgstation/ffmpeg_build/include --extra-ldflags=-L/home/epgstation/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/home/epgstation/bin --enable-libvpx --enable-libx264 --enable-gpl
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hardware acceleration methods:
vdpau
vaapi
cuvid
````
この環境において、config.jsonのmpegTsStreamingに
````
{
    "name": "1280x720(qsv)",
    "cmd": "%FFMPEG% -re -dual_mono_mode main -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format vaapi -i pipe:0 -c:a copy -c:v h264_vaapi -vf 'deinterlace_vaapi,scale_vaapi=w=1280:h=-2' -qp 25 -f mpegts pipe:1"
}
````
を追加してpm2 restartをしましたが、動画プレイヤーにてAPI `/api/streams/live/3273601024/mpegts?mode=0` にアクセスすると、
````
[2018-04-24T00:33:03.344] [INFO] system - create new encode child: 1524497583343
[2018-04-24T00:33:06.956] [FATAL] system - uncaughtException: Error: read ECONNRESET
````
のように、3秒ほどで接続が切断されるのが3回ほど繰り返され、クライアント側でも「この動画は再生できません」のエラーが表示されてしまいます。

ffmpegの動作がおかしいのかと考えましたが、デフォルトで搭載されているlibx264を用いたストリーミング再生は正常に動作する他、
````
cat /mnt/nas/test.m2ts | ffmpeg -re -dual_mono_mode main -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format vaapi -i pipe:0 -c:a copy -c:v h264_vaapi -vf 'deinterlace_vaapi,scale_vaapi=w=1280:h=-2' -qp 25 -f mpegts pipe:1 > /mnt/nas/test_encoded.m2ts
````
のようなコードを実行すると正常なエンコードデータが出力されるので、ffmpeg側の問題ではないのかなぁと考えています。

このような経緯で、EPGStationを経由した場合のみ出力がなされない理由が分からず困惑しております。
流石におま環っぽい感じが強いので原因を探っていただきたいとまではいいませんが、より詳細なエラーログを出力させる方法はあったりしないでしょうか？
コネクションがタイムアウトしてるのか、何かエラーが発生してffmpegプロセス自体が死んでしまっているのかイマイチ分からないのが悩みどころです。

長文な上取り留めがない文章で申し訳ありませんが、よろしくお願いします。

**Comment by l3tnun** [comment]
Z3735F ということはスティックPCとかで動かしているのでしょうか？
面白そうな構成ですね。

ffmpeg の出力をログに書き出させるには、```config/serviceLogConfig.json``` の ```categories``` -> ```stream``` -> ```level``` を ```info``` から ```debug``` へ変更して EPGStation を再起動してください。
```logs/Service/stream.log``` にて ffmpeg の出力が書き出されます。

```tail``` コマンドを使用して ```tail -f logs/Service/stream.log``` とすると逐表示されて動作状況が把握しやすいです。

ちなみに G1820 + Debian9 + ffmpeg 3.4 な環境では以下のコマンドで動作が確認できました。
```
%FFMPEG% -re -dual_mono_mode main -vaapi_device /dev/dri/renderD128 -i pipe:0 -vf format=nv12|vaapi,hwupload,deinterlace_vaapi,scale_vaapi=w=1280:h=720 -c:a aac -ar 48000 -ab 192k -ac 2 -c:v h264_vaapi -level 40 -aspect 16:9 -q 21 -f mpegts pipe:1
```

hwaccel, hwaccel_output_format オプションは使用していない理由は、BS の一部のチャンネル(今年の1月に帯域削減があった局)にて正常にデコードされないためです。
おそらくMPEG2AD の変更が原因なのではないかな？と思います。

hwaccel, hwaccel_output_format オプションをつけた場合は以下のようになります。
```
%FFMPEG% -re -dual_mono_mode main -vaapi_device /dev/dri/renderD128 -i %INPUT% -vf format=nv12|vaapi,hwupload,deinterlace_vaapi,scale_vaapi=w=1280:h=720 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1 -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -threads auto -c:a aac -ar 48000 -ab 192k -ac 2 -c:v h264_vaapi -level 40 -aspect 16:9 -qp 21 -flags +loop-global_header pipe:1
```

**Comment by advancedbear** [comment]
＞Z3735F ということはスティックPCとかで動かしているのでしょうか？
Compute Stickを6000円台で買ったので試しにS1UDを挿して遊んでみているところです。

ログ出力の方法を教えて頂きありがとうございます。
実際にログを出してみたところ以下のような内容になりました。
````
[2018-04-24T21:34:32.512] [DEBUG] stream - Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (copy)
[2018-04-24T21:34:32.802] [DEBUG] stream - [AVFilterGraph @ 0x416d080] No such filter: 'deinterlace_vaapi,scale_vaapi=w=1280:h=720'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[2018-04-24T21:34:32.805] [DEBUG] stream - Conversion failed!
[2018-04-24T21:34:33.349] [INFO] stream - stop stream: 0
````
どうやら-vfの辺りでおかしくなっていました。
試しに-vf以下を消して実行してみると
````
[2018-04-24T21:59:33.083] [DEBUG] stream - Impossible to convert between the formats supported by the filter 'Parsed_format_0' and the filter 'auto_scaler_1'
[2018-04-24T21:59:33.084] [DEBUG] stream - Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
````
とエラーが変わりました。

関連キーワードで検索してみると、どうもVP9絡みのエンコーダのエラーのようです。
多分ドライバー関連じゃないかなという感じはするのでちょっと環境を見直してみます。

ログの設定について教えていただいた上に、そちらの環境でvaapi動作できることを確認していただいてありがとうございました。
これからも応援してます。

**Comment by l3tnun** [comment]
エラー内容からして vaapi が叩けているか怪しいですね。

一応ですが、もしかして ```-vaapi_device /dev/dri/renderD128``` もそのままって同じことはないですよね。環境によって違うので。

あとは EPGStation 実行ユーザが video に属しているか。vainfo を叩いてエラーが無ければ問題ないとは思います。

> ```
> {
>     "name": "1280x720(qsv)",
>     "cmd": "%FFMPEG% -re -dual_mono_mode main -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format vaapi -i pipe:0 -c:a copy -c:v h264_vaapi -vf 'deinterlace_vaapi,scale_vaapi=w=1280:h=-2' -qp 25 -f mpegts pipe:1"
> }
> ```

このコマンドを見ていて思いましたが
これの

```
-vf 'deinterlace_vaapi,scale_vaapi=w=1280:h=-2'
```

この部分の ``` ` ``` は不要です。 ``` ` ``` で括り1つの引数であるようにコマンドに認識させるために bash 等で実行する場合は必要ですが、
EPGStation では 半角スペース区切りで分割して引数をコマンドに渡しているため

```
-vf deinterlace_vaapi,scale_vaapi=w=1280:h=-2
```

と書かないと正しく認識されないです。

> Closeするのは実際に解決してからでも大丈夫でしょうか？

解決してからで大丈夫です。
(ffmpeg に詳しいと言う訳ではないので力になれるかは不明ですが)

**Comment by advancedbear** [comment]
諸々のアドバイスありがとうございました。
無事にh264_vaapiを用いてエンコードが出来るようになりました。
![snapcrab_2018-4-25_20-30-25_no-00](https://user-images.githubusercontent.com/9246266/39243217-bbc74e7a-48c7-11e8-9fc7-9c3b64348b38.png)

最終的に、cmdは
````
%FFMPEG% -re -dual_mono_mode main -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format vaapi -i pipe:0 -c:a copy -c:v h264_vaapi -vf deinterlace_vaapi,scale_vaapi=w=1280:h=-2 -qp 25 -f mpegts pipe:1
````
となりました。（もちろんdevice欄は変えておりました）

l3tnunさんの場合と異なり、こちらの環境では「hwaccel, hwaccel_output_format」を外すと
````
[2018-04-25T20:40:57.125] [DEBUG] stream - Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
[2018-04-25T20:40:57.128] [DEBUG] stream - Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
[2018-04-25T20:40:57.129] [DEBUG] stream - Conversion failed!
````
となってしまうことが分かったため、当初のコマンドどおりに両オプションを付けたままにしました。
それ以外では、`intel-hybrid-driver`のインストールを忘れていたためこれを入れ直したことくらいでしょうか。

いずれにせよ、当初の目的どおりのHWエンコードでストリーミング視聴ができるようになりました。
なお、録画データのHLS配信の方はやはり上述のエラーと同様のものが出ていますが、こちらに関してもオプションの調整等で対応できそうな予感はするので粘ってみたいと思います。

色々とご助言いただきありがとうございました。

**Comment by l3tnun** [comment]
動きましたか！おめでとうございます。
案外負荷も少なくZ3735Fでも使えそうですね。

hls の設定を含めて vaapiでの設定は
https://github.com/l3tnun/docker-mirakurun-epgstation/blob/vaapi/epgstation/config/config.json
にて確認しています。
参考にしてみて下さい。
