### ISSUE TITLE
0.7.7 ==> 0.8.1にアップグレード失敗

### ISSUE THREAD

**Issue by zgock999** [l3tnun/EPGStation#82]
お世話になります。いつも愛用させていただいております
0.7.7の現在環境から最新の0.8.1へアップグレードしようとしたところ
おそらくDB関連エラーと思われるエラーでnpm run に失敗してしまいます
(長くなるのでメッセージはpastebinにて)
https://pastebin.com/aLvpWMWm

config等、0.7.7-->0.8.1に伴って追加修正すべき場所とかがあるのでしょうか？

**Comment by l3tnun** [comment]
> [2018-05-05T04:32:12.021] [WARN] system - reserves.json is not found.
> [2018-05-05T04:32:12.146] [WARN] system - dbinfo.json is not found.

ここから察するに ```EPGStation/data/*.json``` が何らかの原因で消えてしまったのが原因です。

 ```EPGStation/data/dbinfo.json``` を作成して

```
{"revision":1}
```

このように記述を追加すれば起動するはずです。

```reserves.json``` も消えているので手動予約が無くなっていますね。
通常通りアップデートできていれば削除されることはないのでアップデート手順に何らかのミスがあったのではないかと思います。

**Comment by zgock999** [comment]
ありがとうございました。最初zipからの解凍で試験運用しており、常用できそうだということで改めてgit cloneでディレクトリを掘りなおして旧環境から設定群をコピーしたつもりだったのですが抜けがあったようです。大変お騒がせしました。こちらのオペミスが確定しましたのでcloseさせていただきます。
