### ISSUE TITLE
【質問】自作スクリプトが動作しなくなりました

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#87]
たびたびお世話になります。

Windows環境で利用させていただいており、録画後の処理を自作のPowerShellスクリプトで行っています。
先日version 0.8.2へアップデートした後からだと思うのですが、そのスクリプトが動作しなくなりました。

こちらで原因を探ったところ、どうもネットワークフォルダに対する操作ができなくなっており、それでスクリプトがこけているようです。

簡単に検証用のスクリプトを作成して実行したところ、コンソールからは正常に動作しますがEPGStationから実行させると失敗します。

scripttest.ps1

    $ErrorActionPreference = "continue"
    
    $time = (Get-Date -Format "yyyy/MM/dd HH時mm分ss秒")
    $userinfo = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    
    echo "$time 書き込みテスト" | Out-File -filePath "\\hoge\media\Videos\EPGStation.log" -encoding UTF8 -Append
    
    echo $userinfo | Out-File -filePath "C:\tv\EPGStation\recorded\EPGStationMove_userinfo.txt" -encoding UTF8
    
    trap { 
        echo $Error[0] | Out-File -filePath "C:\tv\EPGStation\recorded\EPGStationMove_error.txt" -encoding UTF8 -Append
    }

これをPowerShellコンソールから実行すれば問題ありませんが、EPGStationから実行すると以下のエラーを吐いて失敗します。

    Out-File : 指定されたサーバーは、要求された操作を実行できません。
    
    発生場所 C:\TV\EPGStation\scripttest.ps1:6 文字:24
    + ...  書き込みテスト" | Out-File -filePath "\\hoge\media\Videos\EPGStatio ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OpenError: (:) [Out-File], IOException
        + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou 
       tFileCommand
 
当該フォルダはEveryoneに対してフルコントロールの許可があり、パーミッション上は問題ないように思えます。
何らか回避策などありましたら、教えていただけると助かります。

**Comment by l3tnun** [comment]
Windows のバージョン、スクリプトが動いていた時の EPGStation のバージョン、 config.json での記述等々わからないので何とも言えませんが、EPGStation がエンコードコマンドを実行する部分のコードは version 0.7.8 以降変更していません。

Windows Update 等でなにか変更があったりと色々原因はあると思いますのでこちらでは原因の判断しかねます。

**Comment by cuckoozero** [comment]
情報が足りず失礼しました。
Windows10 home x64
Mirakurun: 2.7.0
Node: v8.10.0
NPM: 6.0.0

その後version 0.8.1に戻してみたところ、先述のscripttest.ps1もEPGStationからの起動で正常に動作するようになりました。

> EPGStation がエンコードコマンドを実行する部分のコードは version 0.7.8 以降変更していません。

そうなんですね。
どうしてこのような結果になるのかはわかりませんが、自分で出来ることとしてここから段階的にバージョンを上げて、どの段階で現象が出現するのかあるいはしないのかを確認してみたいと思います。

**Comment by l3tnun** [comment]
version 0.8.2 〜 0.8.4 の変更点ですが
0.8.3, 0.8.4 は 0.8.2 のバグ修正くらいでserver 側に大きな更新はないです。

0.8.2 は web ui に大きな更新がありましたが、
サーバ側ではストリーム配信方法が複数追加されたくらいで、プロセスの生成方法などのエンコードに影響がある部分の変更は無いですね。

**Comment by cuckoozero** [comment]
version 0.8.1から段階的にバージョンを挙げてテストしたので報告します。
結論から先に言うと単なるオレ環のようです。大変お騒がせしました。m(_ _)m

version 0.8.2から0.8.4まで現象が再現しませんでした。
ご迷惑をおかけしてすみませんでした。

**Comment by l3tnun** [comment]
解決してなによりです。

**Comment by cuckoozero** [comment]
症状が再発してしまいました。
今度はversion 0.8.1戻しても、再度インストールを行っても改善しないでいます。

いろいろググっていたら"Systemユーザーにはネットワーク資源へのアクセス許可がない"という情報に行き当たりました。[Link](https://qiita.com/shisho/items/dcb5ee0fd1dd2e5f5d9b)（こうなってくると今まで動いていたのが不思議というか…、というか今も１０回に１回ぐらいは正常に動作したりするし…？？）

Systemユーザーの権限不足が原因である可能性があると思うのですが、子プロセスの実行ユーザーをNetworkServiceユーザーなどで行っていただくわけにはいけませんでしょうか?

**Comment by l3tnun** [comment]
windows 環境で動かしていないので詳しくは知りませんが、サービスの設定で実行ユーザの変更ができるのでは無いでしょうか？

**Comment by cuckoozero** [comment]
おっしゃったようにサービスの設定で実行ユーザーを"Network Service"に変更したところ、EPGStationのサービスが開始できませんでした。
日頃使用している一般ユーザーを設定したところサービスが開始でき、スクリプトからネットワークフォルダにアクセスすることも出来ています。
一般ユーザーの権限でEPGStationの動作には問題ないのでしょうか?

**Comment by l3tnun** [comment]
管理者権限が必要な操作はないので一般ユーザの権限で問題ないです。
実行ユーザを変えたならば、EPGStation のディレクトリ、ファイルのアクセス権限の確認をしたほうがいいかもしれませんね。

**Comment by cuckoozero** [comment]
管理者権限の必要はないとのこと、安心しました。
しばらくこの状態で経過を見ていきます。
