### ISSUE TITLE
予約録画時間前に、予めHDDをスピンアップする方法？

### ISSUE THREAD

**Issue by soltune** [l3tnun/EPGStation#88]
Raspberry Pi 3 で運用しています。
予約時間になったところ、USBに繋いだHDDがスピンアップするまでに時間が掛かり書き込みが間に合わなかった結果録画に失敗することがありました。
（mirakurunのバッファはデフォルトのままにしています。設定を変えてこれを大きくすれば良さそうではありますが、1GBのメモリではあまり欲張った設定は厳しそうです）

もちろん、HDDをスリープさせなければ良い話ではあるのですが・・・・。
例えば予約時間の数十秒〜1分程度前にHDDに適当にアクセスするなどして（対象ドライブを`ls`するだけでも良いわけなので）予め起こしておけば問題はない訳なので、何か現状の実装のままうまくワークアラウンドできる方法はあるでしょうか？

もし上記が難しいようであれば、なにかしら調整をご検討いただけないでしょうか？

**Comment by l3tnun** [comment]
feature-88 ブランチにて recordedPreStartCommand を追加しました。
config.json に以下のように記述を追加すると録画準備段階で設定したコマンドを実行します。

```
"recordedPreStartCommand": "/bin/bash /hoge/fuga.sh",
```

ただ放映中の番組を予約した場合、録画準備から録画開始までの時間が短いので今回の問題の用途に適切に使用できるかはこちらではわかりません。

時間がある時に試してみてください。問題がなければ master へマージします。

**Comment by soltune** [comment]
早速feature-88ブランチの `recordedPreStartCommand`を追加してみました。
もともとつねに必ず失敗する（録画開始までにスピンアップが間に合わない）という訳ではなかったので、再現が難しいのですが現状のところ特に問題なく動作しているように思います。

こちらで問題があるようでしたらまたご相談させていただきます。
ご対応ありがとうございます。

**Comment by l3tnun** [comment]
master にマージしましたので閉じます
