### ISSUE TITLE
【質問】番組検索について

### ISSUE THREAD

**Issue by cuckoozero** [l3tnun/EPGStation#96]
いつも素早い対応ありがとうございます。
予約ルールの設定を行っていたところ分からないことがありましたので質問させてください。

検索キーワードにおいて番組名に"hoge"、番組詳細に"huga"というワードがあったとして、それをANDまたはORでマッチさせるのにはどうしたらいいら良いのでしょうか?

また、番組詳細に"hoge", "huga"両方が含まれているとして、正規表現でこれをマッチさせるために"^(?=.*hoge)(?=.*huga)"という式を検索キーワードにしたところ"検索失敗: internal server error"と表示されて失敗します。

お手数ですが、正しい方法があれば教えてください。

**Comment by l3tnun** [comment]
> 検索キーワードにおいて番組名に"hoge"、番組詳細に"huga"というワードがあったとして、それをANDまたはORでマッチさせるのにはどうしたらいいら良いのでしょうか?

* タイトル, 詳細にチェックを入れて ```hoge huga``` で and 検索
* 正規表現, タイトル, 詳細にチェックを入れて ```hoge|huga``` で or 検索

タイトルは ```hoge``` だけで検索して、詳細は ```huga``` だけで検索とかはできないです。
タイトルと詳細を ```hoge``` (and, or) ```huge``` で検索となります。

> また、番組詳細に"hoge", "huga"両方が含まれているとして、正規表現でこれをマッチさせるために"(?=.*hoge)(?=.*huga)"という式を検索キーワードにしたところ"検索失敗: internal server error"と表示されて失敗します。

使用しているデータベースの種類が分からないので推測ですが、```Internal Server Error``` が出ているところを見ると SQLite3 のようですね。
[l3tnun/sqlite3-pcre](https://github.com/l3tnun/sqlite3-pcre) では動いたので調べてみたところ、[doc/sqlite3-regexp.md](https://github.com/l3tnun/EPGStation/blob/master/doc/sqlite3-regexp.md) で紹介している方法では肯定先読みが使えないようですね。

https://sqlite.org/src/artifact/a68d25c659bd2d89 でサポートされている正規表現構文内で頑張るか、MySQL 等に乗り換えるのが手っ取り早いと思います。

config.json の sqlite3 -> extensions を [l3tnun/sqlite3-pcre](https://github.com/l3tnun/sqlite3-pcre) に差し替えるのでも問題はありませんが Windows 環境ではビルドが難しいです。

**Comment by cuckoozero** [comment]
お世話になります。
AND/ORとも検索できました。

> 使用しているデータベースの種類が分からないので推測ですが、Internal Server Error が出ているところを見ると SQLite3 のようですね。

データベースはMySQLを使用しています。
 正確には`検索失敗: Error: Internal Server Error`と表示されますが、これはおかしいのでしょうか?
config.jsonのデータベース設定は以下の通りです。

    "dbType": "mysql", 
    "mysql": {
        "host": "127.0.0.1",
        "port": 3306,
        "user": "epgstation",
        "password": "hogehoge",
        "database": "epgstation",
        "connectTimeout": 1000,
        "connectionLimit": 10
    },

**Comment by l3tnun** [comment]
調べてみたところ MySQL は肯定先読みをサポートしていないようですね。
MariaDB では [REGEXP - MariaDB Knowledge Base](https://mariadb.com/kb/en/library/regexp/) をみると pcre で regexp を実現しているためサポートしているようですね。

というわけでサポートされている正規表現構文内で頑張るか、MariaDB or PostgreSQL へ移行するしかないですね。

**Comment by cuckoozero** [comment]
調べていただいてありがとうございました。
そもそもMySQLでサポートされていないのであれば当然ですね。
MariaDBへの移行を検討したいと思います。

しかし、あちらにもう一度書こうと思うのですが[#87](https://github.com/l3tnun/EPGStation/issues/87)と同じ症状が再発して今度はなかなか戻せないでいます。

引き続きよろしくお願いします。
